#!/usr/bin/env node

// push from bundle generated by ./bundle.sh

const fs = require('fs')
const proc = require('child_process')
const argv = require('minimist')(process.argv.slice(2))
let { platform, stage } = argv
if (platform !== 'ios' && platform !== 'android') {
  throw new Error('expected --platform "ios" or "android"')
}

if (!stage) {
  // yes, this is ridiculous, need to do some dev ops
  // to configure things right
  stage = platform === 'ios' ? 'Staging' : 'Production'
}

if (stage !== 'Staging' && stage !== 'Production') {
  throw new Error('expected --stage "Staging" or "Production"')
}

const { getReleaseDir, getVersion } = require('./build-utils')
const releaseDir = getReleaseDir({ platform })
if (!fs.existsSync(releaseDir)) {
  throw new Error(`expected to find release dir: ${releaseDir}`)
}

const fourPartVersion = getVersion({ platform })
const threePartVersion = fourPartVersion.split('.').slice(0, 3).join('.')
if (!threePartVersion) throw new Error('unable to parse version from Dev.plist')

const pushLine = `code-push release tim-${platform} ${releaseDir} ${threePartVersion} -d ${stage}`
console.log(`running: ${pushLine}`)

if (process.argv.indexOf('--dry-run') === -1) {
  proc.execSync(pushLine, {
    cwd: process.cwd(),
    env: process.env,
    stdio: 'inherit'
  })
}
