#!/usr/bin/env node

// push from bundle generated by ./bundle.sh

const fs = require('fs')
const proc = require('child_process')
const argv = require('minimist')(process.argv.slice(2))
const { platform, stage='Staging' } = argv
if (platform !== 'ios' && platform !== 'android') {
  throw new Error('expected --platform "ios" or "android"')
}

if (stage !== 'Staging' && stage !== 'Production') {
  throw new Error('expected --stage "Staging" or "Production"')
}

const releaseDir = require('./build-utils').getReleaseDir({ platform })
if (!fs.existsSync(releaseDir)) {
  throw new Error(`expected to find release dir: ${releaseDir}`)
}

const pushLine = `code-push release tim-${platform} ${releaseDir} ${threePartVersion} -d ${stage}`
console.log(`running: ${pushLine}`)

if (process.argv.indexOf('--dry-run') === -1) {
  proc.execSync(pushLine, {
    cwd: process.cwd(),
    env: process.env,
    stdio: 'inherit'
  })
}
