
function importHelper (Component) {
  return (!Component.prototype && Component.default)
    ? Component.default
    : Component
}

module.exports = {
  get Accordion() { return importHelper(require('./Accordion')) },
  get ActionSheet() { return importHelper(require('./ActionSheet')) },
  get ActivityIndicator() { return importHelper(require('./ActivityIndicator')) },
  get ArticleView() { return importHelper(require('./ArticleView')) },
  get AvivaIntroView() { return importHelper(require('./AvivaIntroView')) },
  get BackgroundImage() { return importHelper(require('./BackgroundImage')) },
  get BlinkID() { return importHelper(require('./BlinkID')) },
  get CameraView() { return importHelper(require('./CameraView')) },
  get ChatContext() { return importHelper(require('./ChatContext')) },
  get ChatMessage() { return importHelper(require('./ChatMessage')) },
  get ContextChooser() { return importHelper(require('./ContextChooser')) },
  get ConversationsIcon() { return importHelper(require('./ConversationsIcon')) },
  get EnumList() { return importHelper(require('./EnumList')) },
  get FadeInView() { return importHelper(require('./FadeInView')) },
  get FormErrorRow() { return importHelper(require('./FormErrorRow')) },
  get FormMessageRow() { return importHelper(require('./FormMessageRow')) },
  get FormRequestRow() { return importHelper(require('./FormRequestRow')) },
  get Geometry() { return importHelper(require('./Geometry')) },
  get GridItemsList() { return importHelper(require('./GridItemsList')) },
  get HomePageMixin() { return importHelper(require('./HomePageMixin')) },
  get IdentitiesList() { return importHelper(require('./IdentitiesList')) },
  get ImageInput() { return importHelper(require('./ImageInput')) },
  get LockScreen() { return importHelper(require('./LockScreen')) },
  get Log() { return importHelper(require('./Log')) },
  get MessageList() { return importHelper(require('./MessageList')) },
  get MessageRow() { return importHelper(require('./MessageRow')) },
  get MessageTypeRow() { return importHelper(require('./MessageTypeRow')) },
  get MessageView() { return importHelper(require('./MessageView')) },
  get MobileAccordion() { return importHelper(require('./MobileAccordion')) },
  get MyProductMessageRow() { return importHelper(require('./MyProductMessageRow')) },
  get NetworkInfoProvider() { return importHelper(require('./NetworkInfoProvider')) },
  get NewItem() { return importHelper(require('./NewItem')) },
  get NewResource() { return importHelper(require('./NewResource')) },
  get NewResourceMixin() { return importHelper(require('./NewResourceMixin')) },
  get NoBacksies() { return importHelper(require('./NoBacksies')) },
  get NoResources() { return importHelper(require('./NoResources')) },
  get PageView() { return importHelper(require('./PageView')) },
  get PasswordCheck() { return importHelper(require('./PasswordCheck')) },
  get PhotoCarousel() { return importHelper(require('./PhotoCarousel')) },
  get PhotoCarouselMixin() { return importHelper(require('./PhotoCarouselMixin')) },
  get PhotoList() { return importHelper(require('./PhotoList')) },
  get PhotoView() { return importHelper(require('./PhotoView')) },
  get ProductChooser() { return importHelper(require('./ProductChooser')) },
  get ProgressInfo() { return importHelper(require('./ProgressInfo')) },
  get QRCode() { return importHelper(require('./QRCode')) },
  get QRCodeScanner() { return importHelper(require('./QRCodeScanner')) },
  get RemediationItemsList() { return importHelper(require('./RemediationItemsList')) },
  get ResourceList() { return importHelper(require('./ResourceList')) },
  get ResourceMixin() { return importHelper(require('./ResourceMixin')) },
  get ResourceRow() { return importHelper(require('./ResourceRow')) },
  get ResourceTypesScreen() { return importHelper(require('./ResourceTypesScreen')) },
  get ResourceView() { return importHelper(require('./ResourceView')) },
  get RowMixin() { return importHelper(require('./RowMixin')) },
  get SearchBar() { return importHelper(require('./SearchBar')) },
  get ShowPropertiesView() { return importHelper(require('./ShowPropertiesView')) },
  get ShowRefList() { return importHelper(require('./ShowRefList')) },
  get SimpleModal() { return importHelper(require('./SimpleModal')) },
  get SupervisoryView() { return importHelper(require('./SupervisoryView')) },
  get SupervisoryViewPerProvider() { return importHelper(require('./SupervisoryViewPerProvider')) },
  get TimHome() { return importHelper(require('./TimHome')) },
  get TouchIDOptIn() { return importHelper(require('./TouchIDOptIn')) },
  get VerificationButton() { return importHelper(require('./VerificationButton')) },
  get VerificationMessageRow() { return importHelper(require('./VerificationMessageRow')) },
  get VerificationRow() { return importHelper(require('./VerificationRow')) },
  get VerificationView() { return importHelper(require('./VerificationView')) },
  get VerifierChooser() { return importHelper(require('./VerifierChooser')) },
  get VideoPlayer() { return importHelper(require('./VideoPlayer')) },
  get makeStylish() { return importHelper(require('./makeStylish')) }
}
