target 'Tradle-dev' do
  pod 'React', subspecs: [
    'RCTActionSheet',
    'RCTGeolocation',
    'RCTImage',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ], path: '../node_modules/react-native'

  pod 'AnylineReact', path: '../node_modules/anyline-ocr-react-native-module/ios'
  pod 'PPBlinkID', '~> 2.5.1'
end
