platform :ios, '9.0'
target 'Tradle' do

  # otherwise get errors like: 'duplicate symbol _GTMNSDataZlibRemainingBytesKey in: ...libGoogleToolboxForMac.a'
  # use_frameworks!

#  pod 'PPBlinkID', '4.5.0'
  pod 'DocumentReader', '~> 5.1'
  pod 'DocumentReaderFull', '~> 5.1'
  pod 'Branch', '0.27.1'

# DocumentReader 5.1.1194
# DocumentReaderFull 5.1.2749

#  pod 'Firebase/Core', '4.13.0'
#  pod 'FirebaseAnalytics', '4.2.0'
#  pod 'iProov', :git => 'https://github.com/iProov/iproov-ios-pod.git'
#  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

#  pod 'Firebase', '~> 3.16', :subspecs => [
#    'Analytics'
#  ]

#  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

end


