module.exports = {
  "searchSomething": "{1} অনুসন্ধান করুন",
  "invalidPattern": "ভুল প্যাটার্ন",
  "enterCurrentPassword": "আপনার বর্তমান পাসওয়ার্ডটি প্রবেশ করান",
  "drawYourOldPassword": "আপনার পুরানো প্যাটার্ন আঁকুন",
  "iproovFailedMessage": "অনুগ্রহপূর্বক আবার চেষ্টা করুন. সেরা ফলাফলগুলির জন্য, রঙ ফুটোয়ের সময় আপনার মুখটি ডিম্বাকৃতিতে কেন্দ্রীভূত রাখুন।",
  "help": "সাহায্য করুন",
  "drawYourNewPassword": "একটি নতুন প্যাটার্ন আঁকা",
  "learnMoreDescriptionTo": "আপনার ডিভাইস সংযুক্ত না থাকলেও আপনি অফলাইন মোডে বার্তাগুলি লিখতে পারেন। যখন আপনি পুনরায় সংযোগ স্থাপন করবেন তখন স্বয়ংক্রিয়ভাবে {1} এ স্বয়ংক্রিয়ভাবে পাঠানো হবে।",
  "shareContext": "{1} ভাগ করুন",
  "providerIsOffline": "{1} অফলাইনে আছে",
  "setNewPassword": "একটি নতুন পাসওয়ার্ড পছন্দ করুন",
  "temporarilyLocked": "আপনার সুরক্ষা জন্য, এই অ্যাপ্লিকেশনটি অস্থায়ীভাবে {1} জন্য লক করা হয়েছে",
  "settings": "সেটিংস",
  "overviewOfApplications": "অ্যাপ্লিকেশনগুলির সংক্ষিপ্ত বিবরণ",
  "restartApp": "অ্যাপ্লিকেশন পুনরায় চালু করুন",
  "formListErrorDescription": "গ্রাহক একটি অ্যাপ্লিকেশন শুরু একবার ফর্ম অনুরোধ করা যেতে পারে",
  "youShallNotPass": "তুমি যাবে না!",
  "sendEditRequestPrompt": "{1} এ সম্পাদনা অনুরোধ পাঠাও?",
  "gestureNotRecognized": "ভুল প্যাটার্ন",
  "offlineMode": "অফলাইন ফ্যাশন",
  "done": "সম্পন্ন",
  "iproovErrorTitle": "ওহো! কিছু ভুল হয়েছে",
  "back": "পিছনে",
  "theMinValueBiggerThenMaxValue": "পরিসরের জন্য মিন মানটি তখন সর্বোচ্চ মানের হওয়া উচিত",
  "backTo": "{1} -এ ফিরে যান",
  "contextsFor": "জন্য কনটেক্সট",
  "ukLicenseUnsupported": "ইউ কে ড্রাইভার লাইসেন্স স্ক্যানিং এই সময়ে সমর্থিত নয়",
  "testForgetMe": "এটি এই প্রদানকারীর সাথে সব যোগাযোগ রিসেট করার জন্য একটি পরীক্ষামূলক প্রক্রিয়া",
  "drawYourPasswordAgain": "আবার আপনার প্যাটার্ন আঁকা",
  "forgetMe": "আমাকে ভুলে যাও",
  "hello": "হ্যালো {1}!",
  "officialAccounts": "কথোপকথন",
  "importYourData": "আপনার ডেটা আমদানি করুন",
  "messageWaitingFrom": "আপনার {1} থেকে একটি নতুন বার্তা আছে",
  "correctGesture": "সঠিক প্যাটার্ন সনাক্ত",
  "invalidProperty": "অবৈধ {1}",
  "asSentTo": "হিসাবে প্রেরিত {1}",
  "ok": "ঠিক আছে",
  "drawYourPassword": "আপনার প্যাটার্ন আঁকুন",
  "iNeed": "আমার দরকার...",
  "confirmForgetMe": "আপনি কি নিশ্চিত যে আপনি '{1}' আপনাকে ভুলে যাবেন",
  "sentTo": "{1} এ পাঠানো হয়েছে",
  "initializingEngine": "ইঞ্জিন আরম্ভ",
  "setPassword": "একটি নিরাপদ পাসওয়ার্ড চয়ন করুন",
  "cancel": "বাতিল",
  "error": "এরর",
  "addServerUrl": "সার্ভার URL যোগ করুন",
  "pleaseRestartTIM": "TiM পুনরায় আরম্ভ করুন",
  "formListError": "অপ্রাপ্য",
  "asVerifiedBy": "{1} দ্বারা যাচাই হিসাবে",
  "digitalWealthPassport": "ডিজিটাল সম্পদ পাসপোর্ট",
  "passwordsDontMatch": "পাসওয়ার্ড মেলে না",
  "invalidDocument": "অবৈধ দস্তাবেজ",
  "formRequest": "{1} এর জন্য অনুরোধ",
  "details": "বিস্তারিত",
  "sharedWith": "{2} সাথে ভাগ করা {1} প্রেক্ষাপট",
  "restartingApp": "অ্যাপ্লিকেশনটি মুহূর্তে পুনরায় চালু হবে",
  "validationErrors": "দয়া করে যাচাইকরণের ব্যর্থতা ক্ষেত্রগুলি সঠিক করুন",
  "edit": "সম্পাদন করা",
  "enterYourName": "আপনার নাম প্রবেশ করুন",
  "passwordLimitations": "প্যাটার্নে 5+ পয়েন্ট থাকতে হবে",
  "turnTouchIdOn": "টাচ আইডি চালু করুন",
  "iproovFailedTitle": "ওহো! কিছু ভুল হয়েছে",
  "pleaseDrawPassword": "আপনার প্যাটার্ন আঁকুন",
  "thisValueIsInvalidPlaceholder": "এই মানটি অবৈধ কারণ ...",
  "backToResults": "ফলাফলগুলি ফিরে যান",
  "search": "অনুসন্ধান",
  "patternNotMatching": "নিদর্শন মেলে না।",
  "issuedBy": "{1} দ্বারা ইস্যু করা",
  "bothOn": "উভয়ই চালু আছে",
  "trustedProviders": "বিশ্বস্ত প্রদানকারী",
  "unreadMessages": "আপনার অপঠিত বার্তা আছে",
  "importingData": "{1} নথি {2} থেকে আমদানি করা হচ্ছে",
  "continue": "চালিয়ে",
  "thePropertyWithMinMaxRangeError": "[সর্বনিম্ন সর্বোচ্চ] সীমার সঙ্গে সম্পত্তির মাত্র দুটি সংখ্যা থাকতে পারে",
  "thisFieldIsRequired": "ঘরটি অবশ্যই পূরণ করতে হবে",
  "no": "না",
  "wrongPattern": "ভুল প্যাটার্ন",
  "viewDebugLog": "ডিবাগ লগ দেখুন",
  "touchIdOn": "স্পর্শ আইডি চালু আছে",
  "unlockDevice": "এগিয়ে যাওয়ার জন্য আপনার ডিভাইস আনলক করুন",
  "yes": "হাঁ",
  "multientryToShare": "ভাগ করার জন্য {1} দস্তাবেজ রয়েছে",
  "nothingToShare": "শেয়ার করতে কিছুই নেই",
  "somethingWrongSubmitLog": "কিছু ভুল হয়েছে বলে মনে হয়। দয়া করে {APPName} বিকাশকারী দলের ডিবাগ লগ জমা দিন",
  "youAreTheRM": "আপনি এই অ্যাপ্লিকেশনের জন্য সম্পর্ক পরিচালক",
  "generatingKeys": "আপনার ব্যক্তিগত কীগুলি তৈরি করা",
  "drawYourNewPasswordAgain": "আবার নতুন প্যাটার্ন আঁকুন",
  "testProviders": "স্যান্ডবক্স",
  "verifyPrompt": "যাচাই করবেন?",
  "pleaseCorrectFields": "নিম্নলিখিত ক্ষেত্র সংশোধন করুন: {1}",
  "pairDevices": "জোড়া ডিভাইস",
  "formChooser": "ফর্ম তালিকা",
  "verifierHelp": "ফর্মটি পর্যালোচনা করার পরে 'সম্পন্ন' বোতামটি ক্লিক করুন কিছু ক্ষেত্র সংশোধন প্রয়োজন হলে তাদের প্রথমে চেক করুন এবং তারপর 'সম্পন্ন' বাটন ক্লিক করুন",
  "centerPassport": "ফ্রেম কেন্দ্র পাসপোর্ট ছবির পৃষ্ঠা",
  "storageCorrupted": "আপনার ব্রাউজারের সঞ্চয় ক্ষতিগ্রস্ত হয়েছে! অ্যাপের পরিচয় এবং সঞ্চয়স্থান পুনরায় সেট করতে ওকে চাপুন।",
  "approveApplicationFor": "{1} এর জন্য অ্যাপ্লিকেশনটি অনুমোদন করুন",
  "shareMyProduct": "{2} সাথে {2} ভাগ করার জন্য আপনি নীচে আলতো চাপতে পারেন",
  "en": "ইংরেজি",
  "authenticationFailed": "প্রমাণীকরণ ব্যর্থ হয়েছে",
  "iproovErrorMessage": "দয়া করে একটু অপেক্ষা করুন এবং আবার চেষ্টা করুন",
  "noScanningOnAndroid": "অ্যান্ড্রয়েডের নথি স্ক্যানিং শীঘ্রই আসছে।",
  "profile": "প্রোফাইলের",
  "verifiedByOn": "{1} দ্বারা যাচাই করা হয়েছে",
  "next": "পরবর্তী",
  "invalidPairingRequest": "অবৈধ জুতা অনুরোধ",
  "youAreAboutToShare": "আপনি ভাগ করতে চলেছেন\n '{1}'\n কাগজপত্র",
  "unknownQRCodeFormat": "অচেনা QR কোড ফর্ম্যাট",
  "shareWith": "{1} ভাগ করুন",
  "fromMyData": "'আমার ডেটা' থেকে",
  "pleaseCorrect": "সংশোধন করুন",
  "areYouSureYouWantToServeThisCustomer": "আপনি এই গ্রাহক পরিবেশন করতে চান আপনি কি নিশ্চিত?",
  "shareOne": "বিকল্পভাবে, নীচে ভাগ করুন",
  "pleaseClickOnAddButton": "'{1}' যোগ করার জন্য নিচে '+' ক্লিক করুন",
  "learnMoreServerIsDown": "আপনি যে কোন বার্তাগুলি অনলাইনে লিখবেন সেগুলি স্বয়ংক্রিয়ভাবে {1} -এ প্রেরণ করা হবে।",
  "creationDate": "তারিখ তৈরী",
  "dataSecurity": "তথ্য নিরাপত্তা",
  "pleaseCorrectTheErrors": "অনুগ্রহ করে ফর্মটিতে ত্রুটি সংশোধন করুন",
  "receiveNotifications?": "আপনি বিজ্ঞপ্তি পেতে চান?",
  "independentBlockchainViewer": "স্বাধীন ব্লকচেন ভিউয়ার",
  "createNext": "অন্য ফর্মটি পূরণ করুন \"{1}\"",
  "sandboxDescription": "স্যান্ডবক্সে, সিমুলটেড সার্ভিস প্রোভাইডারের সাথে অ্যাপ্লিকেশন কিভাবে ব্যবহার করবেন তা শিখুন।",
  "centerID": "ফ্রেমে কেন্দ্র আইডি",
  "centerLicence": "ফ্রেমের কেন্দ্র লাইসেন্স",
  "customerWaiting": "{1} চ্যাটে প্রবেশ করেছে",
  "loadingModels": "লোড হচ্ছে মডেল",
  "updateAppTitle": "অ্যাপ্লিকেশান আপডেট উপলব্ধ",
  "shareAllPastAndFutureMessages": "নির্বাচিত প্রজন্মের সাথে এই প্রসঙ্গে সমস্ত অতীত ও ভবিষ্যতের বার্তাগুলি ভাগ করুন",
  "importDataPrompt": "আপনি আপনার ডেটা আমদানি করতে চান",
  "youAreForgotten": "আপনি সফলভাবে ভুলে গেছেন",
  "reviewScannedProperties": "নীচের তথ্য পর্যালোচনা এবং সংশোধন করুন",
  "scanQRcode": "স্ক্যান QR কোড",
  "neverMissAMessage": "একটি বার্তা মিস্ করবেন না",
  "useGesturePassword": "অঙ্গভঙ্গি পাসওয়ার্ড সক্ষম করুন",
  "fillTheFormWithAttachments": "দয়া করে এই ফর্মটি পূরণ করুন ** {1} **",
  "submitting": "জমা দেওয়া হচ্ছে",
  "cancelItem": "আপনি {1.} বাতিল করতে চলেছেন নিশ্চিত করতে টোকা দয়া করে ট্যাপ করুন",
  "nameUnknown": "নাম অজানা",
  "areYouSureYouWantToDelete": "আপনি কি {1} গোপন করতে চান?",
  "shareOne1": "{1}, এটি আপনার ব্যক্তিগত গোপনীয়তা সহকারী। আমি দেখতে পাচ্ছি আপনি ইতিমধ্যে আপনার {2} যাচাই করেছে। {3} এর সাথে ভাগ করার জন্য আপনি নীচে আলতো চাপতে পারেন।",
  "changeGesturePassword": "অঙ্গভঙ্গি পাসওয়ার্ড পরিবর্তন করুন",
  "createNew": "ফর্মটি পূরণ করুন \"{1}\"",
  "later": "পরবর্তীতে",
  "learnMoreDescription": "আপনার ডিভাইস সংযুক্ত না থাকলেও আপনি অফলাইন মোডে বার্তাগুলি লিখতে পারেন। যখন আপনি পুনরায় সংযোগ স্থাপন করবেন তখন স্বয়ংক্রিয়ভাবে আপনার বার্তা পাঠানো হবে।",
  "addNew": "নতুন যোগ করুন {1}",
  "shareOneOfMany": "বিকল্পভাবে, নীচে ভাগ করুন",
  "somethingWrong": "কিছু ভুল হয়েছে",
  "fieldErrorMessagePrompt": "এই ক্ষেত্রে কি ভুল?",
  "listOfProducts": "পণ্য তালিকা",
  "errorNotification": "ত্রুটি সংশোধন করার জন্য গ্রাহকের কাছে পাঠানো হয়েছে ত্রুটি",
  "acceptTermsAndConditions": "শর্তাবলী দেখুন",
  "approveApplication": "অ্যাপ্লিকেশন অনুমোদন",
  "learnMore": "আরও জানুন",
  "passwordOn": "অঙ্গভঙ্গি পাসওয়ার্ড চালু আছে",
  "receivedForm": "গৃহীত {1}",
  "resetRequired": "রিসেট প্রয়োজন",
  "acceptingTermsAndConditions": "ঠিক আছে টিপে, আপনি শর্তাদি এবং শর্তাবলী স্বীকার করেন",
  "installingUpdate": "আপডেট স্থাপন করা হচ্ছে",
  "oops": "ওহো",
  "updateNow": "এখন হালনাগাদ করুন",
  "incompatibleVersion": "সাম্প্রতিক পিছনের অসঙ্গতিপূর্ণ পরিবর্তনগুলির কারণে, এই আপডেটে অ্যাপ্লিকেশনের একটি হার্ড রিসেট প্রয়োজন। অ্যাপের পরিচয় এবং সঞ্চয়স্থান পুনরায় সেট করতে ওকে চাপুন।",
  "myDocuments": "আমার ডকুমেন্টস",
  "denyApplication": "অ্যাপ্লিকেশন অস্বীকার",
  "documentExpiredTitle": "দস্তাবেজ মেয়াদ শেষ হয়ে গেছে",
  "submittingModifiedForm": "{1} পরিবর্তন করা হচ্ছে",
  "cameraAccess": "ক্যামেরা অ্যাক্সেস",
  "noConnectionForNewProduct": "{1}, {appName} {2} অ্যাপ্লিকেশনটি পূরণ করার জন্য একটি ইন্টারনেট সংযোগ প্রয়োজন।",
  "turnPasswordOn": "অঙ্গভঙ্গি পাসওয়ার্ড চালু করুন",
  "deviceDoesNotHaveMyKeys": "প্রাপ্ত পরিচয়ের কাছে আমার কীগুলি নেই",
  "noNetwork": "কোনও নেটওয়ার্ক নেই",
  "noConnectionWillProcessLater": "{APPName} কে এই মুহূর্তে আপনার কোনও ইন্টারনেট সংযোগের প্রয়োজন নেই। সংযোগ স্থাপন করা হলে অনুরোধ প্রক্রিয়া হবে",
  "receivedVerification": "{1} জন্য যাচাই প্রাপ্ত",
  "viewTerms": "শর্তাবলী এবং শর্তাবলী দেখুন দয়া করে",
  "willBeAvailable": "এই কার্যকারিতা শীঘ্রই পাওয়া যাবে",
  "holdPhoneToPassportBackCover": "আপনার পাসপোর্টের ভেতরের পিছনের ভেতরে আপনার ফোনের পিছনটি ধরে রাখুন।",
  "termsAndConditions": "শর্তাবলী.",
  "textPasswordLimitations": "10+ অক্ষর থাকা আবশ্যক, কমপক্ষে একটি বড় হাতের অক্ষর, ছোট হাতের অক্ষর, সংখ্যা এবং বিশেষ অক্ষর",
  "retryScanning": "যে ছিল একটি {1}? আমি বলতে পারলাম না অনুগ্রহপূর্বক আবার চেষ্টা করুন?\n\nসেরা ফলাফলগুলির জন্য, আড়াআড়ি মোড ব্যবহার করুন, একদৃষ্টি এড়িয়ে যান, এবং দেখানো ফ্রেমের মধ্যে নথির অবস্থানটি নিশ্চিত করুন।",
  "receivedProduct": "গৃহীত {1}",
  "hideResource": "{1} লুকান",
  "holdPhoneToPassport": "আপনার পাসপোর্টের সামনে কভারটির বিরুদ্ধে আপনার ফোনটি পিছনে রাখুন",
  "noConnectionForPL": "{appName} থেকে {1} পণ্যগুলির একটি তালিকা অনুরোধ করার জন্য একটি সক্রিয় ইন্টারনেট সংযোগের প্রয়োজন হয় যা এই মুহূর্তে আপনার কাছে নেই",
  "useTouchId": "টাচ আইডি সক্ষম করুন",
  "youReviewedAll": "আপনি সমস্ত {1} পর্যালোচনা",
  "sharedForm": "{2} থেকে {1} শেয়ার করা হয়েছে",
  "issuedByOn": "{1} দ্বারা ইস্যু করা হয়েছে",
  "scanningFailedTryAgain": "স্ক্যান করা অসফল ছিল। আপনি আবার চেষ্টা করুন?",
  "switchTouchIdOff": "সুইচ স্পর্শ আইডি বন্ধ",
  "verificationTransactionID": "যাচাইকরণ লেনদেন আইডি",
  "enterPassword": "আপনার পাসওয়ার্ড লিখুন",
  "pairingRequestWasProcesseed": "জুতা অনুরোধ প্রক্রিয়া ছিল",
  "updateAppMessage": "এখন আপডেট করুন, বা আমি আপনাকে পরে মনে করিয়ে দিতে হবে?",
  "useTouchIdAndGesturePassword": "টাচ আইডি এবং অঙ্গভঙ্গি সক্ষম করুন",
  "fillRequiredFields": "সমস্ত প্রয়োজনীয় ক্ষেত্রগুলি পূরণ করুন",
  "takeAPicture": "আপনার মুখের একটি ** স্বতন্ত্র ** ছবি নিতে দয়া করে",
  "newProduct": "নতুন পণ্য",
  "submitLog": "লগ জমা দিন",
  "importing": "আমদানি হচ্ছে",
  "verifiedBy": "{1} দ্বারা যাচাই করা হয়েছে",
  "pairingRequest": "জুতা অনুরোধ",
  "inProgress": "আপনার অনুরোধ চলছে",
  "noAccessToServer": "সার্ভার অ্যাক্সেসযোগ্য নয় পরে চেষ্টা করুন।",
  "add": "{1} যোগ করুন",
  "switchToRepresentative": "প্রতিনিধি মোডে স্যুইচ করা এখনও বাস্তবায়িত হয়নি।",
  "invalidDeepLink": "মনে হচ্ছে আপনি একটি অবৈধ লিঙ্ক ক্লিক করেছেন!",
  "documentNotScanning": "কিছু ভুল হয়েছে!",
  "tapToRemovePhotos": "ফটোগুলি সরাতে আলতো চাপুন",
  "nothingChanged": "কিছুই পরিবর্তন করেনি",
  "contactUs": "আমাদের সাথে যোগাযোগ করুন",
  "newContactRequest": "{1} আপনাকে যোগাযোগের অনুরোধ পাঠিয়েছে",
  "confirmAllItems": "সবগুলি নিশ্চিত করার জন্য ঠিক আছে আলতো চাপুন, অথবা পর্যালোচনা চালিয়ে যাওয়ার জন্য বাতিল করুন",
  "denyApplicationFor": "{1} এর জন্য আবেদন প্রত্যাখ্যান করুন",
  "setDateValue": "সেট",
  "shareChangesWith": "সঙ্গে পরিবর্তন ভাগ করুন",
  "verificationBy": "{1} দ্বারা যাচাইকরণ",
  "addAnotherFormOrGetNext": "অন্য {1} যোগ করুন বা পরবর্তী ফর্মটি সরাবেন",
  "areYouSureYouWantToConfirmAllItems": "সব {1} নিশ্চিত করার জন্য ঠিক আছে আলতো চাপুন, বা পর্যালোচনার জন্য বাতিল করুন",
  "shareOneOfMany1": "{1}, এটি আপনার ব্যক্তিগত গোপনীয়তা সহকারী। আমি দেখতে পাচ্ছি আপনি ইতিমধ্যে আপনার {2} যাচাই করেছে। আপনি {3} এর সাথে ভাগ করার জন্য নীচের তালিকাটিতে যেকোনো আইটেমে আলতো চাপতে পারেন।",
  "areYouSureAboutNextForm": "আপনি কি {1} সাথে সম্পন্ন হয়েছেন?",
  "youReviewed": "{2} আইটেমগুলি থেকে আপনি {1} পর্যালোচনা করেছেন",
  "importData": "তারিখগুলি আমদানি করুন",
  "enableCameraAccess": "{APPName} বর্তমানে ক্যামেরা ব্যবহার করার অনুমতি নেই অ্যাক্সেস মঞ্জুর করতে, সেটিংস চয়ন করুন, এবং নিশ্চিত করুন ক্যামেরা সক্ষম করা আছে।",
  "youShared": "আপনি {1} থেকে ভাগ করেছেন",
  "switchTouchIdOn": "স্পর্শ আইডি চালু করুন",
  "newProductMsg": "আমি একটি {1} প্রয়োজন।",
  "documentExpiredMessage": "একটি বৈধ নথি স্ক্যান করুন দয়া করে",
  "fillTheForm": "দয়া করে এই ফর্মটি পূরণ করুন ** {1} **",
  "showQR": "আমার QR কোড",
  "noConnection": "{APPName} কে এই মুহূর্তে আপনার কোনও ইন্টারনেট সংযোগের প্রয়োজন নেই",
  "tooManyPasswordAttempts": "অনেক গুলো ব্যর্থ চেষ্টা! এই ফর্মটি অক্ষম করা হয়েছে।",
  "optional": "ঐচ্ছিক",
  "cancelHideResource": "{1} লুকান",
  "correctPassword": "ওহ, মনে আছে!",
  "serverIsUnreachable": "সার্ভারটি অপ্রচলিত",
  "sponsoredBy": "সৌজন্যে",
  "sourcesBy": "{1} দ্বারা সূত্র",
  "applyForProduct": "একটি পণ্যের জন্য আবেদন",
  "invalidPropertyValue": "অবৈধ মান",
  "confirmedMyData": "সমস্ত আমদানি করা ডেটা আপনার {profileTitle} এ দেখা যাবে",
  "sharedContext": "ভাগ করা প্রসঙ্গ",
  "loadingResources": "সম্পদ লোড হচ্ছে",
  "changePassword": "পাসওয়ার্ড পরিবর্তন করুন",
  "shareProduct": "{2} সাথে {2} ভাগ করার জন্য আপনি নীচে আলতো চাপতে পারেন",
  "homePage": "বাড়ি",
  "enablePasscodeFirst": "মনে হচ্ছে আপনি একটি ডিভাইস পাসকোড সক্ষম না। এটি ছাড়া, এই অ্যাপ্লিকেশন আপনার ডেটা রক্ষা করতে পারে না! OK টিপে আগে এটি সক্রিয় করুন",
  "sentToOn": "{1} -এ পাঠানো হয়েছে",
  "nl": "ডাচ",
  "pleaseTapOnMenu": "দয়া করে লাল বোতামটি ট্যাপ করুন এবং",
  "confirmRevoke": "এই নথিটি তাদের রেকর্ড থেকে মুছে ফেলতে {1} জিজ্ঞাসা করুন?",
  "irrefutableProofs": "অনিবার্য প্রমাণ",
  "turnBothOn": "উভয় চালু করুন",
  "typeMessage": "একটি বার্তা টাইপ করুন",
  "enablePassword": "পাসওয়ার্ড সক্ষম করুন",
  "downloadingUpdate": "একটি আপডেট ডাউনলোড করা হচ্ছে ...",
  "areYouSureAboutWipe": "এই কর্মটি অপরিবর্তনীয়। আপনি আপনার সমস্ত তথ্য এবং ব্যক্তিগত কী হারাবেন। আপনি কি নিশ্চিত আপনি সামনে এগুতে চান?",
  "submittingForm": "Submittted {1}",
  "bookmarks": "বুকমার্ক",
  "exploreData": "ডেটা অন্বেষণ",
  "Please scan your": "আপনার স্ক্যান স্ক্যান করুন",
  "ID document": "আইডি নথি",
  "Please fill out the form": "ফর্মটি পূরণ করুন",
  "See our list of products": "আমাদের পণ্য তালিকা দেখুন",
  "Our products have changed": "আমাদের পণ্য পরিবর্তন হয়েছে",
  "Please take a selfie to prove this is your document. Center your face.": "আপনার নথিটি প্রমাণ করার জন্য দয়া করে একটি স্বতন্ত্র করুন। আপনার মুখ কেন্দ্র",
  "Choose Apply for Product from the menu": "মেনু থেকে পণ্য জন্য আবেদন চয়ন করুন",
  "Application submitted!": "আবেদন জমা দেওয়া!",
  "Sending": "পাঠানো হচ্ছে",
  "Please tap here and sign": "দয়া করে এখানে ট্যাপ করুন এবং সাইন ইন করুন",
  "Give me a moment...": "আমাকে একটি মুহূর্ত দিন ...",
  "Please click to scan your": "আপনার স্ক্যান স্ক্যান করতে ক্লিক করুন",
  "' photo of yourself that I can match against your ID document": "'নিজের ছবি যে আমি আপনার আইডি নথি বিরুদ্ধে ম্যাচ করতে পারেন",
  "Thank you. Now take a '": "ধন্যবাদ. এখন একটি '",
  "pleaseSign": "দয়া করে ধূসর বাক্সের ভিতরে সাইন ইন করুন",
  "getStarted": "এবার শুরু করা যাক",
  "goodNewsFew": "ভাল খবর! আপনি ইতিমধ্যে বেশ কয়েক আছে। নীচের টোক আইকন শেয়ার করতে।",
  "goodNews": "ভাল খবর! আপনার কাছে ইতিমধ্যে {1} আছে। নীচের আইকন টোকেন শেয়ার করতে",
  "Cancel": "বাতিল",
  "Submit": "জমা দিন",
  "Clear": "পরিষ্কার",
  "retake": "পুনরায় নেওয়া",
  "usePhoto": "ফটো ব্যবহার করুন",
  "Deny": "অস্বীকার করা",
  "Approve": "অনুমোদন করা",
  "loading": "লোড হচ্ছে ...",
  "Verifications": "যাচাইকরণ",
  "Seals": "সীল",
  "Applications": "অ্যাপ্লিকেশন",
  "checkIfMatch": "চেক করুন যদি ম্যাচ",
  "Corporation Exists Checks": "কর্পোরেশন চেক বিদ্যমান",
  "createManualMatchCheck": "ম্যানুয়াল ম্যাচ চেক তৈরি করুন",
  "Ready for friendliness?": "বন্ধুত্বের জন্য প্রস্তুত?",
  "Get set for friendliness?": "বন্ধুত্বের জন্য সেট পেতে?",
  "Go friendliness!": "বন্ধুত্ব যান!",
  "Take a quick tour of chat bot?": "চ্যাট বিট একটি দ্রুত সফর নিন?",
  "Finally, you will be in control of your own private information!": "অবশেষে, আপনি নিজের ব্যক্তিগত তথ্য নিয়ন্ত্রণে থাকবেন!",
  "Ready?": "প্রস্তুত?",
  "Go!": "যান!",
  "Get set": "সেট করুন",
  "Before we start you'll need a valid passport, identity card or driving license": "শুরু করার আগে আপনাকে বৈধ পাসপোর্ট, পরিচয়পত্র বা ড্রাইভিং লাইসেন্সের প্রয়োজন হবে",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "আমরা আপনাকে চ্যাটে জিজ্ঞাসা করব এবং আপনি কেবল ফর্মগুলি পূরণ করুন বা অনুরোধগুলি অনুসরণ করুন",
  "Skip": "লাফালাফি করা",
  "Done": "সম্পন্ন",
  "Next": "পরবর্তী",
  "Sanctions Checks": "নিষেধাজ্ঞা চেক",
  "inProcess": "প্রক্রিয়াধীন...",
  "networkFailure": "আমি কিছু নেটওয়ার্ক সমস্যা সম্মুখীন করছি। আপনি চেক এবং তারপর আবার চেষ্টা করুন / বাতিল আলতো চাপুন",
  "invalidQuery": "ওহো, আমরা আপনার অনুসন্ধান চালানোর একটি ত্রুটি আঘাত। আমাদের ডেভেলপাররা এটি অ্যাসপ ঠিক করার চেষ্টা করবে।",
  "validatingDataClaim": "তথ্য আমদানি করা হচ্ছে",
  "invalidQR": "অবৈধ QR কোড",
  "debugLogSent": "ডিবাগ লগ প্রেরিত",
  "failedToSendLog": "লগ পাঠাতে ব্যর্থ",
  "logSentToDevTeam": "লগ ট্রেন্ডেল বিকাশকারী দল পাঠানো হয়েছিল",
  "noResourcesForCriteria": "কোন সম্পদ এই মানদণ্ডের জন্য পাওয়া যায় নি",
  "supportedQrCodes": "সমর্থিত QR কোডগুলি:\n1) চ্যাট চ্যানেল যোগ করুন\n2) আমদানি তথ্য",
  "reviewScannedPropertiesAndSecondSideSnapshot": "নীচের ডেটা পর্যালোচনা করুন এবং দস্তাবেজের {1} পাশের স্ন্যাপশট নিন",
  "documentBackSide": "কেন্দ্র দল ফিরে পাশ",
  "Photo": "ছবি",
  "doYouWantToContinue": "আপনি কি এটিতে স্যুইচ করতে চান এবং সেখানে থেকে যেতে চান?",
  "startedByAnotherEmployee": "{1} এর জন্য আবেদনটি অন্য কর্মচারী দ্বারা শুরু হয়েছিল",
  "reviewData": "পর্যালোচনা তথ্য",
  "afterRefresh": "আপনি বাধা ছাড়া আমাদের সেবা ব্যবহার করার জন্য সাফ করা হয়",
  "requestMyData": "আমার তথ্য অনুরোধ",
  "newCustomer": "নতুন গ্রাহক",
  "areYouSureYouAreDone": "আপনি এই সেশন শেষ করতে চান নিশ্চিত?",
  "resetApp": "অ্যাপ রিসেট করুন",
  "wrongDocumentTypePleaseTryAgain": "ভুল নথি টাইপ। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
  "invalidCountry": "অবৈধ দেশ স্ক্যান করা হয়েছে",
  "scanYourDocument": "আপনার নথি স্ক্যান করুন",
  "wipeTheAppData": "অ্যাপ্লিকেশন তথ্য মুছা",
  "enterPasswordOrWipeOutTheAppData": "পাসওয়ার্ড প্রবেশ করুন বা অ্যাপ্লিকেশন তথ্য মুছে ফেলুন",
  "pleaseChooseCountryAndDT": "প্রথমে দেশ এবং নথি টাইপ নির্বাচন করুন"
}