module.exports = {
  "backToResults": "Retour aux résultats",
  "hideResource": "Masquer {1}",
  "downloadingUpdate": "Téléchargement d'une mise à jour ...",
  "sharedForm": "Partagé {1} à partir de {2}",
  "customerWaiting": "{1} est entré dans le chat",
  "forgetMe": "Oublie moi",
  "verifierHelp": "Cliquez sur le bouton \"Terminé\" après avoir examiné le formulaire. Si certains champs nécessitent une correction, vérifiez-les d'abord, puis cliquez sur le bouton \"Terminé\".",
  "oops": "Oops",
  "youAreForgotten": "Vous avez été oublié avec succès",
  "verifiedBy": "Vérifié par {1}",
  "myDocuments": "Mes documents",
  "homePage": "Accueil",
  "learnMoreDescription": "Vous pouvez toujours écrire des messages en mode hors connexion même si votre appareil n'est pas connecté. Lorsque vous vous reconnectez, tous vos messages seront automatiquement envoyés.",
  "documentExpiredTitle": "Document expiré",
  "officialAccounts": "Conversations",
  "shareOne": "Alternativement, partagez ci-dessous",
  "pairDevices": "Dispositifs de paire",
  "useGesturePassword": "Activer le mot de passe gestuel",
  "testProviders": "bac à sable",
  "theMinValueBiggerThenMaxValue": "La valeur minimale de la plage doit être inférieure à la valeur maximale",
  "termsAndConditions": "Termes et conditions.",
  "thisValueIsInvalidPlaceholder": "cette valeur est invalide car ...",
  "en": "Anglais",
  "typeMessage": "Tapez un message",
  "shareOneOfMany": "Alternativement, partagez ci-dessous",
  "useTouchIdAndGesturePassword": "Activer l'ID tactile et le geste",
  "formChooser": "Liste de formulaires",
  "formListError": "Indisponible",
  "restartApp": "Redémarrer l'application",
  "learnMoreServerIsDown": "Tous les messages que vous écrivez seront automatiquement envoyés à {1} lorsqu'ils seront en ligne.",
  "invalidPropertyValue": "valeur invalide",
  "turnTouchIdOn": "Activer l'identifiant tactile",
  "receivedForm": "Reçu {1}",
  "acceptingTermsAndConditions": "En appuyant sur OK, vous acceptez les conditions générales",
  "contactUs": "Contactez nous",
  "willBeAvailable": "Cette fonctionnalité sera bientôt disponible",
  "turnBothOn": "Tourner tous les deux",
  "documentExpiredMessage": "Veuillez numériser un document valide",
  "add": "Ajouter {1}",
  "correctGesture": "Motif correct détecté",
  "scanQRcode": "Scannez le code QR",
  "help": "Aidez-moi",
  "shareContext": "Partager {1}",
  "updateNow": "Mettre à jour maintenant",
  "cancel": "Annuler",
  "ok": "D'accord",
  "neverMissAMessage": "Ne manquez jamais un message",
  "noNetwork": "Pas de réseau",
  "submittingModifiedForm": "Modifier {1}",
  "sendEditRequestPrompt": "Envoyer une demande de modification à {1}?",
  "addServerUrl": "Ajouter une URL de serveur",
  "formListErrorDescription": "Les formulaires peuvent être demandés une fois que le client commence une application",
  "shareWith": "Partager {1}",
  "tapToRemovePhotos": "Appuyez pour supprimer les photos",
  "bothOn": "Les deux sont ON",
  "listOfProducts": "Liste de produits",
  "youReviewedAll": "Vous avez passé en revue tous les {1}",
  "passwordLimitations": "Le motif doit avoir plus de 5 points",
  "takeAPicture": "S'il vous plaît prendre une photo ** selfie ** de votre visage",
  "asSentTo": "Comme envoyé à {1}",
  "settings": "Paramètres",
  "inProgress": "Votre demande est en cours",
  "continue": "Continuer",
  "verificationTransactionID": "ID de transaction de vérification",
  "touchIdOn": "Touch ID est activé",
  "documentNotScanning": "Oups, quelque chose a mal tourné!",
  "next": "Prochain",
  "searchSomething": "Rechercher {1}",
  "switchToRepresentative": "Le passage au mode représentatif n'est pas encore implémenté.",
  "correctPassword": "Aww, tu t'en souviens!",
  "switchTouchIdOn": "Changer l’identifiant tactile sur",
  "enablePasscodeFirst": "On dirait que vous n’avez pas de mot de passe de périphérique activé. Sans elle, cette application ne peut pas protéger vos données! Veuillez l'activer avant d'appuyer sur OK",
  "shareMyProduct": "Vous pouvez appuyer sur ci-dessous pour partager {1} avec {2}",
  "newProductMsg": "J'ai besoin d'un {1}.",
  "newProduct": "Nouveau produit",
  "acceptTermsAndConditions": "Afficher les termes et conditions",
  "nothingChanged": "Rien n'a changé",
  "errorNotification": "Une notification d'erreur a été envoyée au client pour corriger",
  "digitalWealthPassport": "Passeport numérique de richesse",
  "testForgetMe": "Ceci est un mécanisme de test pour réinitialiser toutes les communications avec ce fournisseur",
  "changeGesturePassword": "Changer le mot de passe du geste",
  "somethingWrongSubmitLog": "Quelque chose semble avoir mal tourné. Veuillez envoyer le journal de débogage à l'équipe de développeurs {appName}",
  "trustedProviders": "Fournisseurs de confiance",
  "ukLicenseUnsupported": "L'analyse du permis de conduire au Royaume-Uni n'est pas prise en charge pour le moment",
  "areYouSureYouWantToConfirmAllItems": "Appuyez sur OK pour confirmer tout {1}, ou sur Annuler pour continuer la révision.",
  "switchTouchIdOff": "Désactiver l'ID tactile",
  "drawYourPasswordAgain": "Dessine ton patron à nouveau",
  "turnPasswordOn": "Activer le mot de passe gestuel",
  "viewTerms": "Veuillez consulter les conditions générales",
  "pleaseCorrect": "Corrigez s'il vous plaît",
  "pairingRequestWasProcesseed": "La demande d'appariement a été traitée",
  "done": "Terminé",
  "showQR": "Mon code QR",
  "search": "Chercher",
  "submittingForm": "Envoyé {1}",
  "noConnectionWillProcessLater": "{appName} nécessite une connexion Internet qui ne fonctionne pas pour le moment. La demande sera traitée lorsqu'une connexion est établie",
  "issuedByOn": "Publié par {1} sur",
  "formRequest": "Demande de {1}",
  "useTouchId": "Activer l'ID tactile",
  "invalidPattern": "Mauvais modèle",
  "deviceDoesNotHaveMyKeys": "L'identité reçue n'a pas mes clés",
  "invalidDocument": "document invalide",
  "youReviewed": "Vous avez consulté {1} sur {2} articles",
  "applyForProduct": "Demander un produit",
  "pleaseCorrectFields": "Veuillez corriger les champs suivants: {1}",
  "thisFieldIsRequired": "Ce champ est requis",
  "receivedProduct": "Reçu {1}",
  "confirmAllItems": "Appuyez sur OK pour tous les confirmer ou sur Annuler pour continuer la révision.",
  "sourcesBy": "Sources par {1}",
  "confirmedMyData": "Toutes les données importées peuvent être visualisées dans votre {profileTitle}",
  "areYouSureAboutWipe": "Cette action est irréversible. Vous perdrez toutes vos données et clés privées. Êtes-vous sur de vouloir continuer?",
  "profile": "Profil",
  "edit": "modifier",
  "newContactRequest": "{1} vous a envoyé une demande de contact",
  "youShared": "Vous avez partagé à partir de {1}",
  "confirmForgetMe": "Êtes-vous sûr de vouloir \"{1}\" vous oublier",
  "asVerifiedBy": "Comme vérifié par {1}",
  "areYouSureAboutNextForm": "Êtes-vous sûr d'avoir fini avec {1}?",
  "cancelHideResource": "Annuler Masquer {1}",
  "setPassword": "Choisissez un mot de passe sécurisé",
  "receivedVerification": "Vérification reçue pour {1}",
  "receiveNotifications?": "Voulez-vous recevoir des notifications?",
  "invalidPairingRequest": "Demande d'appariement non valide",
  "addAnotherFormOrGetNext": "Ajouter un autre {1} ou passer au formulaire suivant",
  "enterPassword": "Tapez votre mot de passe",
  "shareOne1": "{1}, ceci est votre assistant personnel de confidentialité. Je vois que vous avez déjà fait vérifier votre {2}. Vous pouvez appuyer sur ci-dessous pour le partager avec {3}.",
  "unknownQRCodeFormat": "Format de code QR non reconnu",
  "optional": "optionnel",
  "somethingWrong": "Quelque chose a mal tourné",
  "nl": "néerlandais",
  "overviewOfApplications": "Vue d'ensemble des applications",
  "backTo": "Retour à {1}",
  "pleaseCorrectTheErrors": "Veuillez corriger l'erreur dans le formulaire",
  "pairingRequest": "Demande de jumelage",
  "issuedBy": "Publié par {1}",
  "fillTheFormWithAttachments": "Veuillez remplir ce formulaire ** {1} **",
  "submitLog": "Soumettre un journal",
  "error": "Erreur",
  "fillTheForm": "Veuillez remplir ce formulaire ** {1} **",
  "youAreAboutToShare": "Vous êtes sur le point de partager\n '{1}'\n documents",
  "dataSecurity": "Sécurité des données",
  "nameUnknown": "nom inconnu",
  "iproovErrorTitle": "Oops! Quelque chose a mal tourné",
  "importData": "Dates d'importation",
  "sponsoredBy": "Sponsorisé par",
  "no": "Non",
  "noConnection": "{appName} nécessite une connexion Internet fonctionnelle que vous n'avez pas pour le moment",
  "confirmRevoke": "Demander à {1} de supprimer ce document de leurs dossiers?",
  "hello": "Bonjour {1}!",
  "noConnectionForPL": "{appName} nécessite une connexion Internet active pour demander une liste des produits de {1} que vous n'avez pas pour le moment",
  "importDataPrompt": "Vous êtes sur le point d'importer vos données de",
  "centerPassport": "Centre photo passeport photo dans le cadre",
  "contextsFor": "Contextes pour",
  "verifyPrompt": "Vérifier?",
  "noConnectionForNewProduct": "{1}, {appName} nécessite une connexion Internet active pour remplir l'application {2}.",
  "enablePassword": "Activer le mot de passe",
  "providerIsOffline": "{1} est déconnecté",
  "sentTo": "Envoyé à {1}",
  "drawYourNewPasswordAgain": "Dessine le nouveau motif à nouveau",
  "pleaseRestartTIM": "Veuillez redémarrer TiM",
  "incompatibleVersion": "En raison de modifications récentes incompatibles, cette mise à jour nécessite une réinitialisation matérielle de l'application. Appuyez sur OK pour réinitialiser l'identité et le stockage de l'application.",
  "generatingKeys": "générer vos clés privées",
  "loadingModels": "modèles de chargement",
  "iproovErrorMessage": "S'il vous plaît attendez un peu et essayez à nouveau",
  "unreadMessages": "Vous avez des messages non lus",
  "setDateValue": "Ensemble",
  "shareProduct": "Vous pouvez appuyer sur ci-dessous pour partager {1} avec {2}",
  "initializingEngine": "moteur d'initialisation",
  "retryScanning": "Était-ce un {1}? Je ne pouvais pas le dire. Veuillez réessayer?\n\nPour de meilleurs résultats, utilisez le mode paysage, évitez les reflets et veillez à positionner le document dans le cadre indiqué.",
  "createNew": "Remplissez le formulaire \"{1}\"",
  "areYouSureYouWantToDelete": "Êtes-vous sûr de vouloir cacher {1}?",
  "creationDate": "Date créée",
  "holdPhoneToPassportBackCover": "Tenez le dos de votre téléphone contre la couverture arrière de votre passeport.",
  "serverIsUnreachable": "Le serveur est inaccessible",
  "storageCorrupted": "Le stockage de votre navigateur a été corrompu! Appuyez sur OK pour réinitialiser l'identité et le stockage de l'application.",
  "centerLicence": "Centre de licence dans le cadre",
  "cameraAccess": "Accès à la caméra",
  "sharedContext": "Contexte partagé",
  "pleaseClickOnAddButton": "Veuillez cliquer sur '+' ci-dessous pour ajouter '{1}'",
  "youAreTheRM": "Vous êtes le responsable des relations pour cette application",
  "importingData": "Importation de {1} documents à partir de {2}",
  "iproovFailedMessage": "Veuillez réessayer. Pour de meilleurs résultats, gardez votre visage centré dans l'ovale pendant les éclats de couleur.",
  "noScanningOnAndroid": "La numérisation de documents sur Android arrive bientôt.",
  "updateAppTitle": "Mise à jour de l'application disponible",
  "enableCameraAccess": "{appName} n'a actuellement pas l'autorisation d'utiliser la caméra. Pour accorder l'accès, choisissez Paramètres et assurez-vous que Caméra est activée.",
  "pleaseTapOnMenu": "S'il vous plaît appuyez sur le bouton rouge et",
  "approveApplication": "Approuver l'application",
  "back": "Arrière",
  "patternNotMatching": "Les motifs ne correspondaient pas.",
  "youShallNotPass": "Vous ne pouvez pas passer!",
  "approveApplicationFor": "Approuver l'application pour {1}",
  "shareAllPastAndFutureMessages": "Partager tous les messages passés et futurs dans ce contexte avec les parties sélectionnées",
  "wrongPattern": "Mauvais modèle",
  "pleaseDrawPassword": "Dessine ton motif",
  "unlockDevice": "déverrouiller votre appareil pour continuer",
  "nothingToShare": "Rien à partager",
  "learnMore": "Apprendre encore plus",
  "passwordOn": "Le mot de passe gestuel est activé",
  "fillRequiredFields": "S'il-vous-plaît remplissez tous les champs requis",
  "drawYourPassword": "Dessine ton motif",
  "installingUpdate": "Installation de mise à jour",
  "noAccessToServer": "Le serveur n'est pas accessible. Essayer plus tard.",
  "messageWaitingFrom": "Vous avez un nouveau message de {1}",
  "submitting": "Soumission",
  "sandboxDescription": "Dans le bac à sable, découvrez comment utiliser l'application avec des fournisseurs de services simulés.",
  "fromMyData": "de 'Mes données'",
  "areYouSureYouWantToServeThisCustomer": "Êtes-vous sûr de vouloir servir ce client?",
  "yes": "Oui",
  "importYourData": "Importez vos données",
  "reviewScannedProperties": "S'il vous plaît examiner et corriger les données ci-dessous",
  "restartingApp": "L'application va redémarrer momentanément",
  "invalidDeepLink": "On dirait que vous avez cliqué sur un lien invalide!",
  "setNewPassword": "Choisissez un nouveau mot de passe",
  "temporarilyLocked": "Pour votre protection, cette application a été temporairement verrouillée pour {1}",
  "createNext": "Remplissez un autre formulaire \"{1}\"",
  "loadingResources": "chargement des ressources",
  "importing": "Importer",
  "later": "Plus tard",
  "details": "Détails",
  "authenticationFailed": "Authentification échouée",
  "validationErrors": "Veuillez corriger les champs de validation échoués",
  "centerID": "Centre ID dans le cadre",
  "gestureNotRecognized": "Mauvais modèle",
  "changePassword": "Changer le mot de passe",
  "enterCurrentPassword": "Entrer votre mot de passe actuel",
  "enterYourName": "Entrez votre nom",
  "iNeed": "J'ai besoin...",
  "drawYourNewPassword": "Dessine un nouveau motif",
  "sharedWith": "Contexte partagé {1} avec {2}",
  "invalidProperty": "Invalide {1}",
  "shareOneOfMany1": "{1}, ceci est votre assistant personnel de confidentialité. Je vois que vous avez déjà fait vérifier votre {2}. Vous pouvez appuyer sur tous les éléments de la liste ci-dessous pour les partager avec {3}.",
  "viewDebugLog": "Afficher le journal de débogage",
  "sentToOn": "Envoyé à {1} sur",
  "shareChangesWith": "Partager les modifications avec",
  "fieldErrorMessagePrompt": "Qu'est-ce qui ne va pas dans ce domaine?",
  "thePropertyWithMinMaxRangeError": "La propriété avec la plage [min-max] ne peut avoir que deux nombres",
  "textPasswordLimitations": "Doit avoir plus de 10 caractères, au moins une lettre majuscule, une lettre minuscule, un chiffre et un caractère spécial",
  "learnMoreDescriptionTo": "Vous pouvez toujours écrire des messages en mode hors connexion même si votre appareil n'est pas connecté. Lorsque vous vous reconnectez, tous vos messages seront automatiquement envoyés à {1}.",
  "holdPhoneToPassport": "Tenez le dos de votre téléphone contre la couverture de votre passeport",
  "independentBlockchainViewer": "Spectateur indépendant",
  "scanningFailedTryAgain": "La numérisation a échoué. Pourriez-vous s'il vous plaît essayer à nouveau?",
  "multientryToShare": "Il y a {1} documents à partager",
  "denyApplication": "Refuser l'application",
  "iproovFailedTitle": "Oops! Quelque chose a mal tourné",
  "resetRequired": "Réinitialiser requis",
  "cancelItem": "Vous êtes sur le point d'annuler {1}. S'il vous plaît appuyez sur OK pour confirmer",
  "verificationBy": "Vérification par {1}",
  "denyApplicationFor": "Refuser l'application pour {1}",
  "offlineMode": "Mode hors ligne",
  "updateAppMessage": "Mettre à jour maintenant ou dois-je vous rappeler plus tard?",
  "drawYourOldPassword": "Dessine ton vieux motif",
  "tooManyPasswordAttempts": "Trop de tentatives échouées! Ce formulaire a été désactivé.",
  "irrefutableProofs": "Preuves irréfutables",
  "verifiedByOn": "Vérifié par {1} sur",
  "passwordsDontMatch": "Les mots de passe ne correspondent pas",
  "addNew": "Ajouter un nouveau {1}",
  "bookmarks": "Des signets",
  "exploreData": "Explorer les données",
  "Please scan your": "Veuillez scanner votre",
  "See our list of products": "Voir notre liste de produits",
  "Please fill out the form": "S'il vous plaît remplir le formulaire",
  "ID document": "Document d'identité",
  "Please take a selfie to prove this is your document. Center your face.": "Veuillez prendre un selfie pour prouver que c'est votre document. Centrez votre visage.",
  "Choose Apply for Product from the menu": "Choisissez Appliquer au produit dans le menu",
  "Our products have changed": "Nos produits ont changé",
  "Application submitted!": "Application déposée!",
  "Sending": "Envoi",
  "Please tap here and sign": "S'il vous plaît appuyez ici et signez",
  "Give me a moment...": "Accorde moi un instant...",
  "Please click to scan your": "Veuillez cliquer pour scanner votre",
  "Thank you. Now take a '": "Je vous remercie. Maintenant prends un",
  "' photo of yourself that I can match against your ID document": "'photo de toi que je peux associer à ton document d'identité",
  "pleaseSign": "Veuillez vous inscrire dans la case grise",
  "getStarted": "Commencer",
  "goodNewsFew": "Bonnes nouvelles! Vous en avez déjà plusieurs. Pour partager l'icône du robinet ci-dessous.",
  "goodNews": "Bonnes nouvelles! Vous avez déjà {1}. Pour partager, appuyez sur l'icône ci-dessous",
  "Cancel": "Annuler",
  "Submit": "Soumettre",
  "Clear": "Clair",
  "retake": "Reprendre",
  "usePhoto": "Utiliser la photo",
  "Approve": "Approuver",
  "Deny": "Nier",
  "loading": "Chargement...",
  "Applications": "Applications",
  "Verifications": "Vérifications",
  "Seals": "Scellés",
  "checkIfMatch": "Vérifiez si match",
  "Corporation Exists Checks": "La société a des chèques",
  "createManualMatchCheck": "Créer une vérification de correspondance manuelle",
  "Get set for friendliness?": "Préparez-vous à la convivialité?",
  "Take a quick tour of chat bot?": "Faites un tour rapide du chat bot?",
  "Go friendliness!": "Allez la gentillesse!",
  "Ready for friendliness?": "Prêt pour la convivialité?",
  "Finally, you will be in control of your own private information!": "Enfin, vous contrôlerez vos propres informations privées!",
  "Get set": "Se mettre",
  "Go!": "Aller!",
  "Ready?": "Prêt?",
  "Before we start you'll need a valid passport, identity card or driving license": "Avant de commencer, vous aurez besoin d'un passeport, d'une carte d'identité ou d'un permis de conduire valide",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Nous vous poserons des questions dans le chat et vous remplissez simplement les formulaires ou suivez les demandes",
  "Skip": "Sauter",
  "Next": "Prochain",
  "Done": "Terminé",
  "Sanctions Checks": "Contrôles de sanctions",
  "inProcess": "En cours...",
  "networkFailure": "Je rencontre des problèmes de réseau. Pouvez-vous vérifier puis appuyer sur Réessayer / Annuler",
  "invalidQuery": "Oups, nous rencontrons une erreur lors de l'exécution de votre recherche. Nos développeurs vont essayer de résoudre le problème dès que possible.",
  "noResourcesForCriteria": "Aucune ressource trouvée pour ce critère",
  "invalidQR": "Code QR invalide",
  "supportedQrCodes": "Codes QR pris en charge:\n1) ajouter un canal de discussion\n2) importer des données",
  "failedToSendLog": "Échec d'envoi du journal",
  "logSentToDevTeam": "Le journal a été envoyé à l'équipe de développeurs Tradle",
  "validatingDataClaim": "Importer des données",
  "debugLogSent": "Journal de débogage envoyé",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Veuillez examiner les données ci-dessous et prendre un instantané du côté {1} du document.",
  "documentBackSide": "Centrer le dos du document",
  "Photo": "Photo",
  "doYouWantToContinue": "Voulez-vous passer à cela et continuer à partir de là?",
  "startedByAnotherEmployee": "L'application pour {1} a été lancée par un autre employé.",
  "reviewData": "Revoir les données",
  "afterRefresh": "Vous êtes autorisé à utiliser nos services sans interruption",
  "requestMyData": "Demander mes données",
  "newCustomer": "Nouveau client",
  "areYouSureYouAreDone": "Êtes-vous sûr de vouloir terminer cette session?",
  "resetApp": "Réinitialiser l'application",
  "invalidCountry": "Pays invalide scanné",
  "scanYourDocument": "Veuillez numériser votre document",
  "wrongDocumentTypePleaseTryAgain": "Mauvais type de document. Veuillez réessayer",
  "wipeTheAppData": "Effacer les données de l'application",
  "enterPasswordOrWipeOutTheAppData": "Entrez le mot de passe ou effacez les données de l'application",
  "pleaseChooseCountryAndDT": "Choisissez d'abord le pays et le type de document"
}