module.exports = {
  "turnPasswordOn": "제스처 비밀번호 켜기",
  "searchSomething": "검색 {1}",
  "changePassword": "비밀번호 변경",
  "issuedBy": "{1}에 의해 발행 됨",
  "officialAccounts": "대화",
  "touchIdOn": "터치 ID가 켜짐",
  "backTo": "{1} (으)로 돌아 가기",
  "providerIsOffline": "{1}은 오프라인 상태입니다.",
  "drawYourNewPasswordAgain": "새 패턴을 다시 그립니다.",
  "search": "수색",
  "submittingForm": "제출 된 {1}",
  "fillTheForm": "이 양식을 작성하십시오 ** {1} **",
  "wrongPattern": "잘못된 패턴",
  "shareChangesWith": "변경 사항 공유",
  "asVerifiedBy": "{1}에 의해 확인 된대로",
  "sharedContext": "공유 컨텍스트",
  "overviewOfApplications": "응용 프로그램 개요",
  "learnMoreDescription": "장치가 연결되어 있지 않아도 오프라인 모드로 메시지를 쓸 수 있습니다. 다시 연결하면 모든 메시지가 자동으로 전송됩니다.",
  "drawYourPassword": "패턴 그리기",
  "correctGesture": "올바른 패턴이 감지되었습니다.",
  "invalidDocument": "유효하지 않은 문서",
  "issuedByOn": "에 의해 {1}에 발행 됨",
  "shareProduct": "아래에서 탭하여 {1}을 (를) {2}와 (과) 공유 할 수 있습니다.",
  "pleaseCorrectFields": "다음 필드를 수정하십시오 : {1}",
  "details": "세부",
  "passwordsDontMatch": "암호가 일치하지 않습니다.",
  "formChooser": "양식 목록",
  "showQR": "내 QR 코드",
  "tapToRemovePhotos": "사진을 삭제하려면 살짝 누르십시오.",
  "hello": "안녕하세요 {1}!",
  "drawYourPasswordAgain": "패턴 다시 그리기",
  "thisValueIsInvalidPlaceholder": "이 값은 유효하지 않기 때문에 ...",
  "verifiedByOn": "에 의해 확인 됨 {1}",
  "authenticationFailed": "인증 실패",
  "shareOne": "또는 아래 공유",
  "done": "끝난",
  "passwordOn": "제스처 비밀번호 사용",
  "youShallNotPass": "너는지나 가지 않을 것이다!",
  "enterYourName": "당신의 이름을 입력",
  "invalidPattern": "잘못된 패턴",
  "acceptingTermsAndConditions": "확인을 누르면 이용 약관에 동의하게됩니다.",
  "switchTouchIdOn": "터치 ID를 켭니다.",
  "drawYourOldPassword": "이전 패턴 그리기",
  "turnBothOn": "모두 켜기",
  "settings": "설정",
  "receivedVerification": "{1}에 대한 확인을 받았습니다.",
  "pleaseCorrectTheErrors": "양식에서 오류를 수정하십시오.",
  "tooManyPasswordAttempts": "너무 많은 시도를 실패했습니다! 이 양식은 사용 중지되었습니다.",
  "turnTouchIdOn": "터치 ID 켜기",
  "contextsFor": "컨텍스트",
  "backToResults": "검색 결과로 돌아 가기",
  "cancel": "취소",
  "enterPassword": "비밀번호를 입력하십시오.",
  "pleaseDrawPassword": "패턴 그리기",
  "learnMoreServerIsDown": "작성한 모든 메시지는 온라인 상태가되면 자동으로 {1} (으)로 전송됩니다.",
  "newContactRequest": "{1}이 (가) 귀하에게 연락 요청을 보냈습니다.",
  "confirmRevoke": "기록에서이 문서를 삭제하도록 {1} (을)를 요청하십시오.",
  "addAnotherFormOrGetNext": "다른 {1}을 추가하거나 다음 양식으로 이동하십시오.",
  "error": "오류",
  "Cancel": "취소",
  "help": "도움",
  "iproovErrorTitle": "죄송합니다. 문제가 발생했습니다.",
  "profile": "윤곽",
  "invalidPropertyValue": "잘못된 값",
  "verifiedBy": "{1}에 의해 확인 됨",
  "typeMessage": "메시지 입력",
  "enablePassword": "암호 사용",
  "submittingModifiedForm": "{1} 수정 중",
  "inProgress": "요청이 진행 중입니다.",
  "sentTo": "{1} (으)로 전송되었습니다.",
  "sentToOn": "에 {1}에 발송되었습니다.",
  "asSentTo": "{1} (으)로 전송됨에 따라",
  "areYouSureAboutWipe": "이 동작은 되돌릴 수 없습니다. 모든 데이터와 개인 키가 손실됩니다. 계속 하시겠습니까?",
  "dataSecurity": "데이터 보안",
  "getStarted": "시작하다",
  "gestureNotRecognized": "잘못된 패턴",
  "changeGesturePassword": "제스처 암호 변경",
  "downloadingUpdate": "업데이트 다운로드 중 ...",
  "unlockDevice": "계속하려면 장치의 잠금을 해제하십시오.",
  "thisFieldIsRequired": "이 필드는 필수 항목입니다.",
  "continue": "잇다",
  "addNew": "새로운 {1} 추가",
  "learnMore": "더 알아보기",
  "useGesturePassword": "제스처 암호 사용",
  "invalidProperty": "유효하지 않은 {1}",
  "iNeed": "나는 필요하다...",
  "enterCurrentPassword": "현재 비밀번호를 입력하십시오.",
  "pleaseRestartTIM": "TiM을 다시 시작하십시오.",
  "bothOn": "둘 다 ON이다.",
  "nl": "네덜란드 사람",
  "ok": "승인",
  "edit": "편집하다",
  "pairingRequestWasProcesseed": "페어링 요청이 완료되었습니다.",
  "newProduct": "새로운 제품",
  "pairingRequest": "페어링 요청",
  "shareOneOfMany1": "{1}, 귀하의 개인 정보 보호 관리자입니다. 이미 {2}을 (를) 확인했음을 알았습니다. 아래 목록의 항목을 탭하여 {3}와 공유 할 수 있습니다.",
  "newProductMsg": "나는 {1}이 필요하다.",
  "contactUs": "문의하기",
  "Sending": "배상",
  "termsAndConditions": "이용 약관.",
  "acceptTermsAndConditions": "이용 약관보기",
  "scanQRcode": "QR 코드 스캔",
  "optional": "선택 과목",
  "shareWith": "공유하기 {1}",
  "takeAPicture": "** selfie ** 얼굴 사진을 찍어주세요.",
  "willBeAvailable": "이 기능은 곧 제공 될 예정입니다.",
  "sendEditRequestPrompt": "{1} (으)로 수정 요청을 보내시겠습니까?",
  "sourcesBy": "{1}에 의한 출처",
  "shareOne1": "{1}, 귀하의 개인 정보 보호 관리자입니다. 이미 {2}을 (를) 확인했음을 알았습니다. 아래를 탭하여 {3}와 공유 할 수 있습니다.",
  "testProviders": "모래 상자",
  "shareMyProduct": "아래에서 탭하여 {1}을 (를) {2}와 (과) 공유 할 수 있습니다.",
  "shareContext": "공유하기 {1}",
  "add": "{1} 추가",
  "listOfProducts": "제품 목록",
  "thePropertyWithMinMaxRangeError": "[min-max] 범위의 속성은 두 개의 숫자 만 가질 수 있습니다.",
  "fieldErrorMessagePrompt": "이 분야에 어떤 문제가 있습니까?",
  "drawYourNewPassword": "새로운 패턴 그리기",
  "noNetwork": "네트워크 없음",
  "pairDevices": "쌍 장치",
  "verifyPrompt": "검증?",
  "errorNotification": "오류 알림을 고객에게 보내 수정했습니다.",
  "correctPassword": "앗, 너 기억하고있어!",
  "areYouSureAboutNextForm": "{1}로 끝내셨습니까?",
  "receivedForm": "받은 {1}",
  "viewTerms": "이용 약관을 확인하십시오.",
  "no": "아니",
  "formListErrorDescription": "고객이 신청을 시작하면 양식을 요청할 수 있습니다.",
  "learnMoreDescriptionTo": "장치가 연결되어 있지 않아도 오프라인 모드로 메시지를 쓸 수 있습니다. 다시 연결하면 모든 메시지가 자동으로 {1} (으)로 전송됩니다.",
  "confirmForgetMe": "'{1}'이 너를 잊고 싶니?",
  "switchTouchIdOff": "터치 ID 전환",
  "trustedProviders": "신뢰할 수있는 공급자",
  "customerWaiting": "{1}이 (가) 채팅에 입장했습니다.",
  "sharedWith": "{2}와 (과) 공유 된 {1} 컨텍스트",
  "homePage": "집",
  "yes": "예",
  "somethingWrong": "문제가 발생했습니다.",
  "addServerUrl": "서버 URL 추가",
  "verificationTransactionID": "인증 거래 ID",
  "useTouchId": "터치 ID 사용",
  "formListError": "없는",
  "receivedProduct": "받은 {1}",
  "setNewPassword": "새 암호 선택",
  "useTouchIdAndGesturePassword": "터치 ID 및 제스처 사용",
  "youAreForgotten": "너는 성공적으로 잊혀 졌어.",
  "retake": "다시 잡다",
  "setDateValue": "세트",
  "formRequest": "{1}에 대한 요청",
  "irrefutableProofs": "반박 할 수없는 증명",
  "nothingChanged": "아무것도 바뀌지 않았다",
  "forgetMe": "날 잊어 줘",
  "setPassword": "안전한 비밀번호 선택",
  "fillTheFormWithAttachments": "이 양식을 작성하십시오 ** {1} **",
  "sharedForm": "{2}에서 {1}을 공유했습니다.",
  "deviceDoesNotHaveMyKeys": "받은 신원에는 열쇠가 없습니다.",
  "Clear": "명확한",
  "patternNotMatching": "패턴이 일치하지 않았습니다.",
  "shareOneOfMany": "또는 아래 공유",
  "myDocuments": "내 문서",
  "pleaseCorrect": "수정 해주세요",
  "passwordLimitations": "패턴에는 5 점 이상이 있어야합니다.",
  "back": "뒤로",
  "switchToRepresentative": "대표 모드로의 전환은 아직 구현되지 않았습니다.",
  "shareAllPastAndFutureMessages": "이 컨텍스트에서 과거와 미래의 모든 메시지를 선택한 당사자와 공유하십시오.",
  "documentNotScanning": "아차! 문제가 발생했습니다!",
  "oops": "죄송합니다.",
  "installingUpdate": "업데이트 설치 중",
  "iproovFailedTitle": "죄송합니다. 문제가 발생했습니다.",
  "later": "후에",
  "importing": "가져 오는 중",
  "creationDate": "생성 일자",
  "Applications": "응용 분야",
  "testForgetMe": "이 공급자와의 모든 통신을 재설정하는 테스트 메커니즘입니다.",
  "en": "영어",
  "next": "다음 것",
  "noConnection": "{appName} 님은 현재 가지고 있지 않은 인터넷 연결이 필요합니다.",
  "offlineMode": "오프라인 모드",
  "bookmarks": "북마크",
  "loadingResources": "리소스로드 중",
  "submitLog": "로그 제출",
  "loadingModels": "모델 로딩",
  "approveApplication": "승인 신청",
  "loading": "로드 중 ...",
  "Our products have changed": "당사의 제품이 변경되었습니다.",
  "exploreData": "데이터 탐색",
  "sponsoredBy": "후원사",
  "centerLicence": "프레임 라이센스 센터",
  "cameraAccess": "카메라 액세스",
  "Approve": "승인하다",
  "restartApp": "앱 다시 시작",
  "resetRequired": "재설정 필요",
  "Submit": "제출",
  "Deny": "거부하다",
  "updateNow": "지금 업데이트",
  "nameUnknown": "이름을 알 수 없음",
  "Verifications": "확인",
  "Seals": "물개",
  "updateAppTitle": "사용 가능한 앱 업데이트",
  "denyApplication": "응용 프로그램 거부",
  "checkIfMatch": "일치하는지 확인하십시오.",
  "usePhoto": "사진 사용",
  "submitting": "제출",
  "initializingEngine": "엔진 초기화",
  "ID document": "ID 문서",
  "cancelHideResource": "숨기기 취소 {1}",
  "viewDebugLog": "디버그 로그보기",
  "Please scan your": "스캔하십시오.",
  "youReviewedAll": "모든 {1}을 (를) 검토했습니다.",
  "documentExpiredTitle": "문서가 만료되었습니다.",
  "documentExpiredMessage": "유효한 문서를 스캔하십시오.",
  "fromMyData": "'내 데이터'에서",
  "hideResource": "{1} 숨기기",
  "importYourData": "데이터 가져 오기",
  "Please fill out the form": "양식을 작성하십시오.",
  "Application submitted!": "신청서가 제출되었습니다!",
  "generatingKeys": "개인 키 생성",
  "applyForProduct": "제품 신청",
  "fillRequiredFields": "모든 필수 입력란을 작성하십시오.",
  "centerPassport": "센터 여권 사진 페이지 액자",
  "textPasswordLimitations": "10 자 이상, 대문자, 소문자, 숫자 및 특수 문자가 하나 이상 있어야합니다.",
  "Thank you. Now take a '": "고맙습니다. 이제 '",
  "nothingToShare": "공유 할 내용이 없습니다.",
  "noConnectionWillProcessLater": "{appName} 님은 현재 가지고 있지 않은 인터넷 연결이 필요합니다. 연결이 설정되면 요청이 처리됩니다.",
  "Corporation Exists Checks": "법인 확인 수표",
  "createManualMatchCheck": "수동 일치 확인 만들기",
  "restartingApp": "응용 프로그램이 일시적으로 다시 시작됩니다.",
  "validationErrors": "실패한 유효성 검사 필드를 수정하십시오.",
  "pleaseSign": "회색 상자 안에 로그인하십시오.",
  "Give me a moment...": "잠시만 기다려주세요 ...",
  "centerID": "프레임 ID",
  "Choose Apply for Product from the menu": "메뉴에서 제품에 적용을 선택하십시오.",
  "multientryToShare": "공유 할 문서가 {1} 개 있습니다.",
  "iproovErrorMessage": "잠시 후 다시 시도하십시오.",
  "pleaseTapOnMenu": "빨간색 버튼을 탭하고",
  "See our list of products": "제품 목록보기",
  "neverMissAMessage": "메시지를 놓치지 마세요.",
  "reviewScannedProperties": "아래 데이터를 검토하고 수정하십시오.",
  "Please click to scan your": "클릭하여 스캔하십시오.",
  "noScanningOnAndroid": "Android에서 문서 스캔이 곧 제공 될 예정입니다.",
  "serverIsUnreachable": "서버에 연결할 수 없습니다.",
  "Please tap here and sign": "여기를 살짝 눌러주세요.",
  "youShared": "{1}에서 공유했습니다.",
  "noAccessToServer": "서버에 액세스 할 수 없습니다. 나중에 시도하십시오.",
  "noConnectionForNewProduct": "{1}, {appName}은 (는) {2} 응용 프로그램을 작성하기 위해 인터넷 연결이 필요합니다.",
  "approveApplicationFor": "{1}에 대한 신청 승인",
  "noConnectionForPL": "{appName}은 (는) 현재 인터넷 연결이 필요하지 않아 {1}의 제품 목록을 요청합니다.",
  "verificationBy": "{1}에 의한 확인",
  "verifierHelp": "양식을 검토 한 후 '완료'버튼을 클릭하십시오. 일부 필드를 수정해야하는 경우 먼저 필드를 확인한 다음 '완료'버튼을 클릭하십시오.",
  "digitalWealthPassport": "디지털 웰스 패스포트",
  "unreadMessages": "읽지 않은 메시지가 있습니다.",
  "importDataPrompt": "에서 데이터를 가져 오려고합니다.",
  "denyApplicationFor": "{1}에 대한 신청 거부",
  "goodNews": "좋은 소식! 이미 {1}이 (가) 있습니다. 아래 아이콘을 공유하려면 공유하려면",
  "createNew": "양식 \"{1}\"작성",
  "scanningFailedTryAgain": "검사가 실패했습니다. 다시 시도해 주시겠습니까?",
  "messageWaitingFrom": "{1}에서 보낸 새 메시지가 있습니다.",
  "unknownQRCodeFormat": "인식 할 수없는 QR 코드 형식",
  "receiveNotifications?": "알림을 받으시겠습니까?",
  "youAreTheRM": "귀하는이 애플리케이션의 관계 관리자입니다.",
  "areYouSureYouWantToServeThisCustomer": "이 고객에게 서비스 하시겠습니까?",
  "areYouSureYouWantToDelete": "{1}을 (를) 숨기시겠습니까?",
  "ukLicenseUnsupported": "현재 영국 운전 면허 검사는 지원되지 않습니다.",
  "invalidPairingRequest": "잘못된 페어링 요청",
  "cancelItem": "{1}을 (를) 취소하려고합니다. 확인을 눌러 확인하십시오.",
  "youAreAboutToShare": "공유하려고합니다.\n '{1}'\n 서류",
  "createNext": "다른 양식 \"{1}\"을 작성하십시오.",
  "invalidDeepLink": "잘못된 링크를 클릭 한 것 같습니다.",
  "youReviewed": "{2} 개 아이템 중 {1} 개를 검토했습니다.",
  "updateAppMessage": "지금 업데이트 하시겠습니까? 나중에 다시 생각 나게합니까?",
  "importingData": "{2}에서 {1} 문서 가져 오기 중입니다.",
  "storageCorrupted": "브라우저 저장 공간이 손상되었습니다! 확인을 눌러 앱의 ID와 저장 용량을 재설정합니다.",
  "confirmedMyData": "가져온 모든 데이터는 {profileTitle}",
  "Please take a selfie to prove this is your document. Center your face.": "이 문서가 귀하의 문서임을 입증하기 위해 셀카를 가져 가십시오. 얼굴을 가운데에 맞 춥니 다.",
  "' photo of yourself that I can match against your ID document": "너의 신분증 서류와 대조 할 수있는 너 자신의 사진",
  "confirmAllItems": "확인을 눌러 모두 확인한 다음 검토를 계속하려면 취소를 누릅니다.",
  "theMinValueBiggerThenMaxValue": "범위의 최소값은 최대 값보다 작아야합니다.",
  "pleaseClickOnAddButton": "'{1}'을 (를) 추가하려면 아래 '+'를 클릭하십시오.",
  "importData": "날짜 가져 오기",
  "independentBlockchainViewer": "독립적 인 블록 체인 뷰어",
  "holdPhoneToPassportBackCover": "휴대 전화의 뒷면을 여권의 뒷 표지에 붙입니다.",
  "sandboxDescription": "Sandbox에서 시뮬레이션 된 서비스 제공 업체와 함께 앱을 사용하는 방법에 대해 알아보십시오.",
  "enableCameraAccess": "{appName}은 현재 카메라를 사용할 수있는 권한이 없습니다. 액세스 권한을 부여하려면 설정을 선택하고 카메라가 활성화되어 있는지 확인하십시오.",
  "areYouSureYouWantToConfirmAllItems": "확인을 탭하여 모든 {1}을 확인하거나 취소를 눌러 검토를 계속하십시오.",
  "retryScanning": "그게 {1}인가요? 나는 말할 수 없었다. 다시 시도해 주시겠습니까?\n\n최상의 결과를 얻으려면 가로 모드를 사용하고 눈부심을 방지하고 표시된 프레임 내에 문서를 놓아야합니다.",
  "incompatibleVersion": "최근의 호환되지 않는 변경 사항으로 인해이 업데이트를 사용하려면 앱을 하드 리셋해야합니다. 확인을 눌러 앱의 ID와 저장 용량을 재설정합니다.",
  "iproovFailedMessage": "다시 시도하십시오. 최상의 결과를 얻으려면 색상이 깜박이는 동안 타원의 중앙에 얼굴을 유지하십시오.",
  "holdPhoneToPassport": "휴대 전화 뒷면을 여권 앞 표지에 붙입니다.",
  "somethingWrongSubmitLog": "뭔가 잘못 된 것 같습니다. {appName} 개발자 팀에 디버그 로그를 제출하십시오.",
  "goodNewsFew": "좋은 소식! 당신은 이미 꽤 많이 가지고 있습니다. 아래 탭 아이콘을 공유하려면.",
  "temporarilyLocked": "귀하의 보호를 위해이 애플리케이션은 {1}에 대해 잠겨 있습니다.",
  "enablePasscodeFirst": "기기 암호를 사용 설정하지 않은 것 같습니다. 그것 없이는,이 응용 프로그램은 데이터를 보호 할 수 없습니다! 확인을 누르기 전에 활성화하십시오.",
  "Next": "다음 것",
  "Skip": "버킷",
  "Ready?": "준비된?",
  "Done": "끝난",
  "Ready for friendliness?": "친절하게 준비 되었습니까?",
  "Sanctions Checks": "제재 수표",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "우리는 채팅에서 질문을하고 양식을 채우거나 요청을 따르기 만하면됩니다.",
  "Go!": "가기!",
  "Take a quick tour of chat bot?": "채팅 봇을 둘러 보시겠습니까?",
  "Finally, you will be in control of your own private information!": "마지막으로, 귀하는 귀하의 개인 정보를 관리하게 될 것입니다!",
  "Get set for friendliness?": "친절을위한 세트?",
  "Go friendliness!": "가야 해!",
  "Get set": "세트 받기",
  "Before we start you'll need a valid passport, identity card or driving license": "시작하기 전에 유효한 여권, 신분증 또는 운전 면허가 필요합니다.",
  "Photo": "사진",
  "newCustomer": "신규 고객",
  "resetApp": "앱 재설정",
  "inProcess": "처리 중 ...",
  "reviewData": "데이터 검토",
  "scanYourDocument": "문서를 스캔하십시오.",
  "failedToSendLog": "로그를 보내지 못했습니다.",
  "validatingDataClaim": "데이터 가져 오기",
  "requestMyData": "내 데이터 요청",
  "debugLogSent": "디버그 로그 전송 됨",
  "documentBackSide": "중앙 문서 뒷면",
  "wipeTheAppData": "앱 데이터 지우기",
  "pleaseChooseDT": "먼저 문서 유형을 선택하십시오.",
  "invalidCountry": "유효하지 않은 국가 스캔 됨",
  "supportedQrCodes": "지원되는 QR 코드 :\n1) 채팅 채널 추가\n2) 데이터 가져 오기",
  "wrongDocumentTypePleaseTryAgain": "잘못된 문서 유형입니다. 다시 시도하십시오.",
  "invalidQR": "QR 코드가 잘못되었습니다.",
  "networkFailure": "네트워크 문제가 발생했습니다. 확인하고 다시 시도 / 취소 할 수 있습니까?",
  "dateInTheFutureError": "{1}이 (가) 앞으로 있습니다.",
  "enterPasswordOrWipeOutTheAppData": "비밀번호를 입력하거나 앱 데이터 지우기",
  "noResourcesForCriteria": "이 기준에 대한 리소스가 없습니다.",
  "startedByAnotherEmployee": "{1}의 신청서가 다른 직원에 의해 시작되었습니다.",
  "doYouWantToContinue": "그것으로 전환하고 거기에서 계속 하시겠습니까?",
  "afterRefresh": "귀하는 중단없이 본 서비스를 사용하도록 허가됩니다.",
  "logSentToDevTeam": "로그가 Tradle 개발자 팀에 전송되었습니다.",
  "areYouSureYouAreDone": "이 세션을 끝내시겠습니까?",
  "invalidQuery": "죄송합니다. 검색을 실행하는 중에 오류가 발생했습니다. 우리 개발자는 최대한 빨리 수정하려고합니다.",
  "reviewScannedPropertiesAndSecondSideSnapshot": "아래 데이터를 검토하고 문서의 {1}면에 대한 스냅 샷을 작성하십시오."
}