module.exports = {
  "nl": "Голландский",
  "sharedWith": "Общий контекст {1} с {2}",
  "submitting": "предоставление",
  "invalidDocument": "недействительный документ",
  "back": "назад",
  "addNew": "Добавить {1}",
  "fillTheFormWithAttachments": "Заполните эту форму ** {1} **",
  "messageWaitingFrom": "У вас есть новое сообщение из {1}",
  "validationErrors": "Исправьте неверные поля проверки",
  "storageCorrupted": "ваше хранилище браузера повреждено! Нажмите OK, чтобы сбросить идентификатор и хранилище приложения.",
  "updateNow": "Обновить сейчас",
  "forgetMe": "Забудь меня",
  "confirmRevoke": "Попросить {1} удалить этот документ из своих записей?",
  "importData": "Даты импорта",
  "addAnotherFormOrGetNext": "Добавьте еще один {1} или перейдите к следующей форме",
  "youAreForgotten": "Вы были забыты",
  "thePropertyWithMinMaxRangeError": "Свойство с диапазоном [min-max] может иметь только два числа",
  "showQR": "Мой QR-код",
  "verifiedByOn": "Подтверждено {1} on",
  "add": "Добавить {1}",
  "asSentTo": "Как отправлено {1}",
  "ok": "ОК",
  "typeMessage": "Введите сообщение",
  "noScanningOnAndroid": "Сканирование документов на Android скоро появится.",
  "restartingApp": "Приложение перезапустится на мгновение",
  "testProviders": "песочница",
  "profile": "Профиль",
  "shareOneOfMany": "Альтернативно, поделитесь ниже",
  "newProductMsg": "Мне нужно {1}.",
  "setPassword": "Выберите безопасный пароль",
  "somethingWrong": "Что-то пошло не так",
  "termsAndConditions": "Условия и положения.",
  "viewDebugLog": "Просмотр журнала отладки",
  "passwordsDontMatch": "Пароли не совпадают",
  "errorNotification": "Клиенту было отправлено уведомление об ошибке, чтобы исправить",
  "drawYourNewPasswordAgain": "Нарисуйте новый шаблон снова",
  "enterPassword": "Введите ваш пароль",
  "installingUpdate": "Устанавливается обновление",
  "continue": "Продолжать",
  "importYourData": "Импорт данных",
  "changeGesturePassword": "Изменить пароль жестов",
  "sendEditRequestPrompt": "Отправить запрос на редактирование {1}?",
  "restartApp": "Перезапустить приложение",
  "fieldErrorMessagePrompt": "Что случилось с этим полем?",
  "contactUs": "Свяжитесь с нами",
  "passwordOn": "Пароль жестов включен",
  "pleaseCorrectTheErrors": "Исправьте ошибку в форме",
  "switchToRepresentative": "Переход к представительному режиму еще не реализован.",
  "scanQRcode": "Сканировать QR-код",
  "shareOne": "Альтернативно, поделитесь ниже",
  "correctPassword": "Все, ты помнишь!",
  "verifiedBy": "Подтверждено {1}",
  "retryScanning": "Это было {1}? Я не мог сказать. Пожалуйста, попробуйте еще раз?\n\nДля достижения наилучших результатов используйте ландшафтный режим, избегайте бликов и не забудьте поместить документ в рамку.",
  "iproovErrorTitle": "К сожалению! Что-то пошло не так",
  "en": "английский",
  "pleaseRestartTIM": "Перезагрузите TiM",
  "updateAppTitle": "Доступно обновление приложения",
  "edit": "редактировать",
  "importDataPrompt": "Вы собираетесь импортировать свои данные из",
  "fillRequiredFields": "Пожалуйста, заполните все обязательные поля",
  "officialAccounts": "Диалоги",
  "iNeed": "Мне нужно...",
  "help": "Помогите",
  "loadingModels": "модели загрузки",
  "viewTerms": "Ознакомьтесь с Условиями использования",
  "deviceDoesNotHaveMyKeys": "Полученная личность не имеет моих ключей",
  "sourcesBy": "Источники {1}",
  "done": "Готово",
  "thisFieldIsRequired": "Это поле обязательно к заполнению",
  "authenticationFailed": "Ошибка аутентификации",
  "newContactRequest": "{1} отправил вам запрос на контакт",
  "backToResults": "Вернуться к результатам",
  "searchSomething": "Поиск {1}",
  "drawYourOldPassword": "Нарисуйте свой старый узор",
  "issuedByOn": "Выпущено {1} on",
  "customerWaiting": "{1} вошел в чат",
  "overviewOfApplications": "Обзор приложений",
  "shareProduct": "Вы можете нажать ниже, чтобы поделиться {1} с {2}",
  "pleaseClickOnAddButton": "Нажмите '+', чтобы добавить '{1}'",
  "gestureNotRecognized": "Неверный рисунок",
  "tapToRemovePhotos": "Нажмите, чтобы удалить фотографии.",
  "enterYourName": "Введите ваше имя",
  "tooManyPasswordAttempts": "Слишком много неудачных попыток! Эта форма отключена.",
  "myDocuments": "Мои документы",
  "submitLog": "Отправить журнал",
  "later": "Позже",
  "issuedBy": "Выпущено {1}",
  "backTo": "Вернуться к {1}",
  "cameraAccess": "Доступ камеры",
  "enterCurrentPassword": "введи свой текущий пароль",
  "newProduct": "Новый продукт",
  "creationDate": "Дата создания",
  "nameUnknown": "имя неизвестно",
  "learnMore": "Выучить больше",
  "trustedProviders": "Надежные поставщики",
  "listOfProducts": "Список продуктов",
  "youShallNotPass": "Ты не должен пройти!",
  "oops": "ой",
  "setDateValue": "Задавать",
  "centerID": "Идентификатор центра в кадре",
  "formListError": "Недоступен",
  "cancel": "Отмена",
  "addServerUrl": "Добавить URL сервера",
  "shareOneOfMany1": "{1}, это ваш личный помощник по обеспечению конфиденциальности. Я вижу, что вы уже проверили ваш {2}. Вы можете использовать любые элементы в списке ниже, чтобы поделиться им с {3}.",
  "enablePassword": "Включить пароль",
  "centerPassport": "Страница фотоснимка центра в рамке",
  "youReviewed": "Вы просмотрели {1} из {2} элементов",
  "somethingWrongSubmitLog": "Кажется, что-то пошло не так. Отправьте журнал отладки команде разработчиков {appName}",
  "drawYourPasswordAgain": "Нарисуйте рисунок снова",
  "pleaseDrawPassword": "Нарисуйте рисунок",
  "settings": "настройки",
  "invalidPattern": "Неверный рисунок",
  "iproovFailedTitle": "К сожалению! Что-то пошло не так",
  "initializingEngine": "инициализация двигателя",
  "denyApplication": "Отклонить заявку",
  "verificationBy": "Проверка по {1}",
  "learnMoreDescriptionTo": "Вы все равно можете писать сообщения в автономном режиме, даже если ваше устройство не подключено. При повторном подключении все ваши сообщения будут автоматически отправлены {1}.",
  "hideResource": "Скрыть {1}",
  "scanningFailedTryAgain": "Сканирование было неудачным. Не могли бы вы попробовать еще раз?",
  "optional": "необязательный",
  "sandboxDescription": "В Sandbox узнайте, как использовать приложение с имитируемыми поставщиками услуг.",
  "willBeAvailable": "Эта функция будет доступна в ближайшее время",
  "temporarilyLocked": "Для вашей защиты это приложение временно заблокировано для {1}",
  "noAccessToServer": "Сервер недоступен. Попробуй позже.",
  "invalidPairingRequest": "Недопустимый запрос на сопряжение",
  "confirmAllItems": "Нажмите «ОК», чтобы подтвердить их все, или «Отмена», чтобы продолжить просмотр",
  "verifyPrompt": "Проверьте?",
  "downloadingUpdate": "Загрузка обновления ...",
  "pleaseTapOnMenu": "Нажмите красную кнопку и",
  "passwordLimitations": "У шаблона должно быть 5+ очков",
  "search": "Поиск",
  "hello": "Привет {1}!",
  "shareOne1": "{1}, это ваш личный помощник по обеспечению конфиденциальности. Я вижу, что вы уже проверили ваш {2}. Вы можете нажать ниже, чтобы поделиться им с {3}.",
  "wrongPattern": "Неверный рисунок",
  "fillTheForm": "Заполните эту форму ** {1} **",
  "receivedProduct": "Получено {1}",
  "shareMyProduct": "Вы можете нажать ниже, чтобы поделиться {1} с {2}",
  "centerLicence": "Центральная лицензия в кадре",
  "inProgress": "Ваш запрос выполняется",
  "areYouSureYouWantToServeThisCustomer": "Вы уверены, что хотите обслуживать этого клиента?",
  "providerIsOffline": "{1} вне форума",
  "confirmedMyData": "Все импортированные данные можно просмотреть в вашем {profileTitle}",
  "takeAPicture": "Пожалуйста, возьмите ** изображение собственного лица ** на лице",
  "offlineMode": "Не в сети",
  "switchTouchIdOff": "Отключить сенсорный идентификатор",
  "homePage": "Главная",
  "patternNotMatching": "Шаблоны не совпадали.",
  "invalidPropertyValue": "Неверное значение",
  "invalidProperty": "Недопустимый {1}",
  "bothOn": "Оба включены",
  "sharedForm": "Общий {1} из {2}",
  "pleaseCorrectFields": "Исправьте следующие поля: {1}",
  "thisValueIsInvalidPlaceholder": "это значение недействительно, потому что ...",
  "next": "следующий",
  "correctGesture": "Исправлен паттерн",
  "theMinValueBiggerThenMaxValue": "Минимальное значение для диапазона должно быть меньше, чем максимальное значение",
  "approveApplicationFor": "Утвердить заявку на {1}",
  "confirmForgetMe": "Вы действительно хотите «{1}» забыть о вас",
  "nothingChanged": "Ничего не изменилось",
  "cancelHideResource": "Отменить Скрыть {1}",
  "multientryToShare": "Есть {1} документы для обмена",
  "areYouSureYouWantToDelete": "Вы уверены, что хотите скрыть {1}?",
  "youAreTheRM": "Вы являетесь Менеджером связей для этого приложения",
  "sponsoredBy": "При поддержке",
  "neverMissAMessage": "Никогда не пропустите сообщение",
  "importing": "Импорт",
  "documentExpiredTitle": "Истек срок действия документа",
  "unknownQRCodeFormat": "Непризнанный формат QR-кода",
  "touchIdOn": "Сенсорный ID включен",
  "shareChangesWith": "Поделитесь изменениями с",
  "useGesturePassword": "Включить пароль жестов",
  "importingData": "Импорт {1} документов из {2}",
  "contextsFor": "Контексты для",
  "receivedForm": "Получено {1}",
  "sharedContext": "Общий контекст",
  "dataSecurity": "Безопасность данных",
  "useTouchIdAndGesturePassword": "Включить сенсорный идентификатор и жест",
  "changePassword": "Изменить пароль",
  "learnMoreServerIsDown": "Любые сообщения, которые вы пишете, будут автоматически отправлены {1}, когда они выйдут онлайн.",
  "documentExpiredMessage": "Сканировать действительный документ",
  "ukLicenseUnsupported": "Сканирование лицензии на водительские права Великобритании в настоящее время не поддерживается",
  "youReviewedAll": "Вы просмотрели все {1}",
  "error": "ошибка",
  "fromMyData": "из 'Мои данные'",
  "invalidDeepLink": "Похоже, вы нажали недействительную ссылку!",
  "youAreAboutToShare": "Вы собираетесь поделиться\n '{1}'\n документы",
  "noNetwork": "Нет сети",
  "textPasswordLimitations": "Должно иметь 10+ символов, по крайней мере одну прописную букву, строчную букву, номер и специальный символ",
  "setNewPassword": "Выберите новый пароль",
  "unlockDevice": "откройте устройство, чтобы продолжить",
  "drawYourNewPassword": "Нарисуйте новый образец",
  "loadingResources": "загрузка ресурсов",
  "yes": "да",
  "shareWith": "Поделиться {1}",
  "turnBothOn": "Включить оба",
  "approveApplication": "Утвердить заявку",
  "holdPhoneToPassport": "Держите заднюю часть телефона против передней крышки вашего паспорта",
  "areYouSureAboutNextForm": "Вы уверены, что закончили с {1}?",
  "updateAppMessage": "Обновить сейчас, или я должен напомнить вам позже?",
  "areYouSureAboutWipe": "Это действие необратимо. Вы потеряете все свои данные и секретные ключи. Вы уверены, что хотите продолжить?",
  "applyForProduct": "Подать заявку на продукт",
  "digitalWealthPassport": "Паспорт цифрового богатства",
  "details": "Детали",
  "sentToOn": "Отправлено {1} в",
  "reviewScannedProperties": "Пожалуйста, просмотрите и исправьте приведенные ниже данные",
  "noConnectionWillProcessLater": "{appName} требует рабочего интернет-соединения, которого у вас нет на данный момент. Запрос будет обработан при установлении соединения",
  "drawYourPassword": "Нарисуйте рисунок",
  "no": "нет",
  "sentTo": "Отправлено в {1}",
  "shareContext": "Поделиться {1}",
  "asVerifiedBy": "Как проверено {1}",
  "verificationTransactionID": "Идентификатор транзакции проверки",
  "formListErrorDescription": "Формы могут запрашиваться после того, как клиент начинает заявку",
  "pairingRequest": "Запрос на сопряжение",
  "createNew": "Заполните форму \"{1}\"",
  "submittingForm": "Отправлено {1}",
  "enableCameraAccess": "{appName} в настоящее время не имеет разрешения на использование камеры. Чтобы предоставить доступ, выберите «Настройки» и убедитесь, что камера включена.",
  "documentNotScanning": "Упс! Что-то пошло не так!",
  "acceptingTermsAndConditions": "Нажимая «ОК», вы принимаете Условия использования",
  "nothingToShare": "Нечего делиться",
  "resetRequired": "Требуется перезагрузка",
  "denyApplicationFor": "Запретить приложение для {1}",
  "receiveNotifications?": "Вы хотите получать уведомления?",
  "pleaseCorrect": "Пожалуйста исправьте",
  "switchTouchIdOn": "Включить сенсорный идентификатор",
  "serverIsUnreachable": "Сервер недоступен",
  "submittingModifiedForm": "Изменение {1}",
  "receivedVerification": "Полученная проверка для {1}",
  "pairDevices": "Паровые устройства",
  "acceptTermsAndConditions": "Просмотр условий",
  "youShared": "Вы поделились с {1}",
  "useTouchId": "Включить сенсорный ID",
  "generatingKeys": "создание секретных ключей",
  "formRequest": "Запрос {1}",
  "cancelItem": "Вы собираетесь отменить {1}. Нажмите OK, чтобы подтвердить",
  "iproovErrorMessage": "Подождите немного и повторите попытку.",
  "unreadMessages": "У вас есть непрочитанные сообщения",
  "turnPasswordOn": "Включить пароль жестов",
  "noConnectionForNewProduct": "{1}, {appName} требует рабочего интернет-соединения для заполнения приложения {2}.",
  "createNext": "Заполните другую форму \"{1}\"",
  "pairingRequestWasProcesseed": "Запрос на спаривание был обработан",
  "formChooser": "Список форм",
  "enablePasscodeFirst": "Похоже, что у вас нет пароля для доступа к устройству. Без этого приложение не сможет защитить ваши данные! Включите его, прежде чем нажать OK.",
  "turnTouchIdOn": "Включить сенсорный идентификатор",
  "irrefutableProofs": "Неопровержимые доказательства",
  "iproovFailedMessage": "Пожалуйста, попробуйте еще раз. Для достижения наилучших результатов держите лицо в центре в овале во время цветных вспышек.",
  "areYouSureYouWantToConfirmAllItems": "Нажмите «ОК», чтобы подтвердить все {1}, или «Отмена», чтобы продолжить просмотр",
  "shareAllPastAndFutureMessages": "Поделитесь всеми прошлыми и будущими сообщениями в этом контексте с выбранными сторонами",
  "holdPhoneToPassportBackCover": "Держите заднюю часть телефона на задней стороне паспорта.",
  "incompatibleVersion": "Из-за недавних несовместимых изменений, это обновление требует жесткого сброса приложения. Нажмите OK, чтобы сбросить идентификатор и хранилище приложения.",
  "learnMoreDescription": "Вы все равно можете писать сообщения в автономном режиме, даже если ваше устройство не подключено. При повторном подключении все ваши сообщения будут отправляться автоматически.",
  "verifierHelp": "Нажмите кнопку «Готово» после просмотра формы. Если некоторые поля требуют коррекции, сначала проверьте их, а затем нажмите кнопку «Готово»",
  "noConnectionForPL": "{appName} требует рабочего интернет-соединения для запроса списка продуктов из {1}, которого у вас нет в данный момент",
  "noConnection": "{appName} требует рабочего интернет-соединения, которого у вас нет на данный момент",
  "testForgetMe": "Это тестовый механизм для сброса всех сообщений с этим провайдером",
  "independentBlockchainViewer": "Независимый зритель блокчайн",
  "bookmarks": "закладки",
  "exploreData": "Исследуйте данные",
  "Please fill out the form": "Пожалуйста, заполните форму",
  "Choose Apply for Product from the menu": "Выберите «Применить для продукта» в меню",
  "See our list of products": "Смотрите наш список продуктов",
  "Please scan your": "Сканируйте свой",
  "ID document": "Документ ID",
  "Our products have changed": "Наши продукты изменились",
  "Please take a selfie to prove this is your document. Center your face.": "Пожалуйста, возьмите самоуверенность, чтобы доказать, что это ваш документ. Центрируйте свое лицо.",
  "Application submitted!": "Заявка подана!",
  "Sending": "Отправка",
  "Please tap here and sign": "Нажмите здесь и подпишите",
  "Give me a moment...": "Дайте мне минуту ...",
  "Please click to scan your": "Нажмите, чтобы отсканировать",
  "' photo of yourself that I can match against your ID document": "'фото, которое я могу сопоставить с вашим документом ID",
  "Thank you. Now take a '": "Спасибо. Теперь возьмите '",
  "pleaseSign": "Войдите в серый квадрат",
  "getStarted": "Начать",
  "goodNewsFew": "Хорошие новости! У вас уже есть немало. Чтобы поделиться значком крана ниже.",
  "goodNews": "Хорошие новости! У вас уже есть {1}. Чтобы поделиться, нажмите значок ниже",
  "Submit": "Отправить",
  "Clear": "Очистить",
  "Cancel": "Отмена",
  "retake": "Пересдать",
  "usePhoto": "Использовать фотографию",
  "Approve": "Одобрить",
  "Deny": "Отрицать",
  "loading": "Loading ...",
  "Applications": "Приложения",
  "checkIfMatch": "Проверьте соответствие",
  "Seals": "Морские котики",
  "Verifications": "Верификация",
  "Corporation Exists Checks": "Корпорация Except Checks",
  "createManualMatchCheck": "Создать ручную проверку соответствия",
  "Ready for friendliness?": "Готовы к дружелюбию?",
  "Get set for friendliness?": "Подходите к дружелюбию?",
  "Take a quick tour of chat bot?": "Познакомьтесь с чатом ботом?",
  "Go friendliness!": "Идите дружелюбие!",
  "Finally, you will be in control of your own private information!": "Наконец, вы будете контролировать свою личную информацию!",
  "Ready?": "Готов?",
  "Go!": "Идти!",
  "Get set": "Получить набор",
  "Before we start you'll need a valid passport, identity card or driving license": "Прежде чем мы начнем, вам понадобится действительный паспорт, удостоверение личности или водительские права",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Мы зададим вам вопросы в чате, и вы просто заполните формы или выполните запросы",
  "Next": "следующий",
  "Skip": "Пропускать",
  "Done": "Готово",
  "Sanctions Checks": "Проверка санкций",
  "inProcess": "В процессе...",
  "networkFailure": "У меня проблемы с сетью. Вы можете проверить, а затем нажать «Попробовать снова» / «Отменить»",
  "invalidQuery": "К сожалению, мы попали в ошибку при поиске. Наши разработчики попытаются исправить это как можно скорее.",
  "invalidQR": "Неверный QR-код",
  "validatingDataClaim": "Импорт данных",
  "supportedQrCodes": "Поддерживаемые QR-коды:\n1) добавить канал чата\n2) данные импорта",
  "logSentToDevTeam": "Журнал был отправлен команде разработчиков Tradle",
  "noResourcesForCriteria": "Ресурсов для этого критерия не найдено",
  "debugLogSent": "Отладочный журнал отправлен",
  "failedToSendLog": "Не удалось отправить журнал",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Ознакомьтесь с приведенными ниже данными и сделайте снимок {1} стороны документа",
  "documentBackSide": "Обратная сторона центрального документа",
  "Photo": "Фото",
  "startedByAnotherEmployee": "Приложение для {1} было запущено другим сотрудником",
  "doYouWantToContinue": "Вы хотите переключиться на него и продолжить оттуда?",
  "reviewData": "Обзор данных",
  "afterRefresh": "Вы очищены, чтобы использовать наши услуги без перерыва",
  "requestMyData": "Запрос моих данных",
  "newCustomer": "Новый покупатель",
  "areYouSureYouAreDone": "Вы уверены, что хотите завершить эту сессию?",
  "scanYourDocument": "Сканируйте свой документ",
  "wrongDocumentTypePleaseTryAgain": "Неверный тип документа. Пожалуйста, попробуйте еще раз",
  "resetApp": "Сбросить приложение",
  "invalidCountry": "Неверная страна, отсканированная",
  "wipeTheAppData": "Сотрите данные приложения",
  "enterPasswordOrWipeOutTheAppData": "Введите пароль или стереть данные приложения",
  "pleaseChooseCountryAndDT": "Пожалуйста, сначала выберите страну и тип документа"
}