module.exports = {
  "sponsoredBy": "Gefördert durch",
  "shareOne": "Alternativ teilen Sie unten",
  "drawYourOldPassword": "Zeichne dein altes Muster",
  "enterYourName": "Gib deinen Namen ein",
  "fillTheFormWithAttachments": "Bitte füllen Sie dieses Formular aus ** {1} **",
  "digitalWealthPassport": "Digital Reichtum Passport",
  "oops": "Hoppla",
  "back": "Zurück",
  "details": "Einzelheiten",
  "newContactRequest": "{1} hat dir eine Kontaktanfrage gesendet",
  "submitLog": "Protokoll einreichen",
  "setPassword": "Wählen Sie ein sicheres Passwort",
  "hello": "Hallo {1}!",
  "documentExpiredTitle": "Dokument abgelaufen",
  "addNew": "Hinzufügen von neuem {1}",
  "takeAPicture": "Bitte nehmen Sie ein ** Selfie ** Bild von Ihrem Gesicht",
  "enterPassword": "Gib dein Passwort ein",
  "messageWaitingFrom": "Sie haben eine neue Nachricht von {1}",
  "done": "Erledigt",
  "drawYourPasswordAgain": "Zeichne dein Muster erneut",
  "invalidDocument": "ungültiges Dokument",
  "verifiedByOn": "Verifiziert von {1} an",
  "myDocuments": "Meine Dokumente",
  "enableCameraAccess": "{appName} hat derzeit keine Berechtigung, die Kamera zu verwenden. Um Zugriff zu gewähren, wählen Sie Einstellungen und stellen Sie sicher, dass Kamera aktiviert ist.",
  "patternNotMatching": "Die Muster stimmten nicht überein.",
  "issuedByOn": "Ausgestellt von {1} am",
  "youReviewedAll": "Du hast alle {1} überprüft",
  "installingUpdate": "Update installieren",
  "testProviders": "Sandkasten",
  "youShallNotPass": "Du darfst nicht passieren!",
  "error": "Error",
  "confirmedMyData": "Alle importierten Daten können in Ihrem {profileTitle} angezeigt werden",
  "pleaseRestartTIM": "Bitte starten Sie TiM neu",
  "somethingWrong": "Etwas ist schief gelaufen",
  "passwordsDontMatch": "Passwörter stimmen nicht überein",
  "searchSomething": "Suche {1}",
  "issuedBy": "Ausgestellt von {1}",
  "noScanningOnAndroid": "Dokumentenscan auf Android kommt bald.",
  "sharedWith": "Freigegebener {1} Kontext mit {2}",
  "youReviewed": "Sie haben {1} von {2} Elementen überprüft",
  "sandboxDescription": "Erfahren Sie in der Sandbox, wie Sie die App mit simulierten Dienstleistern verwenden können.",
  "invalidPropertyValue": "Ungültiger Wert",
  "verificationBy": "Überprüfung durch {1}",
  "approveApplication": "Antrag genehmigen",
  "invalidProperty": "Ungültig {1}",
  "newProduct": "Neues Produkt",
  "confirmForgetMe": "Sind Sie sicher, dass Sie \"{1}\" vergessen möchten?",
  "offlineMode": "Offline Mode",
  "hideResource": "{1} ausblenden",
  "providerIsOffline": "{1} ist offline",
  "listOfProducts": "Produktliste",
  "thePropertyWithMinMaxRangeError": "Die Eigenschaft mit [min-max] Bereich kann nur zwei Zahlen haben",
  "independentBlockchainViewer": "Independent blockchain viewer",
  "noNetwork": "Kein Netzwerk",
  "backToResults": "Zurück zu den Ergebnissen",
  "pleaseCorrect": "Bitte korrigieren",
  "formListError": "Nicht verfügbar",
  "yes": "Ja",
  "dataSecurity": "Datensicherheit",
  "creationDate": "Datum erstellt",
  "help": "Hilfe",
  "next": "Nächster",
  "shareOneOfMany": "Alternativ teilen Sie unten",
  "gestureNotRecognized": "Falsches Muster",
  "addServerUrl": "Fügen Sie die Server-URL hinzu",
  "continue": "Fortsetzen",
  "shareWith": "Teilen {1}",
  "verificationTransactionID": "Bestätigungstransaktions-ID",
  "switchTouchIdOff": "Schalten Sie die Touch ID aus",
  "updateNow": "Jetzt aktualisieren",
  "changeGesturePassword": "Ändern Sie das Gestenpasswort",
  "add": "Hinzufügen {1}",
  "changePassword": "Passwort ändern",
  "later": "Später",
  "inProgress": "Ihre Anfrage ist in Bearbeitung",
  "loadingModels": "Laden von Modellen",
  "settings": "die Einstellungen",
  "fillTheForm": "Bitte füllen Sie dieses Formular aus ** {1} **",
  "overviewOfApplications": "Übersicht der Anwendungen",
  "contactUs": "Kontaktiere uns",
  "optional": "wahlweise",
  "scanQRcode": "QR-Code scannen",
  "initializingEngine": "Initialisierung der Engine",
  "pleaseDrawPassword": "Zeichne dein Muster",
  "turnBothOn": "Schalte beide an",
  "bothOn": "Beide sind eingeschaltet",
  "importYourData": "Importieren Sie Ihre Daten",
  "forgetMe": "Vergiss mich",
  "thisFieldIsRequired": "Dieses Feld wird benötigt",
  "setDateValue": "einstellen",
  "search": "Suche",
  "formChooser": "Formularliste",
  "trustedProviders": "Vertrauenswürdige Anbieter",
  "pairingRequest": "Paarungsanfrage",
  "cameraAccess": "Kamerazugriff",
  "pairDevices": "Geräte koppeln",
  "invalidPattern": "Falsches Muster",
  "shareChangesWith": "Teilen Sie Änderungen mit",
  "verifyPrompt": "Überprüfen?",
  "enterCurrentPassword": "Gib dein aktuelles Passwort ein",
  "drawYourNewPasswordAgain": "Zeichnen Sie das neue Muster erneut",
  "tooManyPasswordAttempts": "Zu viele Fehlschläge! Dieses Formular wurde deaktiviert.",
  "profile": "Profil",
  "unlockDevice": "entsperren Sie Ihr Gerät, um fortzufahren",
  "ok": "OK",
  "authenticationFailed": "Authentifizierung fehlgeschlagen",
  "setNewPassword": "Wähle ein neues Passwort",
  "sentTo": "An {1} gesendet",
  "drawYourPassword": "Zeichne dein Muster",
  "sentToOn": "An {1} gesendet",
  "edit": "Bearbeiten",
  "passwordOn": "Das Gestenpasswort ist aktiviert",
  "receivedProduct": "Erhalten {1}",
  "viewTerms": "Bitte sehen Sie sich die Allgemeinen Geschäftsbedingungen an",
  "invalidPairingRequest": "Ungültige Kopplungsanfrage",
  "backTo": "Zurück zu {1}",
  "asVerifiedBy": "Wie von {1} bestätigt",
  "turnPasswordOn": "Aktivieren Sie das Gestenpasswort",
  "centerID": "ID im Rahmen zentrieren",
  "turnTouchIdOn": "Schalten Sie die Touch ID ein",
  "customerWaiting": "{1} hat den Chat betreten",
  "receivedForm": "Erhalten {1}",
  "pleaseCorrectTheErrors": "Bitte korrigieren Sie den Fehler im Formular",
  "deviceDoesNotHaveMyKeys": "Die empfangene Identität hat meine Schlüssel nicht",
  "acceptTermsAndConditions": "Nutzungsbedingungen anzeigen",
  "shareContext": "Teilen {1}",
  "wrongPattern": "Falsches Muster",
  "submittingForm": "Übermittelt {1}",
  "termsAndConditions": "Geschäftsbedingungen.",
  "receivedVerification": "Bestätigung für {1} erhalten",
  "en": "Englisch",
  "iNeed": "Ich brauche...",
  "nl": "Niederländisch",
  "documentNotScanning": "Ups! Irgendwas lief schief!",
  "newProductMsg": "Ich brauche ein {1}.",
  "nothingChanged": "Nichts hat sich geändert",
  "unknownQRCodeFormat": "Nicht erkanntes QR-Code-Format",
  "cancel": "Stornieren",
  "restartApp": "App neu starten",
  "homePage": "Zuhause",
  "updateAppTitle": "App-Aktualisierung verfügbar",
  "noAccessToServer": "Der Server ist nicht erreichbar. Versuche es später.",
  "importing": "Importieren",
  "denyApplication": "Anwendung verweigern",
  "enablePassword": "Passwort aktivieren",
  "resetRequired": "Zurücksetzen erforderlich",
  "nothingToShare": "Nichts zu teilen",
  "restartingApp": "Die Anwendung wird momentan neu gestartet",
  "learnMore": "Mehr erfahren",
  "willBeAvailable": "Diese Funktionalität wird in Kürze verfügbar sein",
  "neverMissAMessage": "Verpasse nie eine Nachricht",
  "shareAllPastAndFutureMessages": "Teilen Sie alle vergangenen und zukünftigen Nachrichten in diesem Kontext mit ausgewählten Parteien",
  "sendEditRequestPrompt": "Bearbeitungsanfrage an {1} senden?",
  "approveApplicationFor": "Antrag für {1} genehmigen",
  "centerPassport": "Fotoalbum im Passbild zentrieren",
  "addAnotherFormOrGetNext": "Fügen Sie ein weiteres {1} hinzu oder fahren Sie mit dem nächsten Formular fort",
  "shareProduct": "Sie können unten tippen, um {1} mit {2} zu teilen.",
  "switchToRepresentative": "Der Wechsel in den Vertretungsmodus ist noch nicht implementiert.",
  "acceptingTermsAndConditions": "Mit OK bestätigen Sie die Allgemeinen Geschäftsbedingungen",
  "reviewScannedProperties": "Bitte überprüfen und korrigieren Sie die folgenden Daten",
  "useTouchIdAndGesturePassword": "Aktivieren Sie Touch ID und Geste",
  "scanningFailedTryAgain": "Scannen war nicht erfolgreich. Könnten Sie es bitte noch einmal versuchen?",
  "officialAccounts": "Gespräche",
  "createNext": "Füllen Sie ein anderes Formular \"{1}\" aus",
  "viewDebugLog": "Debug-Protokoll anzeigen",
  "youAreTheRM": "Sie sind der Beziehungsmanager für diese Anwendung",
  "tapToRemovePhotos": "Tippe, um Fotos zu entfernen",
  "importDataPrompt": "Sie sind dabei, Ihre Daten zu importieren",
  "drawYourNewPassword": "Zeichne ein neues Muster",
  "createNew": "Formular \"{1}\" ausfüllen",
  "typeMessage": "Geben Sie eine Nachricht ein",
  "correctGesture": "Korrektes Muster erkannt",
  "confirmAllItems": "Tippen Sie auf OK, um alle zu bestätigen, oder auf Abbrechen, um die Überprüfung fortzusetzen",
  "shareOne1": "{1}, dies ist Ihr persönlicher Datenschutz-Assistent. Ich sehe, du hast deine {2} bereits verifiziert. Sie können unten tippen, um es mit {3} zu teilen.",
  "testForgetMe": "Dies ist ein Testmechanismus, um alle Kommunikationen mit diesem Anbieter zurückzusetzen",
  "fromMyData": "aus 'Meine Daten'",
  "somethingWrongSubmitLog": "Etwas scheint falsch gelaufen zu sein. Senden Sie das Debugprotokoll an das {appName} Entwicklerteam",
  "formRequest": "Anfrage für {1}",
  "documentExpiredMessage": "Bitte scannen Sie ein gültiges Dokument",
  "loadingResources": "Ressourcen laden",
  "youShared": "Du hast von {1} geteilt",
  "temporarilyLocked": "Zu Ihrem Schutz wurde diese Anwendung vorübergehend für {1} gesperrt.",
  "touchIdOn": "Touch ID ist EIN",
  "unreadMessages": "Sie haben ungelesene Nachrichten",
  "learnMoreServerIsDown": "Alle von Ihnen geschriebenen Nachrichten werden automatisch an {1} gesendet, wenn sie online gehen.",
  "verifiedBy": "Verifiziert von {1}",
  "contextsFor": "Kontexte für",
  "learnMoreDescriptionTo": "Sie können weiterhin Nachrichten im Offline-Modus schreiben, obwohl Ihr Gerät nicht verbunden ist. Wenn Sie die Verbindung wiederherstellen, werden alle Ihre Nachrichten automatisch an {1} gesendet.",
  "sourcesBy": "Quellen von {1}",
  "generatingKeys": "Generieren Sie Ihre privaten Schlüssel",
  "applyForProduct": "Bewerben Sie sich für ein Produkt",
  "downloadingUpdate": "Update herunterladen ...",
  "passwordLimitations": "Muster muss 5+ Punkte haben",
  "noConnection": "{appName} benötigt eine funktionierende Internetverbindung, die Sie im Moment nicht haben",
  "cancelHideResource": "Abbrechen Verbergen {1}",
  "asSentTo": "Wie an {1} gesendet",
  "serverIsUnreachable": "Der Server ist nicht erreichbar",
  "irrefutableProofs": "Unwiderlegbare Beweise",
  "pleaseTapOnMenu": "Bitte tippen Sie auf den roten Knopf und",
  "thisValueIsInvalidPlaceholder": "Dieser Wert ist ungültig, weil ...",
  "denyApplicationFor": "Anwendung für {1} verweigern",
  "submitting": "Einreichen",
  "sharedContext": "Gemeinsamer Kontext",
  "youAreForgotten": "Du bist erfolgreich vergessen worden",
  "centerLicence": "Lizenz im Rahmen zentrieren",
  "correctPassword": "Ach, du erinnerst dich!",
  "multientryToShare": "Es gibt {1} Dokumente zum Teilen",
  "shareMyProduct": "Sie können unten tippen, um {1} mit {2} zu teilen.",
  "cancelItem": "Sie sind dabei, {1} abzubrechen. Bitte tippen Sie zur Bestätigung auf OK",
  "areYouSureYouWantToConfirmAllItems": "Tippen Sie auf OK, um alle Angaben zu bestätigen, oder auf Abbrechen, um die Überprüfung fortzusetzen",
  "noConnectionForPL": "{appName} benötigt eine funktionierende Internetverbindung, um eine Liste von Produkten aus {1} anzufordern, die Sie im Moment nicht haben",
  "noConnectionForNewProduct": "{1}, {appName} erfordert eine funktionierende Internetverbindung, um die Anwendung {2} auszufüllen.",
  "theMinValueBiggerThenMaxValue": "Der Mindestwert für den Bereich sollte kleiner als der Maximalwert sein",
  "shareOneOfMany1": "{1}, dies ist Ihr persönlicher Datenschutz-Assistent. Ich sehe, du hast deine {2} bereits verifiziert. Sie können auf beliebige Elemente in der Liste tippen, um sie mit {3} zu teilen.",
  "verifierHelp": "Klicken Sie nach dem Überprüfen des Formulars auf \"Fertig\". Wenn einige Felder korrigiert werden müssen, überprüfen Sie sie zuerst und klicken Sie dann auf die Schaltfläche \"Fertig\"",
  "formListErrorDescription": "Formulare können angefordert werden, sobald der Kunde eine Anwendung beginnt",
  "invalidDeepLink": "Sieht aus, als hättest du auf einen ungültigen Link geklickt!",
  "ukLicenseUnsupported": "Der britische Führerschein-Scan wird derzeit nicht unterstützt",
  "updateAppMessage": "Update jetzt, oder soll ich dich später erinnern?",
  "pleaseCorrectFields": "Bitte korrigieren Sie die folgenden Felder: {1}",
  "fieldErrorMessagePrompt": "Was ist los mit diesem Feld?",
  "pairingRequestWasProcesseed": "Die Kopplungsanfrage wurde verarbeitet",
  "youAreAboutToShare": "Sie werden es teilen\n \"{1}\"\n Unterlagen",
  "sharedForm": "Freigegeben {1} von {2}",
  "submittingModifiedForm": "Ändern von {1}",
  "areYouSureAboutWipe": "Diese Aktion ist irreversibel. Sie verlieren alle Ihre Daten und privaten Schlüssel. Sind Sie sicher, dass Sie fortfahren möchten?",
  "holdPhoneToPassport": "Halten Sie die Rückseite Ihres Telefons gegen die Vorderseite Ihres Reisepasses",
  "enablePasscodeFirst": "Offenbar haben Sie keinen Gerätepasscode aktiviert. Ohne sie kann diese App Ihre Daten nicht schützen! Bitte aktivieren Sie es, bevor Sie auf OK klicken",
  "learnMoreDescription": "Sie können weiterhin Nachrichten im Offline-Modus schreiben, obwohl Ihr Gerät nicht verbunden ist. Wenn Sie die Verbindung wiederherstellen, werden alle Ihre Nachrichten automatisch gesendet.",
  "incompatibleVersion": "Aufgrund der letzten nicht kompatiblen inkompatiblen Änderungen erfordert dieses Update einen Hard Reset der App. Drücken Sie OK, um die Identität und den Speicherplatz der App zurückzusetzen.",
  "retryScanning": "War das ein {1}? Ich konnte es nicht sagen. Bitte versuche es erneut?\n\nUm optimale Ergebnisse zu erzielen, verwenden Sie den Querformatmodus, vermeiden Sie grelles Licht und achten Sie darauf, das Dokument innerhalb des dargestellten Rahmens zu positionieren.",
  "textPasswordLimitations": "Muss mindestens 10 Zeichen enthalten, mindestens einen Großbuchstaben, einen Kleinbuchstaben, eine Zahl und ein Sonderzeichen",
  "storageCorrupted": "Ihr Browserspeicher ist beschädigt! Drücken Sie OK, um die Identität und den Speicherplatz der App zurückzusetzen.",
  "areYouSureYouWantToDelete": "Möchten Sie {1} wirklich ausblenden?",
  "pleaseClickOnAddButton": "Bitte klicken Sie auf \"+\", um \"{1}\" hinzuzufügen",
  "holdPhoneToPassportBackCover": "Halten Sie die Rückseite Ihres Telefons gegen die Rückseite des Reisepasses.",
  "iproovFailedMessage": "Bitte versuche es erneut. Für beste Ergebnisse halten Sie Ihr Gesicht während der Farbblitze im Oval zentriert.",
  "importData": "Daten importieren",
  "no": "Nein",
  "importingData": "Importieren von {1} Dokumenten von {2}",
  "switchTouchIdOn": "Schalten Sie die Touch ID ein",
  "useTouchId": "Aktivieren Sie die Touch ID",
  "useGesturePassword": "Gestenpasswort aktivieren",
  "showQR": "Mein QR-Code",
  "confirmRevoke": "Bitten Sie {1}, dieses Dokument aus ihren Datensätzen zu löschen.",
  "errorNotification": "Zur Korrektur wurde eine Fehlerbenachrichtigung an den Kunden gesendet",
  "areYouSureAboutNextForm": "Sind Sie sicher, dass Sie mit {1} fertig sind?",
  "noConnectionWillProcessLater": "{appName} benötigt eine funktionierende Internetverbindung, die Sie im Moment nicht haben. Die Anfrage wird verarbeitet, wenn eine Verbindung hergestellt wird",
  "iproovFailedTitle": "Hoppla! Etwas ist schief gelaufen",
  "iproovErrorTitle": "Hoppla! Etwas ist schief gelaufen",
  "fillRequiredFields": "Bitte füllen Sie alle erforderlichen Felder aus",
  "iproovErrorMessage": "Bitte warten Sie ein wenig und versuchen Sie es erneut",
  "areYouSureYouWantToServeThisCustomer": "Sind Sie sicher, dass Sie diesen Kunden bedienen möchten?",
  "validationErrors": "Bitte korrigieren Sie die fehlerhaften Validierungsfelder",
  "receiveNotifications?": "Möchten Sie Benachrichtigungen erhalten?",
  "nameUnknown": "Name unbekannt",
  "Next": "Nächster",
  "retake": "Wiederholung",
  "Cancel": "Stornieren",
  "Clear": "klar",
  "Get set": "Richte dich ein",
  "getStarted": "Loslegen",
  "Give me a moment...": "Gib mir einen Moment...",
  "Sending": "Senden",
  "ID document": "ID-Dokument",
  "Applications": "Anwendungen",
  "Go friendliness!": "Geht Freundlichkeit!",
  "Go!": "Gehen!",
  "Submit": "einreichen",
  "Skip": "Überspringen",
  "Seals": "Dichtungen",
  "Done": "Erledigt",
  "goodNewsFew": "Gute Nachrichten! Du hast schon einige. Um das Tap-Symbol unten zu teilen.",
  "Please take a selfie to prove this is your document. Center your face.": "Bitte nehmen Sie ein Selfie, um zu beweisen, dass dies Ihr Dokument ist. Zentriere dein Gesicht.",
  "Finally, you will be in control of your own private information!": "Schließlich haben Sie die Kontrolle über Ihre privaten Informationen!",
  "Choose Apply for Product from the menu": "Wählen Sie im Menü die Option zum Anwenden des Produkts",
  "Take a quick tour of chat bot?": "Machen Sie eine kurze Tour von Chat Bot?",
  "Before we start you'll need a valid passport, identity card or driving license": "Bevor wir anfangen, benötigen Sie einen gültigen Reisepass, Personalausweis oder Führerschein",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Wir stellen Ihnen Fragen im Chat und Sie füllen einfach die Formulare aus oder folgen den Anfragen",
  "Corporation Exists Checks": "Corporation Existiert Prüfungen",
  "bookmarks": "Lesezeichen",
  "' photo of yourself that I can match against your ID document": "\"Foto von dir, das ich mit deinem Ausweisdokument vergleichen kann",
  "Sanctions Checks": "Sanktionen Checks",
  "exploreData": "Daten erkunden",
  "Verifications": "Überprüfungen",
  "Please scan your": "Bitte scannen Sie Ihre",
  "goodNews": "Gute Nachrichten! Du hast bereits {1}. Tippen Sie zum Teilen auf das Symbol unten",
  "loading": "Wird geladen...",
  "Deny": "Verweigern",
  "Our products have changed": "Unsere Produkte haben sich verändert",
  "Ready?": "Bereit?",
  "Approve": "Genehmigen",
  "Please fill out the form": "Bitte füllen Sie das Formular aus",
  "See our list of products": "Siehe unsere Produktliste",
  "pleaseSign": "Bitte unterschreiben Sie in der grauen Box",
  "Get set for friendliness?": "Werden Sie für Freundlichkeit eingestellt?",
  "createManualMatchCheck": "Erstellen Sie eine manuelle Übereinstimmungsprüfung",
  "Please tap here and sign": "Bitte tippen Sie hier und unterschreiben Sie",
  "Ready for friendliness?": "Bereit für Freundlichkeit?",
  "usePhoto": "Verwenden Sie ein Foto",
  "Please click to scan your": "Bitte klicken Sie, um Ihre Suche zu starten",
  "Thank you. Now take a '": "Vielen Dank. Nimm jetzt ein '",
  "checkIfMatch": "Überprüfen Sie, ob Übereinstimmung besteht",
  "Application submitted!": "Bewerbung eingereicht!",
  "Photo": "Foto",
  "inProcess": "Wird bearbeitet...",
  "newCustomer": "Neukunde",
  "reviewData": "Überprüfen Sie die Daten",
  "debugLogSent": "Debug-Protokoll gesendet",
  "wrongDocumentTypePleaseTryAgain": "Falscher Dokumenttyp Bitte versuche es erneut",
  "validatingDataClaim": "Daten importieren",
  "resetApp": "App zurücksetzen",
  "documentBackSide": "Rückseite des Dokuments zentrieren",
  "failedToSendLog": "Protokoll konnte nicht gesendet werden",
  "scanYourDocument": "Bitte scannen Sie Ihr Dokument",
  "invalidCountry": "Ungültiges Land wurde gescannt",
  "invalidQR": "Ungültiger QR-Code",
  "wipeTheAppData": "Wischen Sie die App-Daten ab",
  "requestMyData": "Meine Daten anfordern",
  "pleaseChooseDT": "Bitte wählen Sie zuerst den Dokumenttyp",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Bitte überprüfen Sie die Daten unten und machen Sie einen Überblick über die {1} -Seite des Dokuments",
  "startedByAnotherEmployee": "Die Anwendung für {1} wurde von einem anderen Mitarbeiter gestartet",
  "networkFailure": "Ich habe Probleme mit dem Netzwerk. Können Sie prüfen und dann auf Wiederholen / Abbrechen tippen",
  "areYouSureYouAreDone": "Möchten Sie diese Sitzung wirklich beenden?",
  "doYouWantToContinue": "Möchten Sie dorthin wechseln und von dort fortfahren?",
  "afterRefresh": "Sie dürfen unsere Dienste ohne Unterbrechung nutzen",
  "dateInTheFutureError": "{1} ist in der Zukunft",
  "noResourcesForCriteria": "Für diese Kriterien wurden keine Ressourcen gefunden",
  "invalidQuery": "Hoppla! Beim Ausführen Ihrer Suche ist ein Fehler aufgetreten. Unsere Entwickler werden versuchen, es so schnell wie möglich zu beheben.",
  "supportedQrCodes": "Unterstützte QR-Codes:\n1) Chatkanal hinzufügen\n2) Daten importieren",
  "logSentToDevTeam": "Das Protokoll wurde an das Tradle-Entwicklerteam gesendet",
  "enterPasswordOrWipeOutTheAppData": "Passwort eingeben oder App-Daten löschen"
}