module.exports = {
  "searchSomething": "অনুসন্ধান {1}",
  "invalidPattern": "ভুল প্যাটার্ন",
  "enterCurrentPassword": "আপনার বর্তমান পাসওয়ার্ডটি প্রবেশ করান",
  "drawYourOldPassword": "আপনার পুরানো প্যাটার্ন আঁকা",
  "iproovFailedMessage": "অনুগ্রহপূর্বক আবার চেষ্টা করুন. সেরা ফলাফলের জন্য, রঙের ফ্ল্যাশগুলির সময় ওভালে আপনার কেন্দ্রকে কেন্দ্র করে রাখুন।",
  "help": "সাহায্য করুন",
  "drawYourNewPassword": "একটি নতুন প্যাটার্ন আঁকা",
  "learnMoreDescriptionTo": "আপনার ডিভাইস সংযুক্ত না থাকলেও আপনি এখনও অফলাইন মোডে বার্তা লিখতে পারেন। যখন আপনি আপনার সমস্ত বার্তা পুনঃসংযোগ করবেন তখন স্বয়ংক্রিয়ভাবে {1} পাঠানো হবে।",
  "shareContext": "শেয়ার করুন {1}",
  "providerIsOffline": "{1} অফলাইন",
  "setNewPassword": "একটি নতুন পাসওয়ার্ড পছন্দ করুন",
  "temporarilyLocked": "আপনার সুরক্ষার জন্য, এই অ্যাপ্লিকেশনটিকে সাময়িকভাবে লক করা হয়েছে {1}",
  "settings": "সেটিংস",
  "overviewOfApplications": "অ্যাপ্লিকেশন সংক্ষিপ্ত বিবরণ",
  "restartApp": "অ্যাপ পুনরায় আরম্ভ করুন",
  "formListErrorDescription": "গ্রাহক একটি আবেদন শুরু একবার ফর্ম অনুরোধ করা যেতে পারে",
  "youShallNotPass": "আপনি পাস হবে না!",
  "sendEditRequestPrompt": "সম্পাদনা অনুরোধ পাঠাতে {1}?",
  "gestureNotRecognized": "ভুল প্যাটার্ন",
  "offlineMode": "নীরব কার্যপদ্ধতি",
  "done": "সম্পন্ন",
  "iproovErrorTitle": "ওহো! কিছু ভুল হয়েছে",
  "back": "পিছনে",
  "theMinValueBiggerThenMaxValue": "পরিসরের জন্য মিনি মানটি সর্বোচ্চ মানের পরে ছোট হওয়া উচিত",
  "backTo": "ফিরে {1}",
  "contextsFor": "জন্য কনটেক্সট",
  "ukLicenseUnsupported": "ইউকে ড্রাইভার লাইসেন্স স্ক্যানিং এই সময়ে সমর্থিত নয়",
  "testForgetMe": "এটি এই সরবরাহকারীর সাথে সমস্ত যোগাযোগ পুনরায় সেট করার জন্য একটি পরীক্ষামূলক প্রক্রিয়া",
  "drawYourPasswordAgain": "আবার আপনার প্যাটার্ন আঁকা",
  "forgetMe": "আমাকে ভুলে যাও",
  "hello": "হ্যালো {1}!",
  "officialAccounts": "কথোপকথন",
  "importYourData": "আপনার তথ্য আমদানি করুন",
  "messageWaitingFrom": "আপনার কাছ থেকে একটি নতুন বার্তা আছে {1}",
  "correctGesture": "সঠিক প্যাটার্ন সনাক্ত",
  "invalidProperty": "অবৈধ {1}",
  "asSentTo": "পাঠানো হয়েছে {1}",
  "ok": "ঠিক আছে",
  "drawYourPassword": "আপনার প্যাটার্ন আঁকা",
  "iNeed": "আমার দরকার...",
  "confirmForgetMe": "আপনি কি নিশ্চিত যে আপনি '{1}' আপনাকে ভুলে যেতে চান",
  "sentTo": "পাঠানো হয়েছে {1}",
  "initializingEngine": "ইঞ্জিন আরম্ভ করা",
  "setPassword": "একটি নিরাপদ পাসওয়ার্ড নির্বাচন করুন",
  "cancel": "বাতিল",
  "error": "এরর",
  "addServerUrl": "সার্ভার ইউআরএল যোগ করুন",
  "pleaseRestartTIM": "টিআইএম পুনরায় আরম্ভ করুন",
  "formListError": "অপ্রাপ্য",
  "asVerifiedBy": "হিসাবে যাচাই করে {1}",
  "digitalWealthPassport": "ডিজিটাল সম্পদ পাসপোর্ট",
  "passwordsDontMatch": "পাসওয়ার্ড মেলে না",
  "invalidDocument": "অবৈধ নথি",
  "formRequest": "{1} এর জন্য অনুরোধ",
  "details": "বিস্তারিত",
  "sharedWith": "{1} সাথে ভাগ করা {1}",
  "restartingApp": "অ্যাপ্লিকেশন মুহূর্তে পুনরায় আরম্ভ করা হবে",
  "validationErrors": "ব্যর্থ যাচাই ক্ষেত্র সঠিক করুন",
  "edit": "সম্পাদন করা",
  "enterYourName": "আপনার নাম প্রবেশ করুন",
  "passwordLimitations": "প্যাটার্ন অবশ্যই 5+ পয়েন্ট থাকতে হবে",
  "turnTouchIdOn": "স্পর্শ আইডি চালু করুন",
  "iproovFailedTitle": "ওহো! কিছু ভুল হয়েছে",
  "pleaseDrawPassword": "আপনার প্যাটার্ন আঁকা",
  "thisValueIsInvalidPlaceholder": "এই মান অবৈধ কারণ ...",
  "backToResults": "ফলাফল ফিরে",
  "search": "অনুসন্ধান",
  "patternNotMatching": "নিদর্শন মেলে না।",
  "issuedBy": "দ্বারা ইস্যু করা {1}",
  "bothOn": "উভয় চালু হয়",
  "trustedProviders": "বিশ্বস্ত প্রদানকারী",
  "unreadMessages": "আপনি অপঠিত বার্তা আছে",
  "importingData": "{2} থেকে {1} নথি আমদানি হচ্ছে",
  "continue": "চালিয়ে",
  "thePropertyWithMinMaxRangeError": "[মিনি-সর্বোচ্চ] পরিসরের সাথে সম্পত্তির কেবল দুটি সংখ্যা থাকতে পারে",
  "thisFieldIsRequired": "ঘরটি অবশ্যই পূরণ করতে হবে",
  "no": "না",
  "wrongPattern": "ভুল প্যাটার্ন",
  "viewDebugLog": "ডিবাগ লগ দেখুন",
  "touchIdOn": "টাচ আইডি চালু হয়",
  "unlockDevice": "এগিয়ে যেতে আপনার ডিভাইস আনলক করুন",
  "yes": "হাঁ",
  "multientryToShare": "শেয়ার করতে {1} নথি আছে",
  "nothingToShare": "ভাগ করার কিছুই নেই",
  "somethingWrongSubmitLog": "কিছু ভুল হয়েছে বলে মনে হয়। {AppName} বিকাশকারী দলটিতে ডিবাগ লগ জমা দিন দয়া করে",
  "youAreTheRM": "আপনি এই আবেদনটির জন্য সম্পর্ক ম্যানেজার",
  "generatingKeys": "আপনার ব্যক্তিগত কী উৎপন্ন",
  "drawYourNewPasswordAgain": "আবার নতুন প্যাটার্ন আঁকা",
  "testProviders": "স্যান্ডবক্স",
  "verifyPrompt": "যাচাই করবেন?",
  "pleaseCorrectFields": "নিম্নলিখিত ক্ষেত্রগুলি সঠিক করুন: {1}",
  "pairDevices": "জোড়া ডিভাইস",
  "formChooser": "ফরম তালিকা",
  "verifierHelp": "ফর্মটি পর্যালোচনা করার পরে 'সম্পন্ন' বোতামটি ক্লিক করুন। কিছু ক্ষেত্রের সংশোধন প্রয়োজন হলে প্রথমে তাদের পরীক্ষা করুন এবং তারপরে 'সম্পন্ন' বোতামে ক্লিক করুন",
  "centerPassport": "ফ্রেম সেন্টার পাসপোর্ট ছবির পাতা",
  "storageCorrupted": "আপনার অ্যাপ্লিকেশন এর keychain তথ্য এবং স্টোরেজ দূষিত হয়েছে! যদি আপনি মনে করেন এটি একটি ভুল, আবার চেষ্টা করার জন্য পুনরায় শুরু করুন অ্যাপটি টিপুন। রিসেট অ্যাপ টিপুন অ্যাপটির পরিচয় এবং সঞ্চয়স্থান পুনরায় সেট করবে।",
  "approveApplicationFor": "{1} জন্য অ্যাপ্লিকেশন অনুমোদন",
  "shareMyProduct": "{1} এর সাথে {1} ভাগ করতে আপনি নীচের আলতো চাপুন",
  "en": "ইংরেজি",
  "authenticationFailed": "প্রমাণীকরণ ব্যর্থ হয়েছে",
  "iproovErrorMessage": "একটু অপেক্ষা করুন এবং আবার চেষ্টা করুন",
  "noScanningOnAndroid": "Android এ ডকুমেন্ট স্ক্যানিং শীঘ্রই আসছে।",
  "profile": "প্রোফাইলের",
  "verifiedByOn": "{1} দ্বারা যাচাই করা হয়েছে",
  "next": "পরবর্তী",
  "invalidPairingRequest": "অবৈধ জুড়ি অনুরোধ",
  "youAreAboutToShare": "আপনি ভাগ করতে চলেছেন\n '{1}'\n কাগজপত্র",
  "unknownQRCodeFormat": "অস্বীকৃত QR কোড বিন্যাস",
  "shareWith": "শেয়ার করুন {1}",
  "fromMyData": "'আমার তথ্য' থেকে",
  "pleaseCorrect": "সংশোধন করুন",
  "areYouSureYouWantToServeThisCustomer": "আপনি এই গ্রাহক পরিবেশন করতে চান আপনি কি নিশ্চিত?",
  "shareOne": "বিকল্পভাবে, নিচে ভাগ করুন",
  "pleaseClickOnAddButton": "'{1}' যোগ করার জন্য নিচে '+' ক্লিক করুন",
  "learnMoreServerIsDown": "আপনি অনলাইনে যে কোন বার্তা লিখবেন তা স্বয়ংক্রিয়ভাবে {1} পাঠানো হবে।",
  "creationDate": "তারিখ তৈরী",
  "dataSecurity": "তথ্য নিরাপত্তা",
  "pleaseCorrectTheErrors": "ফর্ম ত্রুটি ত্রুটি দয়া করে",
  "receiveNotifications?": "আপনি বিজ্ঞপ্তি পেতে চান?",
  "independentBlockchainViewer": "স্বাধীন ব্লকচেন দর্শক",
  "createNext": "অন্য ফর্ম পূরণ করুন \"{1}\"",
  "sandboxDescription": "স্যান্ডবক্সে, সিমুলেটেড পরিষেবা সরবরাহকারীদের সাথে অ্যাপ্লিকেশনটি কীভাবে ব্যবহার করবেন তা শিখুন।",
  "centerID": "ফ্রেম সেন্টার আইডি",
  "centerLicence": "ফ্রেম কেন্দ্রের লাইসেন্স",
  "customerWaiting": "{1} চ্যাট প্রবেশ করেছে",
  "loadingModels": "মডেল লোড হচ্ছে",
  "updateAppTitle": "অ্যাপ আপডেট উপলব্ধ",
  "shareAllPastAndFutureMessages": "নির্বাচিত পক্ষের সাথে এই প্রসঙ্গে সমস্ত অতীত এবং ভবিষ্যতের বার্তা ভাগ করুন",
  "importDataPrompt": "আপনি থেকে আপনার তথ্য আমদানি করতে চলেছেন",
  "youAreForgotten": "আপনি সফলভাবে ভুলে গেছেন",
  "reviewScannedProperties": "পর্যালোচনা করুন এবং নীচের তথ্য সংশোধন করুন",
  "scanQRcode": "স্ক্যান QR কোড",
  "neverMissAMessage": "একটি বার্তা মিস করবেন না",
  "useGesturePassword": "অঙ্গভঙ্গি পাসওয়ার্ড সক্রিয় করুন",
  "fillTheFormWithAttachments": "** এই ফর্মটি পূরণ করুন ** {1} **",
  "submitting": "জমা দেওয়া হচ্ছে",
  "cancelItem": "আপনি বাতিল করতে চলেছেন {1}। নিশ্চিত করার জন্য ঠিক আছে আলতো চাপুন",
  "nameUnknown": "নাম অজানা",
  "areYouSureYouWantToDelete": "আপনি কি {1} লুকিয়ে রাখতে চান?",
  "shareOne1": "{1}, এটি আপনার ব্যক্তিগত গোপনীয়তা সহকারী। আমি দেখেছি আপনি ইতিমধ্যে আপনার {2} যাচাই করেছি। আপনি {3} এর সাথে এটি ভাগ করতে নীচের আলতো চাপুন।",
  "changeGesturePassword": "অঙ্গভঙ্গি পাসওয়ার্ড পরিবর্তন করুন",
  "createNew": "ফর্ম পূরণ করুন \"{1}\"",
  "later": "পরবর্তীতে",
  "learnMoreDescription": "আপনার ডিভাইস সংযুক্ত না থাকলেও আপনি এখনও অফলাইন মোডে বার্তা লিখতে পারেন। আপনি আপনার সমস্ত বার্তা পুনরায় সংযোগ যখন স্বয়ংক্রিয়ভাবে পাঠানো হবে।",
  "addNew": "নতুন {1} যোগ করুন",
  "shareOneOfMany": "বিকল্পভাবে, নিচে ভাগ করুন",
  "somethingWrong": "কিছু ভুল হয়েছে",
  "fieldErrorMessagePrompt": "এই ক্ষেত্রে কি ভুল?",
  "listOfProducts": "পণ্য তালিকা",
  "errorNotification": "ত্রুটির নোটিফিকেশন গ্রাহককে ঠিক করতে পাঠানো হয়েছে",
  "acceptTermsAndConditions": "শর্তাবলী দেখুন",
  "approveApplication": "আবেদন অনুমোদন",
  "learnMore": "আরো জানুন",
  "passwordOn": "অঙ্গভঙ্গি পাসওয়ার্ড চালু হয়",
  "receivedForm": "প্রাপ্ত {1}",
  "resetRequired": "রিসেট প্রয়োজন",
  "acceptingTermsAndConditions": "ঠিক আছে টিপে, আপনি শর্তাদি এবং শর্তাদি স্বীকার করেন",
  "installingUpdate": "আপডেট স্থাপন করা হচ্ছে",
  "oops": "ওহো",
  "updateNow": "এখন হালনাগাদ করুন",
  "incompatibleVersion": "সাম্প্রতিক পিছনে সামঞ্জস্যপূর্ণ পরিবর্তনগুলির কারণে, এই আপডেটটির জন্য অ্যাপ্লিকেশনের হার্ড রিসেট প্রয়োজন। অ্যাপ্লিকেশনের পরিচয় এবং সঞ্চয়স্থান পুনরায় সেট করতে ঠিক আছে টিপুন।",
  "myDocuments": "আমার ডকুমেন্টস",
  "denyApplication": "আবেদন অস্বীকার করুন",
  "documentExpiredTitle": "নথি মেয়াদ উত্তীর্ণ",
  "submittingModifiedForm": "পরিবর্তন করা {1}",
  "cameraAccess": "ক্যামেরা এক্সেস",
  "noConnectionForNewProduct": "{1}, {appName} কে {2} অ্যাপ্লিকেশনটি পূরণ করতে একটি কার্যকর ইন্টারনেট সংযোগ প্রয়োজন।",
  "turnPasswordOn": "অঙ্গভঙ্গি পাসওয়ার্ড চালু করুন",
  "deviceDoesNotHaveMyKeys": "পরিচয় প্রাপ্তি আমার কী আছে না",
  "noNetwork": "কোন নেটওয়ার্ক নেই",
  "noConnectionWillProcessLater": "{appName} এর জন্য একটি কার্যকর ইন্টারনেট সংযোগ প্রয়োজন যা আপনার মুহূর্তে নেই। একটি সংযোগ স্থাপন করা হয় যখন অনুরোধ প্রক্রিয়া করা হবে",
  "receivedVerification": "{1} এর জন্য যাচাইকরণ পেয়েছি",
  "viewTerms": "শর্তাবলী দেখুন দয়া করে",
  "willBeAvailable": "এই কার্যকারিতা শীঘ্রই পাওয়া যাবে",
  "holdPhoneToPassportBackCover": "আপনার পাসপোর্টের পিছনের ভেতরের কভারের বিরুদ্ধে আপনার ফোনের পিছনে ধরে রাখুন।",
  "termsAndConditions": "শর্তাবলী.",
  "textPasswordLimitations": "অবশ্যই 10+ অক্ষর, কমপক্ষে একটি বড় হাতের অক্ষর, ছোট হাতের অক্ষর, সংখ্যা এবং বিশেষ অক্ষর থাকতে হবে",
  "retryScanning": "যে একটি {1}? আমি বলতে পারলাম না। অনুগ্রহপূর্বক আবার চেষ্টা করুন?\n\nসেরা ফলাফলের জন্য, আড়াআড়ি মোড ব্যবহার করুন, বিবর্ণতা এড়ান এবং ফ্রেম দেখানো নথির অবস্থান নিশ্চিত করুন।",
  "receivedProduct": "প্রাপ্ত {1}",
  "hideResource": "লুকান {1}",
  "holdPhoneToPassport": "আপনার পাসপোর্টের সামনে কভারের বিরুদ্ধে আপনার ফোনের পিছনে ধরে রাখুন",
  "noConnectionForPL": "{appName} এর থেকে {0} পণ্যগুলির একটি তালিকা অনুরোধ করার জন্য একটি কার্যকর ইন্টারনেট সংযোগ প্রয়োজন যা আপনার কাছে নেই",
  "useTouchId": "টাচ আইডি সক্ষম করুন",
  "youReviewedAll": "আপনি সমস্ত {1} পর্যালোচনা করেছেন",
  "sharedForm": "ভাগ করা {1}",
  "issuedByOn": "দ্বারা প্রকাশিত {1}",
  "scanningFailedTryAgain": "স্ক্যানিং ব্যর্থ হয়েছে। আপনি আবার চেষ্টা করতে পারেন?",
  "switchTouchIdOff": "সুইচ আইডি বন্ধ করুন",
  "verificationTransactionID": "যাচাই লেনদেন আইডি",
  "enterPassword": "আপনার পাসওয়ার্ড লিখুন",
  "pairingRequestWasProcesseed": "জুড়ি অনুরোধ প্রক্রিয়াধীন ছিল",
  "updateAppMessage": "এখন আপডেট করুন, নাকি আমি পরে আপনাকে মনে করিয়ে দেব?",
  "useTouchIdAndGesturePassword": "টাচ আইডি এবং অঙ্গভঙ্গি সক্ষম করুন",
  "fillRequiredFields": "সমস্ত প্রয়োজনীয় ক্ষেত্রগুলি পূরণ করুন",
  "takeAPicture": "আপনার মুখের একটি ** selfie ** ছবি গ্রহণ করুন",
  "newProduct": "নতুন পণ্য",
  "submitLog": "লগ জমা দিন",
  "importing": "আমদানি হচ্ছে",
  "verifiedBy": "দ্বারা যাচাইকৃত {1}",
  "pairingRequest": "জুড়ি অনুরোধ",
  "inProgress": "চলমান...",
  "noAccessToServer": "সার্ভার অ্যাক্সেসযোগ্য নয়। পরে চেষ্টা করুন।",
  "add": "যোগ করুন {1}",
  "switchToRepresentative": "প্রতিনিধি মোডে স্যুইচিং এখনো বাস্তবায়িত হয় না।",
  "invalidDeepLink": "মনে হচ্ছে আপনি একটি অবৈধ লিঙ্ক ক্লিক করেছেন!",
  "documentNotScanning": "কিছু ভুল হয়েছে!",
  "tapToRemovePhotos": "ফটো অপসারণ করতে আলতো চাপুন",
  "nothingChanged": "কিছুই পরিবর্তন হয়নি",
  "contactUs": "আমাদের সাথে যোগাযোগ করুন",
  "newContactRequest": "{1} আপনাকে যোগাযোগ অনুরোধ পাঠানো হয়েছে",
  "confirmAllItems": "তাদের সব নিশ্চিত করতে ঠিক আছে আলতো চাপুন, অথবা পর্যালোচনা চালিয়ে যেতে বাতিল করুন",
  "denyApplicationFor": "{1} জন্য আবেদন প্রত্যাখ্যান",
  "setDateValue": "সেট",
  "shareChangesWith": "সঙ্গে পরিবর্তন শেয়ার করুন",
  "verificationBy": "{1} দ্বারা যাচাইকরণ",
  "addAnotherFormOrGetNext": "অন্য {1} যোগ করুন বা পরবর্তী ফর্মটিতে যান",
  "areYouSureYouWantToConfirmAllItems": "সব {1} নিশ্চিত করতে ঠিক আছে আলতো চাপুন, অথবা পর্যালোচনা চালিয়ে যেতে বাতিল করুন",
  "shareOneOfMany1": "{1}, এটি আপনার ব্যক্তিগত গোপনীয়তা সহকারী। আমি দেখেছি আপনি ইতিমধ্যে আপনার {2} যাচাই করেছি। {3} এর সাথে ভাগ করার জন্য নীচের তালিকাতে যেকোন আইটেমগুলিতে আপনি ট্যাপ করতে পারেন।",
  "areYouSureAboutNextForm": "আপনি কি যোগ করেছেন {1}?",
  "youReviewed": "আপনি {2} আইটেমগুলির মধ্যে {1} পর্যালোচনা করেছেন",
  "importData": "তথ্য আমদানি করুন",
  "enableCameraAccess": "{appName} বর্তমানে ক্যামেরা ব্যবহার করার অনুমতি নেই। অ্যাক্সেস প্রদান করতে, সেটিংস নির্বাচন করুন এবং নিশ্চিত করুন যে ক্যামেরাটি সক্ষম রয়েছে।",
  "youShared": "আপনি {1} থেকে ভাগ করেছেন",
  "switchTouchIdOn": "সুইচ আইডি সুইচ",
  "newProductMsg": "আমি একটি {1} প্রয়োজন।",
  "documentExpiredMessage": "একটি বৈধ নথি স্ক্যান করুন",
  "fillTheForm": "** এই ফর্মটি পূরণ করুন ** {1} **",
  "showQR": "আমার QR কোড",
  "noConnection": "{appName} এর জন্য একটি কার্যকর ইন্টারনেট সংযোগ প্রয়োজন যা আপনার মুহূর্তে নেই",
  "tooManyPasswordAttempts": "অনেক গুলো ব্যর্থ চেষ্টা! এই ফর্মটি নিষ্ক্রিয় করা হয়েছে।",
  "optional": "ঐচ্ছিক",
  "cancelHideResource": "বাতিল করুন {1}",
  "correctPassword": "ওহ, আপনি মনে আছে!",
  "serverIsUnreachable": "সার্ভার অপ্রচলিত",
  "sponsoredBy": "সৌজন্যে",
  "sourcesBy": "সূত্র দ্বারা {1}",
  "applyForProduct": "একটি পণ্যের জন্য আবেদন করুন",
  "invalidPropertyValue": "ভুল মুল্য",
  "confirmedMyData": "সমস্ত আমদানি করা তথ্য আপনার {profileTitle}",
  "sharedContext": "ভাগ করা প্রসঙ্গ",
  "loadingResources": "লোড হচ্ছে সম্পদ",
  "changePassword": "পাসওয়ার্ড পরিবর্তন করুন",
  "shareProduct": "{1} এর সাথে {1} ভাগ করতে আপনি নীচের আলতো চাপুন",
  "homePage": "বাড়ি",
  "enablePasscodeFirst": "মনে হচ্ছে আপনার ডিভাইস পাসকোড সক্ষম নেই। এটি ছাড়া, এই অ্যাপ্লিকেশন আপনার তথ্য রক্ষা করতে পারে না! ঠিক আছে চাপার আগে এটি সক্রিয় করুন",
  "sentToOn": "পাঠানো {1} উপর",
  "nl": "ডাচ",
  "pleaseTapOnMenu": "লাল বোতাম এবং আলতো চাপুন",
  "confirmRevoke": "{1} এই নথিটি তাদের রেকর্ড থেকে মুছতে বলুন?",
  "irrefutableProofs": "অযৌক্তিক প্রমাণ",
  "turnBothOn": "উভয় চালু করুন",
  "typeMessage": "একটি বার্তা টাইপ করুন",
  "enablePassword": "পাসওয়ার্ড সক্রিয় করুন",
  "downloadingUpdate": "একটি আপডেট ডাউনলোড হচ্ছে ...",
  "areYouSureAboutWipe": "এই ক্রিয়া অপরিবর্তনীয়। আপনি আপনার সমস্ত তথ্য এবং ব্যক্তিগত কী হারাবেন। আপনি কি নিশ্চিত আপনি সামনে এগুতে চান?",
  "submittingForm": "জমা দেওয়া {1}",
  "bookmarks": "বুকমার্ক",
  "exploreData": "তথ্য এক্সপ্লোর করুন",
  "Please scan your": "আপনার স্ক্যান করুন দয়া করে",
  "ID document": "আইডি নথি",
  "Please fill out the form": "ফর্মটি পূরণ করুন",
  "See our list of products": "পণ্য আমাদের তালিকা দেখুন",
  "Our products have changed": "আমাদের পণ্য পরিবর্তন হয়েছে",
  "Please take a selfie to prove this is your document. Center your face.": "এই আপনার নথি প্রমাণ করার জন্য একটি selfie নিতে দয়া করে। আপনার মুখ কেন্দ্র।",
  "Choose Apply for Product from the menu": "মেনু থেকে পণ্য জন্য আবেদন করুন নির্বাচন করুন",
  "Application submitted!": "আবেদন জমা!",
  "Sending": "পাঠানো হচ্ছে",
  "Please tap here and sign": "এখানে টোকা এবং সাইন করুন",
  "Give me a moment...": "আমাকে একটা মুহূর্ত দাও",
  "Please click to scan your": "আপনার স্ক্যান করতে ক্লিক করুন",
  "' photo of yourself that I can match against your ID document": "'আপনার নিজের ছবি যা আমি আপনার আইডি নথির সাথে মিলতে পারি",
  "Thank you. Now take a '": "ধন্যবাদ. এখন একটি '",
  "pleaseSign": "ধূসর বাক্সের ভিতরে সাইন ইন করুন",
  "getStarted": "এবার শুরু করা যাক",
  "goodNewsFew": "ভাল খবর! আপনি ইতিমধ্যে বেশ কয়েক আছে। নিচের টোকা আইকন শেয়ার করুন।",
  "goodNews": "ভাল খবর! আপনি ইতিমধ্যে {1} আছে। নীচের আইকন আলতো চাপুন",
  "Cancel": "বাতিল",
  "Submit": "জমা দিন",
  "Clear": "পরিষ্কার",
  "retake": "পুনরায় নেওয়া",
  "usePhoto": "ছবি ব্যবহার করুন",
  "Deny": "অস্বীকার করা",
  "Approve": "অনুমোদন করা",
  "loading": "লোড হচ্ছে ...",
  "Verifications": "যাচাইকরণ",
  "Seals": "সীল",
  "Applications": "অ্যাপ্লিকেশন",
  "checkIfMatch": "ম্যাচ চেক করুন",
  "Corporation Exists Checks": "কর্পোরেশন বিদ্যমান চেক",
  "createManualMatchCheck": "ম্যানুয়াল ম্যাচ চেক তৈরি করুন",
  "Ready for friendliness?": "বন্ধুত্বের জন্য প্রস্তুত?",
  "Get set for friendliness?": "বন্ধুত্বের জন্য সেট পেতে?",
  "Go friendliness!": "বন্ধুত্ব যান!",
  "Take a quick tour of chat bot?": "চ্যাট বট একটি দ্রুত সফর নিন?",
  "Finally, you will be in control of your own private information!": "অবশেষে, আপনি নিজের ব্যক্তিগত তথ্য নিয়ন্ত্রণে থাকবেন!",
  "Ready?": "প্রস্তুত?",
  "Go!": "যান!",
  "Get set": "সেট পেতে",
  "Before we start you'll need a valid passport, identity card or driving license": "আমরা শুরু করার আগে আপনাকে একটি বৈধ পাসপোর্ট, পরিচয়পত্র বা ড্রাইভিং লাইসেন্সের প্রয়োজন হবে",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "আমরা আপনাকে চ্যাটে প্রশ্ন জিজ্ঞাসা করব এবং আপনি কেবল ফর্মগুলি পূরণ করুন বা অনুরোধগুলি অনুসরণ করুন",
  "Skip": "লাফালাফি করা",
  "Done": "সম্পন্ন",
  "Next": "পরবর্তী",
  "Sanctions Checks": "সনদ চেক",
  "inProcess": "প্রক্রিয়া হচ্ছে ...",
  "networkFailure": "আমি কিছু নেটওয়ার্ক সমস্যা সম্মুখীন করছি। আপনি চেক এবং তারপর আবার চেষ্টা / বাতিল করতে পারেন",
  "invalidQuery": "ওহো, আমরা আপনার অনুসন্ধান চালানোর একটি ত্রুটি আঘাত। আমাদের ডেভেলপাররা এটি অ্যাসপ ঠিক করার চেষ্টা করবে।",
  "validatingDataClaim": "তথ্য আমদানি করা হচ্ছে",
  "invalidQR": "অবৈধ QR কোড",
  "debugLogSent": "ডিবাগ লগ প্রেরিত",
  "failedToSendLog": "লগ পাঠাতে ব্যর্থ",
  "logSentToDevTeam": "লগ ট্রেন্ডেল বিকাশকারী দল পাঠানো হয়েছিল",
  "noResourcesForCriteria": "কোন সম্পদ এই মানদণ্ডের জন্য পাওয়া যায় নি",
  "supportedQrCodes": "সমর্থিত QR কোড:\n1) চ্যাট চ্যানেল যোগ করুন\n2) আমদানি তথ্য",
  "reviewScannedPropertiesAndSecondSideSnapshot": "নীচের ডেটা পর্যালোচনা করুন এবং দস্তাবেজের {1} পাশের স্ন্যাপশট নিন",
  "documentBackSide": "কেন্দ্র দল ফিরে পাশ",
  "Photo": "ছবি",
  "doYouWantToContinue": "আপনি কি এটিতে স্যুইচ করতে চান এবং সেখানে থেকে যেতে চান?",
  "startedByAnotherEmployee": "{1} এর জন্য আবেদনটি অন্য কর্মচারী দ্বারা শুরু হয়েছিল",
  "reviewData": "তথ্য পর্যালোচনা করুন",
  "afterRefresh": "আপনি বাধা ছাড়া আমাদের সেবা ব্যবহার করার জন্য সাফ করা হয়",
  "requestMyData": "আমার তথ্য অনুরোধ",
  "newCustomer": "নতুন গ্রাহক",
  "areYouSureYouAreDone": "আপনি এই অধিবেশন শেষ করতে চান আপনি কি নিশ্চিত?",
  "resetApp": "অ্যাপ রিসেট করুন",
  "wrongDocumentTypePleaseTryAgain": "ভুল নথি টাইপ। অনুগ্রহপূর্বক আবার চেষ্টা করুন",
  "invalidCountry": "অবৈধ দেশ স্ক্যান করা হয়েছে",
  "scanYourDocument": "আপনার নথি স্ক্যান করুন",
  "wipeTheAppData": "অ্যাপ্লিকেশন তথ্য মুছা",
  "enterPasswordOrWipeOutTheAppData": "পাসওয়ার্ড প্রবেশ করুন বা অ্যাপ্লিকেশন তথ্য মুছা",
  "dateInTheFutureError": "{1} ভবিষ্যতে",
  "pleaseChooseDT": "প্রথমে নথি টাইপ নির্বাচন করুন"
}