module.exports = {
  "backToResults": "Retour aux résultats",
  "hideResource": "Masquer {1}",
  "downloadingUpdate": "Télécharger une mise à jour ...",
  "sharedForm": "Partagé {1}",
  "customerWaiting": "{1} est entré sur le chat",
  "forgetMe": "Oublie moi",
  "verifierHelp": "Cliquez sur le bouton 'Terminé' après avoir examiné le formulaire. Si certains champs nécessitent une correction, commencez par les vérifier, puis cliquez sur le bouton \"Terminé\".",
  "oops": "Oops",
  "youAreForgotten": "Vous avez été oublié avec succès",
  "verifiedBy": "Vérifié par {1}",
  "myDocuments": "Mes documents",
  "homePage": "Accueil",
  "learnMoreDescription": "Vous pouvez toujours écrire des messages en mode hors connexion même si votre appareil n'est pas connecté. Lorsque vous vous reconnectez, tous vos messages seront automatiquement envoyés.",
  "documentExpiredTitle": "Document expiré",
  "officialAccounts": "Les conversations",
  "shareOne": "Sinon, partagez ci-dessous",
  "pairDevices": "Paire d'appareils",
  "useGesturePassword": "Activer le mot de passe gestuel",
  "testProviders": "bac à sable",
  "theMinValueBiggerThenMaxValue": "La valeur minimale de la plage doit être inférieure à la valeur maximale.",
  "termsAndConditions": "Termes et conditions.",
  "thisValueIsInvalidPlaceholder": "cette valeur est invalide parce que ...",
  "en": "Anglais",
  "typeMessage": "Tapez un message",
  "shareOneOfMany": "Sinon, partagez ci-dessous",
  "useTouchIdAndGesturePassword": "Activer Touch ID et Gesture",
  "formChooser": "Liste de formulaire",
  "formListError": "Indisponible",
  "restartApp": "Redémarrer l'application",
  "learnMoreServerIsDown": "Tous les messages que vous écrivez seront automatiquement envoyés à {1} lorsqu'ils seront mis en ligne.",
  "invalidPropertyValue": "valeur invalide",
  "turnTouchIdOn": "Activer le Touch ID",
  "receivedForm": "Reçu {1}",
  "acceptingTermsAndConditions": "En appuyant sur OK, vous acceptez les termes et conditions",
  "contactUs": "Contactez nous",
  "willBeAvailable": "Cette fonctionnalité sera bientôt disponible",
  "turnBothOn": "Allumer les deux",
  "documentExpiredMessage": "Veuillez numériser un document valide",
  "add": "Ajouter {1}",
  "correctGesture": "Motif correct détecté",
  "scanQRcode": "Scannez le code QR",
  "help": "Aidez-moi",
  "shareContext": "Partager {1}",
  "updateNow": "Mettre à jour maintenant",
  "cancel": "Annuler",
  "ok": "D'accord",
  "neverMissAMessage": "Ne manquez jamais un message",
  "noNetwork": "Pas de réseau",
  "submittingModifiedForm": "Modifier {1}",
  "sendEditRequestPrompt": "Envoyer la demande de modification à {1}?",
  "addServerUrl": "Ajouter l'URL du serveur",
  "formListErrorDescription": "Les formulaires peuvent être demandés une fois que le client commence une application",
  "shareWith": "Partager {1}",
  "tapToRemovePhotos": "Appuyez pour supprimer des photos",
  "bothOn": "Les deux sont sur",
  "listOfProducts": "Liste de produits",
  "youReviewedAll": "Vous avez examiné tous les {1}",
  "passwordLimitations": "Le motif doit avoir plus de 5 points",
  "takeAPicture": "S'il vous plaît prendre une photo ** selfie ** de votre visage",
  "asSentTo": "Comme envoyé à {1}",
  "settings": "Réglages",
  "inProgress": "En cours...",
  "continue": "Continuer",
  "verificationTransactionID": "ID de transaction de vérification",
  "touchIdOn": "Touch ID est activé",
  "documentNotScanning": "Oups, quelque chose s'est mal passé!",
  "next": "Suivant",
  "searchSomething": "Recherche {1}",
  "switchToRepresentative": "Le passage en mode représentatif n'est pas encore implémenté.",
  "correctPassword": "Aww, tu t'es souvenu!",
  "switchTouchIdOn": "Activer ID tactile",
  "enablePasscodeFirst": "On dirait que vous n'avez pas de code d'authentification de périphérique activé. Sans cela, cette application ne peut pas protéger vos données! Veuillez l'activer avant d'appuyer sur OK",
  "shareMyProduct": "Vous pouvez appuyer sur ci-dessous pour partager {1} avec {2}.",
  "newProductMsg": "J'ai besoin d'un {1}.",
  "newProduct": "Nouveau produit",
  "acceptTermsAndConditions": "Voir les termes et conditions",
  "nothingChanged": "Rien n'a changé",
  "errorNotification": "La notification d'erreur a été envoyée au client pour corriger",
  "digitalWealthPassport": "Passeport de richesse numérique",
  "testForgetMe": "Ceci est un mécanisme de test pour réinitialiser toutes les communications avec ce fournisseur",
  "changeGesturePassword": "Changer le mot de passe du geste",
  "somethingWrongSubmitLog": "Quelque chose semble avoir mal tourné. Veuillez envoyer le journal de débogage à l'équipe de développement {appName}.",
  "trustedProviders": "Fournisseurs de confiance",
  "ukLicenseUnsupported": "L'analyse du permis de conduire britannique n'est pas prise en charge pour le moment.",
  "areYouSureYouWantToConfirmAllItems": "Appuyez sur OK pour confirmer tous les {1}, ou sur Annuler pour continuer à consulter.",
  "switchTouchIdOff": "Désactiver le Touch ID",
  "drawYourPasswordAgain": "Dessine à nouveau ton motif",
  "turnPasswordOn": "Activer le mot de passe de geste",
  "viewTerms": "S'il vous plaît voir les termes et conditions",
  "pleaseCorrect": "Corrigez s'il vous plaît",
  "pairingRequestWasProcesseed": "La demande de pairage a été traitée",
  "done": "Terminé",
  "showQR": "Mon code QR",
  "search": "Chercher",
  "submittingForm": "Envoyé {1}",
  "noConnectionWillProcessLater": "{appName} nécessite une connexion Internet fonctionnelle que vous n'avez pas pour le moment. La demande sera traitée lors de l'établissement d'une connexion.",
  "issuedByOn": "Publié par {1} le",
  "formRequest": "Demande de {1}",
  "useTouchId": "Activer Touch ID",
  "invalidPattern": "Mauvais modèle",
  "deviceDoesNotHaveMyKeys": "L'identité reçue n'a pas mes clés",
  "invalidDocument": "document invalide",
  "youReviewed": "Vous avez examiné {1} éléments sur {2}",
  "applyForProduct": "Appliquer pour un produit",
  "pleaseCorrectFields": "Veuillez corriger les champs suivants: {1}",
  "thisFieldIsRequired": "Ce champ est requis",
  "receivedProduct": "Reçu {1}",
  "confirmAllItems": "Appuyez sur OK pour tous les confirmer ou sur Annuler pour continuer à consulter.",
  "sourcesBy": "Sources par {1}",
  "confirmedMyData": "Toutes les données importées peuvent être visualisées dans votre {profileTitle}",
  "areYouSureAboutWipe": "Cette action est irréversible. Vous perdrez toutes vos données et vos clés privées. Êtes-vous sur de vouloir continuer?",
  "profile": "Profil",
  "edit": "modifier",
  "newContactRequest": "{1} vous a envoyé une demande de contact",
  "youShared": "Vous avez partagé du {1}",
  "confirmForgetMe": "Etes-vous sûr de vouloir \"{1}\" vous oublier",
  "asVerifiedBy": "Comme vérifié par {1}",
  "areYouSureAboutNextForm": "Avez-vous fini d'ajouter {1}?",
  "cancelHideResource": "Annuler Masquer {1}",
  "setPassword": "Choisissez un mot de passe sécurisé",
  "receivedVerification": "Vérification reçue pour {1}",
  "receiveNotifications?": "Souhaitez-vous recevoir des notifications?",
  "invalidPairingRequest": "Demande de couplage invalide",
  "addAnotherFormOrGetNext": "Ajouter un autre {1} ou passer au formulaire suivant",
  "enterPassword": "Tapez votre mot de passe",
  "shareOne1": "{1}, il s'agit de votre assistant personnel de confidentialité. Je vois que votre {2} a déjà été vérifié. Vous pouvez appuyer sur ci-dessous pour le partager avec {3}.",
  "unknownQRCodeFormat": "Format de code QR non reconnu",
  "optional": "optionnel",
  "somethingWrong": "Quelque chose a mal tourné",
  "nl": "néerlandais",
  "overviewOfApplications": "Vue d'ensemble des applications",
  "backTo": "Retour à {1}",
  "pleaseCorrectTheErrors": "S'il vous plaît corriger l'erreur dans le formulaire",
  "pairingRequest": "Demande de jumelage",
  "issuedBy": "Publié par {1}",
  "fillTheFormWithAttachments": "Veuillez remplir ce formulaire ** {1} **",
  "submitLog": "Soumettre le journal",
  "error": "Erreur",
  "fillTheForm": "Veuillez remplir ce formulaire ** {1} **",
  "youAreAboutToShare": "Vous allez partager\n '{1}'\n des documents",
  "dataSecurity": "Sécurité des données",
  "nameUnknown": "nom inconnu",
  "iproovErrorTitle": "Oops! Quelque chose a mal tourné",
  "importData": "Importer des données",
  "sponsoredBy": "Sponsorisé par",
  "no": "Non",
  "noConnection": "{appName} nécessite une connexion Internet fonctionnelle que vous ne possédez pas pour le moment.",
  "confirmRevoke": "Demander à {1} de supprimer ce document de leurs archives?",
  "hello": "Bonjour {1}!",
  "noConnectionForPL": "{appName} nécessite une connexion Internet fonctionnelle pour demander la liste des produits de {1} que vous n'avez pas encore.",
  "importDataPrompt": "Vous allez importer vos données depuis",
  "centerPassport": "Page de passeport centrale dans le cadre",
  "contextsFor": "Contextes pour",
  "verifyPrompt": "Vérifier?",
  "noConnectionForNewProduct": "{1}, {appName} nécessite une connexion Internet fonctionnelle pour compléter l'application {2}.",
  "enablePassword": "Activer le mot de passe",
  "providerIsOffline": "{1} est déconnecté",
  "sentTo": "Envoyé à {1}",
  "drawYourNewPasswordAgain": "Dessine le nouveau motif",
  "pleaseRestartTIM": "S'il vous plaît redémarrer TiM",
  "incompatibleVersion": "En raison de récentes modifications incompatibles avec les versions antérieures, cette mise à jour nécessite une réinitialisation matérielle de l'application. Appuyez sur OK pour réinitialiser l'identité et le stockage de l'application.",
  "generatingKeys": "générer vos clés privées",
  "loadingModels": "modèles de chargement",
  "iproovErrorMessage": "S'il vous plaît attendez un peu et essayez à nouveau",
  "unreadMessages": "Vous avez des messages non lus",
  "setDateValue": "Ensemble",
  "shareProduct": "Vous pouvez appuyer sur ci-dessous pour partager {1} avec {2}.",
  "initializingEngine": "moteur d'initialisation",
  "retryScanning": "Était-ce un {1}? Je ne pouvais pas dire. Veuillez réessayer?\n\nPour de meilleurs résultats, utilisez le mode paysage, évitez les reflets et veillez à positionner le document dans le cadre illustré.",
  "createNew": "Remplissez le formulaire \"{1}\"",
  "areYouSureYouWantToDelete": "Êtes-vous sûr de vouloir vous cacher {1}?",
  "creationDate": "Date créée",
  "holdPhoneToPassportBackCover": "Tenez le dos de votre téléphone contre le dos de la couverture de votre passeport.",
  "serverIsUnreachable": "Le serveur est inaccessible",
  "storageCorrupted": "les données et le stockage du trousseau de votre application ont été corrompus! Si vous pensez que c'est une erreur, appuyez sur Redémarrer l'application pour réessayer. Appuyez sur Réinitialiser l'application pour réinitialiser l'identité et le stockage de l'application.",
  "centerLicence": "Licence de centre en cadre",
  "cameraAccess": "Accès à la caméra",
  "sharedContext": "Contexte partagé",
  "pleaseClickOnAddButton": "Veuillez cliquer sur '+' ci-dessous pour ajouter '{1}'",
  "youAreTheRM": "Vous êtes le responsable des relations pour cette application",
  "importingData": "Importation de {1} documents à partir de {2}",
  "iproovFailedMessage": "Veuillez réessayer. Pour de meilleurs résultats, gardez votre visage au centre de l'ovale pendant les flashs de couleur.",
  "noScanningOnAndroid": "La numérisation de documents sur Android arrive bientôt.",
  "updateAppTitle": "Mise à jour de l'application disponible",
  "enableCameraAccess": "{appName} n'a actuellement pas l'autorisation d'utiliser l'appareil photo. Pour accorder l'accès, choisissez Paramètres et assurez-vous que Caméra est activée.",
  "pleaseTapOnMenu": "S'il vous plaît appuyez sur le bouton rouge et",
  "approveApplication": "Approuver l'application",
  "back": "Retour",
  "patternNotMatching": "Les motifs ne correspondaient pas.",
  "youShallNotPass": "Vous ne pouvez pas passer!",
  "approveApplicationFor": "Approuver l'application pour le {1}",
  "shareAllPastAndFutureMessages": "Partager tous les messages passés et à venir dans ce contexte avec les parties sélectionnées",
  "wrongPattern": "Mauvais modèle",
  "pleaseDrawPassword": "Dessine ton motif",
  "unlockDevice": "déverrouiller votre appareil pour continuer",
  "nothingToShare": "Rien à partager",
  "learnMore": "Apprendre encore plus",
  "passwordOn": "Gesture Le mot de passe est activé",
  "fillRequiredFields": "S'il-vous-plaît remplissez tous les champs requis",
  "drawYourPassword": "Dessine ton motif",
  "installingUpdate": "Installation de mise à jour",
  "noAccessToServer": "Le serveur n'est pas accessible. Essayer plus tard.",
  "messageWaitingFrom": "Vous avez un nouveau message de {1}",
  "submitting": "Soumission",
  "sandboxDescription": "Dans la Sandbox, découvrez comment utiliser l'application avec des fournisseurs de services simulés.",
  "fromMyData": "de 'Mes données'",
  "areYouSureYouWantToServeThisCustomer": "Êtes-vous sûr de vouloir servir ce client?",
  "yes": "Oui",
  "importYourData": "Importez vos données",
  "reviewScannedProperties": "Veuillez revoir et corriger les données ci-dessous",
  "restartingApp": "L'application va redémarrer momentanément",
  "invalidDeepLink": "On dirait que vous avez cliqué sur un lien invalide!",
  "setNewPassword": "Choisissez un nouveau mot de passe",
  "temporarilyLocked": "Pour votre protection, cette application a été temporairement verrouillée pour le {1}.",
  "createNext": "Remplissez un autre formulaire \"{1}\"",
  "loadingResources": "chargement des ressources",
  "importing": "Importer",
  "later": "Plus tard",
  "details": "Détails",
  "authenticationFailed": "Authentification échouée",
  "validationErrors": "Veuillez corriger les champs de validation ayant échoué",
  "centerID": "ID du centre dans le cadre",
  "gestureNotRecognized": "Mauvais modèle",
  "changePassword": "Changer le mot de passe",
  "enterCurrentPassword": "Entrer votre mot de passe actuel",
  "enterYourName": "Entrez votre nom",
  "iNeed": "J'ai besoin...",
  "drawYourNewPassword": "Dessine un nouveau motif",
  "sharedWith": "Contexte {1} partagé avec {2}",
  "invalidProperty": "Non valide {1}",
  "shareOneOfMany1": "{1}, il s'agit de votre assistant personnel de confidentialité. Je vois que votre {2} a déjà été vérifié. Vous pouvez appuyer sur n’importe quel élément de la liste ci-dessous pour le partager avec {3}.",
  "viewDebugLog": "Afficher le journal de débogage",
  "sentToOn": "Envoyé à {1} le",
  "shareChangesWith": "Partager les modifications avec",
  "fieldErrorMessagePrompt": "Quel est le problème avec ce domaine?",
  "thePropertyWithMinMaxRangeError": "La propriété avec la plage [min-max] ne peut avoir que deux nombres",
  "textPasswordLimitations": "Doit avoir plus de 10 caractères, au moins une lettre majuscule, une lettre minuscule, un chiffre et un caractère spécial",
  "learnMoreDescriptionTo": "Vous pouvez toujours écrire des messages en mode hors connexion même si votre appareil n'est pas connecté. Lorsque vous vous reconnectez, tous vos messages sont automatiquement envoyés à {1}.",
  "holdPhoneToPassport": "Tenez le dos de votre téléphone contre la couverture de votre passeport",
  "independentBlockchainViewer": "Visualiseur indépendant",
  "scanningFailedTryAgain": "La numérisation a échoué. Pourriez-vous s'il vous plaît essayer à nouveau?",
  "multientryToShare": "Il y a {1} documents à partager",
  "denyApplication": "Refuser l'application",
  "iproovFailedTitle": "Oops! Quelque chose a mal tourné",
  "resetRequired": "Réinitialiser requis",
  "cancelItem": "Vous êtes sur le point d’annuler {1}. S'il vous plaît appuyez sur OK pour confirmer",
  "verificationBy": "Vérification par {1}",
  "denyApplicationFor": "Refuser l'application pour le {1}",
  "offlineMode": "Mode hors-ligne",
  "updateAppMessage": "Mettre à jour maintenant, ou dois-je vous rappeler plus tard?",
  "drawYourOldPassword": "Dessine ton vieux patron",
  "tooManyPasswordAttempts": "Trop de tentatives échouées! Ce formulaire a été désactivé.",
  "irrefutableProofs": "Preuves irréfutables",
  "verifiedByOn": "Vérifié par {1} sur",
  "passwordsDontMatch": "Les mots de passe ne correspondent pas",
  "addNew": "Ajouter nouveau {1}",
  "bookmarks": "Signets",
  "exploreData": "Explorez les données",
  "Please scan your": "Veuillez scanner votre",
  "See our list of products": "Voir notre liste de produits",
  "Please fill out the form": "S'il vous plaît remplir le formulaire",
  "ID document": "Document d'identité",
  "Please take a selfie to prove this is your document. Center your face.": "Veuillez prendre un selfie pour prouver que ceci est votre document. Centrez votre visage.",
  "Choose Apply for Product from the menu": "Choisissez Apply for Product dans le menu",
  "Our products have changed": "Nos produits ont changé",
  "Application submitted!": "Application déposée!",
  "Sending": "Envoi",
  "Please tap here and sign": "S'il vous plaît appuyez ici et signer",
  "Give me a moment...": "Accorde moi un instant...",
  "Please click to scan your": "S'il vous plaît cliquer pour numériser votre",
  "Thank you. Now take a '": "Je vous remercie. Maintenant, prenez un '",
  "' photo of yourself that I can match against your ID document": "'photo de vous que je peux comparer à votre document d'identité",
  "pleaseSign": "Merci de signer à l'intérieur de la case grise",
  "getStarted": "Commencer",
  "goodNewsFew": "Bonnes nouvelles! Vous en avez déjà plusieurs. Pour partager, appuyez sur l'icône ci-dessous.",
  "goodNews": "Bonnes nouvelles! Vous avez déjà {1}. Pour partager, appuyez sur l'icône ci-dessous",
  "Cancel": "Annuler",
  "Submit": "Soumettre",
  "Clear": "Clair",
  "retake": "Reprendre",
  "usePhoto": "Utilisez la photo",
  "Approve": "Approuver",
  "Deny": "Nier",
  "loading": "Chargement...",
  "Applications": "Applications",
  "Verifications": "Des vérifications",
  "Seals": "Scellés",
  "checkIfMatch": "Vérifier si correspond",
  "Corporation Exists Checks": "Corporation Exists Checks",
  "createManualMatchCheck": "Créer un contrôle de match manuel",
  "Get set for friendliness?": "Préparez-vous à la convivialité?",
  "Take a quick tour of chat bot?": "Faites un tour rapide de chat bot?",
  "Go friendliness!": "Allez la convivialité!",
  "Ready for friendliness?": "Prêt pour la convivialité?",
  "Finally, you will be in control of your own private information!": "Enfin, vous aurez le contrôle de vos informations personnelles!",
  "Get set": "Se mettre",
  "Go!": "Aller!",
  "Ready?": "Prêt?",
  "Before we start you'll need a valid passport, identity card or driving license": "Avant de commencer, vous aurez besoin d'un passeport, d'une carte d'identité ou d'un permis de conduire valide.",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Nous vous poserons des questions dans le chat et vous devrez simplement remplir les formulaires ou suivre les demandes.",
  "Skip": "Sauter",
  "Next": "Suivant",
  "Done": "Terminé",
  "Sanctions Checks": "Vérification des sanctions",
  "inProcess": "En traitement...",
  "networkFailure": "Je rencontre des problèmes de réseau. Pouvez-vous vérifier, puis appuyez sur Réessayer / Annuler",
  "invalidQuery": "Oups, nous avons rencontré une erreur lors de votre recherche. Nos développeurs vont essayer de le réparer dès que possible.",
  "noResourcesForCriteria": "Aucune ressource trouvée pour ce critère",
  "invalidQR": "Code QR invalide",
  "supportedQrCodes": "Codes QR pris en charge:\n1) ajouter un canal de discussion\n2) importer des données",
  "failedToSendLog": "Échec d'envoi du journal",
  "logSentToDevTeam": "Le journal a été envoyé à l'équipe de développement de Tradle.",
  "validatingDataClaim": "Importer des données",
  "debugLogSent": "Journal de débogage envoyé",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Veuillez examiner les données ci-dessous et prendre un instantané du côté {1} du document.",
  "documentBackSide": "Centrer le dos du document",
  "Photo": "Photo",
  "doYouWantToContinue": "Voulez-vous passer à cela et continuer à partir de là?",
  "startedByAnotherEmployee": "L'application pour {1} a été lancée par un autre employé.",
  "reviewData": "Revoir les données",
  "afterRefresh": "Vous êtes autorisé à utiliser nos services sans interruption",
  "requestMyData": "Demander mes données",
  "newCustomer": "Nouveau client",
  "areYouSureYouAreDone": "Êtes-vous sûr de vouloir terminer cette session?",
  "resetApp": "Réinitialiser l'application",
  "invalidCountry": "Pays invalide scanné",
  "scanYourDocument": "Veuillez numériser votre document",
  "wrongDocumentTypePleaseTryAgain": "Mauvais type de document. Veuillez réessayer",
  "wipeTheAppData": "Effacer les données de l'application",
  "enterPasswordOrWipeOutTheAppData": "Entrez le mot de passe ou effacez les données de l'application",
  "pleaseChooseCountryAndDT": "Choisissez d'abord le pays et le type de document"
}