module.exports = {
  "updateAppTitle": "Cập nhật ứng dụng có sẵn",
  "continue": "Tiếp tục",
  "incompatibleVersion": "Do những thay đổi không tương thích ngược gần đây, bản cập nhật này yêu cầu thiết lập lại cứng của ứng dụng. Nhấn OK để thiết lập lại danh tính và lưu trữ của ứng dụng.",
  "multientryToShare": "Có {1} tài liệu để chia sẻ",
  "next": "Kế tiếp",
  "verificationBy": "Xác minh bằng {1}",
  "initializingEngine": "khởi tạo động cơ",
  "centerLicence": "Giấy phép trung tâm trong khung",
  "later": "Một lát sau",
  "denyApplication": "Từ chối đơn",
  "sharedForm": "Đã chia sẻ {1}",
  "documentExpiredTitle": "Tài liệu hết hạn",
  "digitalWealthPassport": "Hộ chiếu kỹ thuật số",
  "enablePassword": "Bật mật khẩu",
  "shareOneOfMany": "Hoặc, chia sẻ dưới đây",
  "sentToOn": "Đã gửi tới {1} vào",
  "verificationTransactionID": "Xác minh giao dịch Id",
  "drawYourPasswordAgain": "Vẽ lại mô hình của bạn",
  "listOfProducts": "Danh sách sản phẩm",
  "receiveNotifications?": "Bạn có muốn nhận thông báo?",
  "receivedProduct": "Đã nhận {1}",
  "sandboxDescription": "Trong Sandbox, tìm hiểu cách sử dụng ứng dụng với các nhà cung cấp dịch vụ mô phỏng.",
  "fillTheForm": "Vui lòng điền vào mẫu này ** {1} **",
  "iproovErrorTitle": "Rất tiếc! Đã xảy ra lỗi",
  "resetRequired": "Yêu cầu thiết lập lại",
  "importYourData": "Nhập dữ liệu của bạn",
  "yes": "Vâng",
  "centerPassport": "Trung tâm trang ảnh hộ chiếu trong khung",
  "areYouSureYouWantToServeThisCustomer": "Bạn có chắc chắn muốn phục vụ khách hàng này?",
  "switchTouchIdOn": "Bật ID cảm ứng",
  "holdPhoneToPassport": "Giữ mặt sau của điện thoại so với mặt trước của hộ chiếu của bạn",
  "testProviders": "Hộp cát",
  "contactUs": "Liên hệ chúng tôi",
  "setDateValue": "Bộ",
  "trustedProviders": "Nhà cung cấp đáng tin cậy",
  "useTouchId": "Bật Touch ID",
  "inProgress": "Trong tiến trình...",
  "neverMissAMessage": "Không bao giờ bỏ lỡ một tin nhắn",
  "no": "Không",
  "generatingKeys": "tạo khóa riêng của bạn",
  "holdPhoneToPassportBackCover": "Giữ mặt sau của điện thoại dựa vào mặt sau của hộ chiếu.",
  "importData": "Nhập dữ liệu",
  "myDocuments": "Tai liệu của tôi",
  "fillTheFormWithAttachments": "Vui lòng điền vào mẫu này ** {1} **",
  "updateNow": "Cập nhật bây giờ",
  "youReviewedAll": "Bạn đã xem lại tất cả {1}",
  "iproovFailedMessage": "Vui lòng thử lại. Để có kết quả tốt nhất, hãy giữ khuôn mặt của bạn ở giữa hình bầu dục trong khi nhấp nháy màu.",
  "formListError": "Không có sẵn",
  "providerIsOffline": "{1} đang ngoại tuyến",
  "sourcesBy": "Nguồn của {1}",
  "validationErrors": "Vui lòng sửa các trường xác thực không thành công",
  "dataSecurity": "Bảo mật dữ liệu",
  "unknownQRCodeFormat": "Định dạng mã QR không được công nhận",
  "updateAppMessage": "Cập nhật ngay, hoặc tôi sẽ nhắc bạn sau?",
  "backTo": "Quay lại {1}",
  "submitting": "Đệ trình",
  "youShallNotPass": "Bạn sẽ không vượt qua!",
  "noAccessToServer": "Máy chủ không thể truy cập. Thử lại sau.",
  "centerID": "ID trung tâm trong khung",
  "acceptingTermsAndConditions": "Bằng cách nhấn OK, bạn chấp nhận Điều khoản và Điều kiện",
  "typeMessage": "Gõ một tin nhắn",
  "search": "Tìm kiếm",
  "createNext": "Điền vào một mẫu khác \"{1}\"",
  "scanQRcode": "Quét mã QR",
  "noNetwork": "Không có mạng",
  "shareChangesWith": "Chia sẻ thay đổi với",
  "shareContext": "Chia sẻ {1}",
  "shareWith": "Chia sẻ {1}",
  "learnMore": "Tìm hiểu thêm",
  "youAreForgotten": "Bạn đã bị lãng quên thành công",
  "issuedBy": "Được phát hành bởi {1}",
  "installingUpdate": "Cài đặt bản cập nhật",
  "loadingModels": "tải mô hình",
  "youReviewed": "Bạn đã đánh giá {1} trong số {2} mục",
  "creationDate": "Ngày tạo",
  "nothingChanged": "không có gì thay đổi",
  "pairingRequest": "Yêu cầu ghép nối",
  "passwordOn": "Mật khẩu cử chỉ được BẬT",
  "newContactRequest": "{1} đã gửi cho bạn yêu cầu liên hệ",
  "applyForProduct": "Áp dụng cho một sản phẩm",
  "viewDebugLog": "Xem nhật ký gỡ lỗi",
  "willBeAvailable": "Chức năng này sẽ sớm được cung cấp",
  "somethingWrong": "Đã xảy ra lỗi",
  "loadingResources": "tải tài nguyên",
  "fromMyData": "từ 'Dữ liệu của tôi'",
  "authenticationFailed": "Quá trình xác thực đã thất bại",
  "enterPassword": "Nhập mật khẩu của bạn",
  "submittingModifiedForm": "Sửa đổi {1}",
  "pleaseClickOnAddButton": "Vui lòng nhấp vào '+' bên dưới để thêm '{1}'",
  "profile": "Hồ sơ",
  "turnPasswordOn": "Bật mật khẩu cử chỉ",
  "setNewPassword": "Chọn một mật khẩu mới",
  "youShared": "Bạn đã chia sẻ từ {1}",
  "shareProduct": "Bạn có thể nhấn bên dưới để chia sẻ {1} với {2}",
  "shareMyProduct": "Bạn có thể nhấn bên dưới để chia sẻ {1} với {2}",
  "touchIdOn": "ID cảm ứng đang BẬT",
  "bothOn": "Cả hai đều BẬT",
  "changePassword": "Đổi mật khẩu",
  "hideResource": "Ẩn {1}",
  "add": "Thêm {1}",
  "createNew": "Điền vào mẫu \"{1}\"",
  "acceptTermsAndConditions": "Xem các điều khoản và điều kiện",
  "submittingForm": "Đã gửi {1}",
  "confirmAllItems": "Nhấn OK để xác nhận tất cả hoặc Hủy bỏ để tiếp tục xem xét",
  "officialAccounts": "Cuộc trò chuyện",
  "switchToRepresentative": "Chuyển sang chế độ đại diện chưa được thực hiện.",
  "sponsoredBy": "Được tài trợ bởi",
  "fieldErrorMessagePrompt": "Có gì sai với lĩnh vực này?",
  "pleaseTapOnMenu": "Vui lòng nhấn vào nút màu đỏ và",
  "pleaseRestartTIM": "Vui lòng khởi động lại TiM",
  "addNew": "Thêm {1} mới",
  "newProductMsg": "Tôi cần một {1}.",
  "changeGesturePassword": "Thay đổi mật khẩu cử chỉ",
  "useTouchIdAndGesturePassword": "Bật Touch ID và cử chỉ",
  "oops": "Rất tiếc",
  "verifiedByOn": "Được xác minh bởi {1} vào",
  "storageCorrupted": "dữ liệu và lưu trữ khóa của ứng dụng của bạn đã bị hỏng! Nếu bạn nghĩ rằng đây là một lỗi, hãy nhấn Khởi động lại ứng dụng để thử lại. Nhấn vào Đặt lại ứng dụng sẽ đặt lại danh tính và bộ nhớ của ứng dụng.",
  "newProduct": "Sản phẩm mới",
  "restartApp": "Khởi động lại ứng dụng",
  "done": "Làm xong",
  "noScanningOnAndroid": "Sắp có tài liệu trên Android.",
  "unreadMessages": "Bạn có tin nhắn chưa đọc",
  "formChooser": "Danh sách mẫu",
  "showQR": "Mã QR của tôi",
  "iproovFailedTitle": "Rất tiếc! Đã xảy ra lỗi",
  "importingData": "Nhập tài liệu {1} từ {2}",
  "sentTo": "Đã gửi tới {1}",
  "contextsFor": "Bối cảnh cho",
  "importing": "Nhập khẩu",
  "forgetMe": "Quên tôi đi",
  "en": "Anh",
  "switchTouchIdOff": "Tắt ID cảm ứng",
  "submitLog": "Gửi nhật ký",
  "shareOne": "Hoặc, chia sẻ dưới đây",
  "pairingRequestWasProcesseed": "Yêu cầu ghép đôi đã được cung cấp",
  "addServerUrl": "Thêm url máy chủ",
  "passwordLimitations": "Mẫu phải có hơn 5 điểm",
  "pairDevices": "Thiết bị cặp",
  "invalidPairingRequest": "Yêu cầu ghép nối không hợp lệ",
  "confirmRevoke": "Hỏi {1} để xóa tài liệu này khỏi hồ sơ của họ?",
  "asVerifiedBy": "Theo xác minh của {1}",
  "pleaseCorrectTheErrors": "Vui lòng sửa lỗi trong mẫu",
  "youAreAboutToShare": "Bạn sắp chia sẻ\n '{1}'\n các tài liệu",
  "messageWaitingFrom": "Bạn có một tin nhắn mới từ {1}",
  "verifyPrompt": "Kiểm chứng?",
  "termsAndConditions": "Các điều khoản và điều kiện.",
  "error": "lỗi",
  "issuedByOn": "Được phát hành bởi {1} vào",
  "sharedWith": "Bối cảnh {1} được chia sẻ với {2}",
  "errorNotification": "Thông báo lỗi đã được gửi đến khách hàng để sửa",
  "nameUnknown": "không rõ tên",
  "customerWaiting": "{1} đã vào cuộc trò chuyện",
  "learnMoreDescription": "Bạn vẫn có thể viết tin nhắn ở Chế độ ngoại tuyến ngay cả khi thiết bị của bạn không được kết nối. Khi bạn kết nối lại, tất cả tin nhắn của bạn sẽ được gửi tự động.",
  "independentBlockchainViewer": "Trình xem blockchain độc lập",
  "invalidDocument": "tài liệu không hợp lệ",
  "areYouSureYouWantToConfirmAllItems": "Nhấn OK để xác nhận tất cả {1} hoặc Hủy để tiếp tục xem xét",
  "youAreTheRM": "Bạn là người quản lý mối quan hệ cho ứng dụng này",
  "pleaseCorrectFields": "Vui lòng sửa các trường sau: {1}",
  "pleaseCorrect": "Xin hãy sửa",
  "noConnection": "{appName} yêu cầu kết nối internet đang hoạt động mà hiện tại bạn không có",
  "somethingWrongSubmitLog": "Một cái gì đó dường như đã đi sai. Vui lòng gửi nhật ký gỡ lỗi cho nhóm nhà phát triển {appName}",
  "sharedContext": "Bối cảnh chia sẻ",
  "backToResults": "Quay lại kết quả",
  "nothingToShare": "Không có gì để chia sẻ",
  "turnTouchIdOn": "Bật ID cảm ứng",
  "confirmedMyData": "Tất cả dữ liệu đã nhập có thể được xem trong {profileTitle} của bạn",
  "viewTerms": "Vui lòng xem Điều khoản và Điều kiện",
  "sendEditRequestPrompt": "Gửi yêu cầu chỉnh sửa tới {1}?",
  "downloadingUpdate": "Đang tải xuống bản cập nhật ...",
  "areYouSureYouWantToDelete": "Bạn có chắc chắn muốn ẩn {1}?",
  "thisValueIsInvalidPlaceholder": "giá trị này không hợp lệ vì ...",
  "formListErrorDescription": "Các hình thức có thể được yêu cầu khi khách hàng bắt đầu ứng dụng",
  "iproovErrorMessage": "Vui lòng đợi một chút và thử lại",
  "learnMoreServerIsDown": "Mọi tin nhắn bạn viết sẽ được tự động gửi tới {1} khi chúng trực tuyến.",
  "shareAllPastAndFutureMessages": "Chia sẻ tất cả các tin nhắn trong quá khứ và tương lai trong bối cảnh này với các bên được chọn",
  "areYouSureAboutNextForm": "Bạn đã hoàn thành việc thêm {1} chưa?",
  "addAnotherFormOrGetNext": "Thêm {1} khác hoặc chuyển sang biểu mẫu tiếp theo",
  "areYouSureAboutWipe": "Hành động này là không thể đảo ngược. Bạn sẽ mất tất cả dữ liệu và khóa riêng của bạn. Bạn có chắc muốn tiếp tục?",
  "cancelHideResource": "Hủy Ẩn {1}",
  "overviewOfApplications": "Tổng quan về ứng dụng",
  "serverIsUnreachable": "Máy chủ không thể truy cập được",
  "ukLicenseUnsupported": "Quét bằng lái xe ở Anh không được hỗ trợ tại thời điểm này",
  "fillRequiredFields": "Vui lòng điền vào tất cả các trường bắt buộc",
  "deviceDoesNotHaveMyKeys": "Nhận dạng không có chìa khóa của tôi",
  "shareOneOfMany1": "{1}, đây là trợ lý riêng tư cá nhân của bạn. Tôi thấy bạn đã xác minh {2}. Bạn có thể nhấn vào bất kỳ mục nào trong danh sách bên dưới để chia sẻ chúng với {3}.",
  "drawYourNewPasswordAgain": "Vẽ lại mẫu mới",
  "searchSomething": "Tìm kiếm {1}",
  "gestureNotRecognized": "Mẫu sai",
  "invalidPropertyValue": "giá trị không hợp lệ",
  "iNeed": "Tôi cần...",
  "drawYourPassword": "Vẽ mô hình của bạn",
  "theMinValueBiggerThenMaxValue": "Giá trị tối thiểu cho phạm vi phải nhỏ hơn giá trị tối đa",
  "verifierHelp": "Nhấp vào nút 'Xong' sau khi xem lại biểu mẫu. Nếu một số trường yêu cầu chỉnh sửa, hãy kiểm tra chúng trước và sau đó nhấp vào nút 'Xong'",
  "correctPassword": "À, bạn nhớ rồi!",
  "homePage": "Nhà",
  "textPasswordLimitations": "Phải có hơn 10 ký tự, ít nhất một chữ cái viết hoa, chữ thường, số và ký tự đặc biệt",
  "temporarilyLocked": "Để bảo vệ bạn, ứng dụng này đã tạm thời bị khóa trong {1}",
  "pleaseDrawPassword": "Vẽ mô hình của bạn",
  "irrefutableProofs": "Bằng chứng không thể chối cãi",
  "reviewScannedProperties": "Vui lòng xem lại và sửa dữ liệu dưới đây",
  "enterCurrentPassword": "Nhập mật khẩu hiện tại của bạn",
  "invalidDeepLink": "Có vẻ như bạn đã nhấp vào một liên kết không hợp lệ!",
  "ok": "được",
  "formRequest": "Yêu cầu {1}",
  "wrongPattern": "Mẫu sai",
  "thisFieldIsRequired": "Lĩnh vực này là bắt buộc",
  "approveApplicationFor": "Phê duyệt ứng dụng cho {1}",
  "approveApplication": "Phê duyệt ứng dụng",
  "retryScanning": "Đó có phải là {1} không? Tôi không thể nói. Vui lòng thử lại?\n\nĐể có kết quả tốt nhất, hãy sử dụng chế độ ngang, tránh ánh sáng chói và đảm bảo định vị tài liệu trong khung hiển thị.",
  "testForgetMe": "Đây là một cơ chế thử nghiệm để thiết lập lại tất cả các thông tin liên lạc với nhà cung cấp này",
  "denyApplicationFor": "Từ chối ứng dụng cho {1}",
  "enableCameraAccess": "{appName} hiện không có quyền sử dụng máy ảnh. Để cấp quyền truy cập, chọn Cài đặt và đảm bảo Camera được bật.",
  "documentNotScanning": "Rất tiếc, đã xảy ra lỗi!",
  "asSentTo": "Như đã gửi tới {1}",
  "cameraAccess": "Truy cập máy ảnh",
  "scanningFailedTryAgain": "Quét không thành công. Bạn có thể vui lòng thử lại không?",
  "tooManyPasswordAttempts": "Quá nhiều lần thử không thành công! Biểu mẫu này đã bị tắt.",
  "optional": "không bắt buộc",
  "back": "Trở lại",
  "settings": "Cài đặt",
  "thePropertyWithMinMaxRangeError": "Thuộc tính có phạm vi [tối thiểu] chỉ có thể có hai số",
  "cancel": "Hủy bỏ",
  "hello": "Xin chào {1}!",
  "details": "Chi tiết",
  "invalidPattern": "Mẫu sai",
  "patternNotMatching": "Các mô hình không phù hợp.",
  "tapToRemovePhotos": "Nhấn để xóa ảnh",
  "confirmForgetMe": "Bạn có chắc chắn muốn '{1}' quên bạn",
  "edit": "Chỉnh sửa",
  "enterYourName": "Nhập tên của bạn",
  "receivedVerification": "Đã nhận được xác minh cho {1}",
  "restartingApp": "Ứng dụng sẽ khởi động lại trong giây lát",
  "enablePasscodeFirst": "Có vẻ như bạn không bật mật mã thiết bị. Không có nó, ứng dụng này không thể bảo vệ dữ liệu của bạn! Vui lòng kích hoạt nó trước khi nhấn OK",
  "nl": "Hà Lan",
  "documentExpiredMessage": "Vui lòng quét một tài liệu hợp lệ",
  "importDataPrompt": "Bạn sắp nhập dữ liệu của mình từ",
  "shareOne1": "{1}, đây là trợ lý riêng tư cá nhân của bạn. Tôi thấy bạn đã xác minh {2}. Bạn có thể nhấn vào bên dưới để chia sẻ nó với {3}.",
  "learnMoreDescriptionTo": "Bạn vẫn có thể viết tin nhắn ở Chế độ ngoại tuyến ngay cả khi thiết bị của bạn không được kết nối. Khi bạn kết nối lại, tất cả các tin nhắn của bạn sẽ được tự động gửi tới {1}.",
  "takeAPicture": "Hãy chụp ảnh tự sướng ** khuôn mặt của bạn",
  "useGesturePassword": "Kích hoạt mật khẩu cử chỉ",
  "drawYourOldPassword": "Vẽ mẫu cũ của bạn",
  "noConnectionForNewProduct": "{1}, {appName} yêu cầu kết nối internet hoạt động để điền vào ứng dụng {2}.",
  "noConnectionForPL": "{appName} yêu cầu kết nối internet hoạt động để yêu cầu danh sách các sản phẩm từ {1} mà hiện tại bạn không có",
  "noConnectionWillProcessLater": "{appName} yêu cầu kết nối internet hoạt động mà bạn không có tại thời điểm này. Yêu cầu sẽ được xử lý khi kết nối được thiết lập",
  "turnBothOn": "Bật cả hai",
  "setPassword": "Chọn một mật khẩu an toàn",
  "drawYourNewPassword": "Vẽ một mẫu mới",
  "correctGesture": "Phát hiện đúng mẫu",
  "invalidProperty": "Không hợp lệ {1}",
  "verifiedBy": "Được xác minh bởi {1}",
  "passwordsDontMatch": "Mật khẩu không khớp",
  "unlockDevice": "mở khóa thiết bị của bạn để tiến hành",
  "offlineMode": "Chế độ ngoại tuyến",
  "receivedForm": "Đã nhận {1}",
  "cancelItem": "Bạn sắp hủy {1}. Vui lòng nhấn OK để xác nhận",
  "help": "Cứu giúp",
  "exploreData": "Khám phá dữ liệu",
  "bookmarks": "Dấu trang",
  "ID document": "Tài liệu ID",
  "See our list of products": "Xem danh sách sản phẩm của chúng tôi",
  "Please scan your": "Vui lòng quét",
  "Please fill out the form": "Vui lòng điền vào mẫu đơn",
  "Choose Apply for Product from the menu": "Chọn Áp dụng cho Sản phẩm từ menu",
  "Our products have changed": "Sản phẩm của chúng tôi đã thay đổi",
  "Please take a selfie to prove this is your document. Center your face.": "Hãy chụp ảnh tự sướng để chứng minh đây là tài liệu của bạn. Trung tâm khuôn mặt của bạn.",
  "Application submitted!": "Nộp hồ sơ!",
  "Sending": "Gửi",
  "Please tap here and sign": "Vui lòng nhấn vào đây và ký tên",
  "Give me a moment...": "Hãy cho tôi một chút ...",
  "Please click to scan your": "Hãy nhấp để quét của bạn",
  "Thank you. Now take a '": "Cảm ơn bạn. Bây giờ hãy lấy một '",
  "' photo of yourself that I can match against your ID document": "'ảnh của bạn mà tôi có thể đối chiếu với tài liệu ID của bạn",
  "pleaseSign": "Vui lòng đăng nhập bên trong hộp màu xám",
  "getStarted": "Bắt đầu",
  "goodNewsFew": "Tin tốt! Bạn đã có khá nhiều. Để chia sẻ biểu tượng nhấn bên dưới.",
  "goodNews": "Tin tốt! Bạn đã có {1}. Để chia sẻ, chạm vào biểu tượng bên dưới",
  "Clear": "Thông thoáng",
  "Cancel": "Hủy bỏ",
  "Submit": "Gửi đi",
  "usePhoto": "Sử dụng ảnh",
  "retake": "Lấy lại",
  "Approve": "Phê duyệt",
  "Deny": "Từ chối",
  "loading": "Tải...",
  "Seals": "Con dấu",
  "Applications": "Các ứng dụng",
  "Corporation Exists Checks": "Tổng công ty tồn tại kiểm tra",
  "Verifications": "Xác minh",
  "checkIfMatch": "Kiểm tra nếu khớp",
  "createManualMatchCheck": "Tạo kiểm tra khớp thủ công",
  "Go friendliness!": "Đi thân thiện!",
  "Get set for friendliness?": "Có được thiết lập cho sự thân thiện?",
  "Take a quick tour of chat bot?": "Tham quan nhanh trò chuyện bot?",
  "Finally, you will be in control of your own private information!": "Cuối cùng, bạn sẽ kiểm soát thông tin cá nhân của riêng bạn!",
  "Ready for friendliness?": "Sẵn sàng cho sự thân thiện?",
  "Get set": "Được thiết lập",
  "Ready?": "Sẳn sàng?",
  "Go!": "Đi!",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Chúng tôi sẽ hỏi bạn câu hỏi trong cuộc trò chuyện và bạn chỉ cần điền vào biểu mẫu hoặc làm theo yêu cầu",
  "Before we start you'll need a valid passport, identity card or driving license": "Trước khi chúng tôi bắt đầu, bạn sẽ cần hộ chiếu hợp lệ, chứng minh nhân dân hoặc bằng lái xe",
  "Done": "Làm xong",
  "Next": "Kế tiếp",
  "Skip": "Bỏ qua",
  "Sanctions Checks": "Kiểm tra xử phạt",
  "inProcess": "Chế biến...",
  "networkFailure": "Tôi đang gặp một số vấn đề về mạng. Bạn có thể kiểm tra và sau đó nhấn Thử lại / Hủy không",
  "invalidQuery": "Rất tiếc, chúng tôi đã gặp lỗi khi tìm kiếm của bạn. Các nhà phát triển của chúng tôi sẽ cố gắng sửa nó càng sớm càng tốt.",
  "supportedQrCodes": "Mã QR được hỗ trợ:\n1) thêm kênh trò chuyện\n2) nhập dữ liệu",
  "noResourcesForCriteria": "Không có tài nguyên được tìm thấy cho tiêu chí này",
  "validatingDataClaim": "Nhập dữ liệu",
  "logSentToDevTeam": "Nhật ký đã được gửi đến nhóm nhà phát triển Tradle",
  "invalidQR": "Mã QR không hợp lệ",
  "failedToSendLog": "Không thể gửi nhật ký",
  "debugLogSent": "Nhật ký gỡ lỗi đã gửi",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Vui lòng xem lại dữ liệu bên dưới và chụp ảnh nhanh về phía {1} của tài liệu",
  "documentBackSide": "Trung tâm tài liệu phía sau",
  "Photo": "ảnh",
  "startedByAnotherEmployee": "Ứng dụng cho {1} đã được bắt đầu bởi một nhân viên khác",
  "doYouWantToContinue": "Bạn có muốn chuyển sang nó và tiếp tục từ đó?",
  "reviewData": "Xem lại dữ liệu",
  "afterRefresh": "Bạn bị xóa để sử dụng dịch vụ của chúng tôi mà không bị gián đoạn",
  "requestMyData": "Yêu cầu dữ liệu của tôi",
  "newCustomer": "Khách hàng mới",
  "areYouSureYouAreDone": "Bạn có chắc chắn muốn kết thúc phiên này?",
  "scanYourDocument": "Vui lòng quét tài liệu của bạn",
  "wrongDocumentTypePleaseTryAgain": "Loại tài liệu sai. Vui lòng thử lại",
  "resetApp": "Đặt lại ứng dụng",
  "invalidCountry": "Quốc gia không hợp lệ được quét",
  "enterPasswordOrWipeOutTheAppData": "Nhập mật khẩu hoặc xóa dữ liệu ứng dụng",
  "wipeTheAppData": "Xóa dữ liệu ứng dụng",
  "pleaseChooseCountryAndDT": "Vui lòng chọn quốc gia và loại tài liệu trước"
}