module.exports = {
  "officialAccounts": "conversaties",
  "back": "Terug",
  "profile": "Profiel",
  "done": "Gedaan",
  "edit": "Bewerk",
  "settings": "instellingen",
  "theMinValueBiggerThenMaxValue": "De minimale waarde voor het bereik moet kleiner zijn dan de maximale waarde",
  "thePropertyWithMinMaxRangeError": "De eigenschap met het bereik [min-max] kan slechts twee cijfers bevatten",
  "invalidProperty": "Ongeldige {1}",
  "optional": "facultatief",
  "thisFieldIsRequired": "dit veld is verplicht",
  "pleaseDrawPassword": "Teken je patroon",
  "drawYourPassword": "Teken je patroon",
  "gestureNotRecognized": "Verkeerd patroon",
  "passwordLimitations": "Patroon moet 5+ punten hebben",
  "invalidPattern": "Verkeerd patroon",
  "patternNotMatching": "De patronen kwamen niet overeen.",
  "wrongPattern": "Verkeerd patroon",
  "correctGesture": "Correct patroon gedetecteerd",
  "authenticationFailed": "Verificatie mislukt",
  "pleaseRestartTIM": "Start TiM opnieuw op",
  "cancel": "annuleren",
  "details": "Details",
  "addServerUrl": "Server url toevoegen",
  "search": "Zoeken",
  "listOfProducts": "Lijst met producten",
  "hello": "Hallo {1}!",
  "testForgetMe": "Dit is een testmechanisme om alle communicatie met deze provider te resetten",
  "confirmForgetMe": "Weet je zeker dat je wilt dat '{1}' jou vergeet?",
  "forgetMe": "Vergeet me",
  "iNeed": "Ik heb nodig...",
  "newProduct": "Nieuw product",
  "shareOne": "Of deel hieronder",
  "shareOneOfMany": "Of deel hieronder",
  "tapToRemovePhotos": "Tik om foto's te verwijderen",
  "addNew": "Voeg nieuwe {1} toe",
  "switchToRepresentative": "Overschakelen naar representatieve modus is nog niet geïmplementeerd.",
  "fillTheForm": "Vul dit formulier in ** {1} **",
  "verifiedBy": "Geverifieerd door {1}",
  "issuedBy": "Uitgegeven door {1}",
  "sentTo": "Verzonden naar {1}",
  "typeMessage": "Type een bericht",
  "newProductMsg": "Ik heb een {1} nodig.",
  "verificationTransactionID": "Verificatie transactie-ID",
  "setDateValue": "set",
  "scanQRcode": "Scan QR-code",
  "myDocuments": "Mijn Documenten",
  "confirmRevoke": "Vraag {1} om dit document uit hun administratie te verwijderen?",
  "shareProduct": "U kunt hieronder tikken om {1} te delen met {2}",
  "shareMyProduct": "U kunt hieronder tikken om {1} te delen met {2}",
  "switchTouchIdOff": "Schakel aanraak-ID uit",
  "switchTouchIdOn": "Schakel aanraak-ID in",
  "noConnection": "{appName} vereist een werkende internetverbinding die u op dit moment niet heeft",
  "noConnectionWillProcessLater": "{appName} vereist een werkende internetverbinding die u op dit moment niet heeft. De aanvraag wordt verwerkt wanneer een verbinding tot stand is gebracht",
  "noConnectionForPL": "{appName} vereist een werkende internetverbinding om een lijst met producten van {1} aan te vragen die u op dit moment niet heeft",
  "noConnectionForNewProduct": "{1}, {appName} vereist een werkende internetverbinding om de {2} -toepassing in te vullen.",
  "inProgress": "Bezig...",
  "newContactRequest": "{1} heeft je contactverzoek verzonden",
  "pleaseCorrectTheErrors": "Corrigeer de fout in het formulier",
  "verifierHelp": "Klik op 'Gereed' nadat u het formulier heeft bekeken. Als sommige velden correcties vereisen, controleer ze dan eerst en klik vervolgens op de knop 'Gereed'",
  "addAnotherFormOrGetNext": "Voeg nog een {1} toe of ga verder met het volgende formulier",
  "areYouSureAboutNextForm": "Bent u klaar met het toevoegen van {1}?",
  "sharedForm": "Gedeeld {1}",
  "iproovErrorTitle": "Oops! Er is iets fout gegaan",
  "receivedForm": "{1} ontvangen",
  "add": "Voeg {1} toe",
  "pleaseCorrectFields": "Corrigeer de volgende velden: {1}",
  "fieldErrorMessagePrompt": "Wat is er mis met dit veld?",
  "useGesturePassword": "Schakel wachtwoord voor gebaren in",
  "help": "Helpen",
  "iproovErrorMessage": "Wacht een ogenblik en probeer het opnieuw",
  "drawYourOldPassword": "Teken je oude patroon",
  "asVerifiedBy": "Zoals geverifieerd door {1}",
  "correctPassword": "Aww, je herinnerde het je!",
  "useTouchIdAndGesturePassword": "Schakel Touch ID en gebaar in",
  "approveApplication": "Applicatie goedkeuren",
  "receivedProduct": "{1} ontvangen",
  "temporarilyLocked": "Ter bescherming is deze app tijdelijk vergrendeld voor {1}",
  "createNew": "Vul het formulier \"{1}\" in",
  "importDataPrompt": "U staat op het punt uw gegevens te importeren",
  "invalidPairingRequest": "Ongeldig koppelingsverzoek",
  "useTouchId": "Schakel Touch ID in",
  "continue": "Doorgaan met",
  "shareOneOfMany1": "{1}, dit is uw persoonlijke privacy-assistent. Ik zie dat je je {2} al hebt geverifieerd. Je kunt op alle items in de onderstaande lijst tikken om ze te delen met {3}.",
  "youAreForgotten": "Je bent succesvol vergeten",
  "importYourData": "Importeer uw gegevens",
  "providerIsOffline": "{1} is offline",
  "showQR": "Mijn QR-code",
  "pairingRequestWasProcesseed": "Koppelingsverzoek werd ingediend",
  "learnMore": "Kom meer te weten",
  "fillRequiredFields": "Vul alle verplichte velden in",
  "youAreTheRM": "U bent de relatiemanager voor deze toepassing",
  "documentNotScanning": "Oeps! Er is iets misgegaan!",
  "ok": "OK",
  "invalidPropertyValue": "ongeldige waarde",
  "approveApplicationFor": "Aanvraag goedkeuren voor {1}",
  "shareContext": "Deel {1}",
  "receivedVerification": "Verificatie voor {1} ontvangen",
  "enterCurrentPassword": "voer uw huidige wachtwoord in",
  "drawYourNewPasswordAgain": "Teken het nieuwe patroon opnieuw",
  "tooManyPasswordAttempts": "Teveel mislukte pogingen! Dit formulier is uitgeschakeld.",
  "documentExpiredTitle": "Document verlopen",
  "drawYourPasswordAgain": "Teken je patroon opnieuw",
  "next": "volgende",
  "shareWith": "Deel {1}",
  "fillTheFormWithAttachments": "Vul dit formulier in ** {1} **",
  "pleaseTapOnMenu": "Tik op de rode knop en",
  "contactUs": "Neem contact met ons op",
  "changeGesturePassword": "Verander het wachtwoord van het gebaar",
  "createNext": "Vul een ander formulier in \"{1}\"",
  "turnPasswordOn": "Schakel het wachtwoord voor gebaren in",
  "pleaseCorrect": "Corrigeer alstublieft",
  "submitLog": "Log verzenden",
  "takeAPicture": "Maak een ** selfie ** foto van je gezicht",
  "learnMoreServerIsDown": "Alle berichten die u schrijft, worden automatisch naar {1} verzonden wanneer ze online komen.",
  "enterPassword": "Voer uw wachtwoord in",
  "sentToOn": "Verzonden naar {1} ingeschakeld",
  "pairDevices": "Apparaten koppelen",
  "submittingModifiedForm": "{1} wijzigen",
  "sharedWith": "Gedeelde {1} context met {2}",
  "updateAppTitle": "App-update beschikbaar",
  "verifyPrompt": "Verifiëren?",
  "somethingWrong": "Er is iets fout gegaan",
  "validationErrors": "Corrigeer mislukte validatievelden",
  "formListError": "Niet beschikbaar",
  "importing": "Importeren",
  "shareChangesWith": "Deel veranderingen met",
  "unknownQRCodeFormat": "Niet-herkende QR-code-indeling",
  "generatingKeys": "het genereren van uw privésleutels",
  "customerWaiting": "{1} is de chat binnengekomen",
  "deviceDoesNotHaveMyKeys": "De ontvangen identiteit heeft mijn sleutels niet",
  "passwordsDontMatch": "Wachtwoorden komen niet overeen",
  "neverMissAMessage": "Mis nooit meer een bericht",
  "changePassword": "Wachtwoord wijzigen",
  "nl": "Nederlands",
  "applyForProduct": "Vraag een product aan",
  "backTo": "Terug naar {1}",
  "touchIdOn": "Touch ID is AAN",
  "somethingWrongSubmitLog": "Er lijkt iets mis te zijn gegaan. Dien het foutopsporingslog in bij het ontwikkelaarssteam van {appName}",
  "noNetwork": "Geen netwerk",
  "downloadingUpdate": "Een update downloaden ...",
  "setNewPassword": "kies een nieuw wachtwoord",
  "cameraAccess": "Cameratoegang",
  "resetRequired": "Reset vereist",
  "nothingToShare": "Niets om te delen",
  "updateAppMessage": "Update nu, of zal ik u later herinneren?",
  "iproovFailedMessage": "Probeer het opnieuw. Voor het beste resultaat houdt u uw gezicht gecentreerd in het ovaal tijdens de kleurenflitsen.",
  "areYouSureYouWantToDelete": "Weet u zeker dat u {1} wilt verbergen?",
  "sandboxDescription": "In de Sandbox leert u hoe u de app gebruikt met gesimuleerde serviceproviders.",
  "yes": "Ja",
  "restartApp": "Start App opnieuw",
  "iproovFailedTitle": "Oops! Er is iets fout gegaan",
  "storageCorrupted": "de sleutelhangergegevens en -opslag van uw app zijn beschadigd! Als u denkt dat dit een vergissing is, drukt u op App herstarten om het opnieuw te proberen. Door op de Reset-app te drukken, worden de identiteit en opslag van de app gereset.",
  "holdPhoneToPassportBackCover": "Houd de achterkant van uw telefoon tegen de achterkant binnenzijde van uw paspoort.",
  "sourcesBy": "Bronnen op {1}",
  "en": "Engels",
  "acceptingTermsAndConditions": "Door op OK te drukken, gaat u akkoord met de Algemene voorwaarden",
  "pairingRequest": "Verzoek om paren",
  "enablePassword": "Wachtwoord inschakelen",
  "loadingModels": "modellen laden",
  "verificationBy": "Verificatie per {1}",
  "ukLicenseUnsupported": "Scannen van licenties in het VK wordt momenteel niet ondersteund",
  "areYouSureAboutWipe": "Deze actie is onomkeerbaar. U verliest al uw gegevens en privésleutels. Weet je zeker dat je verder wilt gaan?",
  "submittingForm": "Submittted {1}",
  "digitalWealthPassport": "Digital Wealth Passport",
  "backToResults": "Terug naar resultaten",
  "viewDebugLog": "Bekijk debug-logboek",
  "textPasswordLimitations": "Moet 10+ tekens bevatten, minstens één hoofdletter, kleine letter, cijfer en speciaal teken",
  "areYouSureYouWantToServeThisCustomer": "Weet je zeker dat je deze klant wilt bedienen?",
  "termsAndConditions": "Voorwaarden.",
  "creationDate": "Datum gecreeërd",
  "updateNow": "Update nu",
  "error": "Fout",
  "testProviders": "sandbox",
  "turnTouchIdOn": "Zet aanraak-ID aan",
  "youShared": "U hebt gedeeld vanaf {1}",
  "initializingEngine": "motor initialiseren",
  "turnBothOn": "Schakel beide in",
  "no": "Nee",
  "setPassword": "Kies een veilig wachtwoord",
  "unlockDevice": "ontgrendel je apparaat om verder te gaan",
  "noAccessToServer": "Server is niet toegankelijk. Probeer later.",
  "issuedByOn": "Uitgegeven door {1} aan",
  "sponsoredBy": "Gesponsord door",
  "documentExpiredMessage": "Scan een geldig document",
  "later": "Later",
  "nameUnknown": "naam onbekend",
  "learnMoreDescription": "Je kunt nog steeds berichten schrijven in de offline modus, ook al is je apparaat niet verbonden. Wanneer u opnieuw verbinding maakt, worden al uw berichten automatisch verzonden.",
  "thisValueIsInvalidPlaceholder": "deze waarde is ongeldig omdat ...",
  "overviewOfApplications": "Overzicht van applicaties",
  "enterYourName": "Vul uw naam in",
  "youReviewed": "U hebt {1} uit {2} items beoordeeld",
  "areYouSureYouWantToConfirmAllItems": "Tik op OK om alle {1} te bevestigen, of op Annuleren om door te gaan met beoordelen",
  "offlineMode": "Offline modus",
  "enablePasscodeFirst": "Het lijkt erop dat u geen apparaatwachtwoord hebt ingeschakeld. Zonder dit kan deze app uw gegevens niet beschermen! Schakel dit in voordat u op OK drukt",
  "hideResource": "{1} verbergen",
  "viewTerms": "Raadpleeg de Algemene voorwaarden",
  "serverIsUnreachable": "Server is onbereikbaar",
  "reviewScannedProperties": "Controleer en corrigeer de onderstaande gegevens",
  "bothOn": "Beide zijn AAN",
  "formRequest": "Verzoek om {1}",
  "denyApplicationFor": "Weigeren aanvraag voor {1}",
  "willBeAvailable": "Deze functionaliteit is binnenkort beschikbaar",
  "nothingChanged": "Er is niets veranderd",
  "unreadMessages": "U hebt ongelezen berichten",
  "acceptTermsAndConditions": "Bekijk de algemene voorwaarden",
  "drawYourNewPassword": "Teken een nieuw patroon",
  "centerLicence": "Center-licentie in frame",
  "asSentTo": "Zoals verzonden naar {1}",
  "multientryToShare": "Er zijn {1} documenten om te delen",
  "sharedContext": "Gedeelde context",
  "receiveNotifications?": "Wilt u meldingen ontvangen?",
  "confirmedMyData": "Alle geïmporteerde gegevens kunnen worden bekeken in uw {profileTitle}",
  "restartingApp": "De toepassing wordt kortstondig opnieuw opgestart",
  "learnMoreDescriptionTo": "Je kunt nog steeds berichten schrijven in de offline modus, ook al is je apparaat niet verbonden. Wanneer u opnieuw verbinding maakt, worden al uw berichten automatisch verzonden naar {1}.",
  "independentBlockchainViewer": "Onafhankelijke blockchain-viewer",
  "trustedProviders": "Vertrouwde providers",
  "importingData": "{1} documenten importeren uit {2}",
  "incompatibleVersion": "Vanwege recente onveranderlijke wijzigingen die niet compatibel zijn, vereist deze update een harde reset van de app. Druk op OK om de identiteit en opslag van de app opnieuw in te stellen.",
  "verifiedByOn": "Geverifieerd door {1} op",
  "searchSomething": "Zoeken {1}",
  "passwordOn": "Gebaar wachtwoord is AAN",
  "youShallNotPass": "Je zult niet voorbijgaan!",
  "shareOne1": "{1}, dit is uw persoonlijke privacy-assistent. Ik zie dat je je {2} al hebt geverifieerd. Je kunt hieronder tikken om het te delen met {3}.",
  "noScanningOnAndroid": "Het scannen van documenten op Android komt binnenkort.",
  "shareAllPastAndFutureMessages": "Deel alle eerdere en toekomstige berichten in deze context met geselecteerde partijen",
  "errorNotification": "Foutmeldingen zijn naar de klant gestuurd om te corrigeren",
  "formListErrorDescription": "Formulieren kunnen worden aangevraagd zodra de klant een aanvraag begint",
  "scanningFailedTryAgain": "Scannen was niet succesvol. Kun je alsjeblieft opnieuw proberen?",
  "irrefutableProofs": "Onweerlegbare bewijzen",
  "invalidDocument": "ongeldig document",
  "enableCameraAccess": "{appName} heeft momenteel geen toestemming om de camera te gebruiken. Als u toegang wilt verlenen, kiest u Instellingen en zorgt u ervoor dat Camera is ingeschakeld.",
  "pleaseClickOnAddButton": "Klik hieronder op '+' om '{1}' toe te voegen",
  "cancelItem": "U staat op het punt {1} te annuleren. Tik op OK om te bevestigen",
  "invalidDeepLink": "Het lijkt erop dat je op een ongeldige link hebt geklikt!",
  "submitting": "Het indienen",
  "holdPhoneToPassport": "Houd de achterkant van uw telefoon tegen de voorkant van uw paspoort",
  "dataSecurity": "Dataveiligheid",
  "installingUpdate": "Update installeren",
  "cancelHideResource": "Annuleren Verbergen {1}",
  "loadingResources": "middelen laden",
  "youAreAboutToShare": "Je staat op het punt om te delen\n '{1}'\n documenten",
  "contextsFor": "Contexten voor",
  "importData": "Gegevens importeren",
  "fromMyData": "van 'Mijn gegevens'",
  "retryScanning": "Was dat een {1}? Ik wist het niet. Probeer het nog een keer?\n\nVoor de beste resultaten gebruikt u de liggende modus, vermijdt u verblinding en zorgt u ervoor dat het document zich binnen het weergegeven kader bevindt.",
  "denyApplication": "Weigeren toepassing",
  "centerPassport": "Centreer pasfotopagina in frame",
  "homePage": "Huis",
  "youReviewedAll": "U heeft alle {1} beoordeeld",
  "confirmAllItems": "Tik op OK om ze allemaal te bevestigen, of op Annuleren om door te gaan met beoordelen",
  "sendEditRequestPrompt": "Bewerkingsverzoek verzenden naar {1}?",
  "oops": "Oops",
  "centerID": "Centre ID in frame",
  "messageWaitingFrom": "Je hebt een nieuw bericht van {1}",
  "bookmarks": "bladwijzers",
  "exploreData": "Data verkennen",
  "Please scan your": "Scan alstublieft uw",
  "ID document": "ID-document",
  "Please fill out the form": "Vul alstublieft het formulier in",
  "See our list of products": "Bekijk onze lijst met producten",
  "Our products have changed": "Onze producten zijn veranderd",
  "Please take a selfie to prove this is your document. Center your face.": "Maak een selfie om te bewijzen dat dit uw document is. Centreer je gezicht.",
  "Choose Apply for Product from the menu": "Kies Product toepassen in het menu",
  "Application submitted!": "Aanvraag ingediend!",
  "Sending": "Bezig met verzenden",
  "Please tap here and sign": "Tik hier en teken",
  "Give me a moment...": "Geef me een ogenblik...",
  "Please click to scan your": "Klik om uw te scannen",
  "' photo of yourself that I can match against your ID document": "'foto van jezelf die ik kan evenaren tegen je ID-document",
  "Thank you. Now take a '": "Dank je. Neem nu een '",
  "pleaseSign": "Teken in het grijze vak",
  "getStarted": "Begin",
  "goodNewsFew": "Goed nieuws! Je hebt er al heel wat. Om het tikpictogram hieronder te delen.",
  "goodNews": "Goed nieuws! U heeft al {1}. Tik om te delen op het onderstaande pictogram",
  "Clear": "Duidelijk",
  "Submit": "voorleggen",
  "Cancel": "annuleren",
  "retake": "Re-take",
  "usePhoto": "Gebruik foto",
  "Deny": "Ontkennen",
  "Approve": "Goedkeuren",
  "loading": "Bezig met laden...",
  "Applications": "toepassingen",
  "Seals": "zeehonden",
  "Verifications": "keuringen",
  "checkIfMatch": "Controleer of wedstrijd",
  "Corporation Exists Checks": "Corporation bestaat uit cheques",
  "createManualMatchCheck": "Maak een handmatige matchcontrole",
  "Get set for friendliness?": "Maak je klaar voor vriendelijkheid?",
  "Go friendliness!": "Ga vriendelijkheid!",
  "Ready for friendliness?": "Klaar voor vriendelijkheid?",
  "Finally, you will be in control of your own private information!": "Eindelijk hebt u de controle over uw eigen privégegevens!",
  "Take a quick tour of chat bot?": "Volg een korte rondleiding door chat bot?",
  "Go!": "Gaan!",
  "Ready?": "Klaar?",
  "Get set": "Maak je klaar",
  "Before we start you'll need a valid passport, identity card or driving license": "Voordat we beginnen, heb je een geldig paspoort, een identiteitskaart of een rijbewijs nodig",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "We stellen je vragen in de chat en je vult eenvoudig de formulieren in of volgt de verzoeken",
  "Next": "volgende",
  "Skip": "Overspringen",
  "Done": "Gedaan",
  "Sanctions Checks": "Sanctiescheques",
  "inProcess": "Verwerken...",
  "invalidQuery": "Oeps, we hebben een fout opgetreden bij het uitvoeren van uw zoekopdracht. Onze ontwikkelaars zullen proberen het zo snel mogelijk te herstellen.",
  "networkFailure": "Ik ondervind een aantal netwerkproblemen. Kunt u controleren en vervolgens op Opnieuw / Annuleren tikken",
  "validatingDataClaim": "Gegevens importeren",
  "debugLogSent": "Foutopsporingslogboek verzonden",
  "supportedQrCodes": "Ondersteunde QR-codes:\n1) chatkanaal toevoegen\n2) gegevens importeren",
  "invalidQR": "Ongeldige QR-code",
  "noResourcesForCriteria": "Voor dit criterium zijn geen middelen gevonden",
  "logSentToDevTeam": "Het logboek is verzonden naar het ontwikkelaarsteam van Tradle",
  "failedToSendLog": "Verzenden mislukt",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Bekijk de onderstaande gegevens en maak een momentopname van de {1} kant van het document",
  "documentBackSide": "Middelste document achterkant",
  "Photo": "Foto",
  "startedByAnotherEmployee": "De aanvraag voor {1} is gestart door een andere medewerker",
  "doYouWantToContinue": "Wil je er naar overschakelen en vandaar verder gaan?",
  "afterRefresh": "U bent vrij om onze diensten zonder onderbreking te gebruiken",
  "reviewData": "Gegevens bekijken",
  "requestMyData": "Mijn gegevens opvragen",
  "newCustomer": "Nieuwe klant",
  "areYouSureYouAreDone": "Weet je zeker dat je deze sessie wilt beëindigen?",
  "scanYourDocument": "Scan alstublieft uw document",
  "wrongDocumentTypePleaseTryAgain": "Verkeerd documenttype. Probeer het opnieuw",
  "invalidCountry": "Ongeldig land gescand",
  "resetApp": "Reset app",
  "wipeTheAppData": "Wis de app-gegevens",
  "enterPasswordOrWipeOutTheAppData": "Voer een wachtwoord in of wis de app-gegevens",
  "dateInTheFutureError": "{1} is in de toekomst",
  "pleaseChooseDT": "Kies eerst het documenttype",
  "formChooser": "Vraag een formulier aan"
}