module.exports = {
  "restartingApp": "Ang application ay i-restart sa ilang sandali",
  "oops": "Oops",
  "creationDate": "Nilikha ang petsa",
  "addNew": "Magdagdag ng bagong {1}",
  "optional": "opsyonal",
  "downloadingUpdate": "Nagda-download ng update ...",
  "useTouchIdAndGesturePassword": "Paganahin ang Touch ID at Kilos",
  "overviewOfApplications": "Pangkalahatang-ideya ng Mga Application",
  "acceptingTermsAndConditions": "Sa pamamagitan ng pagpindot sa OK, tinatanggap mo ang Mga Tuntunin at Kundisyon",
  "passwordLimitations": "Dapat may 5+ puntos ang pattern",
  "importData": "Mag-import ng data",
  "verifiedBy": "Na-verify sa pamamagitan ng {1}",
  "somethingWrong": "May nagkamali",
  "trustedProviders": "Mga pinagkakatiwalaang provider",
  "backToResults": "Bumalik sa mga resulta",
  "viewDebugLog": "Tingnan ang debug log",
  "formRequest": "Humiling ng {1}",
  "initializingEngine": "pagsisimula ng engine",
  "shareOneOfMany1": "{1}, ito ang iyong personal na assistant sa privacy. Nakikita ko na mayroon ka na ang iyong {2} na-verify. Maaari mong i-tap ang anumang mga item sa listahan sa ibaba upang ibahagi ang mga ito sa {3}.",
  "deviceDoesNotHaveMyKeys": "Ang natanggap na pagkakakilanlan ay walang mga susi",
  "profile": "Profile",
  "digitalWealthPassport": "Digital Wealth Passport",
  "holdPhoneToPassportBackCover": "I-hold ang likod ng iyong telepono laban sa likod sa loob ng takip ng iyong pasaporte.",
  "details": "Mga Detalye",
  "tapToRemovePhotos": "Tapikin upang alisin ang mga larawan",
  "changeGesturePassword": "Baguhin ang password ng kilos",
  "showQR": "Aking QR code",
  "iproovFailedTitle": "Oops! May nagkamali",
  "importing": "Pag-import",
  "asVerifiedBy": "Tulad ng napatunayan ng {1}",
  "switchTouchIdOff": "Lumipat ang touch ID off",
  "help": "Tulong",
  "homePage": "Bahay",
  "typeMessage": "Mag-type ng mensahe",
  "confirmAllItems": "Tapikin ang OK upang kumpirmahin ang lahat ng ito, o Kanselahin upang magpatuloy sa pagsusuri",
  "correctGesture": "Napansin ang tamang pattern",
  "setDateValue": "Itakda",
  "later": "Mamaya",
  "shareMyProduct": "Maaari mong i-tap sa ibaba upang ibahagi ang {1} sa {2}",
  "generatingKeys": "pagbuo ng iyong mga pribadong key",
  "updateAppTitle": "Available ang Update ng App",
  "shareOne1": "{1}, ito ang iyong personal na assistant sa privacy. Nakikita ko na mayroon ka na ang iyong {2} na-verify. Maaari mong i-tap sa ibaba upang ibahagi ito sa {3}.",
  "installingUpdate": "Pag-install ng update",
  "switchToRepresentative": "Hindi pa naipatupad ang paglipat sa mode ng kinatawan.",
  "loadingModels": "Naglo-load ng mga modelo",
  "error": "Error",
  "passwordOn": "Ang Gesture Password ay SA",
  "asSentTo": "Tulad ng ipinadala sa {1}",
  "addServerUrl": "Magdagdag ng url ng server",
  "noNetwork": "Walang network",
  "newProductMsg": "Kailangan ko ng isang {1}.",
  "updateNow": "I-update Ngayon",
  "holdPhoneToPassport": "Hawakan ang likod ng iyong telepono laban sa harap na takip ng iyong pasaporte",
  "ukLicenseUnsupported": "Hindi sinusuportahan ang pag-scan sa pagmamaneho sa pagmamaneho sa UK sa oras na ito",
  "pairDevices": "Pares ng mga aparato",
  "enableCameraAccess": "Kasalukuyang hindi available ang {appName} na gamitin ang camera. Upang magbigay ng access, piliin ang Mga Setting, at tiyaking pinagana ang Camera.",
  "acceptTermsAndConditions": "Tingnan ang mga tuntunin at kundisyon",
  "verificationBy": "Ang pagpapatunay sa pamamagitan ng {1}",
  "verificationTransactionID": "Id ng Transaksyon ng Pag-verify",
  "confirmedMyData": "Maaaring matingnan ang lahat ng na-import na data sa iyong {profileTitle}",
  "receivedProduct": "Natanggap na {1}",
  "cancel": "Kanselahin",
  "youAreAboutToShare": "Malapit ka na\n '{1}'\n mga dokumento",
  "enablePasscodeFirst": "Mukhang hindi ka pinagana ang passcode ng aparato. Kung wala ito, hindi mapoprotektahan ng app na ito ang iyong data! Mangyaring paganahin ito bago ang pagpindot sa OK",
  "theMinValueBiggerThenMaxValue": "Ang min na halaga para sa hanay ay dapat na mas maliit pagkatapos ang max na halaga",
  "updateAppMessage": "I-update ngayon, o ipapaalala ko sa iyo sa ibang pagkakataon?",
  "searchSomething": "Paghahanap {1}",
  "en": "Ingles",
  "youReviewed": "Sinuri mo ang {1} sa {2} mga item",
  "drawYourNewPassword": "Gumuhit ng isang bagong pattern",
  "hideResource": "Itago ang {1}",
  "sharedForm": "Ibinahagi {1}",
  "shareWith": "Ibahagi ang {1}",
  "bothOn": "Ang parehong ay ON",
  "submittingModifiedForm": "Pagbabago ng {1}",
  "sharedWith": "Ibinahagi ang konteksto ng {1} sa {2}",
  "myDocuments": "Aking Mga Dokumento",
  "scanningFailedTryAgain": "Ang pag-scan ay hindi matagumpay. Pwede bang subukan muli?",
  "nothingChanged": "walang nagbago",
  "importYourData": "I-import ang Iyong Data",
  "cameraAccess": "Access sa Camera",
  "invalidDeepLink": "Mukhang nag-click ka ng isang hindi wastong link!",
  "ok": "OK",
  "invalidPattern": "Maling pattern",
  "iproovFailedMessage": "Ulitin mo ulit. Para sa pinakamahusay na mga resulta, panatilihin ang iyong mukha nakasentro sa bilog sa panahon ng kulay flashes.",
  "iNeed": "Kailangan ko...",
  "fromMyData": "mula sa 'Aking Data'",
  "invalidPropertyValue": "Di-wastong halaga",
  "search": "Paghahanap",
  "drawYourPasswordAgain": "Guhit muli ang iyong pattern",
  "scanQRcode": "I-scan ang QR code",
  "cancelItem": "Iyong kanselahin ang {1}. Mangyaring tapikin ang OK upang kumpirmahin",
  "documentNotScanning": "Oops! May nangyaring mali!",
  "sendEditRequestPrompt": "Ipadala ang kahilingan sa pag-edit sa {1}?",
  "unlockDevice": "i-unlock ang iyong device upang magpatuloy",
  "sentTo": "Ipinadala sa {1}",
  "enterCurrentPassword": "Ipasok ang iyong kasalukuyang password",
  "thisFieldIsRequired": "Ang larangan na ito ay kinakailangan",
  "turnTouchIdOn": "I-ugnay ang ID sa",
  "wrongPattern": "Maling pattern",
  "back": "Bumalik",
  "hello": "Hello {1}!",
  "correctPassword": "Aww, naaalaala mo!",
  "centerLicence": "Lisensya sa center sa frame",
  "authenticationFailed": "Nabigo ang pagpapatotoo",
  "reviewScannedProperties": "Mangyaring suriin at itama ang data sa ibaba",
  "incompatibleVersion": "Dahil sa kamakailang mga pabalik na hindi tugma mga pagbabago, ang update na ito ay nangangailangan ng isang hard reset ng app. Pindutin ang OK upang i-reset ang pagkakakilanlan at imbakan ng app.",
  "irrefutableProofs": "Hindi masasagisag na mga patunay",
  "shareChangesWith": "Ibahagi ang mga pagbabago sa",
  "iproovErrorTitle": "Oops! May nagkamali",
  "continue": "Magpatuloy",
  "importingData": "Ang pag-import ng {1} mga dokumento mula sa {2}",
  "areYouSureYouWantToServeThisCustomer": "Sigurado ka bang gusto mong maghatid ng kostumer na ito?",
  "approveApplicationFor": "Aprubahan ang aplikasyon para sa {1}",
  "youAreTheRM": "Ikaw ang Relationship Manager para sa application na ito",
  "createNew": "Punan ang form na \"{1}\"",
  "setNewPassword": "Pumili ng bagong password",
  "nothingToShare": "Wala nang ibabahagi",
  "pleaseCorrect": "Paki tama",
  "verifierHelp": "I-click ang 'Tapos na' na pindutan pagkatapos suriin ang form. Kung ang ilang mga patlang ay nangangailangan ng pagwawasto suriin muna ang mga ito sa kanila at pagkatapos ay i-click ang pindutang 'Tapos na'",
  "noAccessToServer": "Hindi naa-access ang server. Subukan mamaya.",
  "nl": "Olandes",
  "validationErrors": "Mangyaring iwasto ang mga patlang ng pagpapatunay na nabigo",
  "pleaseRestartTIM": "Paki-restart ang TiM",
  "noConnection": "Ang {appName} ay nangangailangan ng isang gumaganang koneksyon sa internet na wala ka sa ngayon",
  "addAnotherFormOrGetNext": "Magdagdag ng isa pang {1} o lumipat sa susunod na form",
  "formListErrorDescription": "Ang mga form ay maaaring hilingin kapag ang isang customer ay nagsisimula ng isang application",
  "denyApplicationFor": "Tanggihan ang application para sa {1}",
  "turnPasswordOn": "I-on ang Gesture Password",
  "fillTheFormWithAttachments": "Mangyaring punan ang form na ito ** {1} **",
  "changePassword": "Palitan ANG password",
  "areYouSureAboutWipe": "Ang pagkilos na ito ay hindi maibabalik. Mawawala mo ang lahat ng iyong data at mga pribadong key. Sigurado ka bang gusto mong magpatuloy?",
  "learnMore": "Matuto nang higit pa",
  "noScanningOnAndroid": "Ang pag-scan ng dokumento sa Android ay paparating na.",
  "enterYourName": "Ipasok ang iyong pangalan",
  "centerID": "Center ID sa frame",
  "dataSecurity": "Seguridad ng data",
  "next": "Susunod",
  "tooManyPasswordAttempts": "Masyadong maraming mga nabigong mga pagtatangka! Ang form na ito ay hindi pinagana.",
  "setPassword": "Pumili ng isang secure na password",
  "gestureNotRecognized": "Maling pattern",
  "learnMoreServerIsDown": "Ang anumang mga mensaheng iyong isusulat ay awtomatikong ipapadala sa {1} kapag dumating sila online.",
  "fillRequiredFields": "Mangyaring punan ang lahat ng kinakailangang field",
  "no": "Hindi",
  "passwordsDontMatch": "Hindi tumutugma ang mga password",
  "pleaseTapOnMenu": "Paki-tap ang pulang buton at",
  "patternNotMatching": "Ang mga pattern ay hindi tumutugma.",
  "createNext": "Punan ang ibang form na \"{1}\"",
  "issuedByOn": "Ibinigay ng {1} sa",
  "approveApplication": "Aprubahan ang application",
  "pleaseDrawPassword": "Gumuhit ng iyong pattern",
  "pleaseCorrectFields": "Pakitama ang mga sumusunod na field: {1}",
  "retryScanning": "Iyan ba ang isang {1}? Hindi ko masabi. Ulitin mo ulit?\n\nPara sa pinakamahusay na mga resulta, gamitin ang landscape mode, maiwasan ang liwanag na nakasisilaw, at siguraduhin na iposisyon ang dokumento sa loob ng frame na ipinapakita.",
  "drawYourPassword": "Gumuhit ng iyong pattern",
  "done": "Tapos na",
  "contactUs": "Makipag-ugnayan sa amin",
  "useGesturePassword": "Paganahin ang Gesture Password",
  "somethingWrongSubmitLog": "May isang bagay na tila naging mali. Mangyaring isumite ang debug log sa koponan ng developer ng {appName}",
  "turnBothOn": "Lumiko sa parehong",
  "confirmForgetMe": "Sigurado ka na gusto mo '{1}' upang makalimutan ka",
  "officialAccounts": "Mga pag-uusap",
  "invalidProperty": "Di-wastong {1}",
  "youShared": "Ibinahagi mo mula sa {1}",
  "drawYourOldPassword": "Gumuhit ng iyong lumang pattern",
  "sentToOn": "Ipinadala sa {1} sa",
  "textPasswordLimitations": "Dapat magkaroon ng 10+ na character, hindi bababa sa isang uppercase na titik, lowercase na sulat, numero, at espesyal na character",
  "shareProduct": "Maaari mong i-tap sa ibaba upang ibahagi ang {1} sa {2}",
  "newProduct": "Bagong produkto",
  "receivedForm": "Natanggap na {1}",
  "storageCorrupted": "Na-corrupt ang data at imbakan ng keychain ng iyong app! Kung sa tingin mo ito ay isang pagkakamali, pindutin ang I-restart ang App upang subukang muli. Ang pag-reset ng I-reset ang App ay i-reset ang pagkakakilanlan at imbakan ng app.",
  "drawYourNewPasswordAgain": "Gawin muli ang bagong pattern",
  "shareOneOfMany": "Bilang kahalili, ibahagi sa ibaba",
  "shareContext": "Ibahagi ang {1}",
  "add": "Magdagdag ng {1}",
  "pairingRequest": "Kahulugan ng Pagpapares",
  "invalidPairingRequest": "Di-wastong Kahilingan sa Pagpapares",
  "issuedBy": "Ibinigay ng {1}",
  "youShallNotPass": "Hindi ka dapat pumasa!",
  "newContactRequest": "{1} nagpadala sa iyo ng kahilingan sa pakikipag-ugnay",
  "offlineMode": "Di konektado",
  "settings": "Mga Setting",
  "yes": "Oo",
  "sharedContext": "Ibinahagi ang Konteksto",
  "enterPassword": "Ipasok ang iyong password",
  "submitLog": "Magsumite ng Log",
  "thisValueIsInvalidPlaceholder": "di-wasto ang halaga na ito dahil ...",
  "inProgress": "Isinasagawa ...",
  "messageWaitingFrom": "Mayroon kang isang bagong mensahe mula sa {1}",
  "viewTerms": "Mangyaring tingnan ang Mga Tuntunin at Kundisyon",
  "errorNotification": "Ang abiso ng error ay ipinadala sa customer upang itama",
  "useTouchId": "Paganahin ang Touch ID",
  "providerIsOffline": "{1} ay offline",
  "receiveNotifications?": "Gusto mo bang makatanggap ng mga notification?",
  "independentBlockchainViewer": "Independent viewer blockchain",
  "enablePassword": "Paganahin ang Password",
  "pleaseClickOnAddButton": "Mangyaring mag-click sa '+' sa ibaba upang magdagdag ng '{1}'",
  "pairingRequestWasProcesseed": "Ang kahilingan sa pagpapares ay proseso",
  "denyApplication": "Tanggihan ang application",
  "neverMissAMessage": "Huwag kailanman mapalampas ang isang mensahe",
  "documentExpiredTitle": "Nag-expire na ang dokumento",
  "nameUnknown": "hindi kilala ang pangalan",
  "iproovErrorMessage": "Mangyaring maghintay ng kaunti at subukan muli",
  "unreadMessages": "Mayroon kang mga hindi pa nababasang mensahe",
  "testProviders": "Sandbox",
  "resetRequired": "I-reset ang Kinakailangan",
  "multientryToShare": "May mga {1} mga dokumento na ibabahagi",
  "centerPassport": "Pahina ng larawan ng pasaporte ng sentro sa frame",
  "documentExpiredMessage": "Mangyaring i-scan ang isang wastong dokumento",
  "cancelHideResource": "Kanselahin Itago {1}",
  "importDataPrompt": "Malapit ka na mag-import ng iyong data",
  "areYouSureYouWantToConfirmAllItems": "I-tap ang OK upang kumpirmahin ang lahat ng {1}, o Kanselahin upang magpatuloy sa pagsusuri",
  "areYouSureYouWantToDelete": "Sigurado ka ba na nais mong itago ang {1}?",
  "learnMoreDescription": "Maaari ka pa ring magsulat ng mga mensahe sa Mode ng Offline kahit na ang iyong aparato ay hindi nakakonekta. Kapag ikinakabit mo ang lahat ng iyong mensahe ay awtomatikong ipapadala.",
  "areYouSureAboutNextForm": "Natapos mo na bang idagdag ang {1}?",
  "youAreForgotten": "Matagumpay kang nakalimutan",
  "youReviewedAll": "Sinuri mo ang lahat ng {1}",
  "switchTouchIdOn": "Lumipat ugnay ID sa",
  "loadingResources": "load ng mga mapagkukunan",
  "touchIdOn": "Ang Touch ID ay ON",
  "sourcesBy": "Mga Pinagmumulan ng {1}",
  "unknownQRCodeFormat": "Hindi nakikilalang format ng QR code",
  "confirmRevoke": "Tanungin ang {1} tanggalin ang dokumentong ito mula sa kanilang mga rekord?",
  "verifiedByOn": "Na-verify sa pamamagitan ng {1} sa",
  "noConnectionForNewProduct": "{1}, {appName} ay nangangailangan ng isang gumaganang koneksyon sa internet upang punan ang {2} application.",
  "learnMoreDescriptionTo": "Maaari ka pa ring magsulat ng mga mensahe sa Mode ng Offline kahit na ang iyong aparato ay hindi nakakonekta. Kapag ikinakabit mo ang lahat ng iyong mga mensahe ay awtomatikong ipapadala sa {1}.",
  "shareAllPastAndFutureMessages": "Ibahagi ang lahat ng nakaraan at hinaharap na mga mensahe sa kontekstong ito sa mga piniling partido",
  "sponsoredBy": "Ini-sponsored ng",
  "backTo": "Bumalik sa {1}",
  "applyForProduct": "Mag-apply para sa isang produkto",
  "formListError": "Hindi magagamit",
  "restartApp": "I-restart ang App",
  "invalidDocument": "di-wastong dokumento",
  "serverIsUnreachable": "Hindi maabot ang server",
  "customerWaiting": "{1} ay pumasok sa chat",
  "sandboxDescription": "Sa Sandbox, alamin kung paano gagamitin ang app na may kunwa ng mga nagbibigay ng serbisyo.",
  "listOfProducts": "Listahan ng mga produkto",
  "testForgetMe": "Ito ay isang mekanismo ng pagsubok upang i-reset ang lahat ng mga komunikasyon sa provider na ito",
  "fieldErrorMessagePrompt": "Ano ang mali sa patlang na ito?",
  "termsAndConditions": "Mga tuntunin at kundisyon.",
  "shareOne": "Bilang kahalili, ibahagi sa ibaba",
  "submittingForm": "Isinumite {1}",
  "fillTheForm": "Mangyaring punan ang form na ito ** {1} **",
  "forgetMe": "Kalimutan mo ako",
  "verifyPrompt": "Patunayan?",
  "receivedVerification": "Natanggap na pag-verify para sa {1}",
  "willBeAvailable": "Available ang pag-andar na ito sa lalong madaling panahon",
  "pleaseCorrectTheErrors": "Pakitama ang error sa form",
  "contextsFor": "Mga konteksto para sa",
  "temporarilyLocked": "Para sa iyong proteksyon, ang application na ito ay pansamantalang naka-lock para sa {1}",
  "thePropertyWithMinMaxRangeError": "Ang ari-arian na may saklaw na [min-max] ay maaaring magkaroon lamang ng dalawang numero",
  "noConnectionForPL": "Nangangailangan ang {appName} ng isang gumaganang koneksyon sa internet upang humiling ng isang listahan ng mga produkto mula sa {1} na wala ka sa ngayon",
  "takeAPicture": "Mangyaring kumuha ng ** selfie ** larawan ng iyong mukha",
  "submitting": "Pagpadala",
  "edit": "I-edit",
  "noConnectionWillProcessLater": "Ang {appName} ay nangangailangan ng isang gumaganang koneksyon sa internet na wala ka sa ngayon. Ipaproseso ang kahilingan kapag itinatag ang isang koneksyon",
  "bookmarks": "Mga bookmark",
  "exploreData": "Galugarin ang Data",
  "Please fill out the form": "Mangyaring punan ang form",
  "Please scan your": "Mangyaring i-scan ang iyong",
  "ID document": "ID dokumento",
  "See our list of products": "Tingnan ang aming listahan ng mga produkto",
  "Our products have changed": "Nagbago ang aming mga produkto",
  "Choose Apply for Product from the menu": "Pumili ng Mag-apply para sa Produkto mula sa menu",
  "Please take a selfie to prove this is your document. Center your face.": "Mangyaring kumuha ng selfie upang patunayan na ito ang iyong dokumento. I-center ang iyong mukha.",
  "Application submitted!": "Ang aplikasyon ay naipasa!",
  "Please tap here and sign": "Mangyaring mag-tap dito at mag-sign",
  "Sending": "Nagpapadala",
  "Give me a moment...": "Bigyan mo ako ng sandali ...",
  "Please click to scan your": "Mangyaring mag-click upang i-scan ang iyong",
  "' photo of yourself that I can match against your ID document": "'larawan ng iyong sarili na maaari kong tumugma sa iyong ID dokumento",
  "Thank you. Now take a '": "Salamat. Ngayon kumuha ng isang '",
  "pleaseSign": "Mangyaring mag-sign sa loob ng gray na kahon",
  "getStarted": "Magsimula",
  "goodNewsFew": "Magandang balita! Mayroon ka pa ng ilang. Upang ibahagi ang icon ng tapikin sa ibaba.",
  "goodNews": "Magandang balita! Mayroon ka na (1). Upang ibahagi i-tap ang icon sa ibaba",
  "Cancel": "Kanselahin",
  "Submit": "Ipasa",
  "Clear": "Malinaw",
  "usePhoto": "Gumamit ng larawan",
  "retake": "Muling kunin",
  "Deny": "Tanggihan",
  "Approve": "Aprubahan",
  "loading": "Naglo-load ...",
  "checkIfMatch": "Tingnan kung tugma",
  "Verifications": "Mga pagpapatunay",
  "Seals": "Mga seal",
  "Applications": "Mga Application",
  "Corporation Exists Checks": "Nag-e-expire ang Corporation",
  "createManualMatchCheck": "Gumawa ng manu-manong check ng pagtutugma",
  "Finally, you will be in control of your own private information!": "Sa wakas, ikaw ay may kontrol sa iyong sariling pribadong impormasyon!",
  "Get set for friendliness?": "Magtakda ka para sa kabaitan?",
  "Ready for friendliness?": "Handa ka para sa kabaitan?",
  "Take a quick tour of chat bot?": "Kumuha ng isang mabilis na tour ng chat bot?",
  "Go friendliness!": "Pumunta sa pagkamagiliw!",
  "Go!": "Pumunta!",
  "Ready?": "Handa?",
  "Get set": "Magtakda",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Tatanungin kami ng mga tanong sa chat at punan mo lamang ang mga form o sundin ang mga kahilingan",
  "Before we start you'll need a valid passport, identity card or driving license": "Bago kami magsimula kailangan mo ng isang wastong pasaporte, kard ng pagkakakilanlan o lisensya sa pagmamaneho",
  "Done": "Tapos na",
  "Skip": "Laktawan",
  "Next": "Susunod",
  "Sanctions Checks": "Mga tseke ng Sanctions",
  "inProcess": "Pinoproseso ...",
  "networkFailure": "Nakakaranas ako ng ilang mga isyu sa network. Maaari mong suriin at pagkatapos ay tapikin ang Retry / Cancel",
  "invalidQuery": "Oops, naabot namin ang isang error na nagpapatakbo ng iyong paghahanap. Susubukan ng aming mga developer na ayusin ito sa lalong madaling panahon.",
  "invalidQR": "Di-wastong QR code",
  "failedToSendLog": "Nabigong magpadala ng log",
  "debugLogSent": "Naipadala ang Pag-log ng Debug",
  "validatingDataClaim": "Pag-import ng data",
  "supportedQrCodes": "Mga suportadong QR code:\n1) magdagdag ng chat channel\n2) pag-import ng data",
  "logSentToDevTeam": "Ang log ay ipinadala sa koponan ng nag-develop ng Tradle",
  "noResourcesForCriteria": "Walang nakitang mga mapagkukunan para sa pamantayang ito",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Mangyaring suriin ang data sa ibaba, at kumuha ng isang snapshot ng {1} bahagi ng dokumento",
  "documentBackSide": "Dokumento sa likod ng dokumento",
  "Photo": "Larawan",
  "doYouWantToContinue": "Gusto mo bang lumipat dito at magpatuloy mula doon?",
  "startedByAnotherEmployee": "Ang application para sa {1} ay sinimulan ng isa pang empleyado",
  "afterRefresh": "Ikaw ay nalilimas na gamitin ang aming mga serbisyo nang tuluy-tuloy",
  "reviewData": "Repasuhin ang data",
  "requestMyData": "Humihiling ng aking data",
  "newCustomer": "Bagong customer",
  "areYouSureYouAreDone": "Sigurado ka bang gusto mong tapusin ang sesyon na ito?",
  "scanYourDocument": "Mangyaring i-scan ang iyong dokumento",
  "resetApp": "I-reset ang App",
  "invalidCountry": "Di-wastong na-scan ang bansa",
  "wrongDocumentTypePleaseTryAgain": "Maling uri ng dokumento. Ulitin mo ulit",
  "wipeTheAppData": "Linisan ang data ng app",
  "enterPasswordOrWipeOutTheAppData": "Ipasok ang password o punasan ang data ng app",
  "dateInTheFutureError": "{1} ay sa hinaharap",
  "pleaseChooseDT": "Mangyaring pumili ng uri ng dokumento muna",
  "formChooser": "Humiling ng isang Form"
}