module.exports = {
  "search": "ค้นหา",
  "forgetMe": "ลืมฉัน",
  "newProduct": "ผลิตภัณฑ์ใหม่",
  "changePassword": "เปลี่ยนรหัสผ่าน",
  "edit": "แก้ไข",
  "gestureNotRecognized": "รูปแบบผิดพลาด",
  "setNewPassword": "เลือกรหัสผ่านใหม่",
  "invalidPropertyValue": "ค่าไม่ถูกต้อง",
  "officialAccounts": "การสนทนา",
  "cancel": "ยกเลิก",
  "optional": "ไม่จำเป็น",
  "enterCurrentPassword": "ป้อนรหัสผ่านปัจจุบันของคุณ",
  "searchSomething": "ค้นหา {1}",
  "touchIdOn": "รหัสการแตะถูกเปิดอยู่",
  "showQR": "โค้ด QR ของฉัน",
  "drawYourNewPassword": "วาดรูปแบบใหม่",
  "correctGesture": "พบรูปแบบที่ถูกต้อง",
  "passwordLimitations": "รูปแบบต้องมี 5 คะแนน",
  "youShared": "คุณแชร์จาก {1}",
  "shareWith": "แชร์ {1}",
  "useGesturePassword": "เปิดใช้งานรหัสผ่าน Gesture",
  "sharedForm": "แชร์ {1} จาก {2}",
  "issuedByOn": "ออกโดย {1} on",
  "tooManyPasswordAttempts": "พยายามมากเกินไป! แบบฟอร์มนี้ถูกปิดการใช้งาน",
  "addServerUrl": "เพิ่ม URL ของเซิร์ฟเวอร์",
  "myDocuments": "เอกสารของฉัน",
  "backTo": "กลับไปที่ {1}",
  "somethingWrong": "บางอย่างผิดพลาด",
  "homePage": "บ้าน",
  "learnMore": "เรียนรู้เพิ่มเติม",
  "formListError": "ไม่มี",
  "sentTo": "ส่งถึง {1}",
  "invalidPattern": "รูปแบบผิดพลาด",
  "confirmForgetMe": "แน่ใจหรือไม่ว่าคุณต้องการให้ '{1}' ลืมคุณ",
  "pairingRequest": "คำขอจับคู่",
  "iNeed": "ฉันต้องการ...",
  "wrongPattern": "รูปแบบผิดพลาด",
  "enterYourName": "ใส่ชื่อของคุณ",
  "done": "เสร็จสิ้น",
  "back": "กลับ",
  "ok": "ตกลง",
  "profile": "ข้อมูลส่วนตัว",
  "settings": "การตั้งค่า",
  "applyForProduct": "สมัครผลิตภัณฑ์",
  "noNetwork": "ไม่มีเครือข่าย",
  "unlockDevice": "ปลดล็อกอุปกรณ์ของคุณเพื่อดำเนินการต่อ",
  "useTouchIdAndGesturePassword": "เปิดใช้งาน ID แบบสัมผัสและท่าทางสัมผัส",
  "addNew": "เพิ่ม {1} ใหม่",
  "patternNotMatching": "รูปแบบไม่ตรงกัน",
  "invalidProperty": "ไม่ถูกต้อง {1}",
  "irrefutableProofs": "พยานหักล้างไม่ได้",
  "customerWaiting": "{1} เข้าแชทแล้ว",
  "authenticationFailed": "รับรองความถูกต้องล้มเหลว",
  "shareContext": "แชร์ {1}",
  "help": "ช่วยด้วย",
  "details": "รายละเอียด",
  "shareMyProduct": "คุณสามารถแตะด้านล่างเพื่อแชร์ {1} กับ {2}",
  "switchToRepresentative": "ยังไม่ได้ใช้โหมดตัวแทน",
  "reviewScannedProperties": "โปรดตรวจทานและแก้ไขข้อมูลด้านล่างนี้",
  "confirmRevoke": "ขอให้ {1} ลบเอกสารนี้ออกจากบันทึกของพวกเขาหรือไม่?",
  "en": "อังกฤษ",
  "theMinValueBiggerThenMaxValue": "ค่ามิเตอร์สำหรับช่วงควรเล็กกว่าค่าสูงสุด",
  "setDateValue": "ตั้งค่า",
  "next": "ต่อไป",
  "fillTheForm": "โปรดกรอกแบบฟอร์มนี้ ** {1} **",
  "noConnection": "{appName} ต้องการการเชื่อมต่ออินเทอร์เน็ตที่ทำงานซึ่งคุณไม่ได้มีอยู่ในขณะนี้",
  "iproovFailedTitle": "อ๊ะ! บางอย่างผิดพลาด",
  "verifyPrompt": "ตรวจสอบ?",
  "validationErrors": "โปรดแก้ไขเขตตรวจสอบที่ล้มเหลว",
  "later": "ต่อมา",
  "testProviders": "Sandbox",
  "oops": "อุ่ย",
  "sponsoredBy": "สนับสนุนโดย",
  "nl": "ดัตช์",
  "yes": "ใช่",
  "typeMessage": "พิมพ์ข้อความ",
  "useTouchId": "เปิดใช้งาน ID แบบสัมผัส",
  "pleaseCorrect": "โปรดแก้ไข",
  "shareChangesWith": "แชร์การเปลี่ยนแปลงด้วย",
  "bothOn": "ทั้งสองเป็น ON",
  "trustedProviders": "ผู้ให้บริการที่น่าเชื่อถือ",
  "importing": "การนำเข้า",
  "submitting": "ส่ง",
  "iproovErrorTitle": "อ๊ะ! บางอย่างผิดพลาด",
  "restartApp": "รีสตาร์ทแอป",
  "initializingEngine": "initializing engine",
  "error": "ความผิดพลาด",
  "youAreAboutToShare": "คุณกำลังจะแชร์\n '{1}'\n เอกสาร",
  "creationDate": "วันที่สร้าง",
  "youAreTheRM": "คุณเป็นผู้จัดการความสัมพันธ์สำหรับแอ็พพลิเคชันนี้",
  "continue": "ต่อ",
  "invalidPairingRequest": "คำขอจับคู่ไม่ถูกต้อง",
  "tapToRemovePhotos": "แตะเพื่อลบรูปภาพ",
  "viewDebugLog": "ดูบันทึกการแก้ปัญหา",
  "dataSecurity": "การรักษาความปลอดภัยข้อมูล",
  "switchTouchIdOn": "เปลี่ยนรหัสการติดต่อบน",
  "noAccessToServer": "เซิร์ฟเวอร์ไม่สามารถเข้าถึงได้ ลองภายหลัง",
  "termsAndConditions": "ข้อตกลงและเงื่อนไข",
  "contactUs": "ติดต่อเรา",
  "importDataPrompt": "คุณกำลังจะนำเข้าข้อมูลของคุณจาก",
  "submitLog": "ส่งบันทึก",
  "no": "ไม่",
  "acceptTermsAndConditions": "ดูข้อกำหนดในการให้บริการ",
  "drawYourPassword": "วาดรูปแบบของคุณ",
  "inProgress": "กำลังดำเนินการคำขอของคุณ",
  "contextsFor": "บริบทสำหรับ",
  "youShallNotPass": "คุณจะไม่ผ่าน!",
  "thisFieldIsRequired": "ต้องระบุข้อมูลนี้",
  "pleaseDrawPassword": "วาดรูปแบบของคุณ",
  "switchTouchIdOff": "ปิดใช้งานรหัสส่วนติดต่อ",
  "viewTerms": "โปรดดูข้อกำหนดในการให้บริการ",
  "centerLicence": "ศูนย์ใบอนุญาตในเฟรม",
  "enterPassword": "ป้อนรหัสผ่านของคุณ",
  "pairingRequestWasProcesseed": "การจับคู่คำขอถูกประมวลผลแล้ว",
  "willBeAvailable": "ฟังก์ชันนี้จะพร้อมให้บริการเร็ว ๆ นี้",
  "errorNotification": "มีการส่งการแจ้งเตือนข้อผิดพลาดให้กับลูกค้าเพื่อแก้ไข",
  "loadingResources": "กำลังโหลดทรัพยากร",
  "youReviewedAll": "คุณได้ตรวจทาน {1}",
  "verifiedBy": "ยืนยันโดย {1}",
  "youAreForgotten": "คุณลืมสำเร็จแล้ว",
  "invalidDocument": "เอกสารไม่ถูกต้อง",
  "receivedForm": "ได้รับแล้ว {1}",
  "cameraAccess": "การเข้าถึงกล้องถ่ายรูป",
  "enablePassword": "เปิดใช้งานรหัสผ่าน",
  "providerIsOffline": "{1} อยู่ในสถานะออฟไลน์",
  "nameUnknown": "ชื่อที่ไม่รู้จัก",
  "receivedProduct": "ได้รับแล้ว {1}",
  "drawYourOldPassword": "วาดรูปแบบเก่าของคุณ",
  "shareOneOfMany": "หรือแชร์ด้านล่าง",
  "formRequest": "คำขอสำหรับ {1}",
  "verifiedByOn": "ยืนยันโดย {1}",
  "pleaseRestartTIM": "โปรดรีสตาร์ท TiM",
  "areYouSureAboutWipe": "การกระทำนี้ไม่สามารถย้อนกลับได้ คุณจะสูญเสียข้อมูลและคีย์ส่วนตัวทั้งหมด คุณแน่ใจหรือไม่ว่าต้องการดำเนินการต่อ",
  "setPassword": "เลือกรหัสผ่านที่ปลอดภัย",
  "submittingModifiedForm": "กำลังแก้ไข {1}",
  "passwordsDontMatch": "รหัสผ่านไม่ตรงกัน",
  "correctPassword": "ทั้งหมดที่คุณจำได้!",
  "drawYourPasswordAgain": "วาดรูปแบบของคุณอีกครั้ง",
  "hello": "สวัสดี {1}!",
  "pairDevices": "จับคู่อุปกรณ์",
  "turnBothOn": "เปิดทั้งสอง",
  "nothingChanged": "ไม่มีอะไรเปลี่ยนแปลง",
  "approveApplicationFor": "อนุมัติใบสมัครสำหรับ {1}",
  "drawYourNewPasswordAgain": "วาดรูปแบบใหม่อีกครั้ง",
  "formChooser": "รายการแบบฟอร์ม",
  "add": "เพิ่ม {1}",
  "thisValueIsInvalidPlaceholder": "ค่านี้ไม่ถูกต้องเนื่องจาก ...",
  "deviceDoesNotHaveMyKeys": "ข้อมูลประจำตัวที่ได้รับไม่ใช่คีย์ของฉัน",
  "submittingForm": "ส่ง {1}",
  "updateNow": "อัปเดตเดี๋ยวนี้",
  "documentExpiredMessage": "โปรดสแกนเอกสารที่ถูกต้อง",
  "neverMissAMessage": "ไม่พลาดข้อความ",
  "confirmedMyData": "ข้อมูลที่นำเข้าทั้งหมดสามารถดูได้ใน {profileTitle}",
  "noScanningOnAndroid": "การสแกนเอกสารบน Android กำลังจะเร็ว ๆ นี้",
  "unknownQRCodeFormat": "รูปแบบ QR code ที่ไม่รู้จัก",
  "approveApplication": "อนุมัติใบสมัคร",
  "fieldErrorMessagePrompt": "เกิดอะไรขึ้นกับฟิลด์นี้?",
  "generatingKeys": "สร้างคีย์ส่วนตัวของคุณ",
  "pleaseCorrectFields": "โปรดแก้ไขข้อมูลต่อไปนี้: {1}",
  "learnMoreDescriptionTo": "คุณยังสามารถเขียนข้อความในโหมดออฟไลน์ได้แม้ว่าอุปกรณ์ของคุณจะไม่ได้เชื่อมต่อก็ตาม เมื่อคุณเชื่อมต่อข้อความทั้งหมดจะถูกส่งไปที่ {1} โดยอัตโนมัติ",
  "learnMoreServerIsDown": "ข้อความที่คุณเขียนจะถูกส่งไปที่ {1} โดยอัตโนมัติเมื่อออนไลน์",
  "installingUpdate": "การติดตั้งการอัพเดต",
  "issuedBy": "เผยแพร่โดย {1}",
  "retryScanning": "เป็นที่ {1} หรือไม่? ฉันไม่สามารถบอกได้ กรุณาลองอีกครั้ง?\n\nเพื่อให้ได้ผลลัพธ์ที่ดีที่สุดให้ใช้โหมดแนวนอนหลีกเลี่ยงแสงจ้าและตรวจดูให้แน่ใจว่าวางเอกสารไว้ภายในเฟรมที่แสดงไว้",
  "verificationBy": "การยืนยันโดย {1}",
  "storageCorrupted": "ที่เก็บเบราเซอร์ของคุณได้รับความเสียหาย! กดตกลงเพื่อรีเซ็ตข้อมูลประจำตัวและที่เก็บข้อมูลของแอป",
  "receiveNotifications?": "คุณต้องการรับการแจ้งเตือนหรือไม่?",
  "shareOne": "หรือแชร์ด้านล่าง",
  "passwordOn": "รหัสผ่านการป้อนข้อความเปิดอยู่",
  "pleaseCorrectTheErrors": "โปรดแก้ไขข้อผิดพลาดในแบบฟอร์ม",
  "newProductMsg": "ฉันต้องการ {1}",
  "holdPhoneToPassportBackCover": "ถือโทรศัพท์ด้านหลังไว้ด้านหลังของหนังสือเดินทาง",
  "restartingApp": "โปรแกรมจะรีสตาร์ททันที",
  "newContactRequest": "{1} ส่งคำขอติดต่อไปให้คุณ",
  "nothingToShare": "ไม่มีอะไรที่จะแบ่งปัน",
  "turnTouchIdOn": "เปิดรหัสสัมผัสบน",
  "shareOne1": "{1} นี่คือผู้ช่วยส่วนตัวของคุณ ฉันเห็นว่าคุณได้ยืนยัน {2} แล้ว คุณสามารถแตะด้านล่างเพื่อแชร์กับ {3}",
  "documentNotScanning": "อ๊ะมีบางอย่างผิดพลาด!",
  "pleaseTapOnMenu": "กรุณาแตะที่ปุ่มสีแดงและ",
  "verifierHelp": "คลิกปุ่ม 'เสร็จสิ้น' หลังจากตรวจสอบแบบฟอร์ม หากบางฟิลด์ต้องมีการแก้ไขให้ตรวจสอบก่อนแล้วคลิ๊กที่ปุ่ม 'เสร็จสิ้น'",
  "sandboxDescription": "ใน Sandbox ให้เรียนรู้วิธีใช้แอพพลิเคชั่นกับผู้ให้บริการแบบจำลอง",
  "updateAppMessage": "อัปเดตตอนนี้หรือฉันจะเตือนคุณในภายหลัง",
  "createNext": "กรอกแบบฟอร์มอื่น \"{1}\"",
  "noConnectionForPL": "{appName} ต้องการการเชื่อมต่ออินเทอร์เน็ตที่ทำงานเพื่อขอรายการผลิตภัณฑ์จาก {1} ที่คุณไม่มีในขณะนี้",
  "shareOneOfMany1": "{1} นี่คือผู้ช่วยส่วนตัวของคุณ ฉันเห็นว่าคุณได้ยืนยัน {2} แล้ว คุณสามารถแตะที่รายการใด ๆ ในรายการด้านล่างเพื่อแชร์กับ {3}",
  "cancelHideResource": "ยกเลิกการซ่อน {1}",
  "resetRequired": "ต้องตั้งค่าใหม่",
  "listOfProducts": "รายการผลิตภัณฑ์",
  "overviewOfApplications": "ภาพรวมของแอพพลิเคชั่น",
  "iproovErrorMessage": "โปรดรอสักครู่แล้วลองอีกครั้ง",
  "sourcesBy": "แหล่งที่มาโดย {1}",
  "asVerifiedBy": "ยืนยันโดย {1}",
  "messageWaitingFrom": "คุณมีข้อความใหม่จาก {1}",
  "backToResults": "กลับไปที่ผลลัพธ์",
  "centerID": "Center ID ในเฟรม",
  "hideResource": "ซ่อน {1}",
  "documentExpiredTitle": "เอกสารหมดอายุแล้ว",
  "changeGesturePassword": "เปลี่ยนรหัสผ่านท่าทาง",
  "learnMoreDescription": "คุณยังสามารถเขียนข้อความในโหมดออฟไลน์ได้แม้ว่าอุปกรณ์ของคุณจะไม่ได้เชื่อมต่อก็ตาม เมื่อคุณเชื่อมต่อข้อความทั้งหมดจะถูกส่งโดยอัตโนมัติ",
  "scanQRcode": "สแกนโค้ด QR",
  "serverIsUnreachable": "เซิร์ฟเวอร์ไม่สามารถเข้าถึงได้",
  "importYourData": "นำเข้าข้อมูลของคุณ",
  "verificationTransactionID": "รหัสธุรกรรมของการตรวจสอบ",
  "downloadingUpdate": "กำลังดาวน์โหลดการอัปเดต ...",
  "fromMyData": "จาก 'ข้อมูลของฉัน'",
  "youReviewed": "คุณได้ตรวจสอบ {1} จาก {2} รายการแล้ว",
  "areYouSureYouWantToServeThisCustomer": "คุณแน่ใจหรือไม่ว่าต้องการรับใช้ลูกค้ารายนี้?",
  "offlineMode": "แฟชั่นแบบออฟไลน์",
  "addAnotherFormOrGetNext": "เพิ่มอีก {1} หรือย้ายไปที่ฟอร์มถัดไป",
  "areYouSureYouWantToConfirmAllItems": "แตะตกลงเพื่อยืนยันทั้งหมด {1} หรือยกเลิกเพื่อดำเนินการตรวจสอบต่อ",
  "updateAppTitle": "มีการอัปเดตแอปพลิเคชัน",
  "importData": "นำเข้าวันที่",
  "denyApplicationFor": "ปฏิเสธการสมัครสำหรับ {1}",
  "sendEditRequestPrompt": "ส่งคำขอแก้ไขไปที่ {1} หรือไม่?",
  "enablePasscodeFirst": "ดูเหมือนว่าคุณไม่มีรหัสผ่านอุปกรณ์ที่เปิดใช้อยู่ หากไม่มีแอปนี้แอปนี้จะไม่สามารถปกป้องข้อมูลของคุณได้! โปรดเปิดใช้งานก่อนที่จะกด OK",
  "areYouSureYouWantToDelete": "คุณแน่ใจหรือไม่ว่าต้องการซ่อน {1}?",
  "confirmAllItems": "แตะตกลงเพื่อยืนยันทั้งหมดหรือยกเลิกเพื่อดำเนินการตรวจสอบต่อ",
  "iproovFailedMessage": "กรุณาลองอีกครั้ง. เพื่อให้ได้ผลลัพธ์ที่ดีที่สุดให้หน้าของคุณอยู่กึ่งกลางระหว่างรูปไข่ในระหว่างที่กะพริบ",
  "fillRequiredFields": "โปรดกรอกข้อมูลในฟิลด์ที่จำเป็นทั้งหมด",
  "digitalWealthPassport": "หนังสือเดินทางความมั่งคั่งดิจิตอล",
  "denyApplication": "ปฏิเสธใบสมัคร",
  "incompatibleVersion": "เนื่องจากการเปลี่ยนแปลงที่เข้ากันไม่ได้ในช่วงหลัง ๆ นี้การอัปเดตนี้จำเป็นต้องมีการตั้งค่าแอปอย่างหนัก กดตกลงเพื่อรีเซ็ตข้อมูลประจำตัวและที่เก็บข้อมูลของแอป",
  "invalidDeepLink": "ดูเหมือนคุณจะคลิกลิงก์ที่ไม่ถูกต้อง!",
  "importingData": "การนำเข้า {1} เอกสารจาก {2}",
  "multientryToShare": "มี {1} เอกสารที่จะแชร์",
  "createNew": "กรอกแบบฟอร์ม \"{1}\"",
  "areYouSureAboutNextForm": "คุณแน่ใจหรือว่าทำเสร็จแล้ว {1}?",
  "scanningFailedTryAgain": "การสแกนไม่สำเร็จ คุณช่วยลองใหม่อีกครั้งได้ไหม?",
  "testForgetMe": "นี่คือกลไกการทดสอบเพื่อรีเซ็ตการติดต่อสื่อสารทั้งหมดกับผู้ให้บริการรายนี้",
  "holdPhoneToPassport": "จับด้านหลังโทรศัพท์ของคุณไว้กับหน้าปกหนังสือเดินทางของคุณ",
  "takeAPicture": "กรุณาใช้ ** ภาพ selfie ** ของใบหน้าของคุณ",
  "textPasswordLimitations": "ต้องมี 10 ตัวอักษรอย่างน้อยหนึ่งตัวอักษรตัวพิมพ์ใหญ่ตัวพิมพ์เล็กตัวเลขและตัวอักษรพิเศษ",
  "pleaseClickOnAddButton": "โปรดคลิกที่ '+' ด้านล่างเพื่อเพิ่ม '{1}'",
  "thePropertyWithMinMaxRangeError": "พร็อพเพอร์ตี้ที่มีช่วง [ต่ำสุด] สามารถมีได้เพียงสองหมายเลขเท่านั้น",
  "loadingModels": "แบบจำลองการโหลด",
  "shareProduct": "คุณสามารถแตะด้านล่างเพื่อแชร์ {1} กับ {2}",
  "sentToOn": "ส่งไปที่ {1}",
  "asSentTo": "ตามที่ส่งไปที่ {1}",
  "turnPasswordOn": "เปิดใช้รหัสผ่าน Gesture",
  "enableCameraAccess": "{appName} ปัจจุบันไม่มีสิทธิ์ใช้กล้องถ่ายรูป หากต้องการให้สิทธิ์การเข้าถึงให้เลือกการตั้งค่าและตรวจสอบว่าเปิดใช้งานกล้องถ่ายรูปอยู่",
  "noConnectionForNewProduct": "{1}, {appName} ต้องการการเชื่อมต่ออินเทอร์เน็ตที่ทำงานเพื่อกรอกใบสมัคร {2}",
  "receivedVerification": "ได้รับการยืนยันสำหรับ {1}",
  "fillTheFormWithAttachments": "โปรดกรอกแบบฟอร์มนี้ ** {1} **",
  "ukLicenseUnsupported": "การสแกนใบอนุญาตขับขี่ในสหราชอาณาจักรไม่ได้รับการสนับสนุนในขณะนี้",
  "sharedWith": "แชร์ {1} บริบทกับ {2}",
  "formListErrorDescription": "สามารถขอแบบฟอร์มได้เมื่อลูกค้าเริ่มสมัคร",
  "somethingWrongSubmitLog": "มีบางอย่างผิดพลาด โปรดส่งบันทึกการแก้ปัญหาไปยังทีมพัฒนา {appName}",
  "temporarilyLocked": "สำหรับการป้องกันของคุณแอปพลิเคชันนี้ได้ถูกล็อคไว้ชั่วคราวสำหรับ {1}",
  "independentBlockchainViewer": "ผู้ดู blockchain อิสระ",
  "shareAllPastAndFutureMessages": "แชร์ข้อความทั้งหมดในอดีตและในอนาคตในบริบทนี้กับบุคคลที่เลือก",
  "noConnectionWillProcessLater": "{appName} ต้องการการเชื่อมต่ออินเทอร์เน็ตที่ทำงานซึ่งคุณไม่ได้มีอยู่ในขณะนี้ คำขอจะได้รับการประมวลผลเมื่อทำการเชื่อมต่อ",
  "sharedContext": "บริบทที่ใช้ร่วมกัน",
  "cancelItem": "คุณกำลังจะยกเลิก {1} โปรดแตะตกลงเพื่อยืนยัน",
  "unreadMessages": "คุณมีข้อความที่ยังไม่ได้อ่าน",
  "acceptingTermsAndConditions": "เมื่อกดตกลงคุณยอมรับข้อกำหนดในการให้บริการ",
  "centerPassport": "หน้าเว็บหนังสือเดินทางศูนย์ในกรอบ",
  "Next": "ต่อไป",
  "Verifications": "การตรวจสอบ",
  "ID document": "เอกสารประจำตัวประชาชน",
  "Clear": "ชัดเจน",
  "bookmarks": "ที่คั่น",
  "Cancel": "ยกเลิก",
  "Done": "เสร็จสิ้น",
  "Application submitted!": "ส่งใบสมัครแล้ว!",
  "Our products have changed": "ผลิตภัณฑ์ของเรามีการเปลี่ยนแปลง",
  "Deny": "ปฏิเสธ",
  "retake": "ใช้เวลาอีก",
  "Skip": "กระโดด",
  "Applications": "การประยุกต์ใช้งาน",
  "Please click to scan your": "โปรดคลิกเพื่อสแกนของคุณ",
  "Sending": "การส่ง",
  "getStarted": "เริ่ม",
  "Approve": "อนุมัติ",
  "checkIfMatch": "ตรวจสอบว่าตรงกับหรือไม่",
  "Submit": "เสนอ",
  "Seals": "ซีล",
  "Sanctions Checks": "การตรวจสอบการลงโทษ",
  "Give me a moment...": "ให้ฉันสักครู่...",
  "loading": "กำลังโหลด ...",
  "Go!": "ไป!",
  "Ready?": "พร้อมหรือยัง?",
  "Get set for friendliness?": "ได้รับการตั้งค่าเป็นมิตร?",
  "Get set": "ตั้งค่า",
  "pleaseSign": "โปรดลงชื่อเข้าใช้ภายในช่องสีเทา",
  "Please fill out the form": "โปรดกรอกแบบฟอร์ม",
  "exploreData": "สำรวจข้อมูล",
  "Take a quick tour of chat bot?": "ทัวร์ชมบอทแชทอย่างรวดเร็วหรือไม่?",
  "Please take a selfie to prove this is your document. Center your face.": "โปรดใช้ selfie เพื่อพิสูจน์ว่านี่เป็นเอกสารของคุณ เล็งใบหน้าของคุณ",
  "goodNewsFew": "ข่าวดี! คุณมีบ้างแล้ว หากต้องการแชร์ไอคอนการแตะด้านล่าง",
  "Corporation Exists Checks": "บริษัท มีการตรวจสอบ",
  "Go friendliness!": "ไปเป็นมิตร!",
  "usePhoto": "ใช้รูปภาพ",
  "Thank you. Now take a '": "ขอขอบคุณ. ตอนนี้ใช้ '",
  "createManualMatchCheck": "สร้างการตรวจสอบการตรงกันด้วยตนเอง",
  "See our list of products": "ดูรายการผลิตภัณฑ์ของเรา",
  "Please tap here and sign": "กรุณาแตะที่นี่และลงนาม",
  "Please scan your": "โปรดสแกนของคุณ",
  "Ready for friendliness?": "พร้อมสำหรับความเป็นมิตร?",
  "' photo of yourself that I can match against your ID document": "'ภาพของตัวเองที่ฉันสามารถจับคู่กับเอกสาร ID ของคุณ",
  "Choose Apply for Product from the menu": "เลือกใช้สำหรับผลิตภัณฑ์จากเมนู",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "เราจะถามคำถามในการแชทและคุณเพียงแค่กรอกแบบฟอร์มหรือทำตามคำขอ",
  "goodNews": "ข่าวดี! คุณมี {1} แล้ว หากต้องการแบ่งปันแตะที่ไอคอนด้านล่าง",
  "Before we start you'll need a valid passport, identity card or driving license": "ก่อนที่เราจะเริ่มต้นคุณจะต้องมีหนังสือเดินทางที่ถูกต้องบัตรประจำตัวประชาชนหรือใบขับขี่",
  "Finally, you will be in control of your own private information!": "สุดท้ายคุณจะควบคุมข้อมูลส่วนตัวของคุณเอง!",
  "Photo": "ภาพถ่าย",
  "newCustomer": "ลูกค้าใหม่",
  "inProcess": "กำลังประมวลผล ...",
  "invalidCountry": "สแกนประเทศไม่ถูกต้อง",
  "validatingDataClaim": "กำลังนำเข้าข้อมูล",
  "documentBackSide": "จัดกึ่งกลางเอกสารด้านหลัง",
  "noResourcesForCriteria": "ไม่พบทรัพยากรสำหรับเกณฑ์นี้",
  "supportedQrCodes": "รหัส QR ที่รองรับ:\n1) เพิ่มแชทแชนเนล\n2) นำเข้าข้อมูล",
  "enterPasswordOrWipeOutTheAppData": "ป้อนรหัสผ่านหรือล้างข้อมูลแอป",
  "debugLogSent": "แก้ไขบันทึกการทำงานแล้ว",
  "resetApp": "รีเซ็ตแอป",
  "invalidQR": "รหัส QR ไม่ถูกต้อง",
  "scanYourDocument": "กรุณาสแกนเอกสารของคุณ",
  "dateInTheFutureError": "{1} อยู่ในอนาคต",
  "reviewData": "ตรวจสอบข้อมูล",
  "wipeTheAppData": "ล้างข้อมูลแอพ",
  "doYouWantToContinue": "คุณต้องการเปลี่ยนมาใช้และดำเนินการต่อจากที่นั่นหรือไม่",
  "networkFailure": "ฉันประสบปัญหาเครือข่ายบางอย่าง คุณช่วยตรวจสอบแล้วแตะลองใหม่ / ยกเลิก",
  "reviewScannedPropertiesAndSecondSideSnapshot": "โปรดตรวจสอบข้อมูลด้านล่างและถ่ายภาพด้านข้าง {1} ของเอกสาร",
  "startedByAnotherEmployee": "แอปพลิเคชันสำหรับ {1} เริ่มต้นโดยพนักงานคนอื่น",
  "invalidQuery": "อ๊ะเราพบข้อผิดพลาดในการเรียกใช้การค้นหาของคุณ นักพัฒนาของเราจะพยายามแก้ไขโดยเร็ว",
  "logSentToDevTeam": "บันทึกถูกส่งไปยังทีมผู้พัฒนา Tradle",
  "afterRefresh": "คุณได้รับการเคลียร์ให้ใช้บริการของเราโดยไม่หยุดชะงัก",
  "pleaseChooseDT": "โปรดเลือกประเภทเอกสารก่อน",
  "requestMyData": "ขอข้อมูลของฉัน",
  "wrongDocumentTypePleaseTryAgain": "ประเภทเอกสารไม่ถูกต้อง กรุณาลองอีกครั้ง",
  "failedToSendLog": "การส่งบันทึกล้มเหลว",
  "areYouSureYouAreDone": "คุณแน่ใจหรือไม่ว่าต้องการจบเซสชันนี้"
}