module.exports = {
  "back": "ပြန်.",
  "gestureNotRecognized": "မှားယွင်းတဲ့ပုံစံ",
  "patternNotMatching": "အဆိုပါပုံစံများမကိုက်ညီခဲ့ပါဘူး။",
  "drawYourNewPassword": "အသစ်တခုပုံစံဆွဲပါ",
  "addNew": "အသစ်က {1} Add",
  "edit": "Edit ကို",
  "settings": "Settings များ",
  "thePropertyWithMinMaxRangeError": "[မိနစ်-max ကို] အကွာအဝေးနှင့်အတူပိုင်ဆိုင်မှုနှစ်ခုသာနံပါတ်များရှိနိုင်ပါသည်",
  "switchTouchIdOff": "ထိတွေ့ ID ကိုချွတ် Switch",
  "theMinValueBiggerThenMaxValue": "အကွာအဝေးများအတွက်မိတန်ဖိုး max ကိုတနျဖိုးပြီးတော့သေးငယ်ဖြစ်သင့်",
  "setDateValue": "အစုံ",
  "fillTheFormWithAttachments": "** ** {1} ဤပုံစံကိုဖြည့်စွက်ပေးပါ",
  "verificationTransactionID": "verification ငွေသွင်းငွေထုတ် Id",
  "noConnectionForPL": "{APPNAME} {1} သင်ယခုအချိန်တွင်ရှိသည်မဟုတ်ကြဘူးရာမှထုတ်ကုန်များစာရင်းကိုတောင်းဆိုရန်တစ်ဦးအလုပ်လုပ်နေအင်တာနက်ကွန်နက်ရှင်လိုအပ်ပါတယ်",
  "fillTheForm": "** ** {1} ဤပုံစံကိုဖြည့်စွက်ပေးပါ",
  "typeMessage": "သတင်းစကားတစ်ခုရိုက်ထည့်ပါ",
  "verifierHelp": "ပုံစံပြန်လည်သုံးသပ်ပြီးနောက် '' ပြီးပြီ 'ခလုတ်ကိုကလစ်နှိပ်ပါ။ တချို့လယ်ကွင်းဆုံးမခြင်းလိုအပ်ခဲ့လျှင်၎င်းတို့ကိုစစ်ဆေးသူတို့ကိုပထမနှင့်ထို့နောက် '' Done 'ခလုတ်ကိုကလစ်နှိပ်ပါ",
  "issuedBy": "{1} ကထုတ်ပေး",
  "sentToOn": "အပေါ် {1} ထံသို့စေလွှတ်",
  "myDocuments": "My Documents",
  "shareOne": "နောက်တစ်မျိုးအနေနဲ့အောက်ပါဝေမျှ",
  "tapToRemovePhotos": "ဓာတ်ပုံများဖယ်ရှားပစ်ရန်ကိုအသာပုတ်",
  "newProduct": "ထုတ်ကုန်အသစ်",
  "optional": "optional ကို",
  "confirmRevoke": "၎င်းတို့၏မှတ်တမ်းများထံမှဤစာရွက်စာတမ်းကိုဖျက်ပစ်ရန် {1} အမေး",
  "showQR": "အကြှနျုပျ၏ QR ကုဒ်ကို",
  "verifiedByOn": "အပေါ် {1} ကစိစစ်",
  "shareWith": "ဝေမျှမယ် {1}",
  "add": "{1} Add",
  "areYouSureAboutNextForm": "သငျသညျ {1} နှင့်အတူပြုသေချာလား?",
  "sentTo": "{1} ထံသို့စေလွှတ်",
  "shareProduct": "သငျသညျ {2} နှင့်အတူ {1} ဝေမျှဖို့အောက်ကအသာပုတ်နိုင်သည်",
  "noConnection": "{APPNAME} သင်ယခုအချိန်တွင်ရှိသည်မဟုတ်ကြဘူးသောအလုပ်လုပ်နေအင်တာနက်ကွန်နက်ရှင်လိုအပ်ပါတယ်",
  "useGesturePassword": "လက်ဟန် Password ကို Enable",
  "sharedWith": "{2} အတူဝေမျှ {1} အခြေအနေတွင်",
  "useTouchId": "Touch ကို ID ကို Enable",
  "scanQRcode": "QR ကုဒ်ကိုစကင်ဖတ်စစ်ဆေး",
  "pleaseCorrectFields": "အောက်ပါကွက်လပ်များကိုပြင်ပေးပါ: {1}",
  "profile": "ပရိုဖိုင်းကို",
  "somethingWrongSubmitLog": "တစ်ခုခုမှားယွင်းကြပုံရသည်။ အဆိုပါ {APPNAME} ဆော့ဖ်ဝဲရေးအဖွဲ့ကရန်ဒီဘာဂ်မှတ်တမ်းတင်ပြရန် ကျေးဇူးပြု.",
  "youShallNotPass": "သင်မဖြတ်သန်းသင့်ပါ!",
  "enablePasscodeFirst": "သငျသညျပတ်စ်ကုတ် enabled ကိရိယာရှိသည်မဟုတ်ကြဘူးနဲ့တူလှပါတယ်။ ကသာမရှိရင်ဒီ app ကိုသင့်ရဲ့ဒေတာကိုကာကွယ်ပေးမပေးနိုငျသညျ! OK ကိုနှိပ်ရှေ့မှာ enable ပေးပါ",
  "homePage": "နေအိမ်",
  "officialAccounts": "စကားစမြည်",
  "areYouSureYouWantToDelete": "သငျသညျ {1} ဖုံးကွယ်ချင်သင်သေချာပါသလား?",
  "sourcesBy": "{1} အားဖြင့်သတင်းရင်းမြစ်",
  "importData": "တင်သွင်းသည့်ရက်စွဲ",
  "newProductMsg": "ငါ {1} လိုအပ်ပါတယ်။",
  "shareOneOfMany": "နောက်တစ်မျိုးအနေနဲ့အောက်ပါဝေမျှ",
  "shareOne1": "{1}, ဒီသင်၏ပုဂ္ဂိုလ်ရေး privacy ကိုလက်ထောက်ဖြစ်ပါတယ်။ ငါသည်သင်တို့ကိုပြီးသားသင့်ရဲ့ {2} မှန်ကန်ကြောင်းအတည်ပြုခဲ့တယ်ကြည့်ပါ။ သင် {3} နှင့်အတူမျှဝေဖို့အောက်ကသာပုတ်နိုင်သည်။",
  "passwordOn": "လက်ဟန်ခြေဟန် Password ကို ON ဖြစ်ပါသည်",
  "switchToRepresentative": "ကိုယ်စားလှယ် mode ကိုပြောင်းပါသေးစတင်ခြင်းမရှိပါ။",
  "issuedByOn": "အပေါ် {1} ကထုတ်ပေး",
  "serverIsUnreachable": "Server ကိုလက်လှမ်းမမှီပါဖြစ်ပါသည်",
  "verifyPrompt": "Verify?",
  "pleaseCorrect": "ပြင်ပေးပါ",
  "addAnotherFormOrGetNext": "အခြား {1} Add ဒါမှမဟုတ်လာမယ့်ပုံစံကိုမှအပေါ်ကိုရွှေ့",
  "noConnectionWillProcessLater": "{APPNAME} သင်ယခုအချိန်တွင်ရှိသည်မဟုတ်ကြဘူးသောအလုပ်လုပ်နေအင်တာနက်ကွန်နက်ရှင်လိုအပ်သည်။ ချိတ်ဆက်မှုတည်ဆောက်ပြီးသောအခါတောင်းဆိုမှုကိုလုပ်ငန်းများ၌ပါလိမ့်မည်",
  "verifiedBy": "{1} ကစိစစ်",
  "switchTouchIdOn": "ထိတွေ့ ID ကိုအပေါ် Switch",
  "installingUpdate": "Installing update ကို",
  "shareOneOfMany1": "{1}, ဒီသင်၏ပုဂ္ဂိုလ်ရေး privacy ကိုလက်ထောက်ဖြစ်ပါတယ်။ ငါသည်သင်တို့ကိုပြီးသားသင့်ရဲ့ {2} မှန်ကန်ကြောင်းအတည်ပြုခဲ့တယ်ကြည့်ပါ။ သင် {3} သူတို့နှင့်အတူဝေမျှဖို့အောက်ကစာရင်းထဲမှာမဆိုပစ္စည်းများအပေါ်သာပုတ်နိုင်သည်။",
  "viewDebugLog": "ကြည့်ရန်ဒီဘာဂ်မှတ်တမ်း",
  "takeAPicture": "သင်၏မျက်နှာကိုတစ်ဦး ** selfie ** ရုပ်ပုံယူ ကျေးဇူးပြု.",
  "submitLog": "Log in ဝင်ရန် Submit",
  "invalidPropertyValue": "မှားနေသောတန်ဖိုးကို",
  "noConnectionForNewProduct": "{1}, {APPNAME} အဆိုပါ {2} လျှောက်လွှာဖြည့်စွက်ရန်လုပ်ဆောင်နေအင်တာနက်ကွန်နက်ရှင်လိုအပ်သည်။",
  "done": "ပြီးပြီ",
  "oops": "သည်းခံပါ",
  "digitalWealthPassport": "ဒစ်ဂျစ်တယ်ကြွယ်ဝမှုနိုင်ငံကူးလက်မှတ်",
  "unknownQRCodeFormat": "အသိအမှတ်ပြုခြင်းမခံရဖို့အတွက် QR code ကို format နဲ့",
  "restartApp": "ပြန်လည်စတင်ပါက App",
  "cancelHideResource": "{1} ဝှက် Cancel",
  "confirmAllItems": "ထိုသူအပေါင်းတို့ကိုအတည်ပြုရန် OK ကိုထိပုတ်ပါ, ဒါမှမဟုတ်သုံးသပ်ဆက်လက် Cancel",
  "error": "အမှား",
  "somethingWrong": "တစ်ခုခုမှားသွားတယ်",
  "shareMyProduct": "သငျသညျ {2} နှင့်အတူ {1} ဝေမျှဖို့အောက်ကအသာပုတ်နိုင်သည်",
  "newContactRequest": "{1} သင်အဆက်အသွယ်တောင်းဆိုမှုကိုကိုစေလွှတ်",
  "cameraAccess": "ကင်မရာ Access ကို",
  "invalidProperty": "မှားနေသော {1}",
  "confirmedMyData": "အားလုံးတင်သွင်း data တွေကိုသင့်ရဲ့ {profileTitle} အတွက်ကြည့်ရှုနိုင်ပါသည်",
  "centerPassport": "ဘောင်အတွင်းရေးစင်တာနိုင်ငံကူးလက်မှတ်ဓာတ်ပုံကိုစာမျက်နှာ",
  "drawYourOldPassword": "အဟောင်းပုံစံကိုခပ်",
  "unlockDevice": "ဆက်လက်ဆောင်ရွက်ရန်သင့် device ကို unlock",
  "noNetwork": "အဘယ်သူမျှမ network ကို",
  "correctGesture": "မှန်ကန်သောပုံစံကိုရှာဖွေတွေ့ရှိ",
  "holdPhoneToPassportBackCover": "သင့်ရဲ့နိုင်ငံကူးလက်မှတ်၏အဖုံးအတွင်းမှနောက်ကျောဆန့်ကျင်သင့်ရဲ့ဖုန်း၏နောက်ကျောကိုကိုင်ထားပါ။",
  "holdPhoneToPassport": "သင့်ရဲ့နိုင်ငံကူးလက်မှတ်၏ရှေ့မျက်နှာဖုံးဆန့်ကျင်သင့်ရဲ့ဖုန်း၏နောက်ကျော Hold",
  "searchSomething": "ရှာရန် {1}",
  "nothingChanged": "ဘာမှမပြောင်းလဲဘူး",
  "pleaseCorrectTheErrors": "ပုံစံမှန်ကန်သောအမှားစိတ်တော်",
  "enablePassword": "Password ကို Enable",
  "submittingForm": "တင်ပြသူ {1}",
  "resetRequired": "လိုအပ်ပါသည် Reset",
  "pleaseClickOnAddButton": "'' {1} 'add ဖို့အောက်က' + 'ကို click ပေးပါ",
  "sandboxDescription": "အဆိုပါ Sandbox ခုနှစ်, simulated ဝန်ဆောင်မှုပေးနှင့်အတူ app ကိုမည်သို့အသုံးပြုရမည်ကိုလေ့လာပါ။",
  "areYouSureAboutWipe": "ဤလုပ်ဆောင်ချက်သည်နောက်ကြောင်းပြန်မလှည်ဖြစ်ပါတယ်။ သင်တို့ရှိသမျှသည်သင်၏ data နဲ့ private keys တွေကိုဆုံးရှုံးပါလိမ့်မယ်။ သငျသညျဆက်လက်ဆောင်ရွက်လိုသောသေချာလား?",
  "cancelItem": "သင် {1} ကိုပယ်ဖျက်ဖို့အကြောင်းရှိပါသည်။ အတည်ပြုပေးရန် OK ကိုထိပုတ်ပါ ကျေးဇူးပြု.",
  "updateAppTitle": "ရရှိနိုင်သော App ကို Update ကို",
  "acceptingTermsAndConditions": "OK ကိုနှိပ်ခြင်းဖြင့်, သင်သည်စည်းကမ်းသတ်မှတ်ချက်များကိုလက်ခံ",
  "youAreTheRM": "သငျသညျဤလျှောက်လွှာကိုများအတွက်ဆက်ဆံရေး Manager ကိုဖြစ်ကြသည်",
  "customerWaiting": "{1} ထိုချက်တင်ဝင်ကြ၏ထားပါတယ်",
  "reviewScannedProperties": "အောက်က data တွေကိုပြန်လည်သုံးသပ်နှင့်ပြင်ပေးပါ",
  "listOfProducts": "ထုတ်ကုန်များစာရင်း",
  "storageCorrupted": "သင့် browser သိုလှောင်မှုဖေါပြီးပါပြီ! app ကိုဖွင့်ဝိသေသလက္ခဏာများနှင့်သိုလှောင်မှုကို reset OK ကိုနှိပ်ပါ။",
  "documentExpiredMessage": "ခိုင်လုံသောစာရွက်စာတမ်းစကင်ဖတ်စစ်ဆေးပေးပါ",
  "iproovFailedTitle": "သည်းခံပါ! တစ်ခုခုမှားသွားတယ်",
  "iproovErrorMessage": "နည်းနည်းစောင့်ထပ်ကြိုးစားပါ",
  "formListErrorDescription": "ဖောက်သည်တစ်ဦးလျှောက်လွှာစတင်တစ်ချိန်ကပုံစံများကိုမေတ္တာရပ်ခံရနိုင်",
  "testProviders": "sandbox",
  "contactUs": "ကြှနျုပျတို့ကိုဆကျသှယျရနျ",
  "updateNow": "အခုတော့ကိုအပ်ဒိတ်လုပ်",
  "trustedProviders": "အသိမှတ်ပြုပေးသူများ",
  "viewTerms": "စည်းကမ်းသတ်မှတ်ချက်များကိုကြည့်ရှုရန် ကျေးဇူးပြု.",
  "shareContext": "ဝေမျှမယ် {1}",
  "nothingToShare": "ဝေမျှဖို့ဘာမျှမ",
  "creationDate": "နေ့စွဲ created",
  "createNext": "အခြားပုံစံ \"{1}\" ဖြည့်စွက်",
  "incompatibleVersion": "ကြောင့်မကြာသေးမီနောက်ပြန်မကိုက်ညီမှုများအတွက်အပြောင်းအလဲများမှ, ဒီ update ကို app ကိုတစ်ခက်မှပြန်လည်စတင်လိုအပ်သည်။ app ကိုဖွင့်ဝိသေသလက္ခဏာများနှင့်သိုလှောင်မှုကို reset OK ကိုနှိပ်ပါ။",
  "help": "ကူညီပါ",
  "later": "နောက်ပိုင်းတွင်",
  "learnMoreServerIsDown": "သူတို့အွန်လိုင်းလာတဲ့အခါသင်ရေးလိုက်မဆိုမက်ဆေ့ခ်ျကိုအလိုအလျောက် {1} ထံသို့စလှေတျပါလိမ့်မည်။",
  "importing": "သွင်းယူ",
  "importDataPrompt": "သင့်ထံမှသင့်ရဲ့ဒေတာကိုတင်သွင်းဖို့အကြောင်းရှိပါတယ်",
  "generatingKeys": "သင့်ရဲ့ private keys တွေကိုထုတ်လုပ်",
  "messageWaitingFrom": "သင် {1} ကနေအသစ်တခုသတင်းစကားများ",
  "centerID": "ဘောင်အတွင်းရေးစင်တာ ID ကို",
  "approveApplicationFor": "{1} များအတွက်လျှောက်လွှာကိုအတည်ပြု",
  "loadingResources": "တင်အရင်းအမြစ်များကို",
  "documentExpiredTitle": "စာရွက်စာတမ်းကုန်ဆုံး",
  "areYouSureYouWantToServeThisCustomer": "သင်သည်ဤဖောက်သည်အစေခံချင်သင်သေချာပါသလား?",
  "receiveNotifications?": "သငျသညျအသိပေးချက်များကိုလက်ခံရရှိရန်လိုပါသလား",
  "thisValueIsInvalidPlaceholder": "ဒီတန်ဖိုးကိုဘာဖြစ်လို့လဲဆိုတော့မမှန်ကန် ...",
  "updateAppMessage": "ယခုဒိတ်လုပ်ပါ, ဒါမှမဟုတ်ငါနောက်မှသတိပေးရကြမည်လော",
  "multientryToShare": "ဝေမျှဖို့ {1} စာရွက်စာတမ်းများရှိပါတယ်",
  "youAreAboutToShare": "သင်မျှဝေအကြောင်းကိုများမှာ\n '' {1} '\n စာရွက်စာတမ်းများ",
  "denyApplication": "လျှောက်လွှာကိုငြင်းပယ်",
  "importingData": "{2} ကနေ {1} စာရွက်စာတမ်းများတင်သွင်းခြင်း",
  "retryScanning": "တစ် {1} ကြောင့်ခဲ့သလား ငါမပြောနိုင်ဘူး။ ထပ်ကြိုးစားပါ?\n\nအကောင်းဆုံးရလဒ်များကိုအဘို့, တောက်ပရှောင်ရှား, ရှုခင်း mode ကိုအသုံးပြုခြင်းနှင့်ပြသသည် frame အတွင်းစာရွက်စာတမ်းနေရာချရန်သေချာစေပါ။",
  "approveApplication": "လျှောက်လွှာကိုအတည်ပြု",
  "createNew": "ပုံစံ \"{1}\" ဖြည့်စွက်",
  "restartingApp": "အဆိုပါ application ကိုခဏပြန်လည်စတင်လိမ့်မည်",
  "invalidDocument": "မမှန်ကန်တဲ့စာရွက်စာတမ်း",
  "areYouSureYouWantToConfirmAllItems": "အားလုံး {1} ကိုအတည်ပြုရန် OK ကိုထိပုတ်ပါ, ဒါမှမဟုတ်သုံးသပ်ဆက်လက် Cancel",
  "sendEditRequestPrompt": "{1} မှပြင်ဆင်ရန်တောင်းဆိုမှုကိုပို့မလား?",
  "continue": "ဆက်လက်",
  "yes": "ဟုတ်ကဲ့",
  "iproovFailedMessage": "ထပ်ကြိုးစားပါ။ အကောင်းဆုံးရလဒ်များကိုအဘို့, အရောင်တောက်နေစဉ်အတွင်းဘဲဥပုံထဲမှာဗဟိုပြုသင်၏မျက်နှာကိုစောင့်ရှောက်လော့။",
  "iproovErrorTitle": "သည်းခံပါ! တစ်ခုခုမှားသွားတယ်",
  "submittingModifiedForm": "မွမ်းမံမှု {1}",
  "invalidPattern": "မှားယွင်းတဲ့ပုံစံ",
  "pleaseRestartTIM": "Tim ပြန်လည်စတင်ရန် ကျေးဇူးပြု.",
  "changePassword": "စကားဝှက်ကိုပြောင်းရန်",
  "shareChangesWith": "အတူဝေမျှမယ်အပြောင်းအလဲများ",
  "pleaseDrawPassword": "သင့်ရဲ့ပုံစံကိုခပ်",
  "learnMoreDescriptionTo": "သင်ဆဲသင့်ရဲ့ device ကိုချိတ်ဆက်မဟုတ်ပါဘူးသော်လည်းအော့ဖ်လိုင်းဖြင့် Mode တွင်မက်ဆေ့ခ်ျကိုရေးနိုင်ပါတယ်။ သငျသညျပြန်လည်ချိတ်ဆက်တဲ့အခါမှာအားလုံးသင့်ရဲ့မက်ဆေ့ခ်ျကိုအလိုအလျောက် {1} ထံသို့စလှေတျပါလိမ့်မည်။",
  "drawYourPassword": "သင့်ရဲ့ပုံစံကိုခပ်",
  "documentNotScanning": "အိုး .. တစ်ခုခုတော့မှားနေပြီ!",
  "noScanningOnAndroid": "Android ပေါ်မှာစာရွက်စာတမ်းစကင်ဖတ်စစ်ဆေးဖို့မကြာခင်လာသေး၏။",
  "youReviewed": "သငျသညျ {2} ပစ္စည်းများထဲက {1} ပြန်လည်သုံးသပ်",
  "errorNotification": "မှားယွင်းနေသည်အကြောင်းကြားစာပြင်ပေးဖို့ဖောက်သည်ပို့လိုက်ပါပြီ",
  "downloadingUpdate": "တစ်ခု update ကိုဒေါင်းလုဒ်လုပ်ခြင်း ...",
  "drawYourPasswordAgain": "နောက်တဖန်သင့်ရဲ့ပုံစံကိုခပ်",
  "search": "ရှာဖှေ",
  "learnMore": "ပိုမိုသိရှိရန်",
  "wrongPattern": "မှားယွင်းတဲ့ပုံစံ",
  "enterCurrentPassword": "သင့်လက်ရှိစကားဝှက်ကိုရိုက်ထည့်ပါ",
  "textPasswordLimitations": "10+ ဇာတ်ကောင်, အနည်းဆုံးစာလုံးကြီး, အသေးစာအရေအတွက်နှင့်အထူးဇာတ်ကောင်ရှိရမည်",
  "setPassword": "လုံခြုံတဲ့စကားဝှက်ကိုရှေးခယျြပါ",
  "thisFieldIsRequired": "ဤစာကွက်လပ်မှာဖြည့်ရန်လိုအပ်ပါသည်",
  "receivedProduct": "{1} ရရှိထားသည့်",
  "setNewPassword": "သစ်တစ်ခု password ကိုရှေးခယျြပါ",
  "useTouchIdAndGesturePassword": "Touch ကို ID နှင့်လက်ဟန် Enable",
  "sharedForm": "shared {1} {2} ကနေ",
  "asVerifiedBy": "{1} ကစိစစ်အဖြစ်",
  "willBeAvailable": "ဤလုပ်ဆောင်ချက်သည်မကြာမီရရှိနိုင်ပါလိမ့်မည်",
  "receivedVerification": "{1} များအတွက်ရရှိထားသည့်စိစစ်အတည်ပြု",
  "deviceDoesNotHaveMyKeys": "ရရှိထားသည့်ဝိသေသလက္ခဏာငါ၏အသော့ရှိသည်ပါဘူး",
  "pairDevices": "Pair ကို devices များ",
  "turnTouchIdOn": "ထိတွေ့ ID ကိုဖွင့်လိုက်ပါ",
  "receivedForm": "{1} ရရှိထားသည့်",
  "applyForProduct": "ထုတ်ကုန်များအတွက် Apply",
  "cancel": "Cancel",
  "learnMoreDescription": "သင်ဆဲသင့်ရဲ့ device ကိုချိတ်ဆက်မဟုတ်ပါဘူးသော်လည်းအော့ဖ်လိုင်းဖြင့် Mode တွင်မက်ဆေ့ခ်ျကိုရေးနိုင်ပါတယ်။ သငျသညျပြန်လည်ချိတ်ဆက်တဲ့အခါမှာအားလုံးသင့်ရဲ့မက်ဆေ့ခ်ျကိုအလိုအလျောက်လှေတျတျောမူပါလိမ့်မည်။",
  "tooManyPasswordAttempts": "သိပ်အများကြီးကြိုးစားမှုမအောင်မြင်ပါ ဤပုံစံကိုပိတ်ထားပါသည်။",
  "inProgress": "သင့်တောင်းဆိုချက်တိုးတက်မှုအတွက်ဖြစ်ပါသည်",
  "correctPassword": "မော, သင်ကိုအောကျမေ့!",
  "turnBothOn": "နှစ်ဦးစလုံးကိုဖွင့်မည်",
  "authenticationFailed": "authentication ပျက်ကွက်",
  "youShared": "သင် {1} ကနေ shared",
  "asSentTo": "{1} မှစလှေတျတျောအဖြစ်",
  "forgetMe": "ငါ့ကိုမေ့လိုက်ပါ",
  "iNeed": "လိုအပ်တယ်...",
  "addServerUrl": "ဆာဗာက url ကို Add",
  "youAreForgotten": "သငျသညျကိုအောင်မြင်စွာမေ့လျော့ခဲ့ကြရတယ်",
  "passwordLimitations": "pattern 5+ အချက်များရှိရမည်",
  "termsAndConditions": "စည်းကမ်းနှင့်သတ်မှတ်ချက်များ။",
  "offlineMode": "အော့ဖ်လိုင်း mode ကို",
  "pairingRequestWasProcesseed": "တွဲဖက်မှုတောင်းဆိုချက်ကို processeed ခဲ့သည်",
  "formChooser": "form ကိုစာရင်း",
  "details": "အသေးစိတ်",
  "nl": "ဒတျချြ",
  "enterPassword": "သင့်ရဲ့စကားဝှက်ကိုရိုက်ထည့်ပါ",
  "enterYourName": "သင်၏အမည်ကိုရိုက်ထည့်ပါ",
  "testForgetMe": "ဒီ provider ကအားလုံးကိုဆက်သွယ်ရေး reset ရန်စမ်းသပ်မှုယန္တရားဖြစ်ပါသည်",
  "pairingRequest": "တူ့တောင်းဆိုခြင်း",
  "drawYourNewPasswordAgain": "နောက်တဖန်သစ်ကိုပုံစံဆွဲပါ",
  "en": "အင်္ဂလိပ်",
  "temporarilyLocked": "သင့်ရဲ့ကာကွယ်စောင့်ရှောက်ဘို့, ဤလျှောက်လွှာကိုယာယီ {1} အဘို့အသော့ခတ်ထားသည်",
  "changeGesturePassword": "ပြောင်းလဲမှုကိုလက်ဟန်ခြေဟန် password ကို",
  "hello": "{1} မင်္ဂလာပါ!",
  "confirmForgetMe": "သငျသညျ '' {1} '' သင်သည်မေ့လျော့ဖို့လိုတာသေချာ",
  "fromMyData": "'' ငါ့အဖို့ဒေတာ '' ကနေ",
  "bothOn": "နှစ်ဦးစလုံးအပေါ်များမှာ",
  "formListError": "မရရှိနိုင်ပါ",
  "sharedContext": "shared ဆက်စပ်တဲ့အကြောင်းအရာတွေကို",
  "touchIdOn": "Touch ကို ID ကို ON ဖြစ်ပါသည်",
  "formRequest": "{1} ဘို့တောင်းဆိုခြင်း",
  "ok": "ရလား",
  "contextsFor": "အဘို့အအခင်းအကျင်း",
  "invalidPairingRequest": "မှားနေသောတူ့တောင်းဆိုခြင်း",
  "turnPasswordOn": "လက်ဟန် Password ကိုဖွင့်မည်",
  "passwordsDontMatch": "Passwords များကိုမတိုက်ဆိုင်ကြဘူး",
  "validationErrors": "ပျက်ကွက် validation ကိုလယ်ကွင်းပြင်ပေးပါ",
  "verificationBy": "{1} အားဖြင့်စိစစ်အတည်ပြု",
  "fillRequiredFields": "အားလုံးလိုအပ်သောကွက်လပ်များကိုဖြည့်စွက်ပေးပါ",
  "independentBlockchainViewer": "လွတ်လပ်သောပိတ်ပင်တားဆီးမှုကွင်းဆက်ကြည့်ရှုသူ",
  "denyApplicationFor": "{1} များအတွက်လျှောက်လွှာကိုငြင်းပယ်",
  "initializingEngine": "စတင်လုပ်ဆောင်အင်ဂျင်ကို",
  "noAccessToServer": "Server ကိုအသုံးမပြုနိုင်တော့မဟုတ်ပါဘူး။ နောက်ပိုင်းမှာကြိုးစားပါ။",
  "irrefutableProofs": "Irrefutable သက်သေ",
  "shareAllPastAndFutureMessages": "ရွေးချယ်ထားသောပါတီများနှင့်အတူဤအခြေအနေတွင်အားလုံးအတိတ်နှင့်အနာဂတ်မက်ဆေ့ခ်ျကိုမျှဝေရန်",
  "backTo": "နောက်ကျော {1} မှ",
  "acceptTermsAndConditions": "ကြည့်ရန်စည်းကမ်းသတ်မှတ်ချက်များ",
  "backToResults": "နောက်ကျောရလဒ်များကိုမှ",
  "neverMissAMessage": "သတင်းစကားတစ်ခုလက်လွတ်ဘယ်တော့မှမ",
  "importYourData": "သင့်ရဲ့ဒေတာများကိုတင်သွင်းရန်",
  "hideResource": "ဖျောက် {1}",
  "overviewOfApplications": "Applications ကို၏ခြုံငုံသုံးသပ်ချက်",
  "submitting": "တင်ပို့",
  "nameUnknown": "အမည်မသိအမည်",
  "providerIsOffline": "{1} အော့ဖ်လိုင်းဖြစ်ပါသည်",
  "fieldErrorMessagePrompt": "အဘယ်အရာကိုဤနယ်ပယ်တွင်မှားလား",
  "centerLicence": "ဘောင်အတွင်းရေးစင်တာလိုင်စင်",
  "dataSecurity": "ဒေတာကိုလုံခြုံရေး",
  "scanningFailedTryAgain": "scanning မအောင်မြင်ဖြစ်ခဲ့သည်။ သငျသညျ ကျေးဇူးပြု. ထပ်ကြိုးစားရနိုင်မလား?",
  "enableCameraAccess": "{APPNAME} လက်ရှိကင်မရာကိုအသုံးပြုရန်ခွင့်ပြုချက်မရှိပါ။ access ကိုပေးသနားတော်မူရန်, Settings ကိုရွေးပါနှင့်ကင်မရာကို enable လုပ်ထားတဲ့သေချာပါစေ။",
  "ukLicenseUnsupported": "ဗြိတိန်ယာဉ်မောင်းလိုင်စင်ကိုစကင်ဖတ်စစ်ဆေးဖို့ဤအချိန်တွင်ပံ့ပိုးပေးမထားပါ",
  "sponsoredBy": "တို့ကကမကထပြု",
  "youReviewedAll": "သင် {1} အားလုံးပြန်လည်သုံးသပ်",
  "loadingModels": "တင်မော်ဒယ်များ",
  "pleaseTapOnMenu": "အနီရောင်ခလုတ်ကိုထိပုတ်ပါ ကျေးဇူးပြု. နှင့်",
  "unreadMessages": "သငျသညျမဖတ်ရသေးသောမက်ဆေ့ခ်ျများ",
  "no": "အဘယ်သူမျှမ",
  "next": "နောက်တစ်ခု",
  "invalidDeepLink": "သင်တစ်ဦးသည်မမှန်ကန်ပါ link ကိုနှိပ်လိုက်တူ!",
  "Go!": "Go!",
  "pleaseSign": "မီးခိုးရောင်အကွက်ထဲမှာလက်မှတ်ထိုးပေးပါ",
  "Application submitted!": "လျှောက်လွှာတင်သွင်း!",
  "goodNews": "သတင်းကောင်း! သငျသညျပြီးသား {1} ရှိသည်။ ကိုထိပုတ်ပါအောက်က icon ကိုဝေမျှဖို့",
  "Give me a moment...": "ငါ့ကိုခဏ Give ...",
  "createManualMatchCheck": "လက်စွဲပွဲစဉ်စစ်ဆေးမှုများ Create",
  "Our products have changed": "ကျွန်ုပ်တို့၏ထုတ်ကုန်ပြောင်းလဲပြီ",
  "Sending": "ပေးပို့ခြင်း",
  "loading": "Loading ...",
  "Please scan your": "သင့်ရဲ့စကင်ဖတ်စစ်ဆေးပေးပါ",
  "Please take a selfie to prove this is your document. Center your face.": "ဒီသင်၏စာတမ်းကိုဖြစ်ပါတယ်သက်သေပြမယ့် selfie ယူပေးပါ။ သင်၏မျက်နှာကိုအဓိကထား။",
  "Please click to scan your": "သင့်ရဲ့ scan လုပ်ဖို့ကိုနှိပ်ပါ ကျေးဇူးပြု.",
  "usePhoto": "ဓာတ်ပုံကိုသုံးပါ",
  "Submit": "Submit",
  "Before we start you'll need a valid passport, identity card or driving license": "ကျနော်တို့စတင်ခင်မှာသင်တစ်ဦးတရားဝင်နိုင်ငံကူးလက်မှတ်, ဝိသေသလက္ခဏာကဒ်သို့မဟုတ်ယာဉ်မောင်းလိုင်စင်မလိုအပ်ပါလိမ့်မယ်",
  "Next": "နောက်တစ်ခု",
  "exploreData": "ဒေတာများကို Explore",
  "Applications": "လျှောက်လွှာများ",
  "Get set for friendliness?": "ဖော်ရွေမဘို့ရာခန့် Get?",
  "Done": "ပြီးပြီ",
  "retake": "re-ယူ",
  "Take a quick tour of chat bot?": "ချက်တင် bot တစ်ကောင်တစ်ဦးအမြန်ခရီးစဉ်ကိုယူ?",
  "getStarted": "စတင်ရန်",
  "Choose Apply for Product from the menu": "မီနူးကနေကုန်ပစ္စည်းအဘို့အ Apply ကိုရွေးချယ်ပါ",
  "Ready?": "အသင့်ဖြစ်ပြီလား?",
  "Finally, you will be in control of your own private information!": "နောက်ဆုံးအနေနဲ့, သင်သည်သင်၏ကိုယ်ပိုင်ပုဂ္ဂလိကအချက်အလက်များ၏ထိန်းချုပ်မှုအတွက်ဖြစ်လိမ့်မည်!",
  "Cancel": "Cancel",
  "See our list of products": "ထုတ်ကုန်များ၏ကျွန်တော်တို့ရဲ့စာရင်းကိုကြည့်ပါ",
  "checkIfMatch": "ပွဲစဉ်လျှင် Check",
  "Get set": "set Get",
  "Clear": "ရှင်းလင်းသော",
  "Seals": "တံဆိပ်",
  "Please tap here and sign": "ဤနေရာတွင်ကိုထိပုတ်ပါနဲ့နိမိတ်လက္ခဏာကို ကျေးဇူးပြု.",
  "ID document": "ID ကိုစာရွက်စာတမ်း",
  "Skip": "ကြိုးခုန်",
  "Deny": "ငြင်းပယ်",
  "Go friendliness!": "ဖော်ရွေ Go!",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "ကျနော်တို့သင်ချက်တင်အတွက်မေးခွန်းများမေးပါလိမ့်မယ်နှငျ့သငျရိုးရှင်းစွာပုံစံများကိုဖြည့်ပါသို့မဟုတ်တောင်းဆိုမှုများကိုလိုက်နာ",
  "Ready for friendliness?": "ဖော်ရွေများအတွက်အသင့်ဖြစ်ပြီလား?",
  "Sanctions Checks": "ဒဏ်ခတ်အရေးယူမှုစစ်ဆေးပေးပါသည်",
  "Thank you. Now take a '": "ကျေးဇူးတင်ပါတယ်။ အခုတော့တစ်ဦး 'ယူ",
  "bookmarks": "bookmarks",
  "Verifications": "စိစစ်မှုများ",
  "Approve": "အတည်ပြု",
  "goodNewsFew": "သတင်းကောင်း! သငျသညျပြီးသားအတော်လေးအနည်းငယ်ရှိသည်။ အောက်တွင်ဖော်ပြထားသောထိပုတ်ပါအိုင်ကွန် share ရန်။",
  "Please fill out the form": "ပုံစံဖြည့်စွက်ပေးပါ",
  "Corporation Exists Checks": "ကော်ပိုရေးရှင်းစစ်ဆေးပေးပါသည်တည်ရှိ",
  "' photo of yourself that I can match against your ID document": "ငါသည်သင်တို့၏ ID ကိုစာရွက်စာတမ်းဆန့်ကျင်ကိုက်ညီနိုင်မသင်ကိုယ်တိုင်၏ '' ဓာတျပုံ",
  "reviewData": "ဆန်းစစ်ခြင်းဒေတာ",
  "Photo": "ဓာတ်ပုံ",
  "wrongDocumentTypePleaseTryAgain": "မှားယွင်းနေစာရွက်စာတမ်းအမျိုးအစား။ ထပ်ကြိုးစားပါ",
  "logSentToDevTeam": "အဆိုပါသစ်လုံးအဆိုပါ Tradle ဆော့ဖ်ဝဲရေးအဖွဲ့ကိုစေလွှတ်ခဲ့သည်",
  "enterPasswordOrWipeOutTheAppData": "စကားဝှက်ကိုရိုက်ထည့်ပါသို့မဟုတ် app ကိုဒေတာသုတ်",
  "doYouWantToContinue": "သငျသညျကအကူးအပြောင်းနှင့်ထိုအရပ်မှဆက်လက်ချင်ပါသလား",
  "invalidQuery": "သည်းခံပါ, ငါတို့သည်သင်တို့၏ရှာဖွေရေး running မှားယွင်းမှုတစ်ခုထိမှန်။ ကျွန်ုပ်တို့၏ developer များ asap က fix ဖို့ကြိုးစားပါလိမ့်မယ်။",
  "validatingDataClaim": "ဒေတာများကိုတင်သွင်းခြင်း",
  "resetApp": "App ကို Reset",
  "inProcess": "လုပ်ဆောင်နေသည်...",
  "wipeTheAppData": "app ကိုဒေတာ Wipe",
  "supportedQrCodes": "ထောကျပံ့ဖို့အတွက် QR codes တွေကို:\n1) ချက်တင်ရုပ်သံလိုင်း add\n2) သွင်းကုန်ဒေတာ",
  "failedToSendLog": "မှတ်တမ်းပေးပို့ရန်မအောင်မြင်ခဲ့ပါ",
  "pleaseChooseDT": "စာရွက်စာတမ်းအမျိုးအစားပထမဦးဆုံးကိုရွေးပါ ကျေးဇူးပြု.",
  "invalidQR": "မှားနေသော QR ကုဒ်ကို",
  "newCustomer": "ဖောက်သည်အသစ်",
  "scanYourDocument": "သင့်ရဲ့စာရွက်စာတမ်းစကင်ဖတ်စစ်ဆေးပေးပါ",
  "invalidCountry": "မှားနေသောတိုင်းပြည် scan ဖတ်",
  "debugLogSent": "ဒီဘာဂ် Log in ဝင်ရန် Sent",
  "afterRefresh": "သငျသညျပြတ်တောက်မပါဘဲကျွန်ုပ်တို့၏ဝန်ဆောင်မှုများသုံးစွဲဖို့ရှင်းလင်းနေကြသည်",
  "documentBackSide": "Center ကစာရွက်စာတမ်းပြန်ခြမ်း",
  "areYouSureYouAreDone": "သငျသညျဤသင်ခန်းစာကိုလေ့လာဆွေးနွေးပြီးအောင်ချင်သင်သေချာပါသလား?",
  "startedByAnotherEmployee": "{1} များအတွက်လျှောက်လွှာအခြားဝန်ထမ်းများကစတင်ခဲ့သည်",
  "requestMyData": "ငါ၏အ data ကိုတောင်းခံ",
  "dateInTheFutureError": "{1} အနာဂတျမှာဖြစ်ပါတယ်",
  "networkFailure": "ငါအချို့ကွန်ယက်ကိုကိစ္စများကြုံတွေ့ရတာပါ။ သငျသညျစစျဆေးပြီးတော့ Retry / Cancel ကိုအသာပုတ်နိုင်သလား",
  "reviewScannedPropertiesAndSecondSideSnapshot": "အောက်က data တွေကိုပြန်လည်သုံးသပ်နှင့်စာရွက်စာတမ်းများ၏ {1} ဘက်တစ်လျှပ်တစ်ပြက်ယူ ကျေးဇူးပြု.",
  "noResourcesForCriteria": "အရင်းအမြစ်များကိုဤစံများအတွက်မတွေ့"
}