module.exports = {
  "tooManyPasswordAttempts": "Muitas tentativas falhas! Este formulário foi desativado.",
  "pleaseRestartTIM": "Por favor, reinicie o TiM",
  "forgetMe": "Me esqueça",
  "drawYourNewPasswordAgain": "Desenhe o novo padrão novamente",
  "addAnotherFormOrGetNext": "Adicione outro {1} ou passe para o próximo formulário",
  "done": "Feito",
  "verificationTransactionID": "ID de transação de verificação",
  "noConnectionForNewProduct": "{1}, {appName} requer uma conexão de internet ativa para preencher o aplicativo {2}.",
  "youAreForgotten": "Você foi esquecido com sucesso",
  "formChooser": "Lista de formulários",
  "shareContext": "Compartilhar {1}",
  "homePage": "Casa",
  "asVerifiedBy": "Conforme verificado por {1}",
  "unlockDevice": "desbloqueie o seu dispositivo para continuar",
  "gestureNotRecognized": "Padrão errado",
  "shareOne": "Alternativamente, compartilhe abaixo",
  "setDateValue": "Conjunto",
  "thePropertyWithMinMaxRangeError": "A propriedade com intervalo [min-max] pode ter apenas dois números",
  "details": "Detalhes",
  "cancel": "Cancelar",
  "newProduct": "Novo produto",
  "profile": "Perfil",
  "setNewPassword": "Escolha uma nova senha",
  "pleaseCorrect": "Por favor corrija",
  "dataSecurity": "Segurança de dados",
  "formListError": "Indisponível",
  "search": "Pesquisa",
  "optional": "opcional",
  "shareOneOfMany": "Alternativamente, compartilhe abaixo",
  "yes": "sim",
  "contextsFor": "Contextos para",
  "temporarilyLocked": "Para sua proteção, este aplicativo foi bloqueado temporariamente para {1}",
  "passwordsDontMatch": "Senhas não combinam",
  "iNeed": "Eu preciso...",
  "enterCurrentPassword": "Digite sua senha atual",
  "invalidPropertyValue": "Valor inválido",
  "enablePassword": "Ativar senha",
  "shareMyProduct": "Você pode tocar abaixo para compartilhar {1} com {2}",
  "continue": "Continuar",
  "viewDebugLog": "Visualizar log de depuração",
  "searchSomething": "Pesquisa {1}",
  "fillTheForm": "Por favor, preencha este formulário ** {1} **",
  "nl": "holandês",
  "turnBothOn": "Ligue os dois",
  "drawYourPassword": "Desenhe seu padrão",
  "issuedBy": "Emitido por {1}",
  "verificationBy": "Verificação por {1}",
  "sharedForm": "Compartilhada {1} de {2}",
  "pleaseDrawPassword": "Desenhe seu padrão",
  "switchTouchIdOff": "Alterar ID de toque desativado",
  "shareOneOfMany1": "{1}, este é seu assistente de privacidade pessoal. Vejo que você já teve sua {2} confirmada. Você pode tocar em qualquer item da lista abaixo para compartilhá-los com {3}.",
  "edit": "Editar",
  "acceptTermsAndConditions": "Ver termos e condições",
  "en": "Inglês",
  "receivedProduct": "Recebido {1}",
  "noNetwork": "Sem rede",
  "newProductMsg": "Eu preciso de um {1}.",
  "serverIsUnreachable": "Servidor inacessível",
  "add": "Adicione {1}",
  "termsAndConditions": "Termos e Condições.",
  "verifyPrompt": "Verificar?",
  "error": "Erro",
  "submitLog": "Enviar log",
  "correctPassword": "Aww, você se lembrou!",
  "pairDevices": "Par dispositivos",
  "sharedContext": "Contexto Compartilhado",
  "wrongPattern": "Padrão errado",
  "backToResults": "Voltar aos resultados",
  "willBeAvailable": "Esta funcionalidade estará disponível em breve",
  "newContactRequest": "{1} enviou a sua solicitação de contato",
  "addServerUrl": "Adicionar URL do servidor",
  "hello": "Olá {1}!",
  "enterPassword": "Coloque sua senha",
  "invalidDocument": "documento inválido",
  "importYourData": "Importe seus dados",
  "verifiedByOn": "Verificado por {1} em",
  "fromMyData": "de \"Meus dados\"",
  "downloadingUpdate": "Baixando uma atualização ...",
  "back": "Costas",
  "contactUs": "Contate-Nos",
  "fillTheFormWithAttachments": "Por favor, preencha este formulário ** {1} **",
  "listOfProducts": "Lista de produtos",
  "patternNotMatching": "Os padrões não combinaram.",
  "oops": "Ups",
  "providerIsOffline": "{1} está offline",
  "customerWaiting": "{1} entrou no bate-papo",
  "confirmRevoke": "Peça a {1} para excluir este documento de seus registros?",
  "iproovFailedTitle": "Opa! Algo deu errado",
  "settings": "Configurações",
  "sentTo": "Enviado para {1}",
  "youShared": "Você compartilhou de {1}",
  "touchIdOn": "A ID de toque está ativada",
  "testForgetMe": "Este é um mecanismo de teste para redefinir todas as comunicações com esse provedor",
  "learnMoreServerIsDown": "Todas as mensagens que você escrever serão enviadas automaticamente para {1} quando elas estiverem on-line.",
  "shareChangesWith": "Compartilhar alterações com",
  "fillRequiredFields": "Por favor preencha todos os campos requeridos",
  "takeAPicture": "Por favor, tire uma foto do seu rosto",
  "documentExpiredTitle": "Documento expirado",
  "correctGesture": "Padrão correto detectado",
  "issuedByOn": "Emitido por {1} em",
  "invalidProperty": "{1} inválido",
  "authenticationFailed": "Autenticação falhou",
  "formRequest": "Pedido para {1}",
  "pairingRequest": "Pedido de emparelhamento",
  "nothingChanged": "nada mudou",
  "shareProduct": "Você pode tocar abaixo para compartilhar {1} com {2}",
  "useTouchId": "Ativar ID de toque",
  "tapToRemovePhotos": "Toque para remover fotos",
  "irrefutableProofs": "Provas irrefutáveis",
  "officialAccounts": "Conversas",
  "confirmForgetMe": "Tem certeza de que deseja que '{1}' esqueça você",
  "inProgress": "Sua solicitação está em andamento",
  "shareWith": "Compartilhar {1}",
  "pleaseCorrectTheErrors": "Por favor, corrija o erro no formulário",
  "hideResource": "Esconder {1}",
  "viewTerms": "Por favor veja os Termos e Condições",
  "invalidPattern": "Padrão errado",
  "drawYourNewPassword": "Desenhe um novo padrão",
  "verifierHelp": "Clique no botão \"Concluído\" depois de analisar o formulário. Se alguns campos exigirem correção, verifique-os primeiro e, em seguida, clique no botão 'Concluído'",
  "sponsoredBy": "Patrocinado por",
  "next": "Próximo",
  "submitting": "Submetendo",
  "youShallNotPass": "Você não passará!",
  "somethingWrong": "Algo deu errado",
  "passwordOn": "A senha do gesto está ativada",
  "myDocuments": "Meus documentos",
  "typeMessage": "Digite uma mensagem",
  "drawYourPasswordAgain": "Desenhe seu padrão novamente",
  "ok": "Está bem",
  "addNew": "Adicionar novo {1}",
  "setPassword": "Escolha uma senha segura",
  "theMinValueBiggerThenMaxValue": "O valor min para o intervalo deve ser menor que o valor máximo",
  "showQR": "Meu código QR",
  "drawYourOldPassword": "Desenhe seu antigo padrão",
  "help": "Socorro",
  "later": "Mais tarde",
  "approveApplication": "Aprovar aplicativo",
  "switchTouchIdOn": "Mudar o ID de toque",
  "changePassword": "Mudar senha",
  "submittingModifiedForm": "Modificando {1}",
  "receivedForm": "Recebido {1}",
  "learnMore": "Saber mais",
  "submittingForm": "Enviado {1}",
  "scanQRcode": "Escanear o código QR",
  "asSentTo": "Como enviado para {1}",
  "errorNotification": "Notificação de erro foi enviada ao cliente para corrigir",
  "centerLicence": "Licença do centro no quadro",
  "switchToRepresentative": "Mudar para o modo representativo ainda não está implementado.",
  "passwordLimitations": "O padrão deve ter mais de 5 pontos",
  "enterYourName": "Digite seu nome",
  "changeGesturePassword": "Alterar senha de gesto",
  "verifiedBy": "Verificado por {1}",
  "turnTouchIdOn": "Ativar o ID de toque",
  "resetRequired": "Reset Necessário",
  "iproovErrorTitle": "Opa! Algo deu errado",
  "thisFieldIsRequired": "Este campo é obrigatório",
  "noConnection": "{appName} requer uma conexão de internet ativa que você não tem no momento",
  "bothOn": "Ambos estão ligados",
  "backTo": "De volta para {1}",
  "shareOne1": "{1}, este é seu assistente de privacidade pessoal. Vejo que você já teve sua {2} confirmada. Você pode tocar abaixo para compartilhá-lo com {3}.",
  "centerPassport": "Página de foto do centro de passaporte no quadro",
  "importData": "Datas de importação",
  "restartingApp": "O aplicativo será reiniciado momentaneamente",
  "installingUpdate": "Instalando atualização",
  "no": "Não",
  "restartApp": "Reinicie o aplicativo",
  "unreadMessages": "Você tem mensagens não lidas",
  "sendEditRequestPrompt": "Enviar solicitação de edição para {1}?",
  "deviceDoesNotHaveMyKeys": "A identidade recebida não tem minhas chaves",
  "cancelHideResource": "Cancelar esconder {1}",
  "enablePasscodeFirst": "Parece que você não tem uma senha de dispositivo ativada. Sem ele, este aplicativo não pode proteger seus dados! Por favor habilite-o antes de pressionar OK",
  "sourcesBy": "Fontes por {1}",
  "nameUnknown": "nome desconhecido",
  "sentToOn": "Enviado para {1} em",
  "denyApplication": "Negar aplicativo",
  "overviewOfApplications": "Visão geral de aplicativos",
  "testProviders": "Caixa de areia",
  "useGesturePassword": "Ativar senha do gesto",
  "pairingRequestWasProcesseed": "O pedido de emparelhamento foi processado",
  "fieldErrorMessagePrompt": "O que há de errado com esse campo?",
  "creationDate": "Data Criada",
  "cameraAccess": "Acesso à câmera",
  "receivedVerification": "Confirmação recebida para {1}",
  "loadingModels": "carregando modelos",
  "centerID": "ID do centro no quadro",
  "turnPasswordOn": "Ativar senha do gesto",
  "useTouchIdAndGesturePassword": "Ativar ID de toque e gesto",
  "thisValueIsInvalidPlaceholder": "este valor é inválido porque ...",
  "noAccessToServer": "Servidor não está acessível. Tente depois.",
  "trustedProviders": "Provedores confiáveis",
  "nothingToShare": "Nada para compartilhar",
  "generatingKeys": "gerando suas chaves privadas",
  "loadingResources": "carregando recursos",
  "importing": "Importando",
  "updateNow": "Atualizar agora",
  "areYouSureYouWantToServeThisCustomer": "Tem certeza de que deseja atender esse cliente?",
  "denyApplicationFor": "Negar aplicativo para {1}",
  "updateAppTitle": "Atualização do aplicativo disponível",
  "createNew": "Preencha o formulário \"{1}\"",
  "applyForProduct": "Candidate-se a um produto",
  "approveApplicationFor": "Aprovar aplicativo para {1}",
  "pleaseCorrectFields": "Corrija os seguintes campos: {1}",
  "digitalWealthPassport": "Passaporte de riqueza digital",
  "initializingEngine": "inicializando o mecanismo",
  "acceptingTermsAndConditions": "Ao pressionar OK, você aceita os Termos e Condições",
  "iproovErrorMessage": "Por favor, espere um pouco e tente novamente",
  "unknownQRCodeFormat": "Formato de código QR não reconhecido",
  "scanningFailedTryAgain": "A digitalização não foi bem sucedida. Você poderia por favor tentar de novo?",
  "formListErrorDescription": "Formulários podem ser solicitados assim que o cliente inicia um aplicativo",
  "areYouSureYouWantToDelete": "Tem certeza de que deseja ocultar {1}?",
  "ukLicenseUnsupported": "A verificação da carteira de motorista do Reino Unido não é suportada no momento",
  "holdPhoneToPassport": "Segure a parte de trás do seu telefone contra a capa do seu passaporte",
  "invalidDeepLink": "Parece que você clicou em um link inválido!",
  "confirmedMyData": "Todos os dados importados podem ser visualizados no seu {profileTitle}",
  "validationErrors": "Por favor, corrija os campos de validação falhados",
  "neverMissAMessage": "Nunca perca uma mensagem",
  "documentExpiredMessage": "Por favor, digitalize um documento válido",
  "youAreAboutToShare": "Você está prestes a compartilhar\n '{1}'\n documentos",
  "pleaseTapOnMenu": "Por favor, toque no botão vermelho e",
  "learnMoreDescription": "Você ainda pode escrever mensagens no modo off-line, mesmo que o dispositivo não esteja conectado. Quando você se reconectar, todas as suas mensagens serão enviadas automaticamente.",
  "importDataPrompt": "Você está prestes a importar seus dados de",
  "invalidPairingRequest": "Pedido de Emparelhamento Inválido",
  "multientryToShare": "Existem {1} documentos para compartilhar",
  "cancelItem": "Você está prestes a cancelar {1}. Por favor, toque em OK para confirmar",
  "documentNotScanning": "Oops, algo deu errado!",
  "youReviewedAll": "Você analisou todos {1}",
  "noConnectionWillProcessLater": "{appName} exige uma conexão de internet ativa que você não tem no momento. A solicitação será processada quando uma conexão for estabelecida",
  "textPasswordLimitations": "Deve ter mais de 10 caracteres, pelo menos uma letra maiúscula, letra minúscula, número e caractere especial",
  "somethingWrongSubmitLog": "Algo parece ter dado errado. Envie o registro de depuração para a equipe de desenvolvedores do {appName}",
  "reviewScannedProperties": "Por favor, revise e corrija os dados abaixo",
  "learnMoreDescriptionTo": "Você ainda pode escrever mensagens no modo off-line, mesmo que o dispositivo não esteja conectado. Quando você reconectar todas as suas mensagens, elas serão enviadas automaticamente para {1}.",
  "receiveNotifications?": "Você gostaria de receber notificações?",
  "areYouSureAboutNextForm": "Tem certeza de que terminou com {1}?",
  "sharedWith": "Contexto {1} compartilhado com {2}",
  "shareAllPastAndFutureMessages": "Compartilhar todas as mensagens passadas e futuras nesse contexto com partes selecionadas",
  "noScanningOnAndroid": "A digitalização de documentos no Android está chegando em breve.",
  "importingData": "Importando documentos {1} de {2}",
  "updateAppMessage": "Atualize agora ou devo lembrá-lo mais tarde?",
  "storageCorrupted": "o armazenamento do seu navegador foi corrompido! Pressione OK para redefinir a identidade e o armazenamento do aplicativo.",
  "areYouSureAboutWipe": "Esta ação é irreversível. Você perderá todos os seus dados e chaves privadas. Tem certeza de que deseja continuar?",
  "messageWaitingFrom": "Você tem uma nova mensagem de {1}",
  "youAreTheRM": "Você é o gerente de relacionamento deste aplicativo",
  "areYouSureYouWantToConfirmAllItems": "Toque em OK para confirmar todos os {1} ou Cancelar para continuar a rever",
  "noConnectionForPL": "{appName} requer uma conexão de internet ativa para solicitar uma lista de produtos de {1} que você não tem no momento",
  "confirmAllItems": "Toque em OK para confirmar todos ou em Cancelar para continuar a rever",
  "holdPhoneToPassportBackCover": "Segure a parte de trás do seu telefone contra a parte de trás do seu passaporte.",
  "incompatibleVersion": "Devido a recentes alterações incompatíveis com versões anteriores, esta atualização requer uma reinicialização forçada do aplicativo. Pressione OK para redefinir a identidade e o armazenamento do aplicativo.",
  "createNext": "Preencha outro formulário \"{1}\"",
  "pleaseClickOnAddButton": "Por favor, clique em '+' abaixo para adicionar '{1}'",
  "enableCameraAccess": "{appName} atualmente não tem permissão para usar a câmera. Para conceder acesso, escolha Configurações e verifique se a câmera está ativada.",
  "sandboxDescription": "No Sandbox, aprenda a usar o aplicativo com provedores de serviços simulados.",
  "iproovFailedMessage": "Por favor, tente novamente. Para obter melhores resultados, mantenha seu rosto centralizado no oval durante os flashes de cor.",
  "youReviewed": "Você analisou {1} de {2} itens",
  "retryScanning": "Isso foi um {1}? Eu não sabia dizer. Por favor, tente novamente?\n\nPara obter melhores resultados, use o modo paisagem, evite ofuscamento e certifique-se de posicionar o documento dentro do quadro exibido.",
  "offlineMode": "Moda off-line",
  "independentBlockchainViewer": "Visualizador independente de blockchain",
  "bookmarks": "Favoritos",
  "Go!": "Ir!",
  "Clear": "Claro",
  "Cancel": "Cancelar",
  "Submit": "Enviar",
  "loading": "Carregando...",
  "getStarted": "iniciar",
  "retake": "Retomar",
  "Skip": "Pular",
  "Deny": "Negar",
  "Ready?": "Pronto?",
  "Please fill out the form": "Por favor, preencha o formulário",
  "Application submitted!": "Aplicação submetida!",
  "Next": "Próximo",
  "checkIfMatch": "Verifique se o jogo",
  "Get set": "Prepare-se",
  "Done": "Feito",
  "Give me a moment...": "Me dê um momento...",
  "Approve": "Aprovar",
  "exploreData": "Explorar dados",
  "Seals": "Selos",
  "Our products have changed": "Nossos produtos mudaram",
  "Applications": "Aplicações",
  "Ready for friendliness?": "Pronto para amizade?",
  "ID document": "Documento de identificação",
  "Please scan your": "Por favor, escaneie seu",
  "Go friendliness!": "Seja simpático!",
  "Verifications": "Verificações",
  "usePhoto": "Use foto",
  "Sending": "Enviando",
  "Thank you. Now take a '": "Obrigado. Agora pegue um '",
  "Please click to scan your": "Por favor, clique para escanear seu",
  "See our list of products": "Veja nossa lista de produtos",
  "Sanctions Checks": "Verificações de Sanções",
  "createManualMatchCheck": "Criar verificação de correspondência manual",
  "Please tap here and sign": "Por favor, toque aqui e assine",
  "Get set for friendliness?": "Prepare-se para a amizade?",
  "Choose Apply for Product from the menu": "Escolha Aplicar para o produto no menu",
  "goodNews": "Boas notícias! Você já tem {1}. Para compartilhar, toque no ícone abaixo",
  "goodNewsFew": "Boas notícias! Você já tem alguns. Para compartilhar o ícone de toque abaixo.",
  "Take a quick tour of chat bot?": "Faça um tour rápido pelo bot de chat?",
  "Corporation Exists Checks": "Corporação existe cheques",
  "pleaseSign": "Por favor assine dentro da caixa cinza",
  "Please take a selfie to prove this is your document. Center your face.": "Por favor, tire uma selfie para provar que este é o seu documento. Centralize seu rosto.",
  "Finally, you will be in control of your own private information!": "Finalmente, você estará no controle de sua própria informação privada!",
  "' photo of yourself that I can match against your ID document": "'foto de si mesmo que eu posso combinar com o seu documento de identificação",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Vamos fazer-lhe perguntas no chat e basta preencher os formulários ou seguir os pedidos",
  "Before we start you'll need a valid passport, identity card or driving license": "Antes de começar, você precisará de um passaporte, carteira de identidade ou carta de condução válida",
  "Photo": "foto",
  "inProcess": "Em processamento...",
  "newCustomer": "Cliente novo",
  "debugLogSent": "Log de depuração enviado",
  "reviewData": "Rever dados",
  "requestMyData": "Solicitando meus dados",
  "validatingDataClaim": "Importando dados",
  "resetApp": "Repor App",
  "wipeTheAppData": "Limpe os dados do aplicativo",
  "scanYourDocument": "Por favor, digitalize seu documento",
  "documentBackSide": "Parte de trás do documento do centro",
  "invalidQR": "Código QR inválido",
  "supportedQrCodes": "Códigos QR suportados:\n1) adicionar canal de chat\n2) importar dados",
  "pleaseChooseDT": "Por favor escolha o tipo de documento primeiro",
  "wrongDocumentTypePleaseTryAgain": "Tipo de documento incorreto. Por favor, tente novamente",
  "failedToSendLog": "Falha ao enviar log",
  "dateInTheFutureError": "{1} está no futuro",
  "invalidCountry": "País inválido verificado",
  "networkFailure": "Estou com alguns problemas de rede. Você pode verificar e, em seguida, tocar em Repetir / Cancelar",
  "enterPasswordOrWipeOutTheAppData": "Digite a senha ou limpe os dados do aplicativo",
  "noResourcesForCriteria": "Nenhum recurso foi encontrado para este critério",
  "logSentToDevTeam": "O log foi enviado para a equipe de desenvolvedores do Tradle",
  "startedByAnotherEmployee": "O pedido de {1} foi iniciado por outro funcionário",
  "doYouWantToContinue": "Você quer mudar para ele e continuar de lá?",
  "areYouSureYouAreDone": "Tem certeza de que deseja terminar esta sessão?",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Analise os dados abaixo e tire um instantâneo do lado {1} do documento",
  "afterRefresh": "Você está autorizado a usar nossos serviços sem interrupção",
  "invalidQuery": "Ups! Ocorreu um erro ao executar sua pesquisa. Nossos desenvolvedores tentarão corrigi-lo o mais rápido possível."
}