module.exports = {
    "officialAccounts": "Conversations",
    "back": "Back",
    "profile": "Profile",
    "done": "Done",
    "edit": "Edit",
    "settings": "Settings",
    "theMinValueBiggerThenMaxValue": "The min value for the range should be smaller then the max value",
    "thePropertyWithMinMaxRangeError": "The property with [min-max] range can have only two numbers",
    "invalidProperty": "Invalid {1}",
    "invalidPropertyValue": "Invalid value",
    "optional": "optional",
    "thisFieldIsRequired": "This field is required",
    "unlockDevice": "unlock your device to proceed",
    "pleaseDrawPassword": "Draw your pattern",
    "drawYourPassword": "Draw your pattern",
    "drawYourPasswordAgain": "Draw your pattern again",
    "drawYourNewPassword": "Draw a new pattern",
    "drawYourNewPasswordAgain": "Draw the new pattern again",
    "drawYourOldPassword": "Draw your old pattern",
    "gestureNotRecognized": "Wrong pattern",
    "passwordLimitations": "Pattern must have 5+ points",
    "invalidPattern": "Wrong pattern",
    "patternNotMatching": "The patterns didn't match.",
    "wrongPattern": "Wrong pattern",
    "correctGesture": "Correct pattern detected",
    "authenticationFailed": "Authentication failed",
    "setPassword": "Choose a secure password",
    "enterPassword": "Enter your password",
    "enterCurrentPassword": "Enter your current password",
    "setNewPassword": "Choose a new password",
    "textPasswordLimitations": "Must have 10+ characters, at least one uppercase letter, lowercase letter, number, and special character",
    "tooManyPasswordAttempts": "Too many failed attempts! This form has been disabled.",
    "correctPassword": "Aww, you remembered!",
    "passwordsDontMatch": "Passwords don't match",
    "temporarilyLocked": "For your protection, this application has been temporarily locked for {1}",
    "pleaseRestartTIM": "Please restart TiM",
    "ok": "OK",
    "cancel": "Cancel",
    "details": "Details",
    "enterYourName": "Enter your name",
    "addServerUrl": "Add new provider via URL",
    "search": "Search",
    "searchSomething": "Search - {1}",
    "hello": "Hello {1}!",
    "testForgetMe": "This is a test mechanism to reset all communications with this provider",
    "confirmForgetMe": "Are you sure you want '{1}' to forget you",
    "forgetMe": "Forget me",
    "iNeed": "I need...",
    "newProduct": "New product",
    "tapToRemovePhotos": "Tap to remove photos",
    "addNew": "Add new {1}",
    "fillTheForm": "Please fill out this form **{1}**",
    "fillOutTheForm": "The company was not found. Please fill out the form",
    "fillTheFormWithAttachments": "Please fill out this form **{1}**",
    "takeAPicture": "Please take a **selfie** picture of your face",
    "verifiedBy": "Verified by {1}",
    "issuedBy": "Issued by {1}",
    "sentTo": "Sent to {1}",
    "verifiedByOn": "Verified by {1} on",
    "issuedByOn": "Issued by {1} on",
    "sentToOn": "Sent to {1} on",
    "typeMessage": "Type a message",
    "newProductMsg": "I need a {1}.",
    "shareOne": "Alternatively, share below",
    "shareOneOfMany": "Alternatively, share below",
    "shareOne1": "{1}, this is your personal privacy assistant. I see you've already had your {2} verified. You can tap below to share it with {3}.",
    "shareOneOfMany1": "{1}, this is your personal privacy assistant. I see you've already had your {2} verified. You can tap on any items in the list below to share them with {3}.",
    "shareWith": "Share {1}",
    "verificationTransactionID": "Verification Transaction Id",
    "scanQRcode": "Scan QR code",
    "youWantedTo": "You chose to {1}",
    "setDateValue": "Set",
    "add": "Add {1}",
    "myDocuments": "My Documents",
    "confirmRevoke": "Ask {1} to delete this document from their records?",
    "shareProduct": "You can tap below to share {1} with {2}",
    "shareMyProduct": "You can tap below to share {1} with {2}",
    "willBeAvailable": "This functionality will be available soon",
    "switchTouchIdOff": "Switch touch ID off",
    "switchTouchIdOn": "Switch touch ID on",
    "noConnection": "{appName} requires a working internet connection which you don't have at the moment",
    "noConnectionWillProcessLater": "{appName} requires a working internet connection which you don't have at the moment. The request will be processed when a connection is established",
    "noConnectionForPL": "{appName} requires a working internet connection to request a list of products from {1} which you don't have at the moment",
    "noConnectionForNewProduct": "{1}, {appName} requires a working internet connection to fill out the {2} application.",
    "newContactRequest": "{1} sent you contact request",
    "pleaseCorrectTheErrors": "Please correct error in the form",
    "verifierHelp": "Click 'Done' button after reviewing the form. If some fields require correction check them them first and then click the 'Done' button",
    "errorNotification": "Error notification has been sent to the customer to correct",
    "areYouSureAboutNextForm": "Have you finished adding {1}?",
    "formChooser": "Request a Form",
    "showQR": "My QR code",
    "useTouchId": "Enable Touch ID",
    "useGesturePassword": "Enable Gesture Password",
    "useTouchIdAndGesturePassword": "Enable Touch ID and Gesture",
    "changeGesturePassword": "Change gesture password",
    "enablePassword": "Enable Password",
    "changePassword": "Change Password",
    "touchIdOn": "Touch ID is ON",
    "passwordOn": "Gesture Password is ON",
    "bothOn": "Both are ON",
    "turnTouchIdOn": "Turn touch ID on",
    "turnPasswordOn": "Turn Gesture Password on",
    "turnBothOn": "Turn Both on",
    "Pair": "Pair devices",
    "wrongQR": "Wrong QR code",
    "learnMore": "Learn more",
    "offlineMode": "Offline Mode",
    "learnMoreDescriptionTo": "You can still write messages in Offline Mode even though your device is not connected. When you reconnect all your messages will be automatically sent to {1}.",
    "noNetwork": "No network",
    "learnMoreDescription": "You can still write messages in Offline Mode even though your device is not connected. When you reconnect all your messages will be automatically sent.",
    "learnMoreServerIsDown": "Any messages you write will be automatically sent to {1} when they come online.",
    "shareChangesWith": "Share changes with",
    "nothingChanged": "Nothing changed",
    "en": "English",
    "nl": "Dutch",
    "submittingForm": "Submittted {1}",
    "submittingModifiedForm": "Modifying {1}",
    "receivedForm": "Received {1}",
    "receivedProduct": "Received {1}",
    "receivedVerification": "Received verification for {1}",
    "Photo": "Photo",
    "formRequest": "Request for {1}",
    "sharedForm": "Shared {1}",
    "youAreForgotten": "You've been successfully forgotten",
    // "invalidPairingRequest": "Invalid Pairing Request",
    // "pairingRequest": "Pairing Request",
    // "deviceDoesNotHaveMyKeys": "Received identity does not have my keys",
    "pleaseWait": "Please wait",
    "pairingRequestWasProcessed": "Pairing request was processed",
    "pairingDevicesIsInProgress": "Pairing devices is in progress",
    "pairingDevicesSync": "Synchronizing the content",
    "youShared": "You shared from {1}",
    "asVerifiedBy": "As verified by {1}",
    "asSentTo": "As sent to {1}",
    "termsAndConditions": "Terms and conditions.",
    "acceptTermsAndConditions": "View terms and conditions",
    "acceptingTermsAndConditions": "By pressing OK, you accept the Terms and Conditions",
    "viewTerms": "Please view the Terms and Conditions",
    "areYouSureAboutWipe": "This action is irreversible. You will lose all your data and private keys. Are you sure you want to proceed?",
    "irrefutableProofs": "Irrefutable proofs",
    "independentBlockchainViewer": "Independent blockchain viewer",
    "contextsFor": "Contexts for",
    "customerWaiting": "{1} has entered the chat",
    "sharedContext": "Shared Context",
    "shareContext": "Share {1}",
    "shareAllPastAndFutureMessages": "Share all past and future messages in this context with selected parties",
    "listOfProducts": "List of products",
    "backTo": "Back to {1}",
    "backToResults": "Back to results",
    "formListError": "Unavailable",
    "formListErrorDescription": "Forms can be requested once the customer begins an application",
    "providerIsOffline": "{1} is offline",
    "sendEditRequestPrompt": "Send edit request to {1}?",
    "pleaseCorrectFields": "Please correct the following fields: {1}",
    "pleaseCorrect": "Please correct",
    "applyForProduct": "Apply for a product",
    "verifyPrompt": "Verify?",
    "selectPropertiesForCorrection": "Select properties you want recipient to correct",
    "fieldErrorMessagePrompt": "What's wrong with this field?",
    "thisValueIsInvalidPlaceholder": "this value is invalid because...",
    "sourcesBy": "Sources by {1}",
    "youShallNotPass": "You shall not pass!",
    "enablePasscodeFirst": "Looks like you don't have a device passcode enabled. Without it, this app cannot protect your data! Please enable it before pressing OK",
    "downloadingUpdate": "Downloading an update...",
    "trustedProviders": "Trusted providers",
    "overviewOfApplications": "Overview of Applications",
    "serverIsUnreachable": "Server is unreachable",
    "sharedWith": "Shared {1} context with {2}",
    "viewDebugLog": "View debug log",
    "somethingWrongSubmitLog": "Something seems to have gone wrong. Please submit the debug log to the {appName} developer team",
    "submitLog": "Submit Log",
    "submitting": "Submitting",
    "restartApp": "Restart App",
    "resetApp": "Reset App",
    "error": "Error",
    "invalidDocument": "invalid document",
    "somethingWrong": "Something went wrong",
    "oops": "Oops",
    "ukLicenseUnsupported": "UK driver licence scanning is not supported at this time",
    "areYouSureYouWantToDelete": "Are you sure you want to hide {1}?",
    "hideResource": "Hide {1}",
    "cancelHideResource": "Cancel Hide {1}",
    "areYouSureYouWantToConfirmAllItems": "Tap OK to confirm all {1}, or Cancel to continue reviewing",
    "confirmAllItems": "Tap OK to confirm them all, or Cancel to continue reviewing",
    "youReviewed": "You reviewed {1} out of {2} items",
    "youReviewedAll": "You reviewed all {1}",
    "unknownQRCodeFormat": "Unrecognized QR code format",
    "confirmedMyData": "All imported data can be viewed in your {profileTitle}",
    "sendingYourData": "Sending Your Data",
    "importYourData": "Import Your Data",
    "reviewData": "Review data",
    "digitalWealthPassport": "Digital Wealth Passport",
    "homePage": "Home",
    "sponsoredBy": "Sponsored by",
    "installingUpdate": "Installing update",
    "restartingApp": "The application will restart momentarily",
    "loadingModels": "loading models",
    "loadingResources": "loading resources",
    "initializingEngine": "initializing engine",
    "generatingKeys": "generating your private keys",
    "cameraAccess": "Camera Access",
    "enableCameraAccess": "{appName} currently does not have permission to use the camera. To grant access, choose Settings, and make sure Camera is enabled.",
    "noScanningOnAndroid": "Document scanning on Android is coming soon.",
    "pleaseTapOnMenu": "Please tap on the red button and",
    // messages to delete
    "holdPhoneToPassportBackCover": "Hold the back of your phone against the back inside cover of your passport.",
    "holdPhoneToPassport": "Hold the back of your phone against the front cover of your passport",
    "addAnotherFormOrGetNext": "Add another {1} or move on to the next form",
    "switchToRepresentative": "Switching to representative mode is not yet implemented.",
    // end messages to delete
    "scanningFailedTryAgain": "Scanning was unsuccessful. Could you please try again?",
    "documentNotScanning": "Oops, something went wrong!",
    "retryScanning": "Was that a {1}? I couldn't tell. Please try again?\n\nFor best results, use landscape mode, avoid glare, and be sure to position the document within the frame shown.",
    "centerPassport": "Center passport photo page in frame",
    "centerLicence": "Center licence in frame",
    "centerID": "Center ID in frame",
    "documentBackSide": "Center document back side",
    "dataSecurity": "Data Security",
    "noAccessToServer": "Server is not accessible. Try later.",
    "next": "Next",
    "verificationBy": "Verification by {1}",
    "importing": "Importing",
    "sending": "Sending",
    "invalidDeepLink": "Looks like you clicked an invalid link!",
    "fromMyData": "from 'My Data'",
    "enterPasswordOrWipeOutTheAppData": "Enter password or wipe the app data",
    "wipeTheAppData": "Wipe the app data",
    "areYouSureYouWantToServeThisCustomer": "Are you sure you want to serve this customer?",
    "approveApplicationFor": "Approve application for {1}",
    "approveApplication": "Approve application",
    "denyApplicationFor": "Deny application for {1}",
    "denyApplication": "Deny application",
    "documentExpiredTitle": "Document expired",
    "documentExpiredMessage": "Please scan a valid document",
    "contactUs": "Contact us",
    "testProviders": "Sandbox",
    "yes": "Yes",
    "no": "No",
    "neverMissAMessage": "Never miss a message",
    "receiveNotifications?": "Would you like to receive notifications?",
    "help": "Help",
    "continue": "Continue",
    "importDataPrompt": "You are about to import your data from",
    "unreadMessages": "You have unread messages",
    "messageWaitingFrom": "You have a new message from {1}",
    "iproovFailedTitle": "Oops! Something went wrong",
    "iproovFailedMessage": "Please try again. For best results, keep your face centered in the oval during the color flashes.",
    "iproovErrorTitle": "Oops! Something went wrong",
    "iproovErrorMessage": "Please wait a bit and try again",
    "nameUnknown": "name unknown",
    "youAreTheRM": "You are the Relationship Manager for this application",
    "fillRequiredFields": "Please fill out all required fields",
    "multientryToShare": "There are {1} documents to share",
    "youAreAboutToShare": "You are about to share\n '{1}'\n documents",
    "nothingToShare": "Nothing to share",
    "importingData": "Importing {1} documents from {2}",
    "reviewScannedProperties": "Please review and correct the data below",
    "reviewAndConfirm": "Please review and confirm",
    "reviewScannedPropertiesAndSecondSideSnapshot": "Please review the data below, and take a snapshot of the {1} side of the document",
    "pleaseClickOnAddButton": "Please click on '+' below to add '{1}'",
    "validationErrors": "Please correct failed validation fields",
    "createNew": "Fill out form \"{1}\"",
    "createNext": "Fill out another form \"{1}\"",
    "resetRequired": "Reset Required",
    "incompatibleVersion": "Due to recent backwards incompatible changes, this update requires a hard reset of the app. Press OK to reset the app's identity and storage.",
    "storageCorrupted": "your app's keychain data and storage has been corrupted! If you think this is a mistake, press Restart App to try again. Pressing Reset App will reset the app's identity and storage.",
    "updateAppTitle": "App Update Available",
    "updateAppMessage": "Update now, or shall I remind you later?",
    "updateNow": "Update Now",
    "later": "Later",
    "sandboxDescription": "In the Sandbox, learn how to use the app with simulated service providers.",
    "creationDate": "Date created",
    "submissionDate": "Date submitted",
    "cancelItem": "You are about to cancel {1}. Please tap OK to confirm",
    "exploreData": "Explore Data",
    "bookmarks": "Bookmarks",
    "createManualMatchCheck": "Create manual match check",
    "supportedQrCodes": "Supported QR codes: \n1) add chat channel \n2) import data",
    "inProcess": "Processing...",
    "inProgress": "In progress...",
    "networkFailure": "I'm experiencing some network issues. Can you check and then tap Retry / Cancel",
    "invalidQuery": "Oops, we hit an error running your search. Our developers will try to fix it asap.",
    "noResourcesForCriteria": "No resources were found for this criteria",
    "invalidQR": "Invalid QR code",
    "validatingDataClaim": "Importing data",
    "requestMyData": "Requesting my data",
    "startedByAnotherEmployee": "The application for {1} was started by another employee",
    "doYouWantToContinue": "Do you want to switch to it and continue from there?",
    "afterRefresh": "You are cleared to use our services without interruption",
    "newCustomer": "New customer",
    "areYouSureYouAreDone": "Are you sure you want to finish this session?",
    "wrongDocumentTypePleaseTryAgain": "Wrong document type. Please try again",
    "invalidCountry": "Invalid country scanned",
    "scanYourDocument": "Please scan your document",
    "pleaseChooseDT": "Please choose document type first",
    "dateInTheFutureError": "{1} is in the future",
    "enterValidValue": "Please enter the valid value",
    "rescan": "Please re-scan the same document",
    "invalidValue": "This value is invalid. Please re-enter.",
    "outgoingMessages": "Outgoing Messages",
    "pleaseChoose": "Please choose",
    "override": "Override",
    "olderResourceVersion": "This is the older version of this resource",
    "reset": "Reset {1}",
    "completeOnboardingApplication": "Please complete the onboarding application",
    "otherEnumResources": "Other {1} choices",
    "suggestions": "Suggestions",
    "submitDraft": "Send to the prospect prefilled application for: {1}",
    // Bookmarks
    "myCases": "My cases",
    "applicationsHasFailedChecks": "Applications with failed Checks",
    "applicationsHasCheckOverrides": "Applications with Check Overrides",
    "applicationsNotAssigned": "Applications - not assigned",
    "applicationsStarted": "Applications - started",
    "overwriteIfCantReuse": "Please overwrite if data can`t be reused",
    "finCrimeReview": "FinCrime needs to review this application",
    "scanToLogInToTradle": "Scan QR code with your mobile device",
    "toPairDevices": "to pair devices",
    "syncDevicesIsDone": "Device syncronization finished",
    "cancelDevicePairing": "Cancel device pairing",
    // Buttons
    "Submit": "Submit",
    "Clear": "Clear",
    "Cancel": "Cancel",
    "retake": "Re-take",
    "Approve": "Approve",
    "Deny": "Deny",
    "checkIfMatch": "Check if match",
    "loading": "Loading...",
    "usePhoto": "Use photo",
    "Applications": "Applications",
    "Verifications": "Verifications",
    "Seals": "Seals",
    "Sanctions Checks": "Sanctions Checks",
    "Corporation Exists Checks": "Corporation Exists Checks",
    "Application submitted!": "Application submitted!",
    // Server side messages
    "See our list of products": "See our list of products",
    "Please fill out the form": "Please fill out the form ",
    "Our products have changed": "Our products have changed",
    "Choose Apply for Product from the menu": "Choose Apply for Product from the menu",
    "Please take a selfie to prove this is your document. Center your face.": "Please take a selfie to prove this is your document. Center your face.",
    "Please scan your": "Please scan your",
    "ID document": "ID document",
    "Sending": "Sending",

    "Is it your company?": "Is it your company?",
    "Please review and correct the data below": "Please review and correct the data below",
    "Please correct the field": "Please correct the field",
    "Please correct the highlighted property": "Please correct the highlighted property",

    "Please tap here and sign": "Please tap here and sign",
    "Give me a moment...": "Give me a moment...",
    "Please click to scan your": "Please click to scan your",
    "Thank you. Now take a '": "Thank you. Now take a '",
    "' photo of yourself that I can match against your ID document": "' photo of yourself that I can match against your ID document",
    "pleaseSign": "Please sign inside the grey box",
    "getStarted": "Get started",
    "orShare": "Or share",
    "goodNews": "Good news! You already have {1}. To share tap the icon below",
    "goodNewsFew": "Good news! You already have quite a few. To share tap icon below.",
    "prefilledForCustomer": "For your convenience we prefilled some fields. Please review and submit",
    "prefillTheProduct": "Choose the application to prefill for the prospect",
    "importedData": "Click here to see {1} resources imported from {2} on your profile page.",
    // Tours buttons
    "Skip": "Skip",
    "Done": "Done",
    "Next": "Next",
    // TOURS Friendly
    // message
    "Take a quick tour of chat bot?": "Take a quick tour of chat bot?",
    // Page 1
    "Ready for friendliness?": "Ready for friendliness?",
    "Finally, you will be in control of your own private information!": "Finally, you will be in control of your own private information!",
    // Page 2
    "Get set for friendliness?": "Get set for friendliness?",
    // Page 3
    "Go friendliness!": "Go friendliness!",
    // Safe-Re
    // Message
    // Page 1
    "Ready?": "Ready?",
    // Page 2
    "Get set": "Get set",
    "Before we start you'll need a valid passport, identity card or driving license": "Before we start you'll need a valid passport, identity card or driving license",
    // // Page 3
    "Go!": "Go!",
    "We'll ask you questions in the chat and you simply fill the forms or follow the requests":  "We'll ask you questions in the chat and you simply fill the forms or follow the requests",
    "debugLogSent": "Debug Log Sent",
    "logSentToDevTeam": "The log was sent to the Tradle developer team",
    "failedToSendLog": "Failed to send log",
    "appStoreShortDescription": "Track the data you share, get financial products faster by sharing verified data",
    "appStoreLongDescription": "The Tradle app is your secure line to your service providers. It lets you manage your personal data, automatically update your service providers when your situation or documentation changes, and onboard quickly for new products by sharing verified data. Its chat-like interface lets you get customer service and make purchases in one flow. And never again wonder what information you've given your service providers, or be asked to give your name/address/SSN/phone number every time you call.",
}
