module.exports = {
  "searchSomething": "Búsqueda {1}",
  "thisFieldIsRequired": "este campo es requerido",
  "settings": "Ajustes",
  "newProductMsg": "Necesito un {1}.",
  "invalidPropertyValue": "valor no válido",
  "confirmRevoke": "¿Pedir {1} para eliminar este documento de sus registros?",
  "useTouchIdAndGesturePassword": "Habilitar la identificación táctil y el gesto",
  "formChooser": "Lista de formularios",
  "submittingForm": "Enviado {1}",
  "viewTerms": "Por favor vea los Términos y Condiciones",
  "addServerUrl": "Añadir URL del servidor",
  "setNewPassword": "Elija una nueva contraseña",
  "optional": "Opcional",
  "shareOne": "Alternativamente, compartir a continuación",
  "patternNotMatching": "Los patrones no coinciden.",
  "verifierHelp": "Haga clic en el botón 'Hecho' después de revisar el formulario. Si algunos campos requieren corrección, verifíquelos primero y luego haga clic en el botón 'Listo'",
  "confirmForgetMe": "¿Estás seguro de que quieres que {1} te olvide?",
  "customerWaiting": "{1} ha entrado en el chat",
  "invalidPattern": "Patrón incorrecto",
  "back": "Espalda",
  "inProgress": "En progreso...",
  "tooManyPasswordAttempts": "¡Demasiados intentos fallidos! Esta forma a sido inhabilitada.",
  "turnBothOn": "Encienda ambos",
  "formListError": "Indisponible",
  "restartApp": "Reiniciar la aplicación",
  "unreadMessages": "Tienes mensajes sin leer",
  "setDateValue": "Conjunto",
  "sentToOn": "Enviado a {1} en",
  "newContactRequest": "{1} te envió una solicitud de contacto",
  "pleaseRestartTIM": "Por favor reinicia TiM",
  "noConnectionWillProcessLater": "{appName} requiere una conexión a Internet que no tenga en este momento. La solicitud será procesada cuando se establezca una conexión.",
  "providerIsOffline": "{1} está desconectado",
  "forgetMe": "Olvidame",
  "deviceDoesNotHaveMyKeys": "La identidad recibida no tiene mis claves",
  "termsAndConditions": "Términos y Condiciones.",
  "useGesturePassword": "Habilitar contraseña de gestos",
  "formListErrorDescription": "Los formularios se pueden solicitar una vez que el cliente comienza una solicitud.",
  "verifiedByOn": "Verificado por {1} en",
  "fieldErrorMessagePrompt": "¿Qué hay de malo en este campo?",
  "noConnection": "{appName} requiere una conexión a Internet que no tengas en este momento",
  "typeMessage": "Escribe un mensaje",
  "hideResource": "Ocultar {1}",
  "edit": "Editar",
  "tapToRemovePhotos": "Toque para eliminar fotos",
  "myDocuments": "Mis documentos",
  "add": "Añadir {1}",
  "correctGesture": "Patrón correcto detectado",
  "done": "Hecho",
  "showQR": "Mi código QR",
  "restartingApp": "La aplicación se reiniciará momentáneamente.",
  "verifyPrompt": "¿Verificar?",
  "listOfProducts": "Lista de productos",
  "cancel": "Cancelar",
  "drawYourNewPassword": "Dibuja un nuevo patrón",
  "noConnectionForPL": "{appName} requiere una conexión a Internet que funcione para solicitar una lista de productos de {1} que no tiene en este momento",
  "gestureNotRecognized": "Patrón incorrecto",
  "passwordsDontMatch": "Las contraseñas no coinciden",
  "areYouSureAboutNextForm": "¿Has terminado de agregar {1}?",
  "sharedWith": "Contexto {1} compartido con {2}",
  "pleaseDrawPassword": "Dibuja tu patrón",
  "drawYourNewPasswordAgain": "Dibuja el nuevo patrón de nuevo.",
  "offlineMode": "Modo offline",
  "hello": "Hola {1}!",
  "drawYourPassword": "Dibuja tu patrón",
  "invalidProperty": "No válido {1}",
  "verifiedBy": "Verificado por {1}",
  "testForgetMe": "Este es un mecanismo de prueba para restablecer todas las comunicaciones con este proveedor",
  "details": "Detalles",
  "unlockDevice": "desbloquea tu dispositivo para proceder",
  "enterCurrentPassword": "introduce tu contraseña actual",
  "issuedByOn": "Emitido por {1} en",
  "changePassword": "Cambia la contraseña",
  "acceptingTermsAndConditions": "Al presionar OK, usted acepta los Términos y Condiciones",
  "noConnectionForNewProduct": "{1}, {appName} requiere una conexión a Internet que funcione para completar la aplicación {2}.",
  "issuedBy": "Emitido por {1}",
  "temporarilyLocked": "Para su protección, esta aplicación ha sido bloqueada temporalmente para {1}",
  "profile": "Perfil",
  "shareOneOfMany": "Alternativamente, compartir a continuación",
  "areYouSureYouWantToServeThisCustomer": "¿Estás seguro de que quieres atender a este cliente?",
  "authenticationFailed": "Autenticación fallida",
  "pairingRequestWasProcesseed": "La solicitud de emparejamiento fue procesada",
  "loadingModels": "cargando modelos",
  "pleaseCorrectTheErrors": "Por favor corrija el error en el formulario.",
  "drawYourPasswordAgain": "Dibuja tu patrón otra vez",
  "shareChangesWith": "Compartir cambios con",
  "textPasswordLimitations": "Debe tener más de 10 caracteres, al menos una letra mayúscula, una letra minúscula, un número y un carácter especial",
  "correctPassword": "Aww, te acuerdas!",
  "learnMoreDescription": "Aún puede escribir mensajes en el modo sin conexión aunque su dispositivo no esté conectado. Cuando vuelva a conectarse todos sus mensajes serán enviados automáticamente.",
  "irrefutableProofs": "Pruebas irrefutables",
  "youReviewedAll": "Revisaste todo {1}",
  "areYouSureAboutWipe": "Esta acción es irreversible. Perderás todos tus datos y claves privadas. ¿Estas seguro que deseas continuar?",
  "enablePasscodeFirst": "Parece que no tienes un código de acceso del dispositivo habilitado. Sin ella, esta aplicación no puede proteger tus datos! Por favor habilítelo antes de presionar OK.",
  "holdPhoneToPassportBackCover": "Sostenga la parte posterior de su teléfono contra la parte posterior interior de la cubierta de su pasaporte.",
  "turnPasswordOn": "Activar la contraseña del gesto",
  "nl": "holandés",
  "neverMissAMessage": "Nunca te pierdas un mensaje",
  "errorNotification": "Notificación de error ha sido enviada al cliente para corregir",
  "digitalWealthPassport": "Pasaporte de riqueza digital",
  "cameraAccess": "Acceso a la cámara",
  "thePropertyWithMinMaxRangeError": "La propiedad con rango [min-max] solo puede tener dos números",
  "enterYourName": "Introduzca su nombre",
  "learnMoreServerIsDown": "Cualquier mensaje que escriba se enviará automáticamente a {1} cuando se conecten.",
  "sharedContext": "Contexto compartido",
  "invalidDocument": "documento inválido",
  "addAnotherFormOrGetNext": "Agregue otro {1} o pase al siguiente formulario",
  "pairingRequest": "Solicitud de emparejamiento",
  "shareAllPastAndFutureMessages": "Comparta todos los mensajes pasados y futuros en este contexto con partes seleccionadas",
  "sourcesBy": "Fuentes por {1}",
  "willBeAvailable": "Esta funcionalidad estará disponible próximamente.",
  "pleaseClickOnAddButton": "Haga clic en '+' a continuación para agregar '{1}'",
  "youShared": "Compartiste desde {1}",
  "nothingChanged": "nada ha cambiado",
  "invalidPairingRequest": "Solicitud de emparejamiento no válida",
  "sentTo": "Enviado a {1}",
  "later": "Luego",
  "documentExpiredMessage": "Por favor escanee un documento válido",
  "areYouSureYouWantToDelete": "¿Estás seguro de que quieres ocultar {1}?",
  "centerLicence": "Centro de licencia en marco",
  "iNeed": "Necesito...",
  "officialAccounts": "Conversaciones",
  "setPassword": "Elija una contraseña segura",
  "scanQRcode": "Escanear código QR",
  "unknownQRCodeFormat": "Formato de código QR no reconocido",
  "shareProduct": "Puede tocar abajo para compartir {1} con {2}",
  "noNetwork": "Sin red",
  "centerID": "ID de centro en marco",
  "shareOneOfMany1": "{1}, este es tu asistente personal de privacidad. Veo que ya has verificado tu {2}. Puede tocar en cualquier elemento de la lista a continuación para compartirlos con {3}.",
  "verificationTransactionID": "ID de transacción de verificación",
  "shareOne1": "{1}, este es tu asistente personal de privacidad. Veo que ya has verificado tu {2}. Puede tocar abajo para compartirlo con {3}.",
  "noAccessToServer": "El servidor no es accesible. Intenta más tarde.",
  "pleaseCorrect": "Por favor corrija",
  "testProviders": "Salvadera",
  "approveApplicationFor": "Aprobar solicitud para {1}",
  "serverIsUnreachable": "El servidor es inalcanzable",
  "oops": "Ups",
  "acceptTermsAndConditions": "Ver términos y condiciones",
  "sharedForm": "Compartido {1}",
  "overviewOfApplications": "Descripción general de las aplicaciones",
  "asVerifiedBy": "Según lo verificado por {1}",
  "pairDevices": "Emparejar dispositivos",
  "ok": "DE ACUERDO",
  "switchTouchIdOn": "Activar ID táctil",
  "ukLicenseUnsupported": "El escaneo de la licencia de conducir del Reino Unido no es compatible en este momento",
  "formRequest": "Solicitud de {1}",
  "messageWaitingFrom": "Tienes un nuevo mensaje de {1}",
  "shareMyProduct": "Puede tocar abajo para compartir {1} con {2}",
  "centerPassport": "Centro de la página de la foto del pasaporte en el marco",
  "youReviewed": "Has revisado {1} de {2} elementos",
  "denyApplication": "Denegar la solicitud",
  "storageCorrupted": "¡Los datos y el almacenamiento del llavero de tu aplicación se han corrompido! Si cree que esto es un error, presione Reiniciar aplicación para volver a intentarlo. Al presionar Restablecer aplicación, se restablecerá la identidad y el almacenamiento de la aplicación.",
  "nothingToShare": "Nada para compartir",
  "nameUnknown": "anónimo",
  "youAreTheRM": "Usted es el gerente de relaciones para esta aplicación.",
  "yes": "Sí",
  "switchTouchIdOff": "Desactivar la identificación táctil",
  "en": "Inglés",
  "installingUpdate": "Instalando actualización",
  "homePage": "Casa",
  "next": "Siguiente",
  "cancelItem": "Está a punto de cancelar {1}. Por favor, toque OK para confirmar",
  "takeAPicture": "Por favor, tome una foto ** selfie ** de su cara",
  "createNew": "Rellene el formulario \"{1}\"",
  "validationErrors": "Por favor, corrija los campos de validación fallidos",
  "somethingWrongSubmitLog": "Algo parece haber salido mal. Por favor envíe el registro de depuración al equipo de desarrolladores de {appName}",
  "fromMyData": "de 'Mis datos'",
  "approveApplication": "Aprobar solicitud",
  "wrongPattern": "Patrón incorrecto",
  "denyApplicationFor": "Denegar solicitud para {1}",
  "updateAppTitle": "Actualización de la aplicación disponible",
  "pleaseCorrectFields": "Por favor, corrija los siguientes campos: {1}",
  "independentBlockchainViewer": "Visor de blockchain independiente",
  "turnTouchIdOn": "Activar la identificación táctil",
  "youAreAboutToShare": "Estas a punto de compartir\n '{1}'\n documentos",
  "retryScanning": "Fue eso un {1}? No pude decir ¿Inténtalo de nuevo?\n\nPara obtener los mejores resultados, use el modo horizontal, evite el resplandor y asegúrese de colocar el documento dentro del marco que se muestra.",
  "receiveNotifications?": "¿Te gustaría recibir notificaciones?",
  "youShallNotPass": "¡No pasarás!",
  "documentExpiredTitle": "Documento expirado",
  "confirmAllItems": "Toque OK para confirmarlos todos o Cancelar para continuar revisando",
  "sandboxDescription": "En el Sandbox, aprenda cómo usar la aplicación con proveedores de servicios simulados.",
  "viewDebugLog": "Ver registro de depuración",
  "updateNow": "Actualizar ahora",
  "iproovFailedTitle": "Ups! Algo salió mal",
  "iproovFailedMessage": "Inténtalo de nuevo. Para obtener los mejores resultados, mantenga su cara centrada en el óvalo durante los destellos de color.",
  "importing": "Importador",
  "createNext": "Rellene otro formulario \"{1}\"",
  "areYouSureYouWantToConfirmAllItems": "Toque OK para confirmar todo {1}, o Cancelar para continuar revisando",
  "newProduct": "Nuevo producto",
  "touchIdOn": "La identificación táctil está activada",
  "youAreForgotten": "Has sido olvidado con éxito",
  "scanningFailedTryAgain": "El escaneo no tuvo éxito. ¿Podrías intentarlo de nuevo?",
  "importingData": "Importando {1} documentos desde {2}",
  "learnMore": "Aprende más",
  "shareWith": "Compartir {1}",
  "no": "No",
  "multientryToShare": "Hay {1} documentos para compartir",
  "applyForProduct": "Solicitar un producto",
  "bothOn": "Ambos están encendidos",
  "fillRequiredFields": "Por favor llene todos los campos requeridos",
  "submitLog": "Enviar registro",
  "creationDate": "Fecha de creacion",
  "resetRequired": "Se requiere reinicio",
  "iproovErrorTitle": "Ups! Algo salió mal",
  "submitting": "Sumisión",
  "invalidDeepLink": "Parece que has hecho clic en un enlace no válido!",
  "verificationBy": "Verificación por {1}",
  "holdPhoneToPassport": "Sostenga la parte posterior de su teléfono contra la cubierta frontal de su pasaporte",
  "loadingResources": "cargando recursos",
  "trustedProviders": "Proveedores de confianza",
  "generatingKeys": "generando tus claves privadas",
  "help": "Ayuda",
  "enableCameraAccess": "{appName} actualmente no tiene permiso para usar la cámara. Para otorgar acceso, elija Configuración y asegúrese de que la Cámara esté habilitada.",
  "useTouchId": "Habilitar ID táctil",
  "importYourData": "Importa tus datos",
  "pleaseTapOnMenu": "Por favor toque el botón rojo y",
  "cancelHideResource": "Cancelar Ocultar {1}",
  "iproovErrorMessage": "Por favor espere un poco y vuelva a intentarlo",
  "backTo": "Volver a {1}",
  "contactUs": "Contáctenos",
  "documentNotScanning": "¡Huy! Algo salió mal!",
  "continue": "Continuar",
  "confirmedMyData": "Todos los datos importados se pueden ver en su {profileTitle}",
  "search": "Buscar",
  "addNew": "Añadir nuevo {1}",
  "importDataPrompt": "Estás a punto de importar tus datos desde",
  "receivedProduct": "Recibido {1}",
  "error": "Error",
  "initializingEngine": "motor de inicializacion",
  "fillTheFormWithAttachments": "Por favor complete este formulario ** {1} **",
  "reviewScannedProperties": "Por favor revise y corrija los datos a continuación",
  "somethingWrong": "Algo salió mal",
  "incompatibleVersion": "Debido a los recientes cambios incompatibles con versiones anteriores, esta actualización requiere un restablecimiento completo de la aplicación. Presiona OK para restablecer la identidad y el almacenamiento de la aplicación.",
  "updateAppMessage": "Actualízalo ahora, ¿o te lo recuerdo después?",
  "backToResults": "Volver a resultados",
  "importData": "Importar datos",
  "switchToRepresentative": "El cambio al modo representativo aún no está implementado.",
  "fillTheForm": "Por favor complete este formulario ** {1} **",
  "theMinValueBiggerThenMaxValue": "El valor mínimo para el rango debe ser menor que el valor máximo",
  "receivedForm": "Recibido {1}",
  "receivedVerification": "Verificación recibida para {1}",
  "asSentTo": "Como enviado a {1}",
  "sendEditRequestPrompt": "¿Enviar solicitud de edición a {1}?",
  "contextsFor": "Contextos para",
  "downloadingUpdate": "Descargando una actualización ...",
  "enablePassword": "Habilitar contraseña",
  "changeGesturePassword": "Cambiar contraseña de gestos",
  "learnMoreDescriptionTo": "Aún puede escribir mensajes en el modo sin conexión aunque su dispositivo no esté conectado. Cuando vuelva a conectarse, todos sus mensajes se enviarán automáticamente a {1}.",
  "passwordOn": "La contraseña del gesto está activada",
  "noScanningOnAndroid": "El escaneo de documentos en Android llegará pronto.",
  "dataSecurity": "Seguridad de datos",
  "thisValueIsInvalidPlaceholder": "este valor no es válido porque ...",
  "drawYourOldPassword": "Dibuja tu viejo patrón",
  "sponsoredBy": "Patrocinado por",
  "enterPassword": "Ingresa tu contraseña",
  "shareContext": "Compartir {1}",
  "submittingModifiedForm": "Modificando {1}",
  "passwordLimitations": "El patrón debe tener 5+ puntos",
  "bookmarks": "Marcadores",
  "exploreData": "Explorar datos",
  "Please scan your": "Por favor escanea tu",
  "See our list of products": "Vea nuestra lista de productos.",
  "Please fill out the form": "por favor rellena el formulario",
  "ID document": "Documento de identidad",
  "Our products have changed": "Nuestros productos han cambiado.",
  "Choose Apply for Product from the menu": "Seleccione Solicitar producto en el menú.",
  "Please take a selfie to prove this is your document. Center your face.": "Por favor, tome una selfie para demostrar que este es su documento. Centra tu cara.",
  "Application submitted!": "¡Solicitud presentada!",
  "Sending": "Enviando",
  "Please tap here and sign": "Por favor, toque aquí y firme",
  "Give me a moment...": "Dame un momento...",
  "Please click to scan your": "Por favor haga clic para escanear su",
  "Thank you. Now take a '": "Gracias. Ahora toma un",
  "' photo of yourself that I can match against your ID document": "Una foto de usted que puedo comparar con su documento de identificación.",
  "pleaseSign": "Por favor firme dentro de la caja gris",
  "getStarted": "Empezar",
  "goodNewsFew": "¡Buenas noticias! Ya tienes bastantes. Para compartir toque el icono de abajo.",
  "goodNews": "¡Buenas noticias! Ya tienes {1}. Para compartir toca el ícono de abajo",
  "Clear": "Claro",
  "Submit": "Enviar",
  "Cancel": "Cancelar",
  "retake": "Volver a tomar",
  "usePhoto": "Usar foto",
  "Deny": "Negar",
  "Approve": "Aprobar",
  "loading": "Cargando...",
  "checkIfMatch": "Comprobar si coincide",
  "Verifications": "Verificaciones",
  "Seals": "focas",
  "Applications": "Aplicaciones",
  "Corporation Exists Checks": "Corporación existe cheques",
  "createManualMatchCheck": "Crear una verificación manual de partidos",
  "Finally, you will be in control of your own private information!": "¡Finalmente, usted tendrá el control de su propia información privada!",
  "Take a quick tour of chat bot?": "Hacer un recorrido rápido de chat bot?",
  "Go friendliness!": "Ve la amabilidad!",
  "Ready for friendliness?": "Listo para la amistad?",
  "Get set for friendliness?": "¿Prepararse para la amistad?",
  "Ready?": "Listo?",
  "Go!": "¡Ir!",
  "Get set": "Ponte listo",
  "Before we start you'll need a valid passport, identity card or driving license": "Antes de comenzar, necesitará un pasaporte válido, un documento de identidad o un permiso de conducir.",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Le haremos preguntas en el chat y usted simplemente llenará los formularios o seguirá las solicitudes.",
  "Done": "Hecho",
  "Next": "Siguiente",
  "Skip": "Omitir",
  "Sanctions Checks": "Cheques de sanciones",
  "inProcess": "Tratamiento...",
  "networkFailure": "Estoy experimentando algunos problemas de red. ¿Puedes marcar y luego tocar Reintentar / Cancelar?",
  "invalidQuery": "Vaya, hemos detectado un error al ejecutar tu búsqueda. Nuestros desarrolladores tratarán de arreglarlo lo antes posible.",
  "validatingDataClaim": "Importando datos",
  "debugLogSent": "Registro de depuración enviado",
  "failedToSendLog": "Error al enviar el registro",
  "invalidQR": "Código QR no válido",
  "supportedQrCodes": "Códigos QR soportados:\n1) agregar canal de chat\n2) importar datos",
  "logSentToDevTeam": "El registro fue enviado al equipo de desarrolladores de Tradle.",
  "noResourcesForCriteria": "No se encontraron recursos para este criterio.",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Revise los datos a continuación y tome una instantánea del lado {1} del documento",
  "documentBackSide": "Parte central del documento",
  "Photo": "Foto",
  "startedByAnotherEmployee": "La solicitud para {1} fue iniciada por otro empleado",
  "doYouWantToContinue": "¿Quieres cambiar a él y continuar desde allí?",
  "afterRefresh": "Usted está autorizado a utilizar nuestros servicios sin interrupción.",
  "reviewData": "Revisar los datos",
  "requestMyData": "Solicitando mis datos",
  "newCustomer": "Nuevo cliente",
  "areYouSureYouAreDone": "¿Estás seguro de que quieres terminar esta sesión?",
  "resetApp": "Restablecer la aplicación",
  "scanYourDocument": "Por favor escanea tu documento",
  "invalidCountry": "País no válido escaneado",
  "wrongDocumentTypePleaseTryAgain": "Tipo de documento incorrecto. Inténtalo de nuevo",
  "wipeTheAppData": "Borrar los datos de la aplicación",
  "enterPasswordOrWipeOutTheAppData": "Introduzca la contraseña o borre los datos de la aplicación",
  "dateInTheFutureError": "{1} está en el futuro",
  "pleaseChooseDT": "Por favor, elija el tipo de documento primero"
}