module.exports = {
  "updateAppTitle": "Cập nhật ứng dụng có sẵn",
  "continue": "Tiếp tục",
  "incompatibleVersion": "Do các thay đổi không tương thích ngược thời gian gần đây, bản cập nhật này yêu cầu đặt lại khó khăn của ứng dụng. Nhấn OK để đặt lại danh tính và bộ nhớ của ứng dụng.",
  "multientryToShare": "Có {1} tài liệu cần chia sẻ",
  "next": "Kế tiếp",
  "verificationBy": "Xác minh bởi {1}",
  "initializingEngine": "khởi động động cơ",
  "centerLicence": "Giấy phép trung tâm trong khung",
  "later": "Một lát sau",
  "denyApplication": "Từ chối ứng dụng",
  "sharedForm": "Đã chia sẻ {1} từ {2}",
  "documentExpiredTitle": "Tài liệu đã hết hạn",
  "digitalWealthPassport": "Digital Wealth Passport",
  "enablePassword": "Bật mật khẩu",
  "shareOneOfMany": "Ngoài ra, hãy chia sẻ bên dưới",
  "sentToOn": "Đã gửi đến {1} vào",
  "verificationTransactionID": "Id giao dịch xác minh",
  "drawYourPasswordAgain": "Vẽ lại mẫu của bạn",
  "listOfProducts": "Danh sách sản phẩm",
  "receiveNotifications?": "Bạn có muốn nhận thông báo không?",
  "receivedProduct": "Đã nhận {1}",
  "sandboxDescription": "Trong Sandbox, tìm hiểu cách sử dụng ứng dụng với các nhà cung cấp dịch vụ mô phỏng.",
  "fillTheForm": "Vui lòng điền vào biểu mẫu này ** {1} **",
  "iproovErrorTitle": "Rất tiếc! Đã xảy ra sự cố",
  "resetRequired": "Yêu cầu đặt lại",
  "importYourData": "Nhập dữ liệu của bạn",
  "yes": "Vâng",
  "centerPassport": "Trang ảnh hộ chiếu trung tâm trong khung",
  "areYouSureYouWantToServeThisCustomer": "Bạn có chắc chắn muốn phục vụ khách hàng này không?",
  "switchTouchIdOn": "Bật ID cảm ứng",
  "holdPhoneToPassport": "Giữ mặt sau của điện thoại với bìa trước của hộ chiếu",
  "testProviders": "Sandbox",
  "contactUs": "Liên hệ chúng tôi",
  "setDateValue": "Bộ",
  "trustedProviders": "Nhà cung cấp đáng tin cậy",
  "useTouchId": "Bật Touch ID",
  "inProgress": "Yêu cầu của bạn đang được xử lý",
  "neverMissAMessage": "Không bao giờ bỏ lỡ một tin nhắn",
  "no": "Không",
  "generatingKeys": "tạo khóa riêng của bạn",
  "holdPhoneToPassportBackCover": "Giữ mặt sau của điện thoại của bạn vào mặt sau của bìa hộ chiếu của bạn.",
  "importData": "Nhập ngày",
  "myDocuments": "Tai liệu của tôi",
  "fillTheFormWithAttachments": "Vui lòng điền vào biểu mẫu này ** {1} **",
  "updateNow": "Cập nhật bây giờ",
  "youReviewedAll": "Bạn đã xem xét tất cả {1}",
  "iproovFailedMessage": "Vui lòng thử lại. Để có kết quả tốt nhất, hãy giữ khuôn mặt của bạn ở giữa hình bầu dục trong khi nhấp nháy màu.",
  "formListError": "Không có sẵn",
  "providerIsOffline": "{1} đang ngoại tuyến",
  "sourcesBy": "Nguồn bởi {1}",
  "validationErrors": "Vui lòng sửa các trường xác nhận không thành công",
  "dataSecurity": "Bảo mật dữ liệu",
  "unknownQRCodeFormat": "Định dạng mã QR không được công nhận",
  "updateAppMessage": "Cập nhật ngay bây giờ, hoặc tôi sẽ nhắc bạn sau?",
  "backTo": "Quay lại {1}",
  "submitting": "Đang gửi",
  "youShallNotPass": "Bạn sẽ không vượt qua!",
  "noAccessToServer": "Máy chủ không thể truy cập được. Thử lại sau.",
  "centerID": "ID trung tâm trong khung",
  "acceptingTermsAndConditions": "Bằng cách nhấn OK, bạn chấp nhận các Điều khoản và Điều kiện",
  "typeMessage": "Gõ một tin nhắn",
  "search": "Tìm kiếm",
  "createNext": "Điền vào biểu mẫu khác \"{1}\"",
  "scanQRcode": "Quét mã QR",
  "noNetwork": "Không có mạng",
  "shareChangesWith": "Chia sẻ thay đổi với",
  "shareContext": "Chia sẻ {1}",
  "shareWith": "Chia sẻ {1}",
  "learnMore": "Tìm hiểu thêm",
  "youAreForgotten": "Bạn đã quên thành công",
  "issuedBy": "Cấp bởi {1}",
  "installingUpdate": "Đang cài đặt bản cập nhật",
  "loadingModels": "tải mô hình",
  "youReviewed": "Bạn đã xem xét {1} trong tổng số {2} mục",
  "creationDate": "Ngày tạo",
  "nothingChanged": "không có gì thay đổi",
  "pairingRequest": "Yêu cầu ghép nối",
  "passwordOn": "Mật khẩu cử chỉ đang BẬT",
  "newContactRequest": "{1} đã gửi cho bạn yêu cầu liên hệ",
  "applyForProduct": "Áp dụng cho một sản phẩm",
  "viewDebugLog": "Xem nhật ký gỡ lỗi",
  "willBeAvailable": "Chức năng này sẽ sớm khả dụng",
  "somethingWrong": "Đã xảy ra sự cố",
  "loadingResources": "tải tài nguyên",
  "fromMyData": "từ 'Dữ liệu của tôi'",
  "authenticationFailed": "Quá trình xác thực đã thất bại",
  "enterPassword": "Nhập mật khẩu của bạn",
  "submittingModifiedForm": "Sửa đổi {1}",
  "pleaseClickOnAddButton": "Vui lòng nhấp vào '+' bên dưới để thêm '{1}'",
  "profile": "Hồ sơ",
  "turnPasswordOn": "Bật mật khẩu cử chỉ",
  "setNewPassword": "Chọn một mật khẩu mới",
  "youShared": "Bạn đã chia sẻ từ {1}",
  "shareProduct": "Bạn có thể nhấn vào bên dưới để chia sẻ {1} với {2}",
  "shareMyProduct": "Bạn có thể nhấn vào bên dưới để chia sẻ {1} với {2}",
  "touchIdOn": "ID cảm ứng đang BẬT",
  "bothOn": "Cả hai đều BẬT",
  "changePassword": "Đổi mật khẩu",
  "hideResource": "Ẩn {1}",
  "add": "Thêm {1}",
  "createNew": "Điền vào biểu mẫu \"{1}\"",
  "acceptTermsAndConditions": "Xem điều khoản và điều kiện",
  "submittingForm": "Đã gửi {1}",
  "confirmAllItems": "Nhấn OK để xác nhận tất cả hoặc Hủy để tiếp tục đánh giá",
  "officialAccounts": "Cuộc trò chuyện",
  "switchToRepresentative": "Chuyển sang chế độ đại diện chưa được triển khai.",
  "sponsoredBy": "Được tài trợ bởi",
  "fieldErrorMessagePrompt": "Có vấn đề gì với lĩnh vực này?",
  "pleaseTapOnMenu": "Vui lòng nhấn vào nút màu đỏ và",
  "pleaseRestartTIM": "Vui lòng khởi động lại TiM",
  "addNew": "Thêm mới {1}",
  "newProductMsg": "Tôi cần một {1}.",
  "changeGesturePassword": "Thay đổi mật khẩu cử chỉ",
  "useTouchIdAndGesturePassword": "Bật Touch ID và Cử chỉ",
  "oops": "Rất tiếc",
  "verifiedByOn": "Được xác minh bởi {1} vào",
  "storageCorrupted": "bộ nhớ trình duyệt của bạn đã bị hỏng! Nhấn OK để đặt lại danh tính và bộ nhớ của ứng dụng.",
  "newProduct": "Sản phẩm mới",
  "restartApp": "Khởi động lại ứng dụng",
  "done": "Làm xong",
  "noScanningOnAndroid": "Tính năng quét tài liệu trên Android sắp ra mắt.",
  "unreadMessages": "Bạn có tin nhắn chưa đọc",
  "formChooser": "Danh sách biểu mẫu",
  "showQR": "Mã QR của tôi",
  "iproovFailedTitle": "Rất tiếc! Đã xảy ra sự cố",
  "importingData": "Nhập {1} tài liệu từ {2}",
  "sentTo": "Đã gửi đến {1}",
  "contextsFor": "Các ngữ cảnh cho",
  "importing": "Nhập",
  "forgetMe": "Quên tôi đi",
  "en": "Anh",
  "switchTouchIdOff": "Tắt ID cảm ứng",
  "submitLog": "Gửi Nhật ký",
  "shareOne": "Ngoài ra, hãy chia sẻ bên dưới",
  "pairingRequestWasProcesseed": "Yêu cầu ghép nối đã được xử lý",
  "addServerUrl": "Thêm url máy chủ",
  "passwordLimitations": "Mẫu phải có hơn 5 điểm",
  "pairDevices": "Ghép nối thiết bị",
  "invalidPairingRequest": "Yêu cầu ghép nối không hợp lệ",
  "confirmRevoke": "Yêu cầu {1} xóa tài liệu này khỏi hồ sơ của họ?",
  "asVerifiedBy": "Được xác minh bởi {1}",
  "pleaseCorrectTheErrors": "Vui lòng sửa lỗi trong biểu mẫu",
  "youAreAboutToShare": "Bạn sắp chia sẻ\n '{1}'\n các tài liệu",
  "messageWaitingFrom": "Bạn có một tin nhắn mới từ {1}",
  "verifyPrompt": "Kiểm chứng?",
  "termsAndConditions": "Các điều khoản và điều kiện.",
  "error": "lỗi",
  "issuedByOn": "Được cấp bởi {1} vào",
  "sharedWith": "Đã chia sẻ {1} ngữ cảnh với {2}",
  "errorNotification": "Thông báo lỗi đã được gửi đến khách hàng để sửa",
  "nameUnknown": "tên không xác định",
  "customerWaiting": "{1} đã tham gia trò chuyện",
  "learnMoreDescription": "Bạn vẫn có thể viết tin nhắn ở Chế độ ngoại tuyến ngay cả khi thiết bị của bạn không được kết nối. Khi bạn kết nối lại tất cả các tin nhắn của bạn sẽ được tự động gửi đi.",
  "independentBlockchainViewer": "Trình xem blockchain độc lập",
  "invalidDocument": "tài liệu không hợp lệ",
  "areYouSureYouWantToConfirmAllItems": "Nhấn OK để xác nhận tất cả {1} hoặc Hủy để tiếp tục đánh giá",
  "youAreTheRM": "Bạn là Quản lý quan hệ cho ứng dụng này",
  "pleaseCorrectFields": "Vui lòng sửa các trường sau: {1}",
  "pleaseCorrect": "Vui lòng sửa",
  "noConnection": "{appName} yêu cầu kết nối internet đang hoạt động mà bạn không có tại thời điểm này",
  "somethingWrongSubmitLog": "Một cái gì đó dường như đã đi sai. Vui lòng gửi nhật ký gỡ lỗi cho nhóm nhà phát triển {appName}",
  "sharedContext": "Ngữ cảnh được chia sẻ",
  "backToResults": "Quay lại kết quả",
  "nothingToShare": "Không có gì để chia sẻ",
  "turnTouchIdOn": "Bật ID cảm ứng",
  "confirmedMyData": "Bạn có thể xem tất cả dữ liệu đã nhập trong {profileTitle} của mình",
  "viewTerms": "Vui lòng xem Điều khoản và Điều kiện",
  "sendEditRequestPrompt": "Gửi yêu cầu chỉnh sửa đến {1}?",
  "downloadingUpdate": "Đang tải xuống bản cập nhật ...",
  "areYouSureYouWantToDelete": "Bạn có chắc chắn muốn ẩn {1} không?",
  "thisValueIsInvalidPlaceholder": "giá trị này không hợp lệ vì ...",
  "formListErrorDescription": "Các biểu mẫu có thể được yêu cầu khi khách hàng bắt đầu một ứng dụng",
  "iproovErrorMessage": "Vui lòng chờ một chút và thử lại",
  "learnMoreServerIsDown": "Bất kỳ thư nào bạn viết sẽ được tự động gửi đến {1} khi chúng trực tuyến.",
  "shareAllPastAndFutureMessages": "Chia sẻ tất cả các tin nhắn trong quá khứ và tương lai trong ngữ cảnh này với các bên được chọn",
  "areYouSureAboutNextForm": "Bạn có chắc là bạn đã hoàn thành {1}?",
  "addAnotherFormOrGetNext": "Thêm một {1} khác hoặc chuyển sang biểu mẫu tiếp theo",
  "areYouSureAboutWipe": "Hành động này là không thể đảo ngược. Bạn sẽ mất tất cả dữ liệu và khóa riêng tư của mình. Bạn có chắc muốn tiếp tục?",
  "cancelHideResource": "Hủy Ẩn {1}",
  "overviewOfApplications": "Tổng quan về ứng dụng",
  "serverIsUnreachable": "Máy chủ không thể truy cập được",
  "ukLicenseUnsupported": "Quét giấy phép lái xe tại Vương quốc Anh không được hỗ trợ tại thời điểm này",
  "fillRequiredFields": "Vui lòng điền vào tất cả các trường bắt buộc",
  "deviceDoesNotHaveMyKeys": "Nhận dạng đã không có khóa của tôi",
  "shareOneOfMany1": "{1}, đây là trợ lý bảo mật cá nhân của bạn. Tôi thấy bạn đã có {2} xác minh của mình. Bạn có thể nhấn vào bất kỳ mục nào trong danh sách bên dưới để chia sẻ chúng với {3}.",
  "drawYourNewPasswordAgain": "Vẽ lại mẫu mới",
  "searchSomething": "Tìm kiếm {1}",
  "gestureNotRecognized": "Mẫu sai",
  "invalidPropertyValue": "giá trị không hợp lệ",
  "iNeed": "Tôi cần...",
  "drawYourPassword": "Vẽ hình của bạn",
  "theMinValueBiggerThenMaxValue": "Giá trị nhỏ nhất của dải ô phải nhỏ hơn giá trị lớn nhất",
  "verifierHelp": "Nhấp vào nút 'Hoàn tất' sau khi xem xét biểu mẫu. Nếu một số trường yêu cầu sửa, hãy kiểm tra chúng trước và sau đó nhấp vào nút 'Xong'",
  "correctPassword": "Aww, bạn nhớ rồi!",
  "homePage": "Nhà",
  "textPasswordLimitations": "Phải có hơn 10 ký tự, ít nhất một chữ hoa, chữ thường, số và ký tự đặc biệt",
  "temporarilyLocked": "Để bảo vệ bạn, ứng dụng này đã bị khóa tạm thời cho {1}",
  "pleaseDrawPassword": "Vẽ hình của bạn",
  "irrefutableProofs": "Chứng minh không thể chối cãi",
  "reviewScannedProperties": "Vui lòng xem lại và sửa dữ liệu bên dưới",
  "enterCurrentPassword": "Nhập mật khẩu hiện tại của bạn",
  "invalidDeepLink": "Có vẻ như bạn đã nhấp vào một liên kết không hợp lệ!",
  "ok": "được",
  "formRequest": "Yêu cầu cho {1}",
  "wrongPattern": "Mẫu sai",
  "thisFieldIsRequired": "Trường này là bắt buộc",
  "approveApplicationFor": "Phê duyệt đơn đăng ký cho {1}",
  "approveApplication": "Phê duyệt đơn đăng ký",
  "retryScanning": "Đó có phải là {1} không? Tôi không thể nói. Vui lòng thử lại?\n\nĐể có kết quả tốt nhất, hãy sử dụng chế độ ngang, tránh ánh sáng chói và đảm bảo định vị tài liệu trong khung được hiển thị.",
  "testForgetMe": "Đây là cơ chế thử nghiệm để đặt lại tất cả các liên lạc với nhà cung cấp này",
  "denyApplicationFor": "Từ chối đơn đăng ký {1}",
  "enableCameraAccess": "{appName} hiện không có quyền sử dụng máy ảnh. Để cấp quyền truy cập, chọn Cài đặt và đảm bảo Máy ảnh được bật.",
  "documentNotScanning": "Rất tiếc, đã xảy ra sự cố!",
  "asSentTo": "Được gửi đến {1}",
  "cameraAccess": "Truy cập máy ảnh",
  "scanningFailedTryAgain": "Quá trình quét không thành công. Bạn có thể thử lại không?",
  "tooManyPasswordAttempts": "Quá nhiều lần thử không thành công! Biểu mẫu này đã bị tắt.",
  "optional": "không bắt buộc",
  "back": "Trở lại",
  "settings": "Cài đặt",
  "thePropertyWithMinMaxRangeError": "Thuộc tính có phạm vi [min-max] chỉ có thể có hai số",
  "cancel": "Hủy bỏ",
  "hello": "Xin chào {1}!",
  "details": "Chi tiết",
  "invalidPattern": "Mẫu sai",
  "patternNotMatching": "Các mẫu không khớp.",
  "tapToRemovePhotos": "Nhấn để xóa ảnh",
  "confirmForgetMe": "Bạn có chắc chắn muốn '{1}' quên bạn",
  "edit": "Chỉnh sửa",
  "enterYourName": "Nhập tên của bạn",
  "receivedVerification": "Đã xác minh đã nhận cho {1}",
  "restartingApp": "Ứng dụng sẽ khởi động lại trong giây lát",
  "enablePasscodeFirst": "Có vẻ như bạn chưa bật mã khóa thiết bị. Nếu không có nó, ứng dụng này không thể bảo vệ dữ liệu của bạn! Vui lòng kích hoạt nó trước khi nhấn OK",
  "nl": "Người hà lan",
  "documentExpiredMessage": "Vui lòng quét tài liệu hợp lệ",
  "importDataPrompt": "Bạn sắp nhập dữ liệu của mình từ",
  "shareOne1": "{1}, đây là trợ lý bảo mật cá nhân của bạn. Tôi thấy bạn đã có {2} xác minh của mình. Bạn có thể nhấn vào bên dưới để chia sẻ nó với {3}.",
  "learnMoreDescriptionTo": "Bạn vẫn có thể viết tin nhắn ở Chế độ ngoại tuyến ngay cả khi thiết bị của bạn không được kết nối. Khi bạn kết nối lại tất cả các tin nhắn của bạn sẽ được tự động gửi đến {1}.",
  "takeAPicture": "Vui lòng chụp ảnh tự sướng ** trên khuôn mặt của bạn",
  "useGesturePassword": "Bật mật khẩu cử chỉ",
  "drawYourOldPassword": "Vẽ mẫu cũ của bạn",
  "noConnectionForNewProduct": "{1}, {appName} yêu cầu kết nối internet hoạt động để điền vào đơn đăng ký {2}.",
  "noConnectionForPL": "{appName} yêu cầu kết nối internet hoạt động để yêu cầu danh sách các sản phẩm từ {1} mà bạn không có vào lúc này",
  "noConnectionWillProcessLater": "{appName} yêu cầu kết nối internet đang hoạt động mà bạn không có tại thời điểm này. Yêu cầu sẽ được xử lý khi kết nối được thiết lập",
  "turnBothOn": "Bật cả hai",
  "setPassword": "Chọn mật khẩu an toàn",
  "drawYourNewPassword": "Vẽ một mẫu mới",
  "correctGesture": "Đã phát hiện đúng mẫu",
  "invalidProperty": "{1} không hợp lệ",
  "verifiedBy": "Được xác minh bởi {1}",
  "passwordsDontMatch": "Mật khẩu không khớp",
  "unlockDevice": "mở khóa thiết bị của bạn để tiếp tục",
  "offlineMode": "Thời trang ngoại tuyến",
  "receivedForm": "Đã nhận {1}",
  "cancelItem": "Bạn sắp hủy {1}. Vui lòng nhấn OK để xác nhận",
  "help": "Cứu giúp",
  "exploreData": "Khám phá dữ liệu",
  "bookmarks": "Dấu trang",
  "ID document": "Tài liệu ID",
  "See our list of products": "Xem danh sách sản phẩm của chúng tôi",
  "Please scan your": "Vui lòng quét",
  "Please fill out the form": "Vui lòng điền vào mẫu đơn",
  "Choose Apply for Product from the menu": "Chọn Áp dụng cho Sản phẩm từ menu",
  "Our products have changed": "Sản phẩm của chúng tôi đã thay đổi",
  "Please take a selfie to prove this is your document. Center your face.": "Vui lòng chụp ảnh tự sướng để chứng minh đây là tài liệu của bạn. Trung tâm khuôn mặt của bạn.",
  "Application submitted!": "Đã gửi đơn đăng ký!",
  "Sending": "Gửi",
  "Please tap here and sign": "Vui lòng nhấn vào đây và ký tên",
  "Give me a moment...": "Cho tôi một chút ...",
  "Please click to scan your": "Vui lòng nhấp để quét",
  "Thank you. Now take a '": "Cảm ơn bạn. Bây giờ hãy '",
  "' photo of yourself that I can match against your ID document": "'ảnh của chính mình mà tôi có thể khớp với tài liệu ID của bạn",
  "pleaseSign": "Vui lòng đăng nhập vào ô màu xám",
  "getStarted": "Bắt đầu",
  "goodNewsFew": "Tin tốt! Bạn đã có khá một vài. Để chia sẻ biểu tượng nhấn bên dưới.",
  "goodNews": "Tin tốt! Bạn đã có {1}. Để chia sẻ nhấn vào biểu tượng bên dưới",
  "Clear": "Thông thoáng",
  "Cancel": "Hủy bỏ",
  "Submit": "Gửi đi",
  "usePhoto": "Sử dụng ảnh",
  "retake": "Tái lấy",
  "Approve": "Phê duyệt",
  "Deny": "Từ chối",
  "loading": "Tải...",
  "Seals": "Con dấu",
  "Applications": "Các ứng dụng",
  "Corporation Exists Checks": "Công ty kiểm tra tồn tại",
  "Verifications": "Xác minh",
  "checkIfMatch": "Kiểm tra xem có khớp không",
  "createManualMatchCheck": "Tạo kiểm tra đối sánh thủ công",
  "Go friendliness!": "Đi thân thiện!",
  "Get set for friendliness?": "Được thiết lập cho sự thân thiện?",
  "Take a quick tour of chat bot?": "Tham quan nhanh bot trò chuyện?",
  "Finally, you will be in control of your own private information!": "Cuối cùng, bạn sẽ kiểm soát thông tin cá nhân của riêng bạn!",
  "Ready for friendliness?": "Sẵn sàng cho sự thân thiện?",
  "Get set": "Được thiết lập",
  "Ready?": "Sẳn sàng?",
  "Go!": "Đi!",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Chúng tôi sẽ hỏi bạn các câu hỏi trong cuộc trò chuyện và bạn chỉ cần điền vào các biểu mẫu hoặc làm theo các yêu cầu",
  "Before we start you'll need a valid passport, identity card or driving license": "Trước khi bắt đầu, bạn cần có hộ chiếu hợp lệ, giấy chứng minh nhân dân hoặc giấy phép lái xe",
  "Done": "Làm xong",
  "Next": "Kế tiếp",
  "Skip": "Bỏ qua",
  "Sanctions Checks": "Kiểm tra xử phạt",
  "inProcess": "Đang tiến hành...",
  "networkFailure": "Tôi đang gặp một số vấn đề về mạng. Bạn có thể kiểm tra và sau đó nhấn Thử lại / Hủy",
  "invalidQuery": "Rất tiếc, chúng tôi đã gặp lỗi khi chạy tìm kiếm của bạn. Các nhà phát triển của chúng tôi sẽ cố gắng khắc phục nó càng sớm càng tốt.",
  "supportedQrCodes": "Mã QR được hỗ trợ:\n1) thêm kênh trò chuyện\n2) nhập dữ liệu",
  "noResourcesForCriteria": "Không tìm thấy tài nguyên cho tiêu chí này",
  "validatingDataClaim": "Nhập dữ liệu",
  "logSentToDevTeam": "Nhật ký đã được gửi đến nhóm nhà phát triển Tradle",
  "invalidQR": "Mã QR không hợp lệ",
  "failedToSendLog": "Không thể gửi nhật ký",
  "debugLogSent": "Nhật ký gỡ lỗi đã được gửi",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Vui lòng xem lại dữ liệu bên dưới và chụp nhanh mặt {1} của tài liệu",
  "documentBackSide": "Trung tâm tài liệu mặt sau",
  "Photo": "ảnh",
  "startedByAnotherEmployee": "Ứng dụng cho {1} đã được bắt đầu bởi một nhân viên khác",
  "doYouWantToContinue": "Bạn có muốn chuyển sang nó và tiếp tục từ đó không?",
  "reviewData": "Đánh giá dữ liệu",
  "afterRefresh": "Bạn được xóa sử dụng dịch vụ của chúng tôi mà không bị gián đoạn",
  "requestMyData": "Yêu cầu dữ liệu của tôi",
  "newCustomer": "Khách hàng mới",
  "areYouSureYouAreDone": "Bạn có chắc chắn muốn kết thúc phiên này không?",
  "scanYourDocument": "Vui lòng quét tài liệu của bạn",
  "wrongDocumentTypePleaseTryAgain": "Loại tài liệu sai. Vui lòng thử lại",
  "resetApp": "Đặt lại ứng dụng",
  "invalidCountry": "Quốc gia được quét không hợp lệ",
  "enterPasswordOrWipeOutTheAppData": "Nhập mật khẩu hoặc xóa dữ liệu ứng dụng",
  "wipeTheAppData": "Xóa dữ liệu ứng dụng",
  "pleaseChooseCountryAndDT": "Vui lòng chọn quốc gia và loại tài liệu trước"
}