module.exports = {
  "nl": "Голландский",
  "sharedWith": "Общий {1} контекст с {2}",
  "submitting": "предоставление",
  "invalidDocument": "недействительный документ",
  "back": "назад",
  "addNew": "Добавить новый {1}",
  "fillTheFormWithAttachments": "Пожалуйста, заполните эту форму ** {1} **",
  "messageWaitingFrom": "Вы получили новое сообщение от {1}",
  "validationErrors": "Пожалуйста, исправьте ошибочные поля проверки",
  "storageCorrupted": "Данные и хранилище ключей вашего приложения повреждены! Если вы считаете, что это ошибка, нажмите «Перезагрузить приложение», чтобы повторить попытку. Нажатие «Сбросить приложение» приведет к сбросу идентификатора приложения и его хранилища.",
  "updateNow": "Обновить сейчас",
  "forgetMe": "Забудь меня",
  "confirmRevoke": "Попросить {1} удалить этот документ из своих записей?",
  "importData": "Импорт данных",
  "addAnotherFormOrGetNext": "Добавить еще один {1} или перейти к следующей форме",
  "youAreForgotten": "Вы были успешно забыты",
  "thePropertyWithMinMaxRangeError": "Свойство с диапазоном [min-max] может иметь только два числа",
  "showQR": "Мой QR код",
  "verifiedByOn": "Проверено {1} на",
  "add": "Добавить {1}",
  "asSentTo": "Как отправлено на {1}",
  "ok": "Хорошо",
  "typeMessage": "Введите сообщение",
  "noScanningOnAndroid": "Сканирование документов на Android в ближайшее время.",
  "restartingApp": "Приложение будет перезапущено на мгновение",
  "testProviders": "песочница",
  "profile": "Профиль",
  "shareOneOfMany": "В качестве альтернативы, поделитесь ниже",
  "newProductMsg": "Мне нужен {1}.",
  "setPassword": "Выберите безопасный пароль",
  "somethingWrong": "Что-то пошло не так",
  "termsAndConditions": "Условия и положения.",
  "viewDebugLog": "Просмотр журнала отладки",
  "passwordsDontMatch": "Пароли не совпадают",
  "errorNotification": "Клиенту отправлено уведомление об ошибке для исправления",
  "drawYourNewPasswordAgain": "Нарисуйте новый шаблон снова",
  "enterPassword": "Введите ваш пароль",
  "installingUpdate": "Устанавливается обновление",
  "continue": "Продолжить",
  "importYourData": "Импортируйте ваши данные",
  "changeGesturePassword": "Изменить пароль жеста",
  "sendEditRequestPrompt": "Отправить запрос на изменение в {1}?",
  "restartApp": "Перезагрузите приложение",
  "fieldErrorMessagePrompt": "Что не так с этим полем?",
  "contactUs": "Связаться с нами",
  "passwordOn": "Пароль Жеста включен",
  "pleaseCorrectTheErrors": "Пожалуйста, исправьте ошибку в форме",
  "switchToRepresentative": "Переключение в репрезентативный режим еще не реализовано.",
  "scanQRcode": "Сканировать QR-код",
  "shareOne": "В качестве альтернативы, поделитесь ниже",
  "correctPassword": "Ой, ты вспомнил!",
  "verifiedBy": "Проверено {1}",
  "retryScanning": "Это был {1}? Я не мог сказать. Пожалуйста, попробуйте еще раз?\n\nДля достижения наилучших результатов используйте альбомный режим, избегайте бликов и не забудьте расположить документ в показанной рамке.",
  "iproovErrorTitle": "К сожалению! Что-то пошло не так",
  "en": "английский",
  "pleaseRestartTIM": "Пожалуйста, перезапустите TiM",
  "updateAppTitle": "Доступно обновление приложения",
  "edit": "редактировать",
  "importDataPrompt": "Вы собираетесь импортировать ваши данные из",
  "fillRequiredFields": "Пожалуйста, заполните все обязательные поля",
  "officialAccounts": "Диалоги",
  "iNeed": "Я нуждаюсь...",
  "help": "Помогите",
  "loadingModels": "загрузка моделей",
  "viewTerms": "Пожалуйста, ознакомьтесь с Условиями",
  "deviceDoesNotHaveMyKeys": "Полученная личность не имеет моих ключей",
  "sourcesBy": "Источники по {1}",
  "done": "Готово",
  "thisFieldIsRequired": "Это поле обязательно к заполнению",
  "authenticationFailed": "Ошибка аутентификации",
  "newContactRequest": "{1} отправил вам контактный запрос",
  "backToResults": "Вернуться к результатам",
  "searchSomething": "Поиск {1}",
  "drawYourOldPassword": "Нарисуй свой старый шаблон",
  "issuedByOn": "Выдано {1} на",
  "customerWaiting": "{1} вошел в чат",
  "overviewOfApplications": "Обзор приложений",
  "shareProduct": "Вы можете нажать ниже, чтобы поделиться {1} с {2}",
  "pleaseClickOnAddButton": "Пожалуйста, нажмите «+» ниже, чтобы добавить «{1}»",
  "gestureNotRecognized": "Неправильный образец",
  "tapToRemovePhotos": "Нажмите, чтобы удалить фотографии",
  "enterYourName": "Введите ваше имя",
  "tooManyPasswordAttempts": "Слишком много неудачных попыток! Эта форма была отключена.",
  "myDocuments": "Мои документы",
  "submitLog": "Отправить журнал",
  "later": "Потом",
  "issuedBy": "Выдано {1}",
  "backTo": "Вернуться к {1}",
  "cameraAccess": "Доступ к камере",
  "enterCurrentPassword": "введи свой текущий пароль",
  "newProduct": "Новый продукт",
  "creationDate": "Дата создания",
  "nameUnknown": "имя неизвестно",
  "learnMore": "Учить больше",
  "trustedProviders": "Доверенные провайдеры",
  "listOfProducts": "Список продуктов",
  "youShallNotPass": "Ты не должен пройти!",
  "oops": "ой",
  "setDateValue": "Задавать",
  "centerID": "Идентификатор центра в кадре",
  "formListError": "Недоступен",
  "cancel": "отменить",
  "addServerUrl": "Добавить URL сервера",
  "shareOneOfMany1": "{1}, это ваш личный помощник по конфиденциальности. Я вижу, вы уже проверили {2}. Вы можете нажать на любой элемент в списке ниже, чтобы поделиться им с {3}.",
  "enablePassword": "Включить пароль",
  "centerPassport": "Центр паспорт фото в рамке",
  "youReviewed": "Вы просмотрели {1} из {2} товаров",
  "somethingWrongSubmitLog": "Кажется, что-то пошло не так. Пожалуйста, отправьте журнал отладки в команду разработчиков {appName}",
  "drawYourPasswordAgain": "Нарисуй свой рисунок снова",
  "pleaseDrawPassword": "Нарисуй свой рисунок",
  "settings": "настройки",
  "invalidPattern": "Неправильный образец",
  "iproovFailedTitle": "К сожалению! Что-то пошло не так",
  "initializingEngine": "инициализирующий двигатель",
  "denyApplication": "Запретить заявку",
  "verificationBy": "Проверка по {1}",
  "learnMoreDescriptionTo": "Вы по-прежнему можете писать сообщения в автономном режиме, даже если ваше устройство не подключено. При повторном подключении все ваши сообщения будут автоматически отправляться на {1}.",
  "hideResource": "Скрыть {1}",
  "scanningFailedTryAgain": "Сканирование было неудачным. Не могли бы вы попробовать еще раз?",
  "optional": "необязательный",
  "sandboxDescription": "В Песочнице узнайте, как использовать приложение с симулированными поставщиками услуг.",
  "willBeAvailable": "Эта функциональность будет доступна в ближайшее время",
  "temporarilyLocked": "Для вашей защиты это приложение временно заблокировано для {1}",
  "noAccessToServer": "Сервер недоступен. Попробуй позже.",
  "invalidPairingRequest": "Неверный запрос на сопряжение",
  "confirmAllItems": "Нажмите «ОК», чтобы подтвердить их все, или «Отмена», чтобы продолжить просмотр.",
  "verifyPrompt": "Проверьте?",
  "downloadingUpdate": "Загрузка обновления ...",
  "pleaseTapOnMenu": "Пожалуйста, нажмите на красную кнопку и",
  "passwordLimitations": "Узор должен иметь 5+ очков",
  "search": "Поиск",
  "hello": "Здравствуйте, {1}!",
  "shareOne1": "{1}, это ваш личный помощник по конфиденциальности. Я вижу, вы уже проверили {2}. Вы можете нажать ниже, чтобы поделиться им с {3}.",
  "wrongPattern": "Неправильный образец",
  "fillTheForm": "Пожалуйста, заполните эту форму ** {1} **",
  "receivedProduct": "Получено {1}",
  "shareMyProduct": "Вы можете нажать ниже, чтобы поделиться {1} с {2}",
  "centerLicence": "Центр лицензии в рамке",
  "inProgress": "В ходе выполнения...",
  "areYouSureYouWantToServeThisCustomer": "Вы уверены, что хотите обслужить этого клиента?",
  "providerIsOffline": "{1} не в сети",
  "confirmedMyData": "Все импортированные данные можно просмотреть в вашем {profileTitle}",
  "takeAPicture": "Пожалуйста, сделайте ** селфи ** фотографию вашего лица",
  "offlineMode": "Автономный режим",
  "switchTouchIdOff": "Выключить сенсорный ID",
  "homePage": "Главная",
  "patternNotMatching": "Шаблоны не совпадают.",
  "invalidPropertyValue": "Неверное значение",
  "invalidProperty": "Неверно {1}",
  "bothOn": "Оба включены",
  "sharedForm": "Shared {1}",
  "pleaseCorrectFields": "Пожалуйста, исправьте следующие поля: {1}",
  "thisValueIsInvalidPlaceholder": "это значение недопустимо, потому что ...",
  "next": "следующий",
  "correctGesture": "Обнаружен правильный шаблон",
  "theMinValueBiggerThenMaxValue": "Минимальное значение для диапазона должно быть меньше максимального значения",
  "approveApplicationFor": "Одобрить заявку на {1}",
  "confirmForgetMe": "Вы уверены, что хотите, чтобы {1} забыл вас?",
  "nothingChanged": "Ничего не изменилось",
  "cancelHideResource": "Отмена Скрыть {1}",
  "multientryToShare": "{1} документов для обмена",
  "areYouSureYouWantToDelete": "Вы уверены, что хотите скрыть {1}?",
  "youAreTheRM": "Вы менеджер по связям для этого приложения",
  "sponsoredBy": "При финансовой поддержке",
  "neverMissAMessage": "Никогда не пропустите сообщение",
  "importing": "Импорт",
  "documentExpiredTitle": "Срок действия документа истек",
  "unknownQRCodeFormat": "Нераспознанный формат QR-кода",
  "touchIdOn": "Touch ID включен",
  "shareChangesWith": "Поделиться изменениями с",
  "useGesturePassword": "Включить пароль жеста",
  "importingData": "Импорт {1} документов из {2}",
  "contextsFor": "Контексты для",
  "receivedForm": "Получено {1}",
  "sharedContext": "Общий контекст",
  "dataSecurity": "Безопасность данных",
  "useTouchIdAndGesturePassword": "Включить Touch ID и Жест",
  "changePassword": "Изменить пароль",
  "learnMoreServerIsDown": "Все написанные вами сообщения будут автоматически отправляться на {1} при их подключении к сети.",
  "documentExpiredMessage": "Пожалуйста, отсканируйте действительный документ",
  "ukLicenseUnsupported": "В настоящее время сканирование водительских прав в Великобритании не поддерживается",
  "youReviewedAll": "Вы просмотрели все {1}",
  "error": "ошибка",
  "fromMyData": "из «Мои данные»",
  "invalidDeepLink": "Похоже, вы нажали неверную ссылку!",
  "youAreAboutToShare": "Вы собираетесь поделиться\n '{1}'\n документы",
  "noNetwork": "Нет сети",
  "textPasswordLimitations": "Должно иметь более 10 символов, как минимум одну заглавную букву, строчную букву, цифру и специальный символ",
  "setNewPassword": "Выберите новый пароль",
  "unlockDevice": "разблокировать устройство, чтобы продолжить",
  "drawYourNewPassword": "Нарисуйте новый шаблон",
  "loadingResources": "загрузка ресурсов",
  "yes": "да",
  "shareWith": "Поделиться {1}",
  "turnBothOn": "Включите оба",
  "approveApplication": "Утвердить заявку",
  "holdPhoneToPassport": "Держите телефон на задней стороне паспорта",
  "areYouSureAboutNextForm": "Вы закончили добавлять {1}?",
  "updateAppMessage": "Обновите сейчас или я вам напомню позже?",
  "areYouSureAboutWipe": "Это действие необратимо. Вы потеряете все свои данные и личные ключи. Вы уверены, что хотите продолжить?",
  "applyForProduct": "Подать заявку на продукт",
  "digitalWealthPassport": "Паспорт цифрового богатства",
  "details": "подробности",
  "sentToOn": "Отправлено в {1}",
  "reviewScannedProperties": "Пожалуйста, просмотрите и исправьте данные ниже",
  "noConnectionWillProcessLater": "{appName} требует работающего подключения к Интернету, которого у вас нет на данный момент. Запрос будет обработан после установления соединения",
  "drawYourPassword": "Нарисуй свой рисунок",
  "no": "нет",
  "sentTo": "Отправлено в {1}",
  "shareContext": "Поделиться {1}",
  "asVerifiedBy": "Проверено {1}",
  "verificationTransactionID": "Идентификатор транзакции проверки",
  "formListErrorDescription": "Формы могут быть запрошены, как только клиент начинает заявку",
  "pairingRequest": "Запрос на сопряжение",
  "createNew": "Заполните форму \"{1}\"",
  "submittingForm": "Отправлено {1}",
  "enableCameraAccess": "{appName} в настоящее время не имеет разрешения на использование камеры. Чтобы предоставить доступ, выберите «Настройки» и убедитесь, что камера включена.",
  "documentNotScanning": "Упс! Что-то пошло не так!",
  "acceptingTermsAndConditions": "Нажав OK, вы принимаете Условия использования",
  "nothingToShare": "Нечего поделиться",
  "resetRequired": "Требуется сброс",
  "denyApplicationFor": "Запретить заявку на {1}",
  "receiveNotifications?": "Хотите получать уведомления?",
  "pleaseCorrect": "Пожалуйста исправьте",
  "switchTouchIdOn": "Включить сенсорный ID",
  "serverIsUnreachable": "Сервер недоступен",
  "submittingModifiedForm": "Модификация {1}",
  "receivedVerification": "Получено подтверждение для {1}",
  "pairDevices": "Пара устройств",
  "acceptTermsAndConditions": "Посмотреть условия",
  "youShared": "Вы поделились с {1}",
  "useTouchId": "Включить Touch ID",
  "generatingKeys": "генерация ваших личных ключей",
  "formRequest": "Запрос {1}",
  "cancelItem": "Вы собираетесь отменить {1}. Пожалуйста, нажмите OK, чтобы подтвердить",
  "iproovErrorMessage": "Пожалуйста, подождите немного и попробуйте снова",
  "unreadMessages": "У вас есть непрочитанные сообщения",
  "turnPasswordOn": "Включить пароль жеста",
  "noConnectionForNewProduct": "{1}, {appName} требует работающего подключения к Интернету для заполнения заявки {2}.",
  "createNext": "Заполните еще одну форму \"{1}\"",
  "pairingRequestWasProcesseed": "Запрос на сопряжение обработан",
  "enablePasscodeFirst": "Похоже, у вас не включен пароль устройства. Без этого это приложение не сможет защитить ваши данные! Пожалуйста, включите его, прежде чем нажимать ОК",
  "turnTouchIdOn": "Включить Touch ID",
  "irrefutableProofs": "Неопровержимые доказательства",
  "iproovFailedMessage": "Пожалуйста, попробуйте еще раз. Для достижения наилучших результатов держите ваше лицо в центре овала во время цветных вспышек.",
  "areYouSureYouWantToConfirmAllItems": "Нажмите OK, чтобы подтвердить все {1}, или Отмена, чтобы продолжить просмотр.",
  "shareAllPastAndFutureMessages": "Поделиться всеми прошлыми и будущими сообщениями в этом контексте с выбранными сторонами",
  "holdPhoneToPassportBackCover": "Держите заднюю часть телефона напротив задней обложки паспорта.",
  "incompatibleVersion": "Из-за недавних несовместимых изменений, данное обновление требует полной перезагрузки приложения. Нажмите OK, чтобы сбросить идентификатор приложения и его хранилище.",
  "learnMoreDescription": "Вы по-прежнему можете писать сообщения в автономном режиме, даже если ваше устройство не подключено. При повторном подключении все ваши сообщения будут автоматически отправлены.",
  "verifierHelp": "Нажмите кнопку «Готово» после просмотра формы. Если некоторые поля требуют исправления, сначала проверьте их, а затем нажмите кнопку «Готово».",
  "noConnectionForPL": "{appName} требует работающего подключения к Интернету для запроса списка продуктов из {1}, которого у вас нет на данный момент",
  "noConnection": "{appName} требует работающего подключения к Интернету, которого у вас нет на данный момент",
  "testForgetMe": "Это тестовый механизм для сброса всех коммуникаций с этим провайдером",
  "independentBlockchainViewer": "Независимый блокчейн-просмотрщик",
  "bookmarks": "закладки",
  "exploreData": "Исследуйте данные",
  "Please fill out the form": "Пожалуйста, заполните форму",
  "Choose Apply for Product from the menu": "Выберите Применить для продукта из меню",
  "See our list of products": "Смотрите наш список продуктов",
  "Please scan your": "Пожалуйста, отсканируйте ваш",
  "ID document": "Документ, удостоверяющий личность",
  "Our products have changed": "Наши продукты изменились",
  "Please take a selfie to prove this is your document. Center your face.": "Пожалуйста, сделайте селфи, чтобы доказать, что это ваш документ. Сосредоточьте свое лицо.",
  "Application submitted!": "Заявка отправлена!",
  "Sending": "Отправка",
  "Please tap here and sign": "Пожалуйста, нажмите здесь и подпишите",
  "Give me a moment...": "Дай мне минутку ...",
  "Please click to scan your": "Пожалуйста, нажмите, чтобы отсканировать ваш",
  "' photo of yourself that I can match against your ID document": "'фотография себя, которую я могу сопоставить с вашим документом",
  "Thank you. Now take a '": "Спасибо. Теперь возьми",
  "pleaseSign": "Пожалуйста, войдите в серый ящик",
  "getStarted": "Начать",
  "goodNewsFew": "Хорошие новости! У вас уже есть немало. Чтобы поделиться нажмите значок ниже.",
  "goodNews": "Хорошие новости! У вас уже есть {1}. Чтобы поделиться нажмите значок ниже",
  "Submit": "Отправить",
  "Clear": "Очистить",
  "Cancel": "отменить",
  "retake": "Пересдать",
  "usePhoto": "Использовать фото",
  "Approve": "Утвердить",
  "Deny": "Отрицать",
  "loading": "Loading ...",
  "Applications": "Приложения",
  "checkIfMatch": "Проверьте соответствие",
  "Seals": "Морские котики",
  "Verifications": "Верификация",
  "Corporation Exists Checks": "Корпорация существует чеки",
  "createManualMatchCheck": "Создать ручную проверку соответствия",
  "Ready for friendliness?": "Готовы к дружелюбию?",
  "Get set for friendliness?": "Готовы к дружелюбию?",
  "Take a quick tour of chat bot?": "Совершить быстрый тур по чат-боту?",
  "Go friendliness!": "Иди дружелюбие!",
  "Finally, you will be in control of your own private information!": "Наконец, вы будете контролировать свою личную информацию!",
  "Ready?": "Готовы?",
  "Go!": "Идти!",
  "Get set": "Приготовься",
  "Before we start you'll need a valid passport, identity card or driving license": "Прежде чем начать, вам понадобится действительный паспорт, удостоверение личности или водительские права.",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Мы зададим вам вопросы в чате, а вы просто заполните формы или выполните запросы",
  "Next": "следующий",
  "Skip": "Пропускать",
  "Done": "Готово",
  "Sanctions Checks": "Санкции Проверки",
  "inProcess": "Обработка ...",
  "networkFailure": "У меня проблемы с сетью. Можете ли вы проверить и затем нажать Повторить / Отмена",
  "invalidQuery": "К сожалению, при поиске произошла ошибка. Наши разработчики постараются исправить это как можно скорее.",
  "invalidQR": "Неверный QR-код",
  "validatingDataClaim": "Импорт данных",
  "supportedQrCodes": "Поддерживаемые QR-коды:\n1) добавить канал чата\n2) импортировать данные",
  "logSentToDevTeam": "Лог был отправлен команде разработчиков Tradle",
  "noResourcesForCriteria": "По этому критерию ресурсы не найдены",
  "debugLogSent": "Журнал отладки отправлен",
  "failedToSendLog": "Не удалось отправить журнал",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Просмотрите приведенные ниже данные и сделайте снимок {1} стороны документа.",
  "documentBackSide": "Центр документа на обратной стороне",
  "Photo": "Фото",
  "startedByAnotherEmployee": "Приложение для {1} было запущено другим сотрудником",
  "doYouWantToContinue": "Вы хотите переключиться на него и продолжить оттуда?",
  "reviewData": "Просмотр данных",
  "afterRefresh": "Вы можете использовать наши услуги без перерыва",
  "requestMyData": "Запрос моих данных",
  "newCustomer": "Новый покупатель",
  "areYouSureYouAreDone": "Вы уверены, что хотите закончить эту сессию?",
  "scanYourDocument": "Пожалуйста, отсканируйте ваш документ",
  "wrongDocumentTypePleaseTryAgain": "Неправильный тип документа. Пожалуйста, попробуйте еще раз",
  "resetApp": "Сбросить приложение",
  "invalidCountry": "Неверная страна отсканирована",
  "wipeTheAppData": "Протрите данные приложения",
  "enterPasswordOrWipeOutTheAppData": "Введите пароль или стереть данные приложения",
  "dateInTheFutureError": "{1} в будущем",
  "pleaseChooseDT": "Пожалуйста, сначала выберите тип документа",
  "formChooser": "Запросить форму"
}