module.exports = {
  "drawYourNewPassword": "គូរលំនាំថ្មី",
  "settings": "ការកំណត់",
  "switchTouchIdOn": "ប្ដូរលេខសម្គាល់ប៉ះ",
  "takeAPicture": "សូមថតរូប ** មុខខ្លួនឯង ** នៃមុខរបស់អ្នក",
  "verifiedBy": "បានផ្ទៀងផ្ទាត់ដោយ {1}",
  "shareMyProduct": "អ្នកអាចប៉ះខាងក្រោមដើម្បីចែករំលែក {1} ជាមួយ {2}",
  "addNew": "បន្ថែមថ្មី {1}",
  "switchTouchIdOff": "បិទលេខសម្គាល់ប៉ះ",
  "error": "កំហុស",
  "pairingRequestWasProcesseed": "សំណើផ្គូផ្គងត្រូវបានដំណើរការ",
  "search": "ស្វែងរក",
  "thisValueIsInvalidPlaceholder": "តម្លៃនេះមិនត្រឹមត្រូវទេព្រោះ ...",
  "enterPassword": "បញ្ចូលពាក្យសម្ងាត់របស់អ្នក",
  "enterYourName": "បញ្ចូល​ឈ្មោះ​របស់​អ្នក",
  "oops": "អូ៎",
  "importYourData": "នាំចូលទិន្នន័យរបស់អ្នក",
  "wrongPattern": "លំនាំមិនត្រឹមត្រូវ",
  "cancel": "បោះបង់",
  "sponsoredBy": "ឧបត្ថម្ភដោយ",
  "authenticationFailed": "ការផ្ទៀងផ្ទាត់បានបរាជ័យ",
  "shareContext": "ចែករំលែក {1}",
  "forgetMe": "បំភ្លេច​ខ្ញុំ",
  "continue": "បន្ត",
  "iproovErrorMessage": "សូមរង់ចាំបន្តិចហើយព្យាយាមម្តងទៀត",
  "retryScanning": "តើនោះជា {1} មែនទេ? ខ្ញុំមិនអាចប្រាប់បានទេ។ សូម​ព្យាយាម​ម្តង​ទៀត?\n\nសម្រាប់លទ្ធផលល្អបំផុតប្រើរបៀបទេសភាពជៀសវាងពន្លឺហើយត្រូវប្រាកដថាដាក់ឯកសារក្នុងស៊ុមដែលបានបង្ហាញ។",
  "hello": "សួស្ដី {1}!",
  "irrefutableProofs": "ភស្តុតាងមិនអាចបដិសេធបាន",
  "passwordLimitations": "លំនាំត្រូវតែមាន 5+ ចំណុច",
  "drawYourOldPassword": "គូរគំរូចាស់របស់អ្នក",
  "newProductMsg": "ខ្ញុំត្រូវការ {1} ។",
  "enterCurrentPassword": "បញ្ចូលពាក្យសម្ងាត់បច្ចុប្បន្នរបស់អ្នក",
  "denyApplication": "បដិសេធសំណើ",
  "restartingApp": "កម្មវិធីនឹងចាប់ផ្តើមឡើងវិញបន្តិច",
  "areYouSureAboutWipe": "សកម្មភាពនេះមិនអាចត្រឡប់វិញបានទេ។ អ្នកនឹងបាត់បង់ទិន្នន័យនិងកូនសោឯកជនរបស់អ្នក។ តើអ្នកប្រាកដជាចង់បន្តឬ?",
  "useTouchIdAndGesturePassword": "បើកដំណើរការ Touch ID និងកាយវិការ",
  "areYouSureYouWantToServeThisCustomer": "តើអ្នកប្រាកដថាអ្នកចង់បម្រើអតិថិជននេះទេ?",
  "youAreAboutToShare": "អ្នករៀបនឹងចែករំលែក\n '{1}'\n ឯកសារ",
  "correctGesture": "លំនាំត្រឹមត្រូវត្រូវបានរកឃើញ",
  "invalidProperty": "មិនត្រឹមត្រូវ {1}",
  "fillTheFormWithAttachments": "សូមបំពេញបែបបទនេះ ** {1} **",
  "willBeAvailable": "មុខងារនេះនឹងមានក្នុងពេលឆាប់ៗនេះ",
  "newProduct": "ផលិតផល​ថ្មី",
  "searchSomething": "ស្វែងរក {1}",
  "patternNotMatching": "គំរូមិនត្រូវគ្នា។",
  "shareOneOfMany1": "{1} នេះគឺជាអ្នកជំនួយការឯកជនម្នាក់របស់អ្នក។ ខ្ញុំដឹងថាអ្នកធ្លាប់មាន {2} ផ្ទៀងផ្ទាត់រួចហើយ។ អ្នកអាចប៉ះលើធាតុណាមួយនៅក្នុងបញ្ជីខាងក្រោមដើម្បីចែករំលែកវាជាមួយ {3} ។",
  "confirmRevoke": "សួរ {1} ដើម្បីលុបឯកសារនេះពីកំណត់ត្រារបស់ពួកគេ?",
  "pleaseRestartTIM": "សូមចាប់ផ្តើម TiM",
  "officialAccounts": "ការសន្ទនា",
  "drawYourNewPasswordAgain": "គូរលំនាំថ្មីម្តងទៀត",
  "shareChangesWith": "ចែករំលែកការផ្លាស់ប្តូរជាមួយ",
  "formRequest": "សំណើសម្រាប់ {1}",
  "receivedForm": "ទទួលបាន {1}",
  "issuedByOn": "បានចេញផ្សាយដោយ {1} នៅលើ",
  "back": "ថយក្រោយ",
  "documentNotScanning": "អូមានអ្វីមួយខុសឆ្គង!",
  "deviceDoesNotHaveMyKeys": "អត្តសញ្ញាណដែលបានទទួលមិនមានកូនសោរបស់ខ្ញុំទេ",
  "youAreTheRM": "អ្នកគឺជាប្រធានផ្នែកទំនាក់ទំនងសម្រាប់កម្មវិធីនេះ",
  "unlockDevice": "ដោះសោឧបករណ៍របស់អ្នកដើម្បីបន្ត",
  "changeGesturePassword": "ប្តូរពាក្យសម្ងាត់កាយវិការ",
  "showQR": "លេខកូដ QR របស់ខ្ញុំ",
  "profile": "ទម្រង់",
  "trustedProviders": "អ្នកផ្តល់សេវាដែលទុកចិត្ត",
  "holdPhoneToPassportBackCover": "សង្កត់ខាងក្រោយនៃទូរស័ព្ទរបស់អ្នកទៅខាងក្រោយគម្របខាងក្នុងនៃលិខិតឆ្លងដែនរបស់អ្នក។",
  "drawYourPasswordAgain": "គូរលំនាំរបស់អ្នកម្តងទៀត",
  "youReviewedAll": "អ្នកពិនិត្យមើល {1} ទាំងអស់",
  "messageWaitingFrom": "អ្នកមានសារថ្មីពី {1}",
  "gestureNotRecognized": "លំនាំមិនត្រឹមត្រូវ",
  "contactUs": "ទាក់ទង​មក​ពួក​យើង",
  "learnMoreDescription": "អ្នកនៅតែអាចសរសេរសារក្នុងរបៀបក្រៅបណ្ដាញទោះបីជាឧបករណ៍របស់អ្នកមិនបានភ្ជាប់។ នៅពេលដែលអ្នកភ្ជាប់ឡើងវិញសារទាំងអស់របស់អ្នកនឹងត្រូវបានផ្ញើដោយស្វ័យប្រវត្តិ។",
  "noConnectionForPL": "{appName} តម្រូវឱ្យមានការតភ្ជាប់អ៊ីនធឺណិតដំណើរការដើម្បីស្នើសុំបញ្ជីផលិតផលពី {1} ដែលអ្នកមិនមាននៅពេលនេះ",
  "youShallNotPass": "អ្នកមិនត្រូវហុច!",
  "applyForProduct": "ដាក់ពាក្យសុំផលិតផល",
  "passwordsDontMatch": "ពាក្យសម្ងាត់មិនត្រូវគ្នា",
  "formListErrorDescription": "ទម្រង់អាចត្រូវបានស្នើសុំនៅពេលដែលអតិថិជនចាប់ផ្តើមកម្មវិធី",
  "initializingEngine": "ចាប់ផ្ដើមម៉ាស៊ីន",
  "shareAllPastAndFutureMessages": "ចែករំលែកសារអតីតកាលនិងអនាគតទាំងអស់នៅក្នុងបរិបទនេះជាមួយភាគីដែលបានជ្រើសរើស",
  "asVerifiedBy": "បានផ្ទៀងផ្ទាត់ដោយ {1}",
  "overviewOfApplications": "ទិដ្ឋភាពទូទៅនៃកម្មវិធី",
  "receiveNotifications?": "តើអ្នកចង់ទទួលការជូនដំណឹងទេ?",
  "useTouchId": "បើកដំណើរការលេខសម្គាល់ទូច",
  "tooManyPasswordAttempts": "ការព្យាយាមបរាជ័យច្រើនដង! សំណុំបែបបទនេះត្រូវបានបិទ។",
  "turnPasswordOn": "បិទលេខសំងាត់កាយវិការ",
  "sendEditRequestPrompt": "ផ្ញើសំណើកែសម្រួលទៅ {1}?",
  "ok": "យល់ព្រម",
  "shareOne1": "{1} នេះគឺជាអ្នកជំនួយការឯកជនម្នាក់របស់អ្នក។ ខ្ញុំដឹងថាអ្នកធ្លាប់មាន {2} ផ្ទៀងផ្ទាត់រួចហើយ។ អ្នកអាចប៉ះនៅខាងក្រោមដើម្បីចែករំលែកវាជាមួយ {3} ។",
  "centerID": "លេខសម្គាល់ក្នុងស៊ុម",
  "details": "ព័ត៌មានលម្អិត",
  "textPasswordLimitations": "ត្រូវមានតួអក្សរ 10+ តួអក្សរយ៉ាងហោចណាស់មានអក្សរធំអក្សរតូចលេខនិងតួអក្សរពិសេស",
  "invalidPattern": "លំនាំមិនត្រឹមត្រូវ",
  "theMinValueBiggerThenMaxValue": "តម្លៃអប្បបរមាសម្រាប់ជួរគួរតែតូចជាងតម្លៃអតិបរមា",
  "enablePassword": "បើកពាក្យសម្ងាត់",
  "importDataPrompt": "អ្នករៀបនឹងនាំចូលទិន្នន័យរបស់អ្នក",
  "yes": "បាទ",
  "submitting": "ដាក់ស្នើ",
  "sharedContext": "បរិបទដែលបានចែករំលែក",
  "add": "បន្ថែម {1}",
  "termsAndConditions": "លក្ខខណ្ឌនិងលក្ខខណ្ឌ។",
  "setNewPassword": "ជ្រើសរើសពាក្យសម្ងាត់ថ្មី",
  "thePropertyWithMinMaxRangeError": "ទ្រព្យដែលមានជួរ [អប្បបរមា] អាចមានតែលេខពីរ",
  "receivedProduct": "ទទួលបាន {1}",
  "holdPhoneToPassport": "សង្កត់ខាងក្រោយនៃទូរស័ព្ទរបស់អ្នកប្រឆាំងនឹងគម្របខាងមុខនៃលិខិតឆ្លងដែនរបស់អ្នក",
  "useGesturePassword": "បើកដំណើរការពាក្យសម្ងាត់កាយវិការ",
  "verifierHelp": "ចុចប៊ូតុង 'ធ្វើរួច' បន្ទាប់ពីពិនិត្យមើលទម្រង់។ ប្រសិនបើវាលមួយចំនួនត្រូវការការកែតម្រូវពិនិត្យមើលពួកវាមុនហើយបន្ទាប់មកចុចប៊ូតុង 'ធ្វើរួច'",
  "verifyPrompt": "ផ្ទៀង​ផ្ទាត់?",
  "multientryToShare": "មាន {1} ឯកសារត្រូវចែករំលែក",
  "en": "អង់គ្លេស",
  "optional": "ស្រេចចិត្ត",
  "submittingForm": "បានដាក់បណ្ដាសា {1}",
  "centerLicence": "អាជ្ញាប័ណ្ណកណ្តាលនៅក្នុងស៊ុម",
  "addAnotherFormOrGetNext": "បន្ថែម {1} មួយឬផ្លាស់ទីទៅទម្រង់បន្ទាប់",
  "contextsFor": "បរិបទសម្រាប់",
  "enableCameraAccess": "{appName} បច្ចុប្បន្នមិនមានសិទ្ធិប្រើប្រាស់កាមេរ៉ាទេ។ ដើម្បីផ្តល់ការចូលប្រើជ្រើសការកំណត់ហើយប្រាកដថាកាមេរ៉ាត្រូវបានបើក។",
  "iNeed": "ខ្ញុំ​ត្រូវការ...",
  "setDateValue": "កំណត់",
  "setPassword": "ជ្រើសរើសពាក្យសម្ងាត់ដែលមានសុវត្ថិភាព",
  "confirmAllItems": "ប៉ះយល់ព្រមដើម្បីបញ្ជាក់ទាំងអស់ឬបោះបង់ដើម្បីបន្តពិនិត្យមើល",
  "restartApp": "ចាប់ផ្ដើមកម្មវិធីឡើងវិញ",
  "turnBothOn": "បើកទាំងពីរ",
  "fromMyData": "ពី 'ទិន្នន័យរបស់ខ្ញុំ'",
  "pleaseCorrectTheErrors": "សូមកែកំហុសក្នុងទម្រង់",
  "reviewScannedProperties": "សូមពិនិត្យឡើងវិញនិងកែតម្រូវទិន្នន័យខាងក្រោម",
  "documentExpiredTitle": "ឯកសារបានផុតកំណត់",
  "bothOn": "ទាំងពីរគឺបើក",
  "dataSecurity": "សន្តិសុខទិន្នន័យ",
  "pleaseCorrect": "សូមកែតម្រូវ",
  "noConnection": "{appName} តម្រូវឱ្យមានការតភ្ជាប់អ៊ីនធឺណិតដែលអ្នកមិនមាននៅពេលនេះ",
  "iproovFailedMessage": "សូម​ព្យាយាម​ម្តង​ទៀត។ ដើម្បីទទួលបានលទ្ធផលល្អបំផុតសូមឱ្យមុខរបស់អ្នកកណ្តាលក្នុងរាងពងក្រពើក្នុងកំឡុងពេលភ្លឺពណ៌។",
  "viewDebugLog": "មើលកំណត់ហេតុកំហុស",
  "done": "ធ្វើ",
  "nl": "ហូឡង់",
  "updateAppMessage": "ធ្វើបច្ចុប្បន្នភាពឥឡូវនេះឬតើខ្ញុំនឹងរំលឹកអ្នកនៅពេលក្រោយ?",
  "sharedWith": "បរិបទដែលបានចែករំលែក {1} ជាមួយ {2}",
  "acceptTermsAndConditions": "មើលលក្ខខណ្ឌ",
  "pleaseCorrectFields": "សូមកែតម្រូវវាលខាងក្រោម: {1}",
  "centerPassport": "ទំព័ររូបថតអ្នកថតរូបមជ្ឈមណ្ឌលនៅក្នុងស៊ុម",
  "noNetwork": "គ្មានបណ្តាញ",
  "youAreForgotten": "អ្នកត្រូវបានភ្លេចដោយជោគជ័យ",
  "hideResource": "លាក់ {1}",
  "importData": "នាំចូលទិន្នន័យ",
  "documentExpiredMessage": "សូមស្កេនឯកសារត្រឹមត្រូវ",
  "submittingModifiedForm": "កែប្រែ {1}",
  "serverIsUnreachable": "ម៉ាស៊ីនមេមិនអាចទៅដល់ទេ",
  "areYouSureYouWantToConfirmAllItems": "ប៉ះយល់ព្រមដើម្បីបញ្ជាក់ {1} ឬបោះបង់ទាំងអស់ដើម្បីបន្តពិនិត្យឡើងវិញ",
  "learnMoreServerIsDown": "រាល់សារដែលអ្នកសរសេរនឹងត្រូវផ្ញើទៅ {1} ដោយស្វ័យប្រវត្តិនៅពេលពួកគេភ្ជាប់អ៊ីនធឺណិត។",
  "passwordOn": "ពាក្យសម្ងាត់កាយវិការបានបើក",
  "enablePasscodeFirst": "មើលទៅហាក់ដូចជាអ្នកមិនមានលេខកូដសម្ងាត់ឧបករណ៍បើកដំណើរការ។ ដោយគ្មានវា, កម្មវិធីនេះមិនអាចការពារទិន្នន័យរបស់អ្នក! សូមបើកវាមុនពេលចុចយល់ព្រម",
  "cameraAccess": "ការចូលប្រើកាមេរ៉ា",
  "viewTerms": "សូមមើលលក្ខខណ្ឌនិងលក្ខខណ្ឌ",
  "asSentTo": "ផ្ញើតាម {1}",
  "testForgetMe": "នេះគឺជាយន្តការធ្វើតេស្តមួយដើម្បីកំណត់ទំនាក់ទំនងទាំងអស់ឡើងវិញជាមួយក្រុមហ៊ុនផ្តល់សេវាកម្មនេះ",
  "errorNotification": "ការជូនដំណឹងកំហុសត្រូវបានផ្ញើទៅអតិថិជនដើម្បីកែតម្រូវ",
  "approveApplication": "អនុម័តកម្មវិធី",
  "temporarilyLocked": "សម្រាប់ការការពាររបស់អ្នកកម្មវិធីនេះត្រូវបានចាក់សោជាបណ្ដោះអាសន្នសម្រាប់ {1}",
  "importingData": "ការនាំចូលឯកសារ {1} ពី {2}",
  "invalidDocument": "ឯកសារមិនត្រឹមត្រូវ",
  "cancelItem": "អ្នករៀបនឹងបោះបង់ចោល {1} ។ សូមប៉ះយល់ព្រមដើម្បីបញ្ជាក់",
  "digitalWealthPassport": "លិខិតឆ្លងដែនឌីជីថល",
  "thisFieldIsRequired": "ចន្លោះ​នេះ​ត្រូវតែ​បំពេញ",
  "drawYourPassword": "គូរលំនាំរបស់អ្នក",
  "resetRequired": "កំណត់ឡើងវិញ",
  "shareWith": "ចែករំលែក {1}",
  "updateAppTitle": "កម្មវិធីអាចរកបានបច្ចុប្បន្នភាព",
  "verificationTransactionID": "លេខសម្គាល់ប្រតិបត្តិការផ្ទៀងផ្ទាត់",
  "updateNow": "ធ្វើបច្ចុប្បន្នភាពឥឡូវនេះ",
  "issuedBy": "ចេញដោយ {1}",
  "shareOne": "ជាជម្រើសសូមចែករំលែកខាងក្រោម",
  "validationErrors": "សូមកែប្រែវាលសុពលភាពដែលបរាជ័យ",
  "cancelHideResource": "បោះបង់លាក់ {1}",
  "typeMessage": "បញ្ចូលសារ",
  "addServerUrl": "បន្ថែម url ម៉ាស៊ីនមេ",
  "createNext": "បំពេញបែបបទ \"{1}\" ផ្សេងទៀត",
  "invalidPropertyValue": "តម្លៃមិនត្រឹមត្រូវ",
  "sandboxDescription": "នៅក្នុង Sandbox រៀនពីរបៀបប្រើកម្មវិធីជាមួយអ្នកផ្តល់សេវាកម្មដែលបានធ្វើត្រាប់តាម។",
  "sentToOn": "បានផ្ញើទៅ {1} លើ",
  "help": "ជំនួយ",
  "approveApplicationFor": "អនុម័តកម្មវិធីសម្រាប់ {1}",
  "areYouSureYouWantToDelete": "តើអ្នកប្រាកដថាអ្នកចង់លាក់ {1} មែនទេ?",
  "next": "បន្ទាប់",
  "shareProduct": "អ្នកអាចប៉ះខាងក្រោមដើម្បីចែករំលែក {1} ជាមួយ {2}",
  "listOfProducts": "បញ្ជីផលិតផល",
  "pairingRequest": "ផ្គូផ្គងសំណើ",
  "touchIdOn": "លេខសម្គាល់ទូចបានបើក",
  "nothingToShare": "គ្មានអ្វីដែលត្រូវចែកចាយ",
  "customerWaiting": "{1} បានចូលជជែក",
  "no": "ទេ",
  "sourcesBy": "ប្រភពដោយ {1}",
  "fieldErrorMessagePrompt": "តើមានបញ្ហាអ្វីចំពោះវាលនេះ?",
  "edit": "កែប្រែ",
  "somethingWrong": "មាន​អ្វីមួយ​មិន​ប្រក្រតី",
  "pairDevices": "ផ្គូរផ្គងឧបករណ៍",
  "verificationBy": "ការផ្ទៀងផ្ទាត់ដោយ {1}",
  "downloadingUpdate": "កំពុងទាញយកបច្ចុប្បន្នភាព ...",
  "learnMore": "ស្វែង​យល់​បន្ថែម",
  "areYouSureAboutNextForm": "តើអ្នកបានបញ្ចប់ការបន្ថែម {1} មែនទេ?",
  "backTo": "ត្រលប់ទៅ {1}",
  "changePassword": "ផ្លាស់ប្តូរពាក្យសម្ងាត់",
  "loadingModels": "ផ្ទុកម៉ូដែល",
  "createNew": "បំពេញបែបបទ \"{1}\"",
  "fillTheForm": "សូមបំពេញបែបបទនេះ ** {1} **",
  "inProgress": "កំពុង​ដំណើរការ...",
  "backToResults": "ត្រលប់ទៅលទ្ធផល",
  "iproovErrorTitle": "អូ៎! មាន​អ្វីមួយ​មិន​ប្រក្រតី",
  "myDocuments": "ឯកសារ​របស់​ខ្ញុំ",
  "tapToRemovePhotos": "ប៉ះដើម្បីលុបរូបថត",
  "youShared": "អ្នកបានចែករំលែកពី {1}",
  "noConnectionForNewProduct": "{1}, {appName} តម្រូវឱ្យមានការតភ្ជាប់អ៊ីនធឺណិតដំណើរការដើម្បីបំពេញ {2} កម្មវិធី។",
  "learnMoreDescriptionTo": "អ្នកនៅតែអាចសរសេរសារក្នុងរបៀបក្រៅបណ្ដាញទោះបីជាឧបករណ៍របស់អ្នកមិនបានភ្ជាប់។ នៅពេលដែលអ្នកភ្ជាប់ឡើងវិញសារទាំងអស់របស់អ្នកនឹងត្រូវផ្ញើទៅ {1} ដោយស្វ័យប្រវត្តិ។",
  "turnTouchIdOn": "បើកលេខសម្គាល់ប៉ះ",
  "noConnectionWillProcessLater": "{appName} តម្រូវឱ្យមានការតភ្ជាប់អ៊ីនធឺណិតដែលអ្នកមិនមាននៅពេលនេះ។ សំណើនឹងត្រូវបានដំណើរការនៅពេលការភ្ជាប់ត្រូវបានបង្កើតឡើង",
  "pleaseDrawPassword": "គូរលំនាំរបស់អ្នក",
  "testProviders": "Sandbox",
  "confirmedMyData": "ទិន្នន័យដែលបាននាំចូលទាំងអស់អាចមើលបាននៅក្នុង {profileTitle} របស់អ្នក",
  "loadingResources": "ផ្ទុកធនធាន",
  "shareOneOfMany": "ជាជម្រើសសូមចែករំលែកខាងក្រោម",
  "creationDate": "កាលបរិច្ឆេទបង្កើត",
  "iproovFailedTitle": "អូ៎! មាន​អ្វីមួយ​មិន​ប្រក្រតី",
  "scanQRcode": "វិភាគកូដ QR",
  "confirmForgetMe": "តើអ្នកប្រាកដថាអ្នកចង់ '{1}' បំភ្លេចអ្នកទេ",
  "sentTo": "បានផ្ញើទៅ {1}",
  "newContactRequest": "{1} បានផ្ញើសំណើទំនាក់ទំនងមកអ្នក",
  "somethingWrongSubmitLog": "អ្វីមួយហាក់បីដូចជាខុស។ សូមដាក់កំណត់ហេតុកំហុសទៅក្រុមអ្នកអភិវឌ្ឍន៍ {appName}",
  "noAccessToServer": "ម៉ាស៊ីនមេមិនអាចចូលដំណើរការបានទេ។ សាកល្បងពេលក្រោយ។",
  "noScanningOnAndroid": "ការស្កេនឯកសារនៅលើប្រព័ន្ធប្រតិបត្តិការ Android នឹងមកដល់ក្នុងពេលឆាប់ៗនេះ។",
  "invalidDeepLink": "មើលទៅដូចជាអ្នកបានចុចតំណមិនត្រឹមត្រូវ!",
  "providerIsOffline": "{1} គឺនៅក្រៅបណ្ដាញ",
  "nameUnknown": "ឈ្មោះមិនស្គាល់",
  "unreadMessages": "អ្នកមានសារមិនទាន់អាន",
  "generatingKeys": "បង្កើតកូនសោឯកជនរបស់អ្នក",
  "importing": "កំពុងនាំចូល",
  "neverMissAMessage": "មិនដែលខកខានសារ",
  "homePage": "ផ្ទះ",
  "installingUpdate": "កំពុងដំឡើងបច្ចុប្បន្នភាព",
  "storageCorrupted": "ទិន្នន័យនិងឃ្លាំងផ្ទុកកម្មវិធីរបស់អ្នកត្រូវបានខូច! ប្រសិនបើអ្នកគិតថានេះជាកំហុសសូមចុច Restart App ដើម្បីព្យាយាមម្តងទៀត។ ចុចកម្មវិធីកំណត់ឡើងវិញនឹងកំណត់អត្តសញ្ញាណនិងផ្ទុករបស់កម្មវិធីឡើងវិញ។",
  "fillRequiredFields": "សូមបំពេញវាលដែលត្រូវការទាំងអស់",
  "submitLog": "ដាក់ស្នើកំណត់ហេតុ",
  "nothingChanged": "គ្មានអ្វីផ្លាស់ប្តូរ",
  "pleaseTapOnMenu": "សូមប៉ះលើប៊ូតុងពណ៌ក្រហម",
  "scanningFailedTryAgain": "ការស្កេនមិនជោគជ័យ។ តើអ្នកអាចព្យាយាមម្ដងទៀតបានទេ?",
  "ukLicenseUnsupported": "មិនអនុញ្ញាតការស្កេនអាជ្ញាប័ណ្ណកម្មវិធីបញ្ជាចក្រភពអង់គ្លេសនៅពេលនេះទេ",
  "later": "ក្រោយមក",
  "correctPassword": "Aww, អ្នកចាំទេ!",
  "youReviewed": "អ្នកពិនិត្យធាតុ {1} ចេញពី {2}",
  "acceptingTermsAndConditions": "ដោយចុចប៊ូតុងយល់ព្រមអ្នកព្រមទទួលលក្ខខណ្ឌនិងលក្ខខណ្ឌ",
  "sharedForm": "ចែករំលែក {1}",
  "switchToRepresentative": "ការប្ដូរទៅរបៀបតំណាងមិនទាន់ត្រូវបានអនុវត្ត។",
  "receivedVerification": "ទទួលការផ្ទៀងផ្ទាត់សម្រាប់ {1}",
  "invalidPairingRequest": "សំណើផ្គូផ្គងមិនត្រឹមត្រូវ",
  "unknownQRCodeFormat": "ទ្រង់ទ្រាយកូដ QR ដែលមិនស្គាល់",
  "verifiedByOn": "បានផ្ទៀងផ្ទាត់ដោយ {1} នៅ",
  "formListError": "មិនអាចប្រើបាន",
  "pleaseClickOnAddButton": "សូមចុចលើ '+' ខាងក្រោមដើម្បីបន្ថែម '{1}'",
  "incompatibleVersion": "ដោយសារតែការផ្លាស់ប្តូរមិនគាំទ្រមិនឆបគ្នានាពេលថ្មី ៗ នេះការធ្វើបច្ចុប្បន្នភាពនេះតម្រូវឱ្យកំណត់ការលំបាកឡើងវិញរបស់កម្មវិធី។ ចុចយល់ព្រមដើម្បីកំណត់អត្តសញ្ញាណនិងផ្ទុករបស់កម្មវិធីឡើងវិញ។",
  "offlineMode": "របៀបក្រៅបណ្តាញ",
  "denyApplicationFor": "បដិសេធសំណើសម្រាប់ {1}",
  "independentBlockchainViewer": "អ្នកមើលប្លុកឯករាជ្យ",
  "bookmarks": "ចំណាំ",
  "exploreData": "រុករកទិន្នន័យ",
  "Please scan your": "សូមវិភាគរក",
  "Please fill out the form": "សូមបំពេញសំណុំបែបបទ",
  "See our list of products": "សូមមើលបញ្ជីផលិតផលរបស់យើង",
  "ID document": "ឯកសារលេខសម្គាល់",
  "Our products have changed": "ផលិតផលរបស់យើងបានផ្លាស់ប្តូរ",
  "Choose Apply for Product from the menu": "ជ្រើសអនុវត្តសម្រាប់ផលិតផលពីម៉ឺនុយ",
  "Please take a selfie to prove this is your document. Center your face.": "សូមថតរូបដើម្បីបញ្ជាក់ថានេះជាឯកសាររបស់អ្នក។ ដាក់មុខរបស់អ្នក។",
  "Application submitted!": "បានដាក់ស្នើកម្មវិធី!",
  "Please tap here and sign": "សូមប៉ះនៅទីនេះនិងចុះហត្ថលេខា",
  "Sending": "ផ្ញើ",
  "Give me a moment...": "សូមឱ្យខ្ញុំបន្តិច ...",
  "Please click to scan your": "សូមចុចដើម្បីស្កេនអ្នក",
  "' photo of yourself that I can match against your ID document": "'រូបថតរបស់ខ្លួនឯងដែលខ្ញុំអាចផ្គូផ្គងនឹងឯកសារសម្គាល់របស់អ្នក",
  "Thank you. Now take a '": "សូមអរគុណ។ ឥឡូវនេះយក '",
  "pleaseSign": "សូមចូលក្នុងប្រអប់ពណ៌ប្រផេះ",
  "getStarted": "ចាប់ផ្ដើម",
  "goodNewsFew": "ដំណឹង​ល្អ! អ្នកមានរួចទៅហើយ។ ដើម្បីចែករំលែករូបតំណាងម៉ាស៊ីនខាងក្រោម។",
  "goodNews": "ដំណឹង​ល្អ! អ្នកមាន {1} រួចហើយ។ ដើម្បីចែករំលែករូបតំណាងខាងក្រោម",
  "Cancel": "បោះបង់",
  "Clear": "ជម្រះ",
  "Submit": "ដាក់ស្នើ",
  "retake": "យកមកវិញ",
  "usePhoto": "ប្រើរូបថត",
  "Approve": "យល់ព្រម",
  "Deny": "បដិសេធ",
  "loading": "កំពុងផ្ទុក ...",
  "Verifications": "ការផ្ទៀងផ្ទាត់",
  "checkIfMatch": "ពិនិត្យមើលប្រសិនបើត្រូវគ្នា",
  "Seals": "ត្រា",
  "Corporation Exists Checks": "សាជីវកម្មមានការពិនិត្យ",
  "Applications": "កម្មវិធី",
  "createManualMatchCheck": "បង្កើតការពិនិត្យការប្រកួតដោយដៃ",
  "Get set for friendliness?": "ទទួលបានភាពស្និទ្ធស្នាល?",
  "Take a quick tour of chat bot?": "ធ្វើដំណើរទស្សនកិច្ចរហ័សនៃ bot ជជែកកំសាន្ត?",
  "Go friendliness!": "ទៅមិត្តភាព!",
  "Ready for friendliness?": "ត្រៀមខ្លួនសម្រាប់ភាពស្និទ្ធស្នាល?",
  "Finally, you will be in control of your own private information!": "ចុងបញ្ចប់អ្នកនឹងគ្រប់គ្រងព័ត៌មានផ្ទាល់ខ្លួនរបស់អ្នក!",
  "Go!": "ទៅ!",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "យើងនឹងសួរអ្នកនូវសំណួរនៅក្នុងការជជែកហើយអ្នកគ្រាន់តែបំពេញបែបបទឬធ្វើតាមសំណើ",
  "Get set": "ទទួលបានកំណត់",
  "Ready?": "រួចរាល់ហើយ?",
  "Before we start you'll need a valid passport, identity card or driving license": "មុនពេលយើងចាប់ផ្តើមអ្នកនឹងត្រូវការលិខិតឆ្លងដែនត្រឹមត្រូវអត្តសញ្ញាណប័ណ្ណឬប័ណ្ណបើកបរ",
  "Done": "ធ្វើ",
  "Next": "បន្ទាប់",
  "Skip": "រំលង",
  "Sanctions Checks": "ពិនិត្យមើលការដាក់ទណ្ឌកម្ម",
  "inProcess": "កំពុងដំណើរការ ...",
  "networkFailure": "ខ្ញុំកំពុងមានបញ្ហាបណ្តាញមួយចំនួន។ អ្នកអាចពិនិត្យមើលហើយបន្ទាប់មកទាញយកឡើងវិញ / បោះបង់",
  "invalidQuery": "អូយើងវាយបញ្ជូលកំហុសក្នុងការដំណើរការការស្វែងរករបស់អ្នក។ អ្នកអភិវឌ្ឍន៍របស់យើងនឹងព្យាយាមជួសជុលវា។",
  "failedToSendLog": "បានបរាជ័យក្នុងការផ្ញើកំណត់ហេតុ",
  "invalidQR": "លេខកូដ QR មិនត្រឹមត្រូវ",
  "validatingDataClaim": "ការនាំចូលទិន្នន័យ",
  "debugLogSent": "កំណត់ហេតុកំហុសឆ្គងបានផ្ញើរ",
  "noResourcesForCriteria": "មិនមានធនធានត្រូវបានរកឃើញសម្រាប់លក្ខណៈវិនិច្ឆ័យនេះ",
  "logSentToDevTeam": "កំណត់ហេតុត្រូវបានផ្ញើទៅក្រុមអ្នកអភិវឌ្ឍន៍ Tradle",
  "supportedQrCodes": "កូដ QR ដែលបានគាំទ្រ:\n1) បន្ថែមឆានែលជជែក\n2) ទិន្នន័យនាំចូល",
  "reviewScannedPropertiesAndSecondSideSnapshot": "សូមពិនិត្យមើលទិន្នន័យខាងក្រោមហើយថតរូបនៃផ្នែក {1} របស់ឯកសារ",
  "documentBackSide": "ដាក់កណ្តាលផ្នែកឯកសារ",
  "Photo": "រូបថត",
  "doYouWantToContinue": "តើអ្នកចង់ប្ដូរទៅវាហើយបន្តពីទីនោះទេ?",
  "startedByAnotherEmployee": "កម្មវិធីសម្រាប់ {1} ត្រូវបានចាប់ផ្ដើមដោយបុគ្គលិកផ្សេងទៀត",
  "afterRefresh": "អ្នកត្រូវបានជម្រះឱ្យប្រើសេវាកម្មរបស់យើងដោយគ្មានការរំខាន",
  "reviewData": "ពិនិត្យទិន្នន័យឡើងវិញ",
  "requestMyData": "ស្នើសុំទិន្នន័យរបស់ខ្ញុំ",
  "newCustomer": "អតិថិជន​ថ្មី",
  "areYouSureYouAreDone": "តើអ្នកប្រាកដថាអ្នកចង់បញ្ចប់វគ្គនេះទេ?",
  "wrongDocumentTypePleaseTryAgain": "ប្រភេទឯកសារមិនត្រឹមត្រូវ។ សូម​ព្យាយាម​ម្តង​ទៀត",
  "invalidCountry": "ប្រទេសមិនត្រឹមត្រូវបានស្កេន",
  "resetApp": "កំណត់កម្មវិធីឡើងវិញ",
  "scanYourDocument": "សូមវិភាគឯកសាររបស់អ្នក",
  "enterPasswordOrWipeOutTheAppData": "បញ្ចូលពាក្យសម្ងាត់ឬលុបទិន្នន័យកម្មវិធី",
  "wipeTheAppData": "លុបទិន្នន័យកម្មវិធី",
  "dateInTheFutureError": "{1} គឺនាពេលអនាគត",
  "pleaseChooseDT": "សូមជ្រើសរើសប្រភេទឯកសារជាមុនសិន",
  "formChooser": "ស្នើសុំទម្រង់"
}