module.exports = {
  "searchSomething": "Buscar {1}",
  "thisFieldIsRequired": "este campo es requerido",
  "settings": "Configuraciones",
  "newProductMsg": "Necesito un {1}.",
  "invalidPropertyValue": "valor no válido",
  "confirmRevoke": "Pregunta {1} para eliminar este documento de sus registros?",
  "useTouchIdAndGesturePassword": "Habilitar Touch ID y Gesto",
  "formChooser": "Lista de formas",
  "submittingForm": "Sometido {1}",
  "viewTerms": "Por favor, consulte los Términos y Condiciones",
  "addServerUrl": "Agregar URL del servidor",
  "setNewPassword": "Elija una contraseña nueva",
  "optional": "Opcional",
  "shareOne": "Alternativamente, comparta abajo",
  "patternNotMatching": "Los patrones no coinciden.",
  "verifierHelp": "Haga clic en el botón 'Hecho' después de revisar el formulario. Si algunos campos requieren corrección, compruébalos primero y luego haz clic en el botón \"Listo\"",
  "confirmForgetMe": "¿Seguro que quieres que '{1}' te olvide?",
  "customerWaiting": "{1} ha ingresado al chat",
  "invalidPattern": "Patrón incorrecto",
  "back": "Espalda",
  "inProgress": "Su solicitud está en progreso",
  "tooManyPasswordAttempts": "¡Demasiados intentos fallidos! Esta forma a sido inhabilitada.",
  "turnBothOn": "Enciende ambos",
  "formListError": "Indisponible",
  "restartApp": "Reiniciar aplicación",
  "unreadMessages": "Tienes mensajes no leídos",
  "setDateValue": "Conjunto",
  "sentToOn": "Enviado a {1} en",
  "newContactRequest": "{1} te envió una solicitud de contacto",
  "pleaseRestartTIM": "Por favor, reinicie TiM",
  "noConnectionWillProcessLater": "{appName} requiere una conexión a Internet que no tiene en este momento. La solicitud se procesará cuando se establezca una conexión",
  "providerIsOffline": "{1} está fuera de línea",
  "forgetMe": "Olvidame",
  "deviceDoesNotHaveMyKeys": "La identidad recibida no tiene mis llaves",
  "termsAndConditions": "Términos y Condiciones.",
  "useGesturePassword": "Habilitar contraseña de gestos",
  "formListErrorDescription": "Los formularios se pueden solicitar una vez que el cliente comienza una solicitud",
  "verifiedByOn": "Verificado por {1} en",
  "fieldErrorMessagePrompt": "¿Qué pasa con este campo?",
  "noConnection": "{appName} requiere una conexión a Internet que no tiene en este momento",
  "typeMessage": "Escriba un mensaje",
  "hideResource": "Ocultar {1}",
  "edit": "Editar",
  "tapToRemovePhotos": "Toca para eliminar fotos",
  "myDocuments": "Mis documentos",
  "add": "Agregar {1}",
  "correctGesture": "Patrón correcto detectado",
  "done": "Hecho",
  "showQR": "Mi código QR",
  "restartingApp": "La aplicación se reiniciará momentáneamente",
  "verifyPrompt": "¿Verificar?",
  "listOfProducts": "Lista de productos",
  "cancel": "Cancelar",
  "drawYourNewPassword": "Dibuja un nuevo patrón",
  "noConnectionForPL": "{appName} requiere una conexión a Internet que funcione para solicitar una lista de productos de {1} que no tiene en este momento",
  "gestureNotRecognized": "Patrón incorrecto",
  "passwordsDontMatch": "Las contraseñas no coinciden",
  "areYouSureAboutNextForm": "¿Estás seguro de haber terminado con {1}?",
  "sharedWith": "Contexto compartido {1} con {2}",
  "pleaseDrawPassword": "Dibuja tu patrón",
  "drawYourNewPasswordAgain": "Dibuja el nuevo patrón de nuevo",
  "offlineMode": "Moda fuera de línea",
  "hello": "Hola, {1}!",
  "drawYourPassword": "Dibuja tu patrón",
  "invalidProperty": "Inválido {1}",
  "verifiedBy": "Verificado por {1}",
  "testForgetMe": "Este es un mecanismo de prueba para restablecer todas las comunicaciones con este proveedor",
  "details": "Detalles",
  "unlockDevice": "desbloquea tu dispositivo para continuar",
  "enterCurrentPassword": "introduce tu contraseña actual",
  "issuedByOn": "Emitido por {1} en",
  "changePassword": "Cambia la contraseña",
  "acceptingTermsAndConditions": "Al presionar OK, aceptas los Términos y condiciones",
  "noConnectionForNewProduct": "{1}, {appName} requiere una conexión a Internet para completar la {2} aplicación.",
  "issuedBy": "Publicado por {1}",
  "temporarilyLocked": "Para su protección, esta aplicación se ha bloqueado temporalmente para {1}",
  "profile": "Perfil",
  "shareOneOfMany": "Alternativamente, comparta abajo",
  "areYouSureYouWantToServeThisCustomer": "¿Estás seguro de que quieres servir a este cliente?",
  "authenticationFailed": "Autenticación fallida",
  "pairingRequestWasProcesseed": "La solicitud de emparejamiento se procesó",
  "loadingModels": "cargando modelos",
  "pleaseCorrectTheErrors": "Corrija el error en el formulario",
  "drawYourPasswordAgain": "Dibuja tu patrón de nuevo",
  "shareChangesWith": "Comparte los cambios con",
  "textPasswordLimitations": "Debe tener más de 10 caracteres, al menos una letra mayúscula, minúscula, número y carácter especial",
  "correctPassword": "Aww, ¡lo recuerdas!",
  "learnMoreDescription": "Aún puede escribir mensajes en el Modo sin conexión aunque su dispositivo no esté conectado. Cuando vuelvas a conectar todos tus mensajes se enviarán automáticamente.",
  "irrefutableProofs": "Pruebas irrefutables",
  "youReviewedAll": "Revisaste todo {1}",
  "areYouSureAboutWipe": "Esta acción es irreversible. Perderá todos sus datos y claves privadas. ¿Estas seguro que deseas continuar?",
  "enablePasscodeFirst": "Parece que no tienes habilitada una contraseña de dispositivo. Sin él, ¡esta aplicación no puede proteger sus datos! Por favor habilítelo antes de presionar OK",
  "holdPhoneToPassportBackCover": "Sostenga la parte posterior de su teléfono contra la parte posterior de la tapa de su pasaporte.",
  "turnPasswordOn": "Activar contraseña de gestos",
  "nl": "holandés",
  "neverMissAMessage": "No te pierdas ni un mensaje",
  "errorNotification": "Se ha enviado una notificación de error al cliente para corregir",
  "digitalWealthPassport": "Pasaporte de riqueza digital",
  "cameraAccess": "Acceso a la cámara",
  "thePropertyWithMinMaxRangeError": "La propiedad con un rango de [min-max] solo puede tener dos números",
  "enterYourName": "Introduzca su nombre",
  "learnMoreServerIsDown": "Todos los mensajes que escriba se enviarán automáticamente a {1} cuando se conecten.",
  "sharedContext": "Contexto Compartido",
  "invalidDocument": "documento inválido",
  "addAnotherFormOrGetNext": "Agregue otro {1} o avance al siguiente formulario",
  "pairingRequest": "Solicitud de emparejamiento",
  "shareAllPastAndFutureMessages": "Comparta todos los mensajes pasados ​​y futuros en este contexto con las partes seleccionadas",
  "sourcesBy": "Fuentes por {1}",
  "willBeAvailable": "Esta funcionalidad estará disponible pronto",
  "pleaseClickOnAddButton": "Haga clic en '+' a continuación para agregar '{1}'",
  "youShared": "Has compartido desde {1}",
  "nothingChanged": "nada ha cambiado",
  "invalidPairingRequest": "Solicitud de vinculación no válida",
  "sentTo": "Enviado a {1}",
  "later": "Luego",
  "documentExpiredMessage": "Por favor, escanee un documento válido",
  "areYouSureYouWantToDelete": "¿Estás seguro de que quieres ocultar {1}?",
  "centerLicence": "Licencia de centro en marco",
  "iNeed": "Necesito...",
  "officialAccounts": "Conversaciones",
  "setPassword": "Elija una contraseña segura",
  "scanQRcode": "Escanear código QR",
  "unknownQRCodeFormat": "Formato de código QR no reconocido",
  "shareProduct": "Puede tocar a continuación para compartir {1} con {2}",
  "noNetwork": "Sin red",
  "centerID": "ID del centro en el marco",
  "shareOneOfMany1": "{1}, este es tu asistente de privacidad personal. Veo que ya has verificado tu {2}. Puede tocar cualquier elemento de la lista a continuación para compartirlos con {3}.",
  "verificationTransactionID": "Identificación de transacción de verificación",
  "shareOne1": "{1}, este es tu asistente de privacidad personal. Veo que ya has verificado tu {2}. Puede tocar debajo para compartirlo con {3}.",
  "noAccessToServer": "El servidor no es accesible. Intenta más tarde.",
  "pleaseCorrect": "Por favor corrige",
  "testProviders": "Salvadera",
  "approveApplicationFor": "Aprobar la solicitud para {1}",
  "serverIsUnreachable": "El servidor es inalcanzable",
  "oops": "Uy",
  "acceptTermsAndConditions": "Ver los términos y condiciones",
  "sharedForm": "Compartido {1} desde {2}",
  "overviewOfApplications": "Descripción general de las aplicaciones",
  "asVerifiedBy": "Según verificado por {1}",
  "pairDevices": "Emparejar dispositivos",
  "ok": "DE ACUERDO",
  "switchTouchIdOn": "Cambiar la ID táctil en",
  "ukLicenseUnsupported": "El escaneo de la licencia de conducir del Reino Unido no es compatible en este momento",
  "formRequest": "Solicitud de {1}",
  "messageWaitingFrom": "Tienes un nuevo mensaje de {1}",
  "shareMyProduct": "Puede tocar a continuación para compartir {1} con {2}",
  "centerPassport": "Página de la foto del pasaporte del centro en el marco",
  "youReviewed": "Ha revisado {1} de {2} elementos",
  "denyApplication": "Denegar aplicación",
  "storageCorrupted": "¡el almacenamiento de tu navegador se ha dañado! Presione OK para restablecer la identidad y el almacenamiento de la aplicación.",
  "nothingToShare": "Nada para compartir",
  "nameUnknown": "anónimo",
  "youAreTheRM": "Usted es el Gerente de Relaciones para esta aplicación",
  "yes": "Sí",
  "switchTouchIdOff": "Desactivar la identificación táctil",
  "en": "Inglés",
  "installingUpdate": "Instalando actualización",
  "homePage": "Casa",
  "next": "Siguiente",
  "cancelItem": "Estás a punto de cancelar {1}. Toca Aceptar para confirmar",
  "takeAPicture": "Por favor, toma una foto ** selfie ** de tu cara",
  "createNew": "Completa el formulario \"{1}\"",
  "validationErrors": "Corrija los campos de validación fallidos",
  "somethingWrongSubmitLog": "Algo parece haber salido mal. Envíe el registro de depuración al equipo de desarrolladores de {appName}",
  "fromMyData": "de 'My Data'",
  "approveApplication": "Aprobar la aplicación",
  "wrongPattern": "Patrón incorrecto",
  "denyApplicationFor": "Denegar aplicación para {1}",
  "updateAppTitle": "Actualización de la aplicación disponible",
  "pleaseCorrectFields": "Por favor corrija los siguientes campos: {1}",
  "independentBlockchainViewer": "Visor de blockchain independiente",
  "turnTouchIdOn": "Activar ID táctil",
  "youAreAboutToShare": "Estás a punto de compartir\n '{1}'\n documentos",
  "retryScanning": "¿Era eso un {1}? No podría decirlo. ¿Inténtalo de nuevo?\n\nPara obtener mejores resultados, use el modo horizontal, evite el deslumbramiento y asegúrese de colocar el documento dentro del marco que se muestra.",
  "receiveNotifications?": "¿Te gustaría recibir notificaciones?",
  "youShallNotPass": "¡No pasarás!",
  "documentExpiredTitle": "Documento expirado",
  "confirmAllItems": "Toque Aceptar para confirmarlos todos, o Cancelar para continuar revisando",
  "sandboxDescription": "En Sandbox, aprende a usar la aplicación con proveedores de servicios simulados.",
  "viewDebugLog": "Ver registro de depuración",
  "updateNow": "Actualizar ahora",
  "iproovFailedTitle": "Oops! Algo salió mal",
  "iproovFailedMessage": "Inténtalo de nuevo. Para obtener los mejores resultados, mantenga su cara centrada en el óvalo durante los destellos de color.",
  "importing": "Importador",
  "createNext": "Completa otro formulario \"{1}\"",
  "areYouSureYouWantToConfirmAllItems": "Toque Aceptar para confirmar todo {1}, o Cancelar para seguir revisando",
  "newProduct": "Nuevo producto",
  "touchIdOn": "Touch ID está activado",
  "youAreForgotten": "Has sido olvidado exitosamente",
  "scanningFailedTryAgain": "El escaneo no tuvo éxito. ¿Podrías intentarlo de nuevo?",
  "importingData": "Importación de {1} documentos de {2}",
  "learnMore": "Aprende más",
  "shareWith": "Compartir {1}",
  "no": "No",
  "multientryToShare": "Hay {1} documentos para compartir",
  "applyForProduct": "Solicite un producto",
  "bothOn": "Ambos están en ON",
  "fillRequiredFields": "Por favor llene todos los campos requeridos",
  "submitLog": "Enviar registro",
  "creationDate": "Fecha de creacion",
  "resetRequired": "Restablecer requerido",
  "iproovErrorTitle": "Oops! Algo salió mal",
  "submitting": "Sumisión",
  "invalidDeepLink": "Parece que ha hecho clic en un enlace no válido.",
  "verificationBy": "Verificación por {1}",
  "holdPhoneToPassport": "Sostenga la parte posterior de su teléfono contra la portada de su pasaporte",
  "loadingResources": "carga de recursos",
  "trustedProviders": "Proveedores confiables",
  "generatingKeys": "generando tus claves privadas",
  "help": "Ayuda",
  "enableCameraAccess": "{appName} actualmente no tiene permiso para usar la cámara. Para otorgar acceso, elija Configuración y asegúrese de que la Cámara esté habilitada.",
  "useTouchId": "Habilitar Touch ID",
  "importYourData": "Importa tus datos",
  "pleaseTapOnMenu": "Toca el botón rojo y",
  "cancelHideResource": "Cancelar Ocultar {1}",
  "iproovErrorMessage": "Espera un poco y vuelve a intentarlo",
  "backTo": "Volver a {1}",
  "contactUs": "Contáctenos",
  "documentNotScanning": "¡Huy! Algo salió mal!",
  "continue": "Continuar",
  "confirmedMyData": "Todos los datos importados se pueden ver en tu {profileTitle}",
  "search": "Buscar",
  "addNew": "Agregar nuevo {1}",
  "importDataPrompt": "Está a punto de importar sus datos de",
  "receivedProduct": "Recibido {1}",
  "error": "Error",
  "initializingEngine": "motor de inicialización",
  "fillTheFormWithAttachments": "Por favor complete este formulario ** {1} **",
  "reviewScannedProperties": "Por favor revise y corrija los datos a continuación",
  "somethingWrong": "Algo salió mal",
  "incompatibleVersion": "Debido a los recientes cambios incompatibles, esta actualización requiere un restablecimiento completo de la aplicación. Presione OK para restablecer la identidad y el almacenamiento de la aplicación.",
  "updateAppMessage": "Actualiza ahora, ¿o te lo recordaré más tarde?",
  "backToResults": "Volver a los resultados",
  "importData": "Importar fechas",
  "switchToRepresentative": "Cambiar al modo representativo aún no está implementado.",
  "fillTheForm": "Por favor complete este formulario ** {1} **",
  "theMinValueBiggerThenMaxValue": "El valor mínimo para el rango debe ser más pequeño que el valor máximo",
  "receivedForm": "Recibido {1}",
  "receivedVerification": "Verificación recibida por {1}",
  "asSentTo": "Según lo enviado a {1}",
  "sendEditRequestPrompt": "¿Enviar solicitud de edición a {1}?",
  "contextsFor": "Contextos para",
  "downloadingUpdate": "Descargando una actualización ...",
  "enablePassword": "Habilitar contraseña",
  "changeGesturePassword": "Cambiar la contraseña de gesto",
  "learnMoreDescriptionTo": "Aún puede escribir mensajes en el Modo sin conexión aunque su dispositivo no esté conectado. Cuando vuelvas a conectar todos tus mensajes se enviarán automáticamente a {1}.",
  "passwordOn": "La contraseña de gestos está activada",
  "noScanningOnAndroid": "El escaneo de documentos en Android llegará pronto.",
  "dataSecurity": "Seguridad de datos",
  "thisValueIsInvalidPlaceholder": "este valor no es válido porque ...",
  "drawYourOldPassword": "Dibuja tu viejo patrón",
  "sponsoredBy": "Patrocinado por",
  "enterPassword": "Ingresa tu contraseña",
  "shareContext": "Compartir {1}",
  "submittingModifiedForm": "Modificando {1}",
  "passwordLimitations": "El patrón debe tener más de 5 puntos",
  "bookmarks": "Marcadores",
  "exploreData": "Explore los datos",
  "Please scan your": "Por favor escanea tu",
  "See our list of products": "Vea nuestra lista de productos",
  "Please fill out the form": "por favor rellena el formulario",
  "ID document": "Documento de identidad",
  "Our products have changed": "Nuestros productos han cambiado",
  "Choose Apply for Product from the menu": "Elija Aplicar para Producto desde el menú",
  "Please take a selfie to prove this is your document. Center your face.": "Por favor, tome una selfie para demostrar que este es su documento. Centre su cara.",
  "Application submitted!": "¡Solicitud presentada!",
  "Sending": "Enviando",
  "Please tap here and sign": "Toca aquí y firma",
  "Give me a moment...": "Dame un momento...",
  "Please click to scan your": "Haga clic para escanear su",
  "Thank you. Now take a '": "Gracias. Ahora toma un '",
  "' photo of yourself that I can match against your ID document": "' foto tuya que puedo hacer coincidir con tu documento de identidad",
  "pleaseSign": "Por favor firme dentro de la caja gris",
  "getStarted": "Empezar",
  "goodNewsFew": "¡Buenas noticias! Ya tienes bastantes. Para compartir el icono de toque a continuación.",
  "goodNews": "¡Buenas noticias! Ya tienes {1}. Para compartir, toca el icono a continuación",
  "Clear": "Claro",
  "Submit": "Enviar",
  "Cancel": "Cancelar",
  "retake": "Volver a tomar",
  "usePhoto": "Usar foto",
  "Deny": "Negar",
  "Approve": "Aprobar",
  "loading": "Cargando...",
  "checkIfMatch": "Verifica si coinciden",
  "Verifications": "Verificaciones",
  "Seals": "Sellos",
  "Applications": "Aplicaciones",
  "Corporation Exists Checks": "Corporación existe cheques",
  "createManualMatchCheck": "Crear verificación de coincidencia manual",
  "Finally, you will be in control of your own private information!": "¡Finalmente, usted tendrá el control de su propia información privada!",
  "Take a quick tour of chat bot?": "Haga un recorrido rápido por chat bot?",
  "Go friendliness!": "Vaya amistad!",
  "Ready for friendliness?": "Listo para la amistad?",
  "Get set for friendliness?": "Prepárate para la amistad?",
  "Ready?": "Listo?",
  "Go!": "¡Ir!",
  "Get set": "Establecerse",
  "Before we start you'll need a valid passport, identity card or driving license": "Antes de comenzar, necesitará un pasaporte válido, documento de identidad o permiso de conducir",
  "We'll ask you questions in the chat and you simply fill the forms or follow the requests": "Le haremos preguntas en el chat y simplemente complete los formularios o siga las solicitudes",
  "Done": "Hecho",
  "Next": "Siguiente",
  "Skip": "Omitir",
  "Sanctions Checks": "Verificaciones de sanciones",
  "inProcess": "En proceso...",
  "networkFailure": "Estoy experimentando algunos problemas de red. ¿Puedes verificar y luego tocar Volver a intentar / Cancelar",
  "invalidQuery": "Vaya, nos topamos con un error al ejecutar su búsqueda. Nuestros desarrolladores intentarán solucionarlo lo antes posible.",
  "validatingDataClaim": "Importando datos",
  "debugLogSent": "Registro de depuración enviado",
  "failedToSendLog": "Error al enviar el registro",
  "invalidQR": "Código QR no válido",
  "supportedQrCodes": "Códigos QR soportados:\n1) agregar canal de chat\n2) importar datos",
  "logSentToDevTeam": "El registro fue enviado al equipo de desarrolladores de Tradle.",
  "noResourcesForCriteria": "No se encontraron recursos para este criterio.",
  "reviewScannedPropertiesAndSecondSideSnapshot": "Revise los datos a continuación y tome una instantánea del lado {1} del documento",
  "documentBackSide": "Parte central del documento",
  "Photo": "Foto",
  "startedByAnotherEmployee": "La solicitud para {1} fue iniciada por otro empleado",
  "doYouWantToContinue": "¿Quieres cambiar a él y continuar desde allí?",
  "afterRefresh": "Usted está autorizado a utilizar nuestros servicios sin interrupción.",
  "reviewData": "Revisar datos",
  "requestMyData": "Solicitando mis datos",
  "newCustomer": "Nuevo cliente",
  "areYouSureYouAreDone": "¿Estás seguro de que quieres terminar esta sesión?",
  "resetApp": "Restablecer la aplicación",
  "scanYourDocument": "Por favor escanea tu documento",
  "invalidCountry": "País no válido escaneado",
  "wrongDocumentTypePleaseTryAgain": "Tipo de documento incorrecto. Inténtalo de nuevo",
  "wipeTheAppData": "Borrar los datos de la aplicación",
  "enterPasswordOrWipeOutTheAppData": "Introduzca la contraseña o borre los datos de la aplicación",
  "pleaseChooseCountryAndDT": "Por favor, elija el país y el tipo de documento primero"
}