
var Rabobank = Object.freeze({
  LINK_COLOR: '#FF6D0D',
  PRODUCT_ROW_BG_COLOR: '#466399',
  PRODUCT_ROW_TEXT_COLOR: '#eeeeee',

  // BACKGROUND_COLOR: '#3A5280',
  VERIFIED_HEADER_COLOR: '#FF6D0D',//'#3A5280',
  VERIFIED_BORDER_COLOR: '#FFCFB0',

  // CONFIRMATION_BACKGROUND_COLOR: '#ffffff',
  // CONFIRMATION_COLOR: '#B458ED',

  NAV_TITLE: '#FF6D0D',
  NAV_BUTTONS: '#F7F7F7',
  NAV_BG: '#223251',

  SEPARATOR: '#006A4D',
  MY_MESSAGE_BG: '#4884BD',
  STRUCTURED_MESSAGE_COLOR: '#3A5280',

  BANKLINKS: '#3A5280',
});

module.exports = Rabobank;
